// src/scripts/fix-ui-issues.ts
/**
 * Bulk UI‑audit auto‑fix script.
 *
 * Reads the JSON report generated by `src/utils/uiAudit.ts` (ui-audit-report.json)
 * and applies safe placeholder fixes for two common accessibility problems:
 *   1️⃣ <a> or <Link> elements missing a destination (`href` / `to`).
 *   2️⃣ Non‑interactive elements (e.g., <div>, <span>) that have an `onClick` handler.
 *
 * The script performs **in‑place edits** on the source files. It adds a TODO comment
 * so you can replace the placeholder later with a real route or proper button.
 *
 * Usage (run from the project root or any sub‑directory):
 *   npx ts-node src/scripts/fix-ui-issues.ts
 */

import * as fs from "fs";
import * as path from "path";

// Absolute path to the audit report – adjust if the file lives elsewhere.
const REPORT_PATH = path.resolve(
  "/Users/rmpgutah/RMPG Flex/ui-audit-report.json"
);

interface Issue {
  file: string; // relative to repository root, POSIX style (e.g., "client/src/pages/admin/AdminCompetitiveTab.tsx")
  line: number;
  column: number;
  type: string; // e.g., "missingHref", "nonInteractiveOnClick"
  snippet: string; // original source snippet (optional)
}

function loadReport(): Issue[] {
  if (!fs.existsSync(REPORT_PATH)) {
    console.error("[fix-ui-issues] Report not found at", REPORT_PATH);
    process.exit(1);
  }
  const raw = fs.readFileSync(REPORT_PATH, "utf-8");
  const data = JSON.parse(raw);
  // The report may be an object with an "issues" array or just an array.
  return Array.isArray(data) ? data : data.issues || [];
}

function applyMissingHref(content: string, issue: Issue): string {
  // Very simple regex: find the start tag that ends with '>' and does NOT contain href or to.
  // We only replace the first occurrence on the reported line.
  const lines = content.split("\n");
  const idx = issue.line - 1; // 0‑based
  if (idx < 0 || idx >= lines.length) return content;
  const line = lines[idx];
  const updated = line.replace(
    /<(a|Link)(?![^>]*\b(?:href|to)=)[^>]*>/,
    (match) => {
      // Insert href="#" and a TODO comment.
      const withHref = match.replace(
        /<(a|Link)/,
        `<$1 href="#"`
      );
      return withHref + " {/* TODO: add real destination */}";
    }
  );
  lines[idx] = updated;
  return lines.join("\n");
}

function applyNonInteractiveOnClick(content: string, issue: Issue): string {
  const lines = content.split("\n");
  const idx = issue.line - 1;
  if (idx < 0 || idx >= lines.length) return content;
  const line = lines[idx];
  // Detect a tag that is not inherently interactive (div, span, li, etc.) with onClick.
  const updated = line.replace(
    /<(div|span|li|section|article)([^>]*)\bonClick=/,
    (match, tag, rest) => {
      // Replace the tag with a button preserving attributes (except className if you want).
      const newTag = `<button${rest} onClick=`;
      return newTag + " {/* TODO: ensure accessible label */}";
    }
  );
  lines[idx] = updated;
  return lines.join("\n");
}

function processFile(issue: Issue) {
  const absolutePath = path.resolve(issue.file.startsWith("/") ? issue.file : path.join("/Users/rmpgutah/RMPG Flex", issue.file));
  if (!fs.existsSync(absolutePath)) {
    console.warn(`[fix-ui-issues] File not found: ${absolutePath}`);
    return;
  }
  let content = fs.readFileSync(absolutePath, "utf-8");
  switch (issue.type) {
    case "missingHref":
    case "missingHrefOrTo":
      content = applyMissingHref(content, issue);
      break;
    case "nonInteractiveOnClick":
      content = applyNonInteractiveOnClick(content, issue);
      break;
    default:
      // Unsupported type – skip.
      return;
  }
  fs.writeFileSync(absolutePath, content, "utf-8");
  console.log(`[fix-ui-issues] Fixed ${issue.type} in ${issue.file}`);
}

function main() {
  const issues = loadReport();
  if (issues.length === 0) {
    console.log("[fix-ui-issues] No issues found in the report.");
    return;
  }
  // Group by file for efficiency.
  const byFile = new Map<string, Issue[]>();
  for (const issue of issues) {
    if (!byFile.has(issue.file)) byFile.set(issue.file, []);
    byFile.get(issue.file)!.push(issue);
  }
  for (const [file, fileIssues] of byFile.entries()) {
    // Load file once, apply all relevant fixes sequentially.
    const absolutePath = path.resolve(file.startsWith("/") ? file : path.join("/Users/rmpgutah/RMPG Flex", file));
    if (!fs.existsSync(absolutePath)) {
      console.warn(`[fix-ui-issues] Skipping missing file: ${absolutePath}`);
      continue;
    }
    let content = fs.readFileSync(absolutePath, "utf-8");
    for (const issue of fileIssues) {
      if (issue.type === "missingHref" || issue.type === "missingHrefOrTo") {
        content = applyMissingHref(content, issue);
      } else if (issue.type === "nonInteractiveOnClick") {
        content = applyNonInteractiveOnClick(content, issue);
      }
    }
    fs.writeFileSync(absolutePath, content, "utf-8");
    console.log(`[fix-ui-issues] Updated ${file}`);
  }
}

main();
