-- Migration number: 0008 	 2026-05-22T08:21:00.923Z
-- Add missing columns to users table (see 0007 which was merged into this)

ALTER TABLE users ADD COLUMN first_name TEXT;
ALTER TABLE users ADD COLUMN last_name TEXT;
ALTER TABLE users ADD COLUMN middle_name TEXT;
ALTER TABLE users ADD COLUMN date_of_birth TEXT;
ALTER TABLE users ADD COLUMN ssn_last4 TEXT;
ALTER TABLE users ADD COLUMN address TEXT;
ALTER TABLE users ADD COLUMN city TEXT;
ALTER TABLE users ADD COLUMN state TEXT;
ALTER TABLE users ADD COLUMN zip TEXT;
ALTER TABLE users ADD COLUMN emergency_contact_name TEXT;
ALTER TABLE users ADD COLUMN emergency_contact_phone TEXT;
ALTER TABLE users ADD COLUMN emergency_contact_relationship TEXT;
ALTER TABLE users ADD COLUMN hire_date TEXT;
ALTER TABLE users ADD COLUMN termination_date TEXT;
ALTER TABLE users ADD COLUMN rank TEXT;
ALTER TABLE users ADD COLUMN department TEXT;
ALTER TABLE users ADD COLUMN shift_preference TEXT;
ALTER TABLE users ADD COLUMN dl_number TEXT;
ALTER TABLE users ADD COLUMN dl_state TEXT;
ALTER TABLE users ADD COLUMN dl_expiry TEXT;
ALTER TABLE users ADD COLUMN blood_type TEXT;
ALTER TABLE users ADD COLUMN allergies TEXT;
ALTER TABLE users ADD COLUMN uniform_size TEXT;
ALTER TABLE users ADD COLUMN employee_id TEXT;
ALTER TABLE users ADD COLUMN certifications TEXT;
ALTER TABLE users ADD COLUMN notes TEXT;
ALTER TABLE users ADD COLUMN profile_image TEXT;
ALTER TABLE users ADD COLUMN last_password_change TEXT;
ALTER TABLE users ADD COLUMN login_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN last_login_at TEXT;
ALTER TABLE users ADD COLUMN must_change_password INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN totp_secret_enc TEXT;
ALTER TABLE users ADD COLUMN totp_enabled INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN totp_backup_codes TEXT;
ALTER TABLE users ADD COLUMN totp_pending_secret TEXT;
ALTER TABLE users ADD COLUMN totp_exempt INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN password_history TEXT;
ALTER TABLE users ADD COLUMN password_changed_at TEXT;
ALTER TABLE users ADD COLUMN digital_signature TEXT;
ALTER TABLE users ADD COLUMN voice_persona TEXT DEFAULT 'en-US-JennyNeural';
ALTER TABLE users ADD COLUMN voice_rate REAL DEFAULT 1.0;
ALTER TABLE users ADD COLUMN voice_pitch REAL DEFAULT 0;
ALTER TABLE users ADD COLUMN voice_terseness TEXT DEFAULT 'standard';
ALTER TABLE users ADD COLUMN voice_brain_enabled INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN photo TEXT;
ALTER TABLE users ADD COLUMN territory_zips TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN availability TEXT DEFAULT '{}';
ALTER TABLE users ADD COLUMN active_case_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN performance TEXT DEFAULT '{}';
ALTER TABLE users ADD COLUMN notification_prefs TEXT DEFAULT '{}';
ALTER TABLE users ADD COLUMN theme_preference TEXT DEFAULT 'dark';
ALTER TABLE users ADD COLUMN font_size_preference TEXT DEFAULT 'medium';
ALTER TABLE users ADD COLUMN favorites TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN recently_viewed TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN fitness_scores TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN commendations TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN status_history TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN assignment_history TEXT DEFAULT '[]';
