-- Migration number: 0009    2026-05-23T00:00:00.000Z
-- Add missing columns to calls_for_service table for D1 production parity with local SQLite

ALTER TABLE calls_for_service ADD COLUMN caller_address TEXT DEFAULT '';
ALTER TABLE calls_for_service ADD COLUMN case_number TEXT;
ALTER TABLE calls_for_service ADD COLUMN case_id INTEGER;
ALTER TABLE calls_for_service ADD COLUMN cross_street TEXT;
ALTER TABLE calls_for_service ADD COLUMN location_building TEXT;
ALTER TABLE calls_for_service ADD COLUMN location_floor TEXT;
ALTER TABLE calls_for_service ADD COLUMN location_room TEXT;
ALTER TABLE calls_for_service ADD COLUMN weapons_involved TEXT;
ALTER TABLE calls_for_service ADD COLUMN injuries_reported INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN num_subjects INTEGER;
ALTER TABLE calls_for_service ADD COLUMN subject_description TEXT;
ALTER TABLE calls_for_service ADD COLUMN vehicle_description TEXT;
ALTER TABLE calls_for_service ADD COLUMN direction_of_travel TEXT;
ALTER TABLE calls_for_service ADD COLUMN responding_officer TEXT;
ALTER TABLE calls_for_service ADD COLUMN secondary_type TEXT;
ALTER TABLE calls_for_service ADD COLUMN contact_method TEXT;
ALTER TABLE calls_for_service ADD COLUMN scene_safety TEXT;
ALTER TABLE calls_for_service ADD COLUMN weather_conditions TEXT;
ALTER TABLE calls_for_service ADD COLUMN lighting_conditions TEXT;
ALTER TABLE calls_for_service ADD COLUMN num_victims INTEGER;
ALTER TABLE calls_for_service ADD COLUMN alcohol_involved INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN drugs_involved INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN domestic_violence INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN supervisor_notified INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN le_notified INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN le_agency TEXT;
ALTER TABLE calls_for_service ADD COLUMN le_case_number TEXT;
ALTER TABLE calls_for_service ADD COLUMN damage_estimate REAL;
ALTER TABLE calls_for_service ADD COLUMN damage_description TEXT;
ALTER TABLE calls_for_service ADD COLUMN action_taken TEXT;
ALTER TABLE calls_for_service ADD COLUMN updated_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN received_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN previous_status TEXT;
ALTER TABLE calls_for_service ADD COLUMN client_id INTEGER;
ALTER TABLE calls_for_service ADD COLUMN starting_mileage REAL;
ALTER TABLE calls_for_service ADD COLUMN ending_mileage REAL;
ALTER TABLE calls_for_service ADD COLUMN dispatch_code TEXT;
ALTER TABLE calls_for_service ADD COLUMN sector_id TEXT;
ALTER TABLE calls_for_service ADD COLUMN sector_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN zone_id TEXT;
ALTER TABLE calls_for_service ADD COLUMN zone_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN zone_beat TEXT DEFAULT '';
ALTER TABLE calls_for_service ADD COLUMN beat_id TEXT;
ALTER TABLE calls_for_service ADD COLUMN beat_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN beat_descriptor TEXT;
ALTER TABLE calls_for_service ADD COLUMN contract_id TEXT;
ALTER TABLE calls_for_service ADD COLUMN tags TEXT DEFAULT '[]';
ALTER TABLE calls_for_service ADD COLUMN priority_score INTEGER DEFAULT 0;
ALTER TABLE calls_for_service ADD COLUMN response_time_seconds REAL;
ALTER TABLE calls_for_service ADD COLUMN status_changed_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN onscene_duration_seconds REAL;
ALTER TABLE calls_for_service ADD COLUMN overdue_notified TEXT;
ALTER TABLE calls_for_service ADD COLUMN archived_at TEXT;

-- Process service / PSO columns specifically for serveIntake
ALTER TABLE calls_for_service ADD COLUMN pso_requestor_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_requestor_phone TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_requestor_email TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_service_type TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_billing_code TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_authorization TEXT;
ALTER TABLE calls_for_service ADD COLUMN pso_attempt_number INTEGER;
ALTER TABLE calls_for_service ADD COLUMN pso_service_windows TEXT;
ALTER TABLE calls_for_service ADD COLUMN process_service_type TEXT;
ALTER TABLE calls_for_service ADD COLUMN process_served_to TEXT;
ALTER TABLE calls_for_service ADD COLUMN process_served_address TEXT;
ALTER TABLE calls_for_service ADD COLUMN process_attempts INTEGER;
