-- link_options: admin-editable option lists for call-linkage dropdowns.
-- Layered UNDER hardcoded client defaults (constants/linkOptions.ts) which
-- guarantee non-empty dropdowns if this table is empty/unreachable. Rows here
-- override a default's label/sort, hide it (is_active=0), or add a custom value.
-- is_default=1 marks seeded baseline rows (protected from hard-delete in admin).
CREATE TABLE IF NOT EXISTS link_options (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,            -- person_role | vehicle_role | caller_relationship | business_role
  value TEXT NOT NULL,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 100,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_default INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT,
  UNIQUE(category, value)
);
CREATE INDEX IF NOT EXISTS idx_link_options_cat ON link_options(category, is_active, sort_order);

INSERT OR IGNORE INTO link_options (category, value, label, sort_order, is_default) VALUES
  ('person_role','suspect','Suspect',10,1),
  ('person_role','victim','Victim',20,1),
  ('person_role','witness','Witness',30,1),
  ('person_role','reporting_party','Reporting Party',40,1),
  ('person_role','involved','Involved',50,1),
  ('person_role','complainant','Complainant',60,1),
  ('person_role','serve_recipient','Serve Recipient',70,1),
  ('person_role','serve_recipient_agent','Serve Recipient Agent',80,1),
  ('person_role','registered_agent','Registered Agent',90,1),
  ('person_role','authorized_agent','Authorized Agent',100,1),
  ('person_role','plaintiff','Plaintiff',110,1),
  ('person_role','defendant','Defendant',120,1),
  ('person_role','attorney','Attorney',130,1),
  ('person_role','process_server','Process Server',140,1),
  ('person_role','client_contact','Client Contact',150,1),
  ('person_role','mentioned','Mentioned',160,1),
  ('person_role','other','Other',170,1),
  ('vehicle_role','suspect_vehicle','Suspect Vehicle',10,1),
  ('vehicle_role','victim_vehicle','Victim Vehicle',20,1),
  ('vehicle_role','witness_vehicle','Witness Vehicle',30,1),
  ('vehicle_role','involved','Involved',40,1),
  ('vehicle_role','evidence','Evidence',50,1),
  ('vehicle_role','towed','Towed',60,1),
  ('vehicle_role','recovered','Recovered',70,1),
  ('vehicle_role','other','Other',80,1),
  ('caller_relationship','employee','Employee',10,1),
  ('caller_relationship','victim','Victim',20,1),
  ('caller_relationship','witness','Witness',30,1),
  ('caller_relationship','complainant','Complainant',40,1),
  ('caller_relationship','management','Management',50,1),
  ('caller_relationship','alarm_company','Alarm Company',60,1),
  ('caller_relationship','officer','Officer',70,1),
  ('caller_relationship','anonymous','Anonymous',80,1),
  ('caller_relationship','registered_agent','Registered Agent',90,1),
  ('caller_relationship','attorney','Attorney',100,1),
  ('caller_relationship','plaintiff','Plaintiff',110,1),
  ('caller_relationship','defendant','Defendant',120,1),
  ('caller_relationship','property_manager','Property Manager',130,1),
  ('caller_relationship','tenant','Tenant',140,1),
  ('caller_relationship','client','Client',150,1),
  ('caller_relationship','guard_on_duty','Guard On Duty',160,1),
  ('caller_relationship','third_party','Third Party',170,1),
  ('caller_relationship','automated_system','Automated System',180,1),
  ('caller_relationship','neighbor','Neighbor',190,1),
  ('caller_relationship','family_member','Family Member',200,1),
  ('caller_relationship','other','Other',210,1),
  ('business_role','served_business','Served Business',10,1),
  ('business_role','client_org','Client Organization',20,1),
  ('business_role','alarm_company','Alarm Company',30,1),
  ('business_role','property','Property',40,1),
  ('business_role','employer','Employer',50,1),
  ('business_role','registered_agent_entity','Registered Agent Entity',60,1),
  ('business_role','involved','Involved',70,1),
  ('business_role','other','Other',80,1);
