-- 0219: normalize fleet_fuel_log.fuel_date to canonical UTC.
--
-- Source: live audit 2026-07-31. One column held FOUR incompatible formats,
-- because all three write paths stored the caller's string verbatim:
--
--     87 rows  2026-06-25T14:14:50                 ISO, no offset  (Denver local)
--     22 rows  2026-07-28T20:33:39.000000-06:00    ISO, with offset
--      3 rows  2026-07-29 02:33:03                 space-separated (already UTC)
--      1 row   2026-07-17                          date only       (Denver local)
--
-- SQLite reads an offset-less string as UTC, but the T-separated offset-less
-- values are Denver wall-clock, so every one of them was read 6-7 hours early.
-- Evidence: rows entered promptly sat 6.06h / 6.11h ahead of their UTC
-- created_at -- exactly the MDT offset. Consequence:
-- date('2026-07-17T19:28:00-06:00') yields 2026-07-18, so evening fills
-- bucketed into the next day, skewing COUNT(DISTINCT DATE(fuel_date)),
-- monthly grouping and 30-day windows.
--
-- ⚠️ THE SEPARATOR IDENTIFIES THE PRODUCER, and the two offset-less forms mean
-- DIFFERENT ZONES:
--     'YYYY-MM-DD HH:MM:SS' (space) <- SQLite datetime('now')  => already UTC
--     'YYYY-MM-DDTHH:MM:SS' (T)     <- toDenverWallClock()     => Denver local
-- Proven by the three double-logged fills, where one real fill exists once
-- with an explicit -06:00 offset and once space-separated:
--     id 114 20:33:39-06:00 -> 02:33:39Z   vs   id 115 '2026-07-29 02:33:03'
--     id 113 14:42:00-06:00 -> 20:42:00Z   vs   id 116 '2026-07-21 20:42:31'
--     id  94 19:28:00-06:00 -> 01:28:00Z   vs   id 117 '2026-07-18 01:28:47'
-- All three align only if the space form is UTC. An earlier draft of this
-- migration treated it as Denver and would have pushed ids 115/116/117 a
-- further +6h into the future. Those three rows are deliberately NOT updated
-- below (110 of 113 rows change; 3 are already canonical).
--
-- The write paths are fixed separately (normalizeToUtcTimestamp, applied in
-- fleet.ts manual + bulk-import and fleetio/pull.ts). This file repairs the
-- rows already stored.
--
-- REVERSIBLE: fuel_date_original preserves every pre-migration value, so this
-- can be undone with
--     UPDATE fleet_fuel_log SET fuel_date = fuel_date_original
--      WHERE fuel_date_original IS NOT NULL;
-- rather than a D1 Time Travel restore. The inference that T-separated values
-- are Denver-local is well supported but rests on 3 promptly-entered rows; the
-- other 84 are backfilled imports whose source zone cannot be observed. Keep
-- the backup column.
--
-- IDEMPOTENT: each UPDATE is guarded on the exact pre-migration value, so a
-- re-apply matches nothing and cannot double-shift a row.
--
-- Statements were generated by running the SAME normalizeToUtcTimestamp used
-- at runtime over the live values, so migration and code cannot drift. DST is
-- per-row exact (2025-11-01 shifts +6 MDT, 2025-11-02 shifts +7 MST).

ALTER TABLE fleet_fuel_log ADD COLUMN fuel_date_original TEXT;

UPDATE fleet_fuel_log SET fuel_date_original = fuel_date WHERE fuel_date_original IS NULL;

UPDATE fleet_fuel_log SET fuel_date = '2026-05-01 02:01:00' WHERE id = 2 AND fuel_date = '2026-04-30T20:01:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-10-31 12:44:00' WHERE id = 4 AND fuel_date = '2025-10-31T06:44:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-01 03:37:00' WHERE id = 5 AND fuel_date = '2025-10-31T21:37:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-01 14:13:00' WHERE id = 6 AND fuel_date = '2025-11-01T08:13:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-02 16:44:00' WHERE id = 7 AND fuel_date = '2025-11-02T09:44:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-04 05:25:00' WHERE id = 8 AND fuel_date = '2025-11-03T22:25:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-07 04:53:00' WHERE id = 9 AND fuel_date = '2025-11-06T21:53:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-08 04:45:00' WHERE id = 10 AND fuel_date = '2025-11-07T21:45:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-13 10:03:00' WHERE id = 11 AND fuel_date = '2025-11-13T03:03:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-13 13:31:00' WHERE id = 12 AND fuel_date = '2025-11-13T06:31:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-14 04:26:00' WHERE id = 13 AND fuel_date = '2025-11-13T21:26:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-15 04:22:00' WHERE id = 14 AND fuel_date = '2025-11-14T21:22:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-15 21:05:00' WHERE id = 15 AND fuel_date = '2025-11-15T14:05:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-16 04:14:00' WHERE id = 16 AND fuel_date = '2025-11-15T21:14:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-17 14:04:00' WHERE id = 17 AND fuel_date = '2025-11-17T07:04:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-18 06:02:00' WHERE id = 18 AND fuel_date = '2025-11-17T23:02:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-19 05:36:00' WHERE id = 19 AND fuel_date = '2025-11-18T22:36:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-20 03:11:00' WHERE id = 20 AND fuel_date = '2025-11-19T20:11:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-21 13:37:00' WHERE id = 21 AND fuel_date = '2025-11-21T06:37:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-24 00:12:00' WHERE id = 22 AND fuel_date = '2025-11-23T17:12:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-27 04:45:00' WHERE id = 23 AND fuel_date = '2025-11-26T21:45:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-30 15:23:00' WHERE id = 24 AND fuel_date = '2025-11-30T08:23:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-05 17:35:00' WHERE id = 25 AND fuel_date = '2025-12-05T10:35:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-06 07:31:00' WHERE id = 26 AND fuel_date = '2025-12-06T00:31:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-06 10:24:00' WHERE id = 27 AND fuel_date = '2025-12-06T03:24:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-21 15:55:00' WHERE id = 28 AND fuel_date = '2025-12-21T08:55:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-22 11:12:00' WHERE id = 29 AND fuel_date = '2025-12-22T04:12:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-25 15:53:00' WHERE id = 30 AND fuel_date = '2025-12-25T08:53:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-27 07:53:00' WHERE id = 31 AND fuel_date = '2025-12-27T00:53:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-29 07:53:00' WHERE id = 32 AND fuel_date = '2025-12-29T00:53:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-30 01:15:00' WHERE id = 33 AND fuel_date = '2025-12-29T18:15:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-30 06:44:00' WHERE id = 34 AND fuel_date = '2025-12-29T23:44:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-30 14:53:00' WHERE id = 35 AND fuel_date = '2025-12-30T07:53:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-30 22:36:00' WHERE id = 36 AND fuel_date = '2025-12-30T15:36:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-31 18:20:00' WHERE id = 37 AND fuel_date = '2025-12-31T11:20:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-31 20:21:00' WHERE id = 38 AND fuel_date = '2025-12-31T13:21:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-01 02:05:00' WHERE id = 39 AND fuel_date = '2025-12-31T19:05:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-02 04:35:00' WHERE id = 40 AND fuel_date = '2026-01-01T21:35:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-02 08:11:00' WHERE id = 41 AND fuel_date = '2026-01-02T01:11:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-03 03:58:00' WHERE id = 42 AND fuel_date = '2026-01-02T20:58:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-04 05:58:05' WHERE id = 43 AND fuel_date = '2026-01-03T22:58:05';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-04 12:46:00' WHERE id = 44 AND fuel_date = '2026-01-04T05:46:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-05 14:25:00' WHERE id = 45 AND fuel_date = '2026-01-05T07:25:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-06 09:18:00' WHERE id = 46 AND fuel_date = '2026-01-06T02:18:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-08 05:39:00' WHERE id = 47 AND fuel_date = '2026-01-07T22:39:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-08 19:55:00' WHERE id = 48 AND fuel_date = '2026-01-08T12:55:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-09 23:54:00' WHERE id = 49 AND fuel_date = '2026-01-09T16:54:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-11 20:09:00' WHERE id = 50 AND fuel_date = '2026-01-11T13:09:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-15 01:47:00' WHERE id = 51 AND fuel_date = '2026-01-14T18:47:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-15 19:20:00' WHERE id = 52 AND fuel_date = '2026-01-15T12:20:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-19 01:56:00' WHERE id = 53 AND fuel_date = '2026-01-18T18:56:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-20 09:12:00' WHERE id = 54 AND fuel_date = '2026-01-20T02:12:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-22 14:20:00' WHERE id = 55 AND fuel_date = '2026-01-22T07:20:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-23 04:58:00' WHERE id = 56 AND fuel_date = '2026-01-22T21:58:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-24 22:28:00' WHERE id = 57 AND fuel_date = '2026-01-24T15:28:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-26 06:06:00' WHERE id = 58 AND fuel_date = '2026-01-25T23:06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-26 18:06:00' WHERE id = 59 AND fuel_date = '2026-01-26T11:06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-27 23:02:00' WHERE id = 60 AND fuel_date = '2026-01-27T16:02:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-29 08:39:00' WHERE id = 61 AND fuel_date = '2026-01-29T01:39:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-30 02:55:00' WHERE id = 62 AND fuel_date = '2026-01-29T19:55:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-01-31 06:45:00' WHERE id = 63 AND fuel_date = '2026-01-30T23:45:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-01 06:21:12' WHERE id = 64 AND fuel_date = '2026-01-31T23:21:12';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-02 03:12:03' WHERE id = 65 AND fuel_date = '2026-02-01T20:12:03';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-04 14:46:37' WHERE id = 66 AND fuel_date = '2026-02-04T07:46:37';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-04 22:00:22' WHERE id = 67 AND fuel_date = '2026-02-04T15:00:22';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-06 05:57:48' WHERE id = 68 AND fuel_date = '2026-02-05T22:57:48';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-07 20:19:07' WHERE id = 69 AND fuel_date = '2026-02-07T13:19:07';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-10 03:18:00' WHERE id = 70 AND fuel_date = '2026-02-09T20:18:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-25 22:27:17' WHERE id = 71 AND fuel_date = '2026-02-25T15:27:17';
UPDATE fleet_fuel_log SET fuel_date = '2026-03-03 08:27:19' WHERE id = 72 AND fuel_date = '2026-03-03T01:27:19';
UPDATE fleet_fuel_log SET fuel_date = '2026-03-14 22:18:00' WHERE id = 73 AND fuel_date = '2026-03-14T16:18:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-03-21 11:40:49' WHERE id = 74 AND fuel_date = '2026-03-21T05:40:49';
UPDATE fleet_fuel_log SET fuel_date = '2026-03-26 23:41:45' WHERE id = 75 AND fuel_date = '2026-03-26T17:41:45';
UPDATE fleet_fuel_log SET fuel_date = '2026-03-30 23:10:30' WHERE id = 76 AND fuel_date = '2026-03-30T17:10:30';
UPDATE fleet_fuel_log SET fuel_date = '2026-04-19 15:11:49' WHERE id = 77 AND fuel_date = '2026-04-19T09:11:49';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-10 00:30:00' WHERE id = 78 AND fuel_date = '2026-05-09T18:30:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-08 00:55:28' WHERE id = 79 AND fuel_date = '2026-05-07T18:55:28';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-05 22:22:00' WHERE id = 80 AND fuel_date = '2026-05-05T16:22:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-04-23 21:27:28' WHERE id = 81 AND fuel_date = '2026-04-23T15:27:28';
UPDATE fleet_fuel_log SET fuel_date = '2026-04-05 10:02:34' WHERE id = 82 AND fuel_date = '2026-04-05T04:02:34';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-28 22:57:39' WHERE id = 83 AND fuel_date = '2026-05-28T16:57:39';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-09 04:45:20' WHERE id = 84 AND fuel_date = '2026-02-08T21:45:20';
UPDATE fleet_fuel_log SET fuel_date = '2026-02-07 13:47:51' WHERE id = 85 AND fuel_date = '2026-02-07T06:47:51';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-08 21:37:36' WHERE id = 86 AND fuel_date = '2026-06-08T15:37:36';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-18 16:01:10' WHERE id = 89 AND fuel_date = '2026-05-18T10:01:10';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-18 01:33:04' WHERE id = 90 AND fuel_date = '2026-06-17T19:33:04';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-25 20:14:50' WHERE id = 91 AND fuel_date = '2026-06-25T14:14:50';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-17 06:00:00' WHERE id = 92 AND fuel_date = '2026-07-17';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-18 01:39:00' WHERE id = 93 AND fuel_date = '2026-07-17T19:39:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-18 01:28:00' WHERE id = 94 AND fuel_date = '2026-07-17T19:28:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-09 07:35:26' WHERE id = 95 AND fuel_date = '2026-07-09T01:35:26.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-20 22:38:00' WHERE id = 96 AND fuel_date = '2026-05-20T16:38:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-08 18:44:00' WHERE id = 97 AND fuel_date = '2026-07-08T12:44:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-08 00:55:00' WHERE id = 98 AND fuel_date = '2026-05-07T18:55:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-10 00:30:00' WHERE id = 99 AND fuel_date = '2026-05-09T18:30:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-18 16:01:00' WHERE id = 100 AND fuel_date = '2026-05-18T10:01:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-07 04:53:00' WHERE id = 101 AND fuel_date = '2025-11-06T21:53:00.000000-07:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-04 05:25:00' WHERE id = 102 AND fuel_date = '2025-11-03T22:25:00.000000-07:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-02 16:44:00' WHERE id = 103 AND fuel_date = '2025-11-02T09:44:00.000000-07:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-01 14:13:00' WHERE id = 104 AND fuel_date = '2025-11-01T08:13:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-11-01 03:37:00' WHERE id = 105 AND fuel_date = '2025-10-31T21:37:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-10-31 12:44:00' WHERE id = 106 AND fuel_date = '2025-10-31T06:44:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-04 02:41:13' WHERE id = 107 AND fuel_date = '2026-07-03T20:41:13.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-05-28 21:37:00' WHERE id = 108 AND fuel_date = '2026-05-28T15:37:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-25 20:14:00' WHERE id = 109 AND fuel_date = '2026-06-25T14:14:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-18 01:38:00' WHERE id = 110 AND fuel_date = '2026-06-17T19:38:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-06-08 21:37:48' WHERE id = 111 AND fuel_date = '2026-06-08T15:37:48.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2025-12-29 07:53:00' WHERE id = 112 AND fuel_date = '2025-12-29T00:53:00.000000-07:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-21 20:42:00' WHERE id = 113 AND fuel_date = '2026-07-21T14:42:00.000000-06:00';
UPDATE fleet_fuel_log SET fuel_date = '2026-07-29 02:33:39' WHERE id = 114 AND fuel_date = '2026-07-28T20:33:39.000000-06:00';
