@echo off
:: ============================================================
:: RMPG Flex — Enable Kiosk Shell Mode (FZ-55 / Windows)
:: ============================================================
:: Run this script AS ADMINISTRATOR from Command Prompt.
:: It writes the Windows Winlogon Shell registry key so the FZ-55
:: boots directly into RMPG Flex instead of Windows Explorer.
::
:: The script auto-detects whether to use:
::   (A) A built installer (.exe) in Program Files — preferred
::   (B) The source-run launcher (this repo's desktop/ directory)
::
:: UNDO: run disable-kiosk.cmd as Administrator to restore explorer.exe
:: IN-APP: Settings → OS tab → Kiosk Mode → Enable (requires admin login)
:: ESCAPE: Ctrl+Alt+Shift+F12 while FlexOS is running
:: ============================================================

setlocal EnableDelayedExpansion

:: ── Admin check ──────────────────────────────────────────────
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo  ERROR: This script must be run as Administrator.
    echo  Right-click enable-kiosk.cmd and choose "Run as administrator".
    echo.
    pause
    exit /b 1
)

:: ── Locate the RMPG Flex executable ──────────────────────────
set "FLEX_EXE="

:: Option A: installed build (NSIS perMachine default path)
if exist "%ProgramFiles%\RMPG Flex\RMPG Flex.exe" (
    set "FLEX_EXE=%ProgramFiles%\RMPG Flex\RMPG Flex.exe"
    echo  [KIOSK] Using installed build: !FLEX_EXE!
    goto :write_registry
)

:: Option B: built locally — dist/win-unpacked
set "REPO_ROOT=%~dp0..\.."
if exist "%REPO_ROOT%\desktop\dist\win-unpacked\RMPG Flex.exe" (
    set "FLEX_EXE=%REPO_ROOT%\desktop\dist\win-unpacked\RMPG Flex.exe"
    echo  [KIOSK] Using local build: !FLEX_EXE!
    goto :write_registry
)

:: Option C: source-run via launcher script
:: Create a small launcher .cmd at a stable path so the shell key
:: points to something that survives reboots (node must be in PATH).
set "LAUNCHER=%REPO_ROOT%\desktop\scripts\rmpg-flex-kiosk-launcher.cmd"
echo  [KIOSK] No built .exe found — creating source-run launcher.
echo  [KIOSK] Launcher: !LAUNCHER!
(
    echo @echo off
    echo :: Auto-generated kiosk launcher — do not edit manually
    echo :: Regenerated by enable-kiosk.cmd when no installed .exe was found.
    echo cd /d "%REPO_ROOT%\desktop"
    echo set "NODE_PATH="
    for /f "delims=" %%i in ('where node 2^>nul') do @if "!NODE_PATH!"=="" set "NODE_PATH=%%~dpi"
    echo if defined NODE_PATH set "PATH=!NODE_PATH!;%%PATH%%"
    echo npx electron . 2^>^>"%REPO_ROOT%\desktop\kiosk-launcher.log"
) > "!LAUNCHER!"
if not exist "!LAUNCHER!" (
    echo  ERROR: Could not write launcher script. Check permissions.
    pause
    exit /b 1
)
set "FLEX_EXE=!LAUNCHER!"

:write_registry
:: ── Write the Winlogon Shell key ─────────────────────────────
echo.
echo  [KIOSK] Writing registry key...
echo  [KIOSK]   HKLM\...\Winlogon\Shell = "!FLEX_EXE!"
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" ^
    /v Shell /t REG_SZ /d "\"!FLEX_EXE!\"" /f >nul 2>&1
if %errorlevel% neq 0 (
    echo  ERROR: reg add failed ^(exit code %errorlevel%^).
    echo  Make sure you are running as Administrator.
    pause
    exit /b 1
)

:: ── Verify ───────────────────────────────────────────────────
for /f "tokens=3*" %%a in (
    'reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v Shell 2^>nul'
) do set "SHELL_VALUE=%%a %%b"
echo.
echo  [KIOSK] Registry updated successfully.
echo  [KIOSK] Shell = !SHELL_VALUE!
echo.
echo  ============================================================
echo   Kiosk Mode ENABLED
echo  ============================================================
echo   This machine will boot directly into RMPG Flex on next restart.
echo   Windows Explorer will not load.
echo.
echo   To exit kiosk once running: Ctrl+Alt+Shift+F12 (admin password)
echo   To disable kiosk:           run disable-kiosk.cmd as Administrator
echo  ============================================================
echo.
set /p "RESTART=Restart now to apply? [Y/N]: "
if /i "!RESTART!"=="Y" shutdown /r /t 5 /c "Applying RMPG Flex Kiosk Mode"

endlocal
