ALTER TABLE calls_for_service ADD COLUMN beat_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN beat_descriptor TEXT;
ALTER TABLE calls_for_service ADD COLUMN contract_id TEXT;
ALTER TABLE calls_for_service ADD COLUMN priority_score INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN response_time_seconds REAL;
ALTER TABLE calls_for_service ADD COLUMN status_changed_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN onscene_duration_seconds REAL;
ALTER TABLE calls_for_service ADD COLUMN overdue_notified TEXT;
ALTER TABLE calls_for_service ADD COLUMN received_at TEXT;
ALTER TABLE incidents ADD COLUMN occurred_date TEXT;
ALTER TABLE incidents ADD COLUMN occurred_time TEXT;
ALTER TABLE incidents ADD COLUMN end_date TEXT;
ALTER TABLE incidents ADD COLUMN end_time TEXT;
ALTER TABLE incidents ADD COLUMN weather_conditions TEXT;
ALTER TABLE incidents ADD COLUMN lighting_conditions TEXT;
ALTER TABLE incidents ADD COLUMN injuries INTEGER  0;
ALTER TABLE incidents ADD COLUMN injury_description TEXT;
ALTER TABLE incidents ADD COLUMN damage_estimate REAL;
ALTER TABLE incidents ADD COLUMN damage_description TEXT;
ALTER TABLE incidents ADD COLUMN weapons_involved TEXT;
ALTER TABLE incidents ADD COLUMN alcohol_involved INTEGER  0;
ALTER TABLE incidents ADD COLUMN drugs_involved INTEGER  0;
ALTER TABLE incidents ADD COLUMN domestic_violence INTEGER  0;
ALTER TABLE incidents ADD COLUMN review_notes TEXT;
ALTER TABLE incidents ADD COLUMN disposition TEXT;
ALTER TABLE incidents ADD COLUMN zone_beat TEXT;
ALTER TABLE incidents ADD COLUMN section_id TEXT;
ALTER TABLE incidents ADD COLUMN sector_id TEXT;
ALTER TABLE incidents ADD COLUMN zone_id TEXT;
ALTER TABLE incidents ADD COLUMN beat_id TEXT;
