ALTER TABLE evidence ADD COLUMN photo_taken INTEGER  0;
ALTER TABLE evidence ADD COLUMN lab_submitted INTEGER  0;
ALTER TABLE evidence ADD COLUMN lab_case_number TEXT;
ALTER TABLE evidence ADD COLUMN lab_name TEXT;
ALTER TABLE evidence ADD COLUMN disposal_method TEXT;
ALTER TABLE evidence ADD COLUMN disposal_date TEXT;
ALTER TABLE evidence ADD COLUMN disposal_authorized_by TEXT;
ALTER TABLE evidence ADD COLUMN serial_number TEXT;
ALTER TABLE evidence ADD COLUMN brand TEXT;
ALTER TABLE evidence ADD COLUMN model TEXT;
ALTER TABLE evidence ADD COLUMN estimated_value REAL;
ALTER TABLE evidence ADD COLUMN category TEXT;
ALTER TABLE evidence ADD COLUMN notes TEXT;
ALTER TABLE evidence ADD COLUMN updated_at TEXT;
ALTER TABLE evidence ADD COLUMN retention_until TEXT;
ALTER TABLE evidence ADD COLUMN disposition TEXT;
ALTER TABLE evidence ADD COLUMN storage_temperature REAL;
ALTER TABLE evidence ADD COLUMN is_biological INTEGER  0;
ALTER TABLE properties ADD COLUMN city TEXT;
ALTER TABLE properties ADD COLUMN state TEXT;
ALTER TABLE properties ADD COLUMN zip TEXT;
ALTER TABLE properties ADD COLUMN access_instructions TEXT;
ALTER TABLE properties ADD COLUMN is_active INTEGER NOT NULL  1;
ALTER TABLE properties ADD COLUMN updated_at TEXT;
ALTER TABLE properties ADD COLUMN notes TEXT;
ALTER TABLE properties ADD COLUMN business_type TEXT;
ALTER TABLE properties ADD COLUMN structure_type TEXT;
ALTER TABLE properties ADD COLUMN occupancy_status TEXT;
ALTER TABLE properties ADD COLUMN year_built TEXT;
ALTER TABLE properties ADD COLUMN square_footage TEXT;
