ALTER TABLE calls_for_service ADD COLUMN archived_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN responding_officer TEXT;
ALTER TABLE calls_for_service ADD COLUMN secondary_type TEXT;
ALTER TABLE calls_for_service ADD COLUMN contact_method TEXT;
ALTER TABLE calls_for_service ADD COLUMN scene_safety TEXT;
ALTER TABLE calls_for_service ADD COLUMN weather_conditions TEXT;
ALTER TABLE calls_for_service ADD COLUMN lighting_conditions TEXT;
ALTER TABLE calls_for_service ADD COLUMN num_victims INTEGER;
ALTER TABLE calls_for_service ADD COLUMN alcohol_involved INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN drugs_involved INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN domestic_violence INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN supervisor_notified INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN le_notified INTEGER  0;
ALTER TABLE calls_for_service ADD COLUMN le_agency TEXT;
ALTER TABLE calls_for_service ADD COLUMN le_case_number TEXT;
ALTER TABLE calls_for_service ADD COLUMN damage_estimate REAL;
ALTER TABLE calls_for_service ADD COLUMN damage_description TEXT;
ALTER TABLE calls_for_service ADD COLUMN action_taken TEXT;
ALTER TABLE calls_for_service ADD COLUMN updated_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN received_at TEXT;
ALTER TABLE calls_for_service ADD COLUMN previous_status TEXT;
ALTER TABLE calls_for_service ADD COLUMN client_id INTEGER;
ALTER TABLE calls_for_service ADD COLUMN starting_mileage REAL;
ALTER TABLE calls_for_service ADD COLUMN ending_mileage REAL;
ALTER TABLE calls_for_service ADD COLUMN case_id INTEGER;
ALTER TABLE calls_for_service ADD COLUMN case_number TEXT;
ALTER TABLE calls_for_service ADD COLUMN dispatch_code TEXT;
ALTER TABLE calls_for_service ADD COLUMN section_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN sector_name TEXT;
ALTER TABLE calls_for_service ADD COLUMN zone_name TEXT;
