ALTER TABLE ofac_sdn_addresses ADD COLUMN add_num INTEGER;
ALTER TABLE ofac_sdn_addresses ADD COLUMN add_remarks TEXT;
ALTER TABLE ofac_sdn_ids ADD COLUMN remarks TEXT;
ALTER TABLE cases ADD COLUMN deadline TEXT;
ALTER TABLE cases ADD COLUMN sla_hours INTEGER;
ALTER TABLE court_events ADD COLUMN continuance_count INTEGER  0;
ALTER TABLE court_events ADD COLUMN defendant_dob TEXT;
ALTER TABLE court_events ADD COLUMN bail_amount REAL;
ALTER TABLE court_events ADD COLUMN bond_status TEXT;
ALTER TABLE court_events ADD COLUMN surety_info TEXT;
ALTER TABLE court_events ADD COLUMN judge_notes TEXT;
ALTER TABLE court_events ADD COLUMN prosecutor_phone TEXT;
ALTER TABLE court_events ADD COLUMN prosecutor_email TEXT;
ALTER TABLE email_cache ADD COLUMN owner_user_id INTEGER;
ALTER TABLE email_rules ADD COLUMN owner_user_id INTEGER;
ALTER TABLE bolos ADD COLUMN auto_expire_hours INTEGER;
ALTER TABLE bolos ADD COLUMN expired_at TEXT;
ALTER TABLE fleet_vehicles ADD COLUMN total_maintenance_cost REAL  0;
ALTER TABLE fleet_vehicles ADD COLUMN total_fuel_cost REAL  0;
ALTER TABLE fleet_vehicles ADD COLUMN total_trips INTEGER  0;
ALTER TABLE fleet_vehicles ADD COLUMN avg_mpg REAL;
ALTER TABLE fleet_vehicles ADD COLUMN next_service_mileage INTEGER;
ALTER TABLE patrol_scans ADD COLUMN weather_json TEXT;
ALTER TABLE trespass_orders ADD COLUMN subject_photo_url TEXT;
ALTER TABLE offender_alerts ADD COLUMN alert_latitude REAL;
ALTER TABLE offender_alerts ADD COLUMN alert_longitude REAL;
ALTER TABLE offender_alerts ADD COLUMN alert_address TEXT;
ALTER TABLE offender_alerts ADD COLUMN alert_enabled INTEGER  1;
ALTER TABLE dashcam_videos ADD COLUMN incident_id INTEGER;
ALTER TABLE serve_queue ADD COLUMN recipient_person_id INTEGER;
