ALTER TABLE citations ADD COLUMN vehicle_model TEXT;
ALTER TABLE citations ADD COLUMN vehicle_color TEXT;
ALTER TABLE citations ADD COLUMN vehicle_id INTEGER;
ALTER TABLE citations ADD COLUMN speed_recorded INTEGER;
ALTER TABLE citations ADD COLUMN speed_limit INTEGER;
ALTER TABLE citations ADD COLUMN radar_type TEXT;
ALTER TABLE citations ADD COLUMN bac_level REAL;
ALTER TABLE citations ADD COLUMN bond_amount REAL;
ALTER TABLE citations ADD COLUMN bond_type TEXT;
ALTER TABLE citations ADD COLUMN is_warning INTEGER  0;
ALTER TABLE citations ADD COLUMN is_equipment_violation INTEGER  0;
ALTER TABLE citations ADD COLUMN weather_conditions TEXT;
ALTER TABLE citations ADD COLUMN road_conditions TEXT;
ALTER TABLE citations ADD COLUMN accident_related INTEGER  0;
ALTER TABLE citations ADD COLUMN dui_related INTEGER  0;
ALTER TABLE citations ADD COLUMN school_zone INTEGER  0;
ALTER TABLE citations ADD COLUMN construction_zone INTEGER  0;
ALTER TABLE citations ADD COLUMN commercial_vehicle INTEGER  0;
ALTER TABLE citations ADD COLUMN hazmat INTEGER  0;
ALTER TABLE citations ADD COLUMN voided_reason TEXT;
ALTER TABLE citations ADD COLUMN voided_by INTEGER;
ALTER TABLE citations ADD COLUMN voided_at TEXT;
ALTER TABLE citations ADD COLUMN court_time TEXT;
ALTER TABLE citations ADD COLUMN court_room TEXT;
ALTER TABLE citations ADD COLUMN appearance_required INTEGER  0;
ALTER TABLE citations ADD COLUMN plea TEXT;
ALTER TABLE citations ADD COLUMN verdict TEXT;
ALTER TABLE citations ADD COLUMN sentence TEXT;
ALTER TABLE citations ADD COLUMN disposition_date TEXT;
ALTER TABLE citations ADD COLUMN case_id INTEGER;
