ALTER TABLE clients ADD COLUMN billing_cycle TEXT;
ALTER TABLE clients ADD COLUMN billing_day INTEGER;
ALTER TABLE clients ADD COLUMN discount_percent REAL  0;
ALTER TABLE clients ADD COLUMN late_fee_percent REAL  0;
ALTER TABLE clients ADD COLUMN total_invoiced REAL  0;
ALTER TABLE clients ADD COLUMN total_paid REAL  0;
ALTER TABLE clients ADD COLUMN outstanding_balance REAL  0;
ALTER TABLE clients ADD COLUMN incident_count INTEGER  0;
ALTER TABLE clients ADD COLUMN last_incident_date TEXT;
ALTER TABLE clients ADD COLUMN account_manager TEXT;
ALTER TABLE clients ADD COLUMN priority_client INTEGER  0;
ALTER TABLE clients ADD COLUMN client_since TEXT;
ALTER TABLE clients ADD COLUMN rate_per_hour REAL;
ALTER TABLE clients ADD COLUMN rate_per_incident REAL;
ALTER TABLE clients ADD COLUMN rate_per_cfs REAL;
ALTER TABLE clients ADD COLUMN email_verified INTEGER  0;
ALTER TABLE clients ADD COLUMN verification_token TEXT;
ALTER TABLE clients ADD COLUMN avatar TEXT;
ALTER TABLE clients ADD COLUMN last_active_at TEXT;
ALTER TABLE evidence ADD COLUMN evidence_number TEXT;
ALTER TABLE evidence ADD COLUMN location_found TEXT;
ALTER TABLE evidence ADD COLUMN condition TEXT;
ALTER TABLE evidence ADD COLUMN quantity INTEGER  1;
ALTER TABLE evidence ADD COLUMN release_authorized_by TEXT;
ALTER TABLE evidence ADD COLUMN released_to TEXT;
ALTER TABLE evidence ADD COLUMN release_date TEXT;
ALTER TABLE evidence ADD COLUMN collected_date TEXT;
ALTER TABLE evidence ADD COLUMN packaging_type TEXT;
ALTER TABLE evidence ADD COLUMN dimensions TEXT;
ALTER TABLE evidence ADD COLUMN weight TEXT;
