ALTER TABLE users ADD COLUMN must_change_password INTEGER  0;
ALTER TABLE users ADD COLUMN totp_secret_enc TEXT;
ALTER TABLE users ADD COLUMN totp_enabled INTEGER  0;
ALTER TABLE users ADD COLUMN totp_backup_codes TEXT;
ALTER TABLE users ADD COLUMN totp_pending_secret TEXT;
ALTER TABLE users ADD COLUMN totp_exempt INTEGER  0;
ALTER TABLE users ADD COLUMN password_history TEXT;
ALTER TABLE users ADD COLUMN password_changed_at TEXT;
ALTER TABLE users ADD COLUMN digital_signature TEXT;
ALTER TABLE users ADD COLUMN voice_rate REAL  1.0;
ALTER TABLE users ADD COLUMN voice_pitch REAL  0;
ALTER TABLE users ADD COLUMN voice_brain_enabled INTEGER  0;
ALTER TABLE users ADD COLUMN photo TEXT;
ALTER TABLE users ADD COLUMN active_case_count INTEGER  0;
ALTER TABLE units ADD COLUMN assigned_beat TEXT;
ALTER TABLE units ADD COLUMN mileage REAL;
ALTER TABLE units ADD COLUMN gps_source TEXT;
ALTER TABLE units ADD COLUMN gps_updated_at TEXT;
ALTER TABLE clients ADD COLUMN billing_email TEXT;
ALTER TABLE clients ADD COLUMN billing_address TEXT;
ALTER TABLE clients ADD COLUMN contract_type TEXT;
ALTER TABLE clients ADD COLUMN contract_value REAL;
ALTER TABLE clients ADD COLUMN payment_terms TEXT;
ALTER TABLE clients ADD COLUMN auto_renew INTEGER  0;
ALTER TABLE clients ADD COLUMN updated_at TEXT;
ALTER TABLE clients ADD COLUMN client_code TEXT;
ALTER TABLE clients ADD COLUMN industry TEXT;
ALTER TABLE clients ADD COLUMN website TEXT;
ALTER TABLE clients ADD COLUMN tax_id TEXT;
ALTER TABLE clients ADD COLUMN payment_method TEXT;
