// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "RMPGFlexConnect",
    platforms: [.iOS(.v18)],
    products: [
        .library(name: "CoreAPI", targets: ["CoreAPI"]),
        .library(name: "CoreAuth", targets: ["CoreAuth"]),
        .library(name: "CorePush", targets: ["CorePush"]),
        .library(name: "CoreLocationService", targets: ["CoreLocationService"]),
        .library(name: "CoreIDScan", targets: ["CoreIDScan"]),
        .library(name: "CoreOffline", targets: ["CoreOffline"]),
        .library(name: "DesignSystem", targets: ["DesignSystem"]),
        .library(name: "FeatureShell", targets: ["FeatureShell"]),
        .library(name: "FeatureDispatch", targets: ["FeatureDispatch"]),
        .library(name: "FeatureRecords", targets: ["FeatureRecords"]),
        .library(name: "FeatureIncidents", targets: ["FeatureIncidents"]),
        .library(name: "FeatureCases", targets: ["FeatureCases"]),
        .library(name: "FeaturePatrol", targets: ["FeaturePatrol"]),
        .library(name: "FeatureFleet", targets: ["FeatureFleet"]),
        .library(name: "FeatureServe", targets: ["FeatureServe"]),
        .library(name: "FeatureWarrants", targets: ["FeatureWarrants"]),
        .library(name: "FeatureQuickActions", targets: ["FeatureQuickActions"]),
        .library(name: "FeatureCFS", targets: ["FeatureCFS"]),
        .library(name: "FeatureDuty", targets: ["FeatureDuty"]),
        .library(name: "FeatureRunID", targets: ["FeatureRunID"]),
        .library(name: "FeatureRunPlate", targets: ["FeatureRunPlate"]),
        .library(name: "FeatureReports", targets: ["FeatureReports"]),
        .library(name: "FeatureMap", targets: ["FeatureMap"]),
    ],
    dependencies: [],
    targets: [
        .target(name: "CoreAPI", path: "Sources/CoreAPI"),
        .target(name: "DesignSystem", path: "Sources/DesignSystem"),
        .target(name: "CoreAuth", dependencies: ["CoreAPI", "DesignSystem"], path: "Sources/CoreAuth"),
        .target(name: "CorePush", dependencies: ["CoreAPI"], path: "Sources/CorePush"),
        .target(name: "CoreLocationService", dependencies: ["CoreAPI"], path: "Sources/CoreLocationService"),
        .target(name: "CoreOffline", dependencies: ["CoreAPI"], path: "Sources/CoreOffline"),
        .target(name: "CoreIDScan", dependencies: ["DesignSystem"], path: "Sources/CoreIDScan"),
        .target(name: "CoreAudioService", path: "Sources/CoreAudioService"),
        .target(name: "FeatureDispatch", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem", "CoreLocationService", "CorePush"], path: "Sources/FeatureDispatch"),
        .target(name: "FeatureRecords", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureRecords"),
        .target(name: "FeatureIncidents", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureIncidents"),
        .target(name: "FeatureCases", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureCases"),
        .target(name: "FeaturePatrol", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem", "CoreLocationService"], path: "Sources/FeaturePatrol"),
        .target(name: "FeatureFleet", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureFleet"),
        .target(name: "FeatureServe", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureServe"),
        .target(name: "FeatureWarrants", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Sources/FeatureWarrants"),
        .target(name: "FeatureQuickActions", dependencies: ["CoreAPI", "CoreIDScan", "DesignSystem", "FeatureRunPlate", "FeatureReports", "FeatureRunID"], path: "Sources/FeatureQuickActions"),
        .target(name: "FeatureCFS", dependencies: ["CoreAPI", "DesignSystem"], path: "Packages/FeatureCFS/Sources/FeatureCFS"),
        .target(name: "FeatureDuty", dependencies: ["CoreAPI", "CoreAuth", "DesignSystem"], path: "Packages/FeatureDuty/Sources/FeatureDuty"),
        .target(name: "FeatureRunID", dependencies: ["CoreAPI", "DesignSystem"], path: "Packages/FeatureRunID/Sources/FeatureRunID"),
        .target(name: "FeatureRunPlate", dependencies: ["CoreAPI", "DesignSystem"], path: "Packages/FeatureRunPlate/Sources/FeatureRunPlate"),
        .target(name: "FeatureReports", dependencies: ["CoreAPI", "CoreOffline", "DesignSystem"], path: "Packages/FeatureReports/Sources/FeatureReports"),
        .target(name: "FeatureMap", dependencies: ["CoreAPI", "CoreLocationService", "DesignSystem", "FeatureCFS"], path: "Packages/FeatureMap/Sources/FeatureMap"),
        .target(name: "FeatureShell", dependencies: [
            "CoreAPI", "CoreAuth", "DesignSystem", "CorePush",
            "FeatureDispatch", "FeatureRecords", "FeatureIncidents",
            "FeatureCases", "FeaturePatrol", "FeatureFleet",
            "FeatureServe", "FeatureWarrants", "FeatureQuickActions",
            "FeatureCFS", "FeatureDuty", "FeatureRunID",
            "FeatureRunPlate", "FeatureReports", "FeatureMap"
        ], path: "Sources/FeatureShell"),
    ]
)
