// 10 audit compliance features
export interface AuditTrail { id:string; entityType:string; entityId:string; action:string; userId:string; timestamp:string; beforeValue:any; afterValue:any; }
export function reconstructAuditTrail(entityId:string,trails:AuditTrail[]): AuditTrail[] { return trails.filter(t=>t.entityId===entityId).sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime()); }
export interface DataChange { entityType:string; changes:number; users:number; period:string; }
export function analyzeDataChanges(changes:DataChange[]): {totalChanges:number;byEntity:Record<string,number>;mostActive:string} { const be:Record<string,number>={};for(const c of changes)be[c.entityType]=(be[c.entityType]||0)+c.changes; const most=Object.entries(be).sort((a,b)=>b[1]-a[1])[0]; return{totalChanges:changes.reduce((s,c)=>s+c.changes,0),byEntity:be,mostActive:most?most[0]:'N/A'}; }
export interface UserActivity { userId:string; logins:number; actions:number; lastActive:string; ipAddresses:string[]; }
export function monitorUserActivity(users:UserActivity[]): {activeUsers:number;dormantUsers:UserActivity[]} { const now=Date.now(); return{activeUsers:users.filter(u=>now-new Date(u.lastActive).getTime()<30*86400000).length,dormantUsers:users.filter(u=>now-new Date(u.lastActive).getTime()>=30*86400000)}; }
export interface AccessReview { id:string; reviewType:string; reviewedBy:string; reviewDate:string; usersReviewed:number; accessRemoved:number; }
export function conductAccessReview(reviewer:string,users:number): AccessReview { return{id:`ar-${Date.now()}`,reviewType:'quarterly',reviewedBy:reviewer,reviewDate:new Date().toISOString().slice(0,10),usersReviewed:users,accessRemoved:0}; }
export interface SecurityIncident { id:string; incidentType:string; severity:string; reportedAt:string; resolvedAt:string|null; description:string; }
export function trackSecurityIncidents(incidents:SecurityIncident[]): {total:number;open:number;avgResolutionHours:number} { const open=incidents.filter(i=>!i.resolvedAt); const resolved=incidents.filter(i=>i.resolvedAt).map(i=>(new Date(i.resolvedAt!).getTime()-new Date(i.reportedAt).getTime())/3600000); return{total:incidents.length,open:open.length,avgResolutionHours:resolved.length>0?Math.round(resolved.reduce((s,v)=>s+v,0)/resolved.length):0}; }
export interface PolicyViolation { id:string; policyName:string; violatedBy:string; violationDate:string; severity:string; correctiveAction:string; }
export function trackPolicyViolations(violations:PolicyViolation[]): {total:number;byPolicy:Record<string,number>;repeatOffenders:string[]} { const bp:Record<string,number>={};const byUser:Record<string,number>={};for(const v of violations){bp[v.policyName]=(bp[v.policyName]||0)+1;byUser[v.violatedBy]=(byUser[v.violatedBy]||0)+1;} return{total:violations.length,byPolicy:bp,repeatOffenders:Object.entries(byUser).filter(([,c])=>c>=2).map(([u])=>u)}; }
export interface RiskAssessment { id:string; riskArea:string; likelihood:number; impact:number; riskScore:number; mitigation:string; }
export function assessRisk(area:string,likelihood:number,impact:number): RiskAssessment { const score=likelihood*impact; return{id:`risk-${Date.now()}`,riskArea:area,likelihood,impact,riskScore:score,mitigation:score>6?'High priority mitigation required':score>3?'Monitor and mitigate':'Accept risk'}; }
export interface ComplianceChecklist { id:string; checklistType:string; items:Array<{item:string;compliant:boolean;evidence:string|null}>; completedBy:string; completedAt:string; }
export function checklistComplianceRate(checklists:ComplianceChecklist[]): {averageRate:number;commonNonCompliance:string[]} { const allItems=checklists.flatMap(c=>c.items); const compliant=allItems.filter(i=>i.compliant).length; const nonCompliant=allItems.filter(i=>!i.compliant).map(i=>i.item); return{averageRate:allItems.length>0?Math.round(compliant/allItems.length*100):0,commonNonCompliance:nonCompliant}; }
export interface AuditFinding { id:string; auditId:string; finding:string; severity:'critical'|'major'|'minor'|'observation'; status:'open'|'remediated'|'accepted'; }
export function trackAuditFindings(findings:AuditFinding[]): {total:number;open:number;critical:number;remediationRate:number} { const open=findings.filter(f=>f.status==='open'); const critical=findings.filter(f=>f.severity==='critical'); return{total:findings.length,open:open.length,critical:critical.length,remediationRate:findings.length>0?Math.round(findings.filter(f=>f.status!=='open').length/findings.length*100):0}; }
export interface ComplianceDashboard { auditFindings:number; openFindings:number; policiesViolated:number; accessReviewsCompleted:number; riskScore:number; }
export function compileAuditDashboard(findings:AuditFinding[],violations:PolicyViolation[],risks:RiskAssessment[]): ComplianceDashboard { return{auditFindings:findings.length,openFindings:findings.filter(f=>f.status==='open').length,policiesViolated:violations.length,accessReviewsCompleted:0,riskScore:risks.length>0?Math.round(risks.reduce((s,r)=>s+r.riskScore,0)/risks.length):0}; }
