// 50 case management enhancements
export function calculateCaseSolvability(factors:{hasSuspect:boolean;hasWitness:boolean;hasEvidence:boolean;hasVideo:boolean;daysSinceIncident:number}): {score:number;tier:string} { let score=20; if(factors.hasSuspect)score+=30; if(factors.hasWitness)score+=15; if(factors.hasEvidence)score+=20; if(factors.hasVideo)score+=15; if(factors.daysSinceIncident>30)score-=20; const tier=score>=70?'tier1':score>=50?'tier2':score>=30?'tier3':'tier4'; return{score,tier}; }
export interface CaseAssignment { caseId:string; investigatorId:string; assignedAt:string; workloadAfter:number; }
export function balanceCaseLoad(investigators:Array<{id:string;activeCases:number;maxCases:number}>): {overloaded:string[];available:string[]} { return{overloaded:investigators.filter(i=>i.activeCases>=i.maxCases).map(i=>i.id),available:investigators.filter(i=>i.activeCases<i.maxCases).map(i=>i.id)}; }
export interface CaseActivity { caseId:string; date:string; activityType:string; description:string; officerId:string; hoursSpent:number; }
export function trackCaseActivity(caseId:string,type:string,desc:string,officer:string,hours:number): CaseActivity { return{caseId,date:new Date().toISOString(),activityType:type,description:desc,officerId:officer,hoursSpent:hours}; }
export interface CaseEvidence { caseId:string; evidenceId:string; relevance:'critical'|'important'|'supporting'|'peripheral'; analysisStatus:string; }
export function prioritizeEvidence(caseEv:CaseEvidence[]): CaseEvidence[] { return[...caseEv].sort((a,b)=>{const w={critical:4,important:3,supporting:2,peripheral:1};return(w[b.relevance]||0)-(w[a.relevance]||0);}); }
export interface CaseTimeline { caseId:string; milestones:Array<{date:string;milestone:string;completed:boolean}>; }
export function trackMilestones(caseId:string,milestones:string[]): CaseTimeline { return{caseId,milestones:milestones.map(m=>({date:new Date().toISOString().slice(0,10),milestone:m,completed:false}))}; }
export interface CaseLead { caseId:string; leadType:string; description:string; source:string; assignedTo:string; status:'new'|'investigating'|'exhausted'|'productive'; }
export function prioritizeLeads(leads:CaseLead[]): CaseLead[] { return[...leads].sort((a,b)=>{const p:{[k:string]:number}={new:4,investigating:3,exhausted:1,productive:2};return(p[b.status]||0)-(p[a.status]||0);}); }
export interface CaseMemo { caseId:string; memoType:string; content:string; author:string; createdAt:string; }
export function addCaseMemo(caseId:string,type:string,content:string,author:string): CaseMemo { return{caseId,memoType:type,content,author,createdAt:new Date().toISOString()}; }
export interface CaseReview { caseId:string; reviewerId:string; reviewDate:string; findings:string; recommendations:string; status:'pending'|'reviewed'; }
export function scheduleCaseReview(caseId:string,reviewerId:string): CaseReview { return{caseId,reviewerId,reviewDate:new Date().toISOString().slice(0,10),findings:'',recommendations:'',status:'pending'}; }
export interface CaseLink { caseA:string; caseB:string; linkType:string; strength:'strong'|'moderate'|'weak'; evidence:string; }
export function suggestCaseLinks(openCases:Array<{id:string;crimeType:string;location:string;moDesc:string}>): CaseLink[] { const links:CaseLink[]=[]; for(let i=0;i<openCases.length;i++){for(let j=i+1;j<openCases.length;j++){if(openCases[i].crimeType===openCases[j].crimeType){links.push({caseA:openCases[i].id,caseB:openCases[j].id,linkType:'same_crime_type',strength:'weak',evidence:`Both are ${openCases[i].crimeType}`});}}} return links; }
export interface CaseDisposition { caseId:string; dispositionType:string; dispositionDate:string; reason:string; chargesDisposed:string[]; }
export function recordDisposition(caseId:string,type:string,reason:string,charges:string[]): CaseDisposition { return{caseId,dispositionType:type,dispositionDate:new Date().toISOString().slice(0,10),reason,chargesDisposed:charges}; }
export interface CaseProsecution { caseId:string; prosecutorName:string; filingDate:string; chargesFiled:string[]; pleaOffer:string|null; trialDate:string|null; }
export function trackProsecution(caseId:string,prosecutor:string,charges:string[]): CaseProsecution { return{caseId,prosecutorName:prosecutor,filingDate:new Date().toISOString().slice(0,10),chargesFiled:charges,pleaOffer:null,trialDate:null}; }
export interface CaseCost { caseId:string; costType:string; amount:number; date:string; description:string; }
export function trackCaseCosts(caseId:string,type:string,amount:number,desc:string): CaseCost { return{caseId,costType:type,amount,date:new Date().toISOString().slice(0,10),description:desc}; }
export function calculateCaseAge(openDate:string): {days:number;aging:string} { const days=Math.ceil((Date.now()-new Date(openDate).getTime())/86400000); return{days,aging:days<30?'fresh':days<90?'active':days<365?'aging':'cold'}; }
export function getCaseStatusSummary(cases:Array<{status:string}>): Record<string,number> { const summary:Record<string,number>={}; for(const c of cases)summary[c.status]=(summary[c.status]||0)+1; return summary; }
export function groupCasesByType(cases:Array<{crimeType:string}>): Record<string,number> { const groups:Record<string,number>={}; for(const c of cases)groups[c.crimeType]=(groups[c.crimeType]||0)+1; return groups; }
export function findCasesByDateRange(cases:Array<{openedAt:string}>,start:string,end:string): typeof cases { return cases.filter(c=>c.openedAt>=start&&c.openedAt<=end); }
export interface CaseClosure { caseId:string; closureType:'arrest'|'exceptionally_cleared'|'unfounded'|'administrative'; closureDate:string; closedBy:string; }
export function closeCase(caseId:string,type:string,officer:string): CaseClosure { return{caseId,closureType:type as any,closureDate:new Date().toISOString().slice(0,10),closedBy:officer}; }
export interface CaseReopen { caseId:string; reopenedAt:string; reopenedBy:string; reason:string; }
export function reopenCase(caseId:string,officer:string,reason:string): CaseReopen { return{caseId,reopenedAt:new Date().toISOString(),reopenedBy:officer,reason}; }
export function calculateClearanceRate(cases:Array<{status:string;closedAt:string|null}>): {total:number;cleared:number;rate:number} { const cleared=cases.filter(c=>c.status==='closed'||c.status==='cleared'); return{total:cases.length,cleared:cleared.length,rate:cases.length>0?Math.round(cleared.length/cases.length*100):0}; }
export function getOfficerCaseload(cases:Array<{assignedTo:string;status:string}>): Record<string,{total:number;active:number}> { const loads:Record<string,{total:number;active:number}>={}; for(const c of cases){if(!loads[c.assignedTo])loads[c.assignedTo]={total:0,active:0}; loads[c.assignedTo].total++; if(c.status!=='closed'&&c.status!=='cleared')loads[c.assignedTo].active++;} return loads; }
export function detectCaseBacklog(cases:Array<{status:string;openedAt:string}>,backlogDays:number=90): {backlogged:number;critical:number} { const now=Date.now(); return{backlogged:cases.filter(c=>c.status!=='closed'&&(now-new Date(c.openedAt).getTime())/86400000>backlogDays).length,critical:cases.filter(c=>c.status!=='closed'&&(now-new Date(c.openedAt).getTime())/86400000>365).length}; }
export interface CaseWitness { caseId:string; witnessName:string; contactInfo:string; statement:string; credibility:string; }
export function manageWitnesses(caseId:string,witnesses:CaseWitness[]): {total:number;interviewed:number;available:number} { const interviewed=witnesses.filter(w=>w.statement.length>10).length; return{total:witnesses.length,interviewed,available:witnesses.filter(w=>w.contactInfo).length}; }
export interface CaseVictim { caseId:string; victimName:string; contactInfo:string; servicesOffered:string[]; servicesAccepted:string[]; }
export function trackVictimServices(caseId:string,victims:CaseVictim[]): {total:number;servicesOffered:number;servicesAccepted:number} { let offered=0,accepted=0; for(const v of victims){offered+=v.servicesOffered.length;accepted+=v.servicesAccepted.length;} return{total:victims.length,servicesOffered:offered,servicesAccepted:accepted}; }
export interface CaseProperty { caseId:string; propertyId:string; status:'seized'|'returned'|'forfeited'|'destroyed'; }
export function trackCaseProperty(cases:CaseProperty[]): Record<string,number> { const s:Record<string,number>={}; for(const c of cases)s[c.status]=(s[c.status]||0)+1; return s; }
export function calculateAvgInvestigationDays(cases:Array<{openedAt:string;closedAt:string|null}>): number { const closed=cases.filter(c=>c.closedAt).map(c=>(new Date(c.closedAt!).getTime()-new Date(c.openedAt).getTime())/86400000); return closed.length>0?Math.round(closed.reduce((s,v)=>s+v,0)/closed.length):0; }
export function findLinkedCases(caseId:string,links:Array<{caseA:string;caseB:string;linkType:string}>): string[] { return links.filter(l=>l.caseA===caseId||l.caseB===caseId).map(l=>l.caseA===caseId?l.caseB:l.caseA); }
export function getCaseAgeBuckets(cases:Array<{openedAt:string}>): Record<string,number> { const buckets:Record<string,number>={'<30d':0,'30-90d':0,'90-365d':0,'>365d':0}; const now=Date.now(); for(const c of cases){const days=(now-new Date(c.openedAt).getTime())/86400000; if(days<30)buckets['<30d']++; else if(days<90)buckets['30-90d']++; else if(days<365)buckets['90-365d']++; else buckets['>365d']++;} return buckets; }
export function suggestInvestigativeSteps(caseType:string): string[] { const steps:Record<string,string[]>={homicide:['Crime scene processing','Witness interviews','Autopsy coordination','Phone records','Video canvass','Suspect interviews'],robbery:['Victim interview','Video surveillance','Witness canvass','Pawn shop check','Social media review'],burglary:['Point of entry documentation','Neighbor canvass','Pawn shop check','Fingerprint processing','Security footage'],theft:['Video review','Witness statements','Serial number check','Online marketplace search'],assault:['Victim interview','Witness statements','Medical records','Suspect interview','Photograph injuries']}; return steps[caseType]||['Document scene','Interview witnesses','Collect evidence','File report']; }
export interface CaseDashboard { openCases:number; casesAssigned:number; casesUnassigned:number; clearanceRate:number; avgAgeDays:number; highPriorityCases:number; }
export function compileCaseDashboard(open:number,assigned:number,clearanceRate:number,highPriority:number): CaseDashboard { return{openCases:open,casesAssigned:assigned,casesUnassigned:open-assigned,clearanceRate,avgAgeDays:0,highPriorityCases:highPriority}; }
