// 10 community outreach features
export interface OutreachEvent { id:string; eventName:string; date:string; location:string; type:'neighborhood_watch'|'coffee_with_cop'|'town_hall'|'youth_program'|'senior_outreach'|'business_roundtable'; attendees:number; officersPresent:number; feedback:string|null; }
export function measureOutreachImpact(events:OutreachEvent[]): {totalEvents:number;totalAttendees:number;avgAttendance:number;byType:Record<string,number>} { const bt:Record<string,number>={};for(const e of events)bt[e.type]=(bt[e.type]||0)+1; return{totalEvents:events.length,totalAttendees:events.reduce((s,e)=>s+e.attendees,0),avgAttendance:events.length>0?Math.round(events.reduce((s,e)=>s+e.attendees,0)/events.length):0,byType:bt}; }
export interface SocialMediaCampaign { id:string; platform:string; campaignName:string; startDate:string; endDate:string; posts:number; reach:number; engagement:number; }
export function campaignROI(campaigns:SocialMediaCampaign[]): {totalReach:number;avgEngagementRate:number;bestPlatform:string} { const byPlat:Record<string,{reach:number;posts:number}>={};for(const c of campaigns){if(!byPlat[c.platform])byPlat[c.platform]={reach:0,posts:0};byPlat[c.platform].reach+=c.reach;byPlat[c.platform].posts+=c.posts;} const best=Object.entries(byPlat).sort((a,b)=>(a[1].reach/a[1].posts)-(b[1].reach/b[1].posts)).pop(); return{totalReach:campaigns.reduce((s,c)=>s+c.reach,0),avgEngagementRate:0,bestPlatform:best?best[0]:'N/A'}; }
export interface CitizenAcademy { id:string; classNumber:string; startDate:string; endDate:string; participants:number; graduates:number; }
export function trackCitizenAcademy(academies:CitizenAcademy[]): {total:number;totalGraduates:number;graduationRate:number} { const grads=academies.reduce((s,a)=>s+a.graduates,0); const parts=academies.reduce((s,a)=>s+a.participants,0); return{total:academies.length,totalGraduates:grads,graduationRate:parts>0?Math.round(grads/parts*100):0}; }
export interface CommunitySurvey { id:string; topic:string; responses:number; avgSatisfaction:number; keyFindings:string[]; date:string; }
export function analyzeSurveys(surveys:CommunitySurvey[]): {avgSatisfaction:number;totalResponses:number} { const avg=surveys.length>0?Math.round(surveys.reduce((s,sv)=>s+sv.avgSatisfaction,0)/surveys.length*10)/10:0; return{avgSatisfaction:avg,totalResponses:surveys.reduce((s,sv)=>s+sv.responses,0)}; }
export interface SchoolProgram { id:string; schoolName:string; programType:'DARE'|'GREAT'|'SRO'|'explorer'|'mentoring'; studentsReached:number; sessions:number; }
export function evaluateSchoolPrograms(programs:SchoolProgram[]): {totalStudents:number;byType:Record<string,number>} { const bt:Record<string,number>={};for(const p of programs)bt[p.programType]=(bt[p.programType]||0)+p.studentsReached; return{totalStudents:programs.reduce((s,p)=>s+p.studentsReached,0),byType:bt}; }
export interface FaithBasedPartnership { id:string; organization:string; faithTradition:string; contactName:string; partnershipType:string; }
export function manageFBP(partnerships:FaithBasedPartnership[]): {total:number;byTradition:Record<string,number>} { const bt:Record<string,number>={};for(const p of partnerships)bt[p.faithTradition]=(bt[p.faithTradition]||0)+1; return{total:partnerships.length,byTradition:bt}; }
export interface CrisisInterventionTeam { id:string; teamName:string; members:number; callsThisMonth:number; hospitalDiversions:number; }
export function evaluateCIT(cit:CrisisInterventionTeam): {diversionRate:number;effectiveness:string} { const rate=cit.callsThisMonth>0?Math.round(cit.hospitalDiversions/cit.callsThisMonth*100):0; return{diversionRate:rate,effectiveness:rate>50?'highly_effective':rate>25?'effective':'needs_improvement'}; }
export interface SpecialOlympics { id:string; eventName:string; date:string; officersVolunteering:number; athletes:number; fundsRaised:number; }
export function trackSOLEvent(event:SpecialOlympics): {engagementScore:number} { return{engagementScore:event.officersVolunteering*2+Math.round(event.fundsRaised/100)}; }
export interface CommunityDashboard { eventsThisMonth:number; totalAttendees:number; satisfactionAvg:number; programsActive:number; }
export function compileCommunityDashboard(events:OutreachEvent[],surveys:CommunitySurvey[]): CommunityDashboard { const avg=surveys.length>0?Math.round(surveys.reduce((s,sv)=>s+sv.avgSatisfaction,0)/surveys.length*10)/10:0; return{eventsThisMonth:events.length,totalAttendees:events.reduce((s,e)=>s+e.attendees,0),satisfactionAvg:avg,programsActive:0}; }
