// RMPG Flex — Community Relations — 10 features
export interface CommunityProgram { id:string; programName:string; programType:string; startDate:string; participants:number; budget:number; outcomes:string[]; coordinator:string; }
export function evaluateProgramImpact(programs:CommunityProgram[]): {totalParticipants:number;avgPerProgram:number;byType:Record<string,number>} { const bt:Record<string,number>={};for(const p of programs)bt[p.programType]=(bt[p.programType]||0)+p.participants; return{totalParticipants:programs.reduce((s,p)=>s+p.participants,0),avgPerProgram:programs.length>0?Math.round(programs.reduce((s,p)=>s+p.participants,0)/programs.length):0,byType:bt}; }
export interface CommunityMeeting { id:string; date:string; location:string; topic:string; attendees:number; officersPresent:number; feedback:string|null; }
export function trackMeetings(meetings:CommunityMeeting[]): {total:number;totalAttendees:number;avgAttendance:number;avgOfficers:number} { return{total:meetings.length,totalAttendees:meetings.reduce((s,m)=>s+m.attendees,0),avgAttendance:meetings.length>0?Math.round(meetings.reduce((s,m)=>s+m.attendees,0)/meetings.length):0,avgOfficers:meetings.length>0?Math.round(meetings.reduce((s,m)=>s+m.officersPresent,0)/meetings.length):0}; }
export interface BusinessContact { id:string; businessName:string; contactName:string; phone:string; lastContact:string; nextContact:string; issues:string[]; }
export function getOverdueContacts(contacts:BusinessContact[]): BusinessContact[] { const now=new Date(); return contacts.filter(c=>new Date(c.nextContact)<now); }
export interface FaithLeader { id:string; name:string; organization:string; faithTradition:string; contactInfo:string; partnershipActive:boolean; }
export function getPartnershipsByTradition(leaders:FaithLeader[]): Record<string,number> { const bt:Record<string,number>={};for(const l of leaders)if(l.partnershipActive)bt[l.faithTradition]=(bt[l.faithTradition]||0)+1; return bt; }
export interface SchoolLiaison { officerId:string; schoolName:string; assignedDate:string; hoursPerWeek:number; incidentsHandled:number; programsDelivered:number; }
export function evaluateSchoolProgram(liaisons:SchoolLiaison[]): {totalSchools:number;totalHours:number;avgIncidents:number;programsPerSchool:number} { return{totalSchools:liaisons.length,totalHours:liaisons.reduce((s,l)=>s+l.hoursPerWeek,0)*52,avgIncidents:liaisons.length>0?Math.round(liaisons.reduce((s,l)=>s+l.incidentsHandled,0)/liaisons.length):0,programsPerSchool:liaisons.length>0?Math.round(liaisons.reduce((s,l)=>s+l.programsDelivered,0)/liaisons.length):0}; }
export interface SocialMediaPost { id:string; platform:string; content:string; postedAt:string; likes:number; shares:number; comments:number; }
export function trackSocialEngagement(posts:SocialMediaPost[]): {totalPosts:number;totalEngagement:number;avgPerPost:number;bestPlatform:string} { const bp:Record<string,{total:number;count:number}>={};for(const p of posts){if(!bp[p.platform])bp[p.platform]={total:0,count:0};bp[p.platform].total+=p.likes+p.shares+p.comments;bp[p.platform].count++;} const best=Object.entries(bp).sort((a,b)=>(a[1].total/a[1].count)-(b[1].total/b[1].count)).pop(); return{totalPosts:posts.length,totalEngagement:posts.reduce((s,p)=>s+p.likes+p.shares+p.comments,0),avgPerPost:posts.length>0?Math.round(posts.reduce((s,p)=>s+p.likes+p.shares+p.comments,0)/posts.length):0,bestPlatform:best?best[0]:'N/A'}; }
export interface CommunityDashboard { activePrograms:number; meetingsThisMonth:number; socialReach:number; businessContacts:number; schoolPrograms:number; }
export function compileCommunityDashboard(programs:CommunityProgram[],meetings:CommunityMeeting[],posts:SocialMediaPost[],schools:SchoolLiaison[]): CommunityDashboard { return{activePrograms:programs.length,meetingsThisMonth:meetings.length,socialReach:posts.reduce((s,p)=>s+p.likes+p.shares+p.comments,0),businessContacts:0,schoolPrograms:schools.length}; }
