// 10 data export features
export interface ExportJob { id:string; exportType:string; format:'csv'|'json'|'xml'|'pdf'|'excel'; filters:Record<string,any>; recordCount:number; status:'queued'|'processing'|'completed'|'failed'; fileUrl:string|null; }
export function createExportJob(type:string,format:string,filters:Record<string,any>,count:number): ExportJob { return{id:`exp-${Date.now()}`,exportType:type,format:format as any,filters,recordCount:count,status:'queued',fileUrl:null}; }
export interface ScheduledExport { id:string; exportType:string; schedule:'daily'|'weekly'|'monthly'; nextRun:string; recipients:string[]; lastRun:string|null; }
export function scheduleRecurringExport(type:string,schedule:string,recipients:string[]): ScheduledExport { const next=new Date();if(schedule==='weekly')next.setDate(next.getDate()+7); if(schedule==='monthly')next.setMonth(next.getMonth()+1); return{id:`sexp-${Date.now()}`,exportType:type,schedule:schedule as any,nextRun:next.toISOString(),recipients,lastRun:null}; }
export interface ExportTemplate { id:string; name:string; columns:string[]; sortField:string; sortDirection:'asc'|'desc'; filters:Record<string,any>; }
export function applyExportTemplate(template:ExportTemplate,records:Record<string,any>[]): Record<string,any>[] { let result=records.map(r=>{const out:Record<string,any>={};for(const c of template.columns)out[c]=r[c]||''; return out;}); if(template.sortField)result.sort((a,b)=>String(a[template.sortField]).localeCompare(String(b[template.sortField]))*(template.sortDirection==='desc'?-1:1)); return result; }
export interface DataValidation { recordId:string; validationRules:string[]; passed:boolean; failures:string[]; }
export function validateExportData(records:Record<string,any>[],requiredFields:string[]): DataValidation[] { return records.map((r,i)=>{const failures=requiredFields.filter(f=>!r[f]); return{recordId:String(i),validationRules:requiredFields,passed:failures.length===0,failures};}); }
export interface ExportLog { exportId:string; exportedBy:string; exportedAt:string; fileSize:number; downloadCount:number; }
export function logExportActivity(exportId:string,userId:string,fileSize:number): ExportLog { return{exportId,exportedBy:userId,exportedAt:new Date().toISOString(),fileSize,downloadCount:0}; }
export interface BatchExport { batchId:string; exports:string[]; totalRecords:number; createdAt:string; }
export function createBatchExport(exportIds:string[]): BatchExport { return{batchId:`batch-${Date.now()}`,exports:exportIds,totalRecords:exportIds.length,createdAt:new Date().toISOString()}; }
export interface ComplianceExport { exportId:string; regulation:string; dataRetention:string; auditTrail:boolean; }
export function ensureCompliance(exportJob:ExportJob,regulations:string[]): ComplianceExport { return{exportId:exportJob.id,regulation:regulations.join(', '),dataRetention:'30 days',auditTrail:true}; }
export interface ExportRestriction { userId:string; allowedTypes:string[]; maxRecords:number; requiresApproval:boolean; }
export function checkExportPermissions(userId:string,exportType:string,restrictions:ExportRestriction[]): {allowed:boolean;reason:string} { const user=restrictions.find(r=>r.userId===userId); if(!user)return{allowed:false,reason:'No export permissions'}; if(!user.allowedTypes.includes(exportType))return{allowed:false,reason:`Export type ${exportType} not allowed`}; return{allowed:true,reason:''}; }
export interface ExportFormat { format:string; mimeType:string; extension:string; supportsLargeData:boolean; }
export const EXPORT_FORMATS: ExportFormat[] = [{format:'csv',mimeType:'text/csv',extension:'.csv',supportsLargeData:true},{format:'json',mimeType:'application/json',extension:'.json',supportsLargeData:true},{format:'pdf',mimeType:'application/pdf',extension:'.pdf',supportsLargeData:false},{format:'excel',mimeType:'application/vnd.ms-excel',extension:'.xlsx',supportsLargeData:true}];
export interface ExportDashboard { exportsToday:number; exportsThisMonth:number; totalRecordsExported:number; avgExportSize:number; failedExports:number; }
export function compileExportDashboard(exports:ExportJob[]): ExportDashboard { return{exportsToday:exports.length,exportsThisMonth:exports.length,totalRecordsExported:exports.reduce((s,e)=>s+e.recordCount,0),avgExportSize:0,failedExports:exports.filter(e=>e.status==='failed').length}; }
