// ============================================================
// RMPG Flex — Dispatch System Enhancements (Spillman Flex Standard)
// 50 dispatch improvements: call stacking, priority override,
// sector load balancing, ETA calculation, call batching,
// auto-close rules, dispatch tones, quick-call templates,
// multi-unit response protocols, CAD audit logging, custom
// status codes, shift-based routing, call escalation chains,
// response zone optimization, emergency button protocols,
// dispatch workload analytics, silent dispatch mode,
// call backfill, officer-initiated calls, duplicate detection,
// geocode validation, address history, call transfer protocols,
// after-hours routing, holiday schedules, weather integration,
// CAD terminal commands, quick-code favorites, supervisor
// override tracking, dispatch console layout presets.
// ============================================================

/* 1: Call Stacking */ export interface CallStack { zone:string; pending:number; dispatched:number; onscene:number; total:number; maxCapacity:number; overloaded:boolean; }
export function calculateCallStack(calls:Array<{zone:string;status:string}>, capacity:Record<string,number>): CallStack[] { const byZone:Record<string,{pending:number;dispatched:number;onscene:number}>={}; for(const c of calls){if(!byZone[c.zone])byZone[c.zone]={pending:0,dispatched:0,onscene:0}; if(c.status==='pending')byZone[c.zone].pending++; else if(c.status==='dispatched')byZone[c.zone].dispatched++; else if(c.status==='onscene')byZone[c.zone].onscene++; } return Object.entries(byZone).map(([z,d])=>{const total=d.pending+d.dispatched+d.onscene; const max=capacity[z]||20; return{zone:z,...d,total,maxCapacity:max,overloaded:total>max};}); }
/* 2: Priority Override */ export interface PriorityOverride { callId:string; originalPriority:string; newPriority:string; reason:string; authorizedBy:string; timestamp:string; }
export function validatePriorityOverride(override:PriorityOverride): {valid:boolean;requiresNotification:boolean} { const valid=['P1','P2','P3','P4'].includes(override.newPriority)&&override.reason.length>10; return{valid,requiresNotification:override.newPriority==='P1'}; }
/* 3: Sector Load Balancing */ export interface SectorLoad { sector:string; activeCalls:number; availableUnits:number; loadFactor:number; recommendReallocation:boolean; }
export function balanceSectorLoad(sectors:Array<{name:string;calls:number;units:number;maxLoad:number}>): SectorLoad[] { return sectors.map(s=>({sector:s.name,activeCalls:s.calls,availableUnits:s.units,loadFactor:s.units>0?Math.round(s.calls/s.units*100)/100:99,recommendReallocation:s.calls/s.units>s.maxLoad})); }
/* 4: ETA Calculation */ export interface ETAEstimate { callId:string; unitId:string; distanceMiles:number; speedMph:number; etaMinutes:number; trafficFactor:number; }
export function calculateETA(distanceMiles:number, speedMph:number=35, trafficFactor:number=1.0): {etaMinutes:number;arrivalTime:Date} { const eta=Math.round(distanceMiles/speedMph*60*trafficFactor); const arrival=new Date(Date.now()+eta*60000); return{etaMinutes:eta,arrivalTime:arrival}; }
/* 5: Call Batching */ export interface CallBatch { batchId:string; calls:string[]; commonZone:string; createdAt:string; assignedDispatcher:string; }
export function createCallBatch(calls:Array<{id:string;zone:string}>, zone:string): CallBatch { return {batchId:`batch-${Date.now()}`,calls:calls.filter(c=>c.zone===zone).map(c=>c.id),commonZone:zone,createdAt:new Date().toISOString(),assignedDispatcher:''}; }
/* 6: Auto-Close Rules */ export interface AutoCloseRule { id:string; ruleName:string; condition:string; inactiveMinutes:number; applyToPriorities:string[]; enabled:boolean; }
export const DEFAULT_AUTO_CLOSE: AutoCloseRule[] = [{id:'ac1',ruleName:'Admin calls 48h',condition:'status=pending AND priority=P4',inactiveMinutes:2880,applyToPriorities:['P4'],enabled:true},{id:'ac2',ruleName:'Cleared calls 24h',condition:'status=cleared',inactiveMinutes:1440,applyToPriorities:['P1','P2','P3','P4'],enabled:true}];
/* 7: Dispatch Tones */ export interface DispatchTone { id:string; toneName:string; priority:string; audioFile:string; duration:number; loop:boolean; }
export function selectDispatchTone(priority:string, tones:DispatchTone[]): DispatchTone|null { return tones.find(t=>t.priority===priority)||tones[0]||null; }
/* 8: Quick-Call Templates */ export interface QuickCallTemplate { id:string; name:string; natureCode:string; priority:string; defaultZone:string; prefillData:Record<string,string>; usageCount:number; }
export function getPopularTemplates(templates:QuickCallTemplate[]): QuickCallTemplate[] { return [...templates].sort((a,b)=>b.usageCount-a.usageCount).slice(0,10); }
/* 9: Multi-Unit Response Protocols */ export interface MultiUnitResponse { callType:string; primaryUnits:number; backupUnits:number; supervisorRequired:boolean; stagingArea:string; tacticalChannel:string; }
export const MULTI_UNIT_PROTOCOLS: Record<string,MultiUnitResponse> = { robbery_armed:{callType:'Armed Robbery',primaryUnits:3,backupUnits:2,supervisorRequired:true,stagingArea:'Nearest intersection',tacticalChannel:'TAC-1'}, shots_fired:{callType:'Shots Fired',primaryUnits:4,backupUnits:2,supervisorRequired:true,stagingArea:'Perimeter',tacticalChannel:'TAC-1'}, officer_down:{callType:'Officer Down',primaryUnits:99,backupUnits:0,supervisorRequired:true,stagingArea:'Command Post',tacticalChannel:'TAC-PRIORITY'} };
/* 10: CAD Audit Logging */ export interface CADAuditEntry { id:string; timestamp:string; userId:string; action:string; callId:string|null; details:string; ipAddress:string; }
export function logCADAction(userId:string,action:string,callId:string|null,details:string): CADAuditEntry { return {id:`cad-audit-${Date.now()}`,timestamp:new Date().toISOString(),userId,action,callId,details,ipAddress:''}; }
/* 11: Custom Status Codes */ export interface CustomStatus { code:string; label:string; color:string; category:string; requiresNote:boolean; availableForCalls:boolean; }
export function validateStatusTransition(from:string,to:string,allowedTransitions:Record<string,string[]>): {valid:boolean;reason:string} { const allowed=allowedTransitions[from]||[]; return{valid:allowed.includes(to),reason:allowed.includes(to)?'':'Invalid status transition'}; }
/* 12: Shift-Based Routing */ export interface ShiftRouting { shiftName:string; startHour:number; endHour:number; primaryZone:string; dispatcherCount:number; supervisorCount:number; }
export function getActiveShift(hour:number, shifts:ShiftRouting[]): ShiftRouting|null { return shifts.find(s=>s.startHour<=hour&&s.endHour>hour)||null; }
/* 13: Call Escalation Chains */ export interface EscalationStep { step:number; timeoutMinutes:number; action:string; notifyRoles:string[]; }
export const DEFAULT_ESCALATION: EscalationStep[] = [{step:1,timeoutMinutes:5,action:'Notify zone supervisor',notifyRoles:['supervisor']},{step:2,timeoutMinutes:10,action:'Notify watch commander',notifyRoles:['commander']},{step:3,timeoutMinutes:15,action:'Notify division chief',notifyRoles:['chief']}];
/* 14: Response Zone Optimization */ export interface ZoneOptimization { zone:string; currentCoverage:number; optimalCoverage:number; deficit:number; recommendations:string[]; }
export function optimizeZoneCoverage(zones:Array<{name:string;coverage:number;optimal:number;crimes:number}>): ZoneOptimization[] { return zones.map(z=>{const deficit=Math.max(0,z.optimal-z.coverage);return{zone:z.name,currentCoverage:z.coverage,optimalCoverage:z.optimal,deficit,recommendations:deficit>0?[`Add ${deficit} units`,'Consider overtime','Request mutual aid']:['Coverage adequate']};}); }
/* 15: Emergency Button Protocols */ export interface EmergencyButton { officerId:string; activationTime:string; location:{lat:number;lng:number}|null; status:'active'|'acknowledged'|'resolved'; respondingUnits:string[]; }
export function handleEmergencyActivation(officerId:string,location:{lat:number;lng:number}|null): EmergencyButton { return {officerId,activationTime:new Date().toISOString(),location,status:'active',respondingUnits:[]}; }
/* 16: Dispatch Workload Analytics */ export interface DispatcherWorkload { dispatcherId:string; activeCalls:number; callsHandled:number; avgHandleTime:number; stressScore:number; }
export function calculateDispatcherStress(calls:number,avgTime:number,threshold:number): {score:number;level:string;recommendBreak:boolean} { const score=Math.round(calls*avgTime/threshold*100); return{score,level:score>80?'high':score>50?'moderate':'normal',recommendBreak:score>80}; }
/* 17: Silent Dispatch Mode */ export interface SilentDispatch { callId:string; silentMode:boolean; notificationSuppressed:boolean; suppressedChannels:string[]; reason:string; }
export function enableSilentDispatch(callId:string,reason:string,channels:string[]): SilentDispatch { return {callId,silentMode:true,notificationSuppressed:true,suppressedChannels:channels,reason}; }
/* 18: Call Backfill */ export interface CallBackfill { originalCallId:string; backfillCallId:string; backfillReason:string; originalUnitCleared:boolean; }
export function generateBackfillCall(originalCallId:string,unitId:string,reason:string): CallBackfill { return {originalCallId,backfillCallId:`bf-${originalCallId}`,backfillReason:reason,originalUnitCleared:false}; }
/* 19: Officer-Initiated Calls */ export interface OfficerInitiated { officerId:string; callType:string; location:string; initiatedAt:string; mergedWithExisting:boolean; mergedCallId:string|null; }
export function createOfficerInitiatedCall(officerId:string,callType:string,location:string): OfficerInitiated { return {officerId,callType,location,initiatedAt:new Date().toISOString(),mergedWithExisting:false,mergedCallId:null}; }
/* 20: Duplicate Detection */ export interface DuplicateCandidate { callA:string; callB:string; matchType:'address'|'phone'|'name'|'coordinates'; matchScore:number; }
export function detectDuplicates(calls:Array<{id:string;address:string;phone:string;lat:number;lng:number}>): DuplicateCandidate[] { const results:DuplicateCandidate[]=[]; for(let i=0;i<calls.length;i++){for(let j=i+1;j<calls.length;j++){if(calls[i].address===calls[j].address)results.push({callA:calls[i].id,callB:calls[j].id,matchType:'address',matchScore:95});else if(calls[i].phone===calls[j].phone&&calls[i].phone)results.push({callA:calls[i].id,callB:calls[j].id,matchType:'phone',matchScore:90});}} return results; }
/* 21: Geocode Validation */ export interface GeocodeResult { address:string; latitude:number; longitude:number; confidence:'high'|'medium'|'low'; validated:boolean; }
export function validateGeocode(address:string,lat:number,lng:number,confidence:string): GeocodeResult { return {address,latitude:lat,longitude:lng,confidence:confidence as any,validated:confidence==='high'}; }
/* 22: Address History */ export interface AddressHistory { address:string; totalCalls:number; lastCallDate:string|null; callTypes:Record<string,number>; flags:string[]; }
export function checkAddressHistory(address:string,calls:Array<{address:string;natureCode:string;date:string}>): AddressHistory { const matches=calls.filter(c=>c.address===address); const types:Record<string,number>={}; for(const c of matches)types[c.natureCode]=(types[c.natureCode]||0)+1; return{address,totalCalls:matches.length,lastCallDate:matches.length>0?matches[matches.length-1].date:null,callTypes:types,flags:matches.length>10?['High call volume location']:[]}; }
/* 23: Call Transfer Protocols */ export interface CallTransfer { callId:string; fromAgency:string; toAgency:string; transferReason:string; transferredAt:string; acceptedAt:string|null; trackingNumber:string; }
export function transferCall(callId:string,toAgency:string,reason:string): CallTransfer { return {callId,fromAgency:'RMPG',toAgency,transferReason:reason,transferredAt:new Date().toISOString(),acceptedAt:null,trackingNumber:`XFER-${Date.now()}`}; }
/* 24: After-Hours Routing */ export interface AfterHoursRouting { timeRange:{start:string;end:string}; routeToAgency:string; routeToPhone:string; backupPhone:string; active:boolean; }
export function isAfterHours(time:string, routing:AfterHoursRouting): boolean { return time>=routing.timeRange.start&&time<=routing.timeRange.end; }
/* 25: Holiday Schedules */ export interface HolidaySchedule { date:string; name:string; staffingLevel:'full'|'reduced'|'skeleton'; overtimeMultiplier:number; }
export function getHolidayStaffing(date:string, schedules:HolidaySchedule[]): HolidaySchedule|null { return schedules.find(s=>s.date===date)||null; }
/* 26: Weather Integration */ export interface WeatherAlert { type:string; severity:string; affectedZones:string[]; startTime:string; endTime:string; impact:'none'|'minor'|'moderate'|'severe'; }
export function assessWeatherImpact(alert:WeatherAlert, zone:string): {affected:boolean;precautions:string[]} { const affected=alert.affectedZones.includes(zone); return{affected,precautions:affected?['Increase patrol visibility','Monitor flood-prone areas','Coordinate with road crews']:[]}; }
/* 27: CAD Terminal Commands */ export interface CADCommand { command:string; description:string; syntax:string; category:string; shortcut:string|null; }
export const CAD_COMMANDS: CADCommand[] = [{command:'NEWCALL',description:'Create new call',syntax:'NEWCALL [type] [location] [priority]',category:'dispatch',shortcut:'F1'},{command:'ASSIGN',description:'Assign unit to call',syntax:'ASSIGN [unit] [call#]',category:'dispatch',shortcut:'F2'},{command:'STATUS',description:'Update unit status',syntax:'STATUS [unit] [status]',category:'units',shortcut:'F3'},{command:'LOOKUP',description:'Look up record',syntax:'LOOKUP [name/plate/case#]',category:'records',shortcut:'F4'},{command:'CLEAR',description:'Clear a call',syntax:'CLEAR [call#] [disposition]',category:'dispatch',shortcut:'F5'}];
/* 28: Quick-Code Favorites */ export interface FavoriteCode { officerId:string; code:string; label:string; usageCount:number; lastUsed:string; }
export function getFavoriteCodes(officerId:string, favorites:FavoriteCode[]): FavoriteCode[] { return favorites.filter(f=>f.officerId===officerId).sort((a,b)=>b.usageCount-a.usageCount); }
/* 29: Supervisor Override */ export interface SupervisorOverride { overrideId:string; supervisorId:string; action:string; callId:string|null; reason:string; timestamp:string; }
export function logSupervisorOverride(supervisorId:string,action:string,callId:string|null,reason:string): SupervisorOverride { return {overrideId:`ovr-${Date.now()}`,supervisorId,action,callId,reason,timestamp:new Date().toISOString()}; }
/* 30: Console Layout Presets */ export interface ConsoleLayout { id:string; name:string; panels:Array<{panel:string;position:string;size:number;visible:boolean}>; isDefault:boolean; }
export function saveConsoleLayout(name:string,panels:ConsoleLayout['panels']): ConsoleLayout { return {id:`layout-${Date.now()}`,name,panels,isDefault:false}; }
/* 31: Call Reopen */ export interface CallReopen { callId:string; reopenedAt:string; reopenedBy:string; reason:string; originalDisposition:string; }
export function reopenCall(callId:string,officerId:string,reason:string,disposition:string): CallReopen { return{callId,reopenedAt:new Date().toISOString(),reopenedBy:officerId,reason,originalDisposition:disposition}; }
/* 32: Multi-Agency Event */ export interface MultiAgencyEvent { eventId:string; name:string; agencies:string[]; unifiedCommand:boolean; commandPost:string; frequency:string; }
export function establishUnifiedCommand(agencies:string[],location:string): MultiAgencyEvent { return{eventId:`mae-${Date.now()}`,name:'Multi-Agency Response',agencies,unifiedCommand:true,commandPost:location,frequency:'TAC-UNIFIED'}; }
/* 33: Officer Status Watchdog */ export interface StatusWatchdog { officerId:string; expectedStatus:string; lastUpdate:string; timeoutMinutes:number; alerted:boolean; }
export function monitorStatusTimeout(officers:Array<{id:string;status:string;lastUpdate:string}>,timeoutMin:number): StatusWatchdog[] { return officers.map(o=>({officerId:o.id,expectedStatus:o.status,lastUpdate:o.lastUpdate,timeoutMinutes:timeoutMin,alerted:(Date.now()-new Date(o.lastUpdate).getTime())/60000>timeoutMin})); }
/* 34: Dispatch Chat */ export interface DispatchChat { id:string; senderId:string; message:string; callId:string|null; timestamp:string; priority:'normal'|'urgent'; }
export function sendDispatchMessage(senderId:string,message:string,priority:'normal'|'urgent'='normal'): DispatchChat { return{id:`dmsg-${Date.now()}`,senderId,message,callId:null,timestamp:new Date().toISOString(),priority}; }
/* 35: Call Annotation */ export interface CallAnnotation { id:string; callId:string; annotationType:string; content:string; author:string; timestamp:string; pinned:boolean; }
export function annotateCall(callId:string,type:string,content:string,author:string): CallAnnotation { return{id:`ann-${Date.now()}`,callId,annotationType:type,content,author,timestamp:new Date().toISOString(),pinned:false}; }
/* 36: Response Time SLA */ export interface ResponseSLA { priority:string; targetSeconds:number; warningSeconds:number; criticalSeconds:number; }
export const RESPONSE_SLAS: ResponseSLA[] = [{priority:'P1',targetSeconds:480,warningSeconds:360,criticalSeconds:420},{priority:'P2',targetSeconds:900,warningSeconds:600,criticalSeconds:780},{priority:'P3',targetSeconds:2700,warningSeconds:1800,criticalSeconds:2400},{priority:'P4',targetSeconds:86400,warningSeconds:43200,criticalSeconds:72000}];
/* 37: Unit Check-In Reminder */ export interface CheckInReminder { unitId:string; lastCheckIn:string; reminderInterval:number; overdue:boolean; }
export function remindUnitCheckIn(units:Array<{id:string;lastCheckIn:string}>,intervalMin:number=30): CheckInReminder[] { return units.map(u=>({unitId:u.id,lastCheckIn:u.lastCheckIn,reminderInterval:intervalMin,overdue:(Date.now()-new Date(u.lastCheckIn).getTime())/60000>intervalMin})); }
/* 38: Dispatcher Handoff */ export interface DispatcherHandoff { outgoingDispatcher:string; incomingDispatcher:string; handoffTime:string; activeCallSummary:Record<string,number>; notes:string; }
export function prepareHandoff(outgoing:string,incoming:string,calls:Array<{status:string}>): DispatcherHandoff { const summary:Record<string,number>={}; for(const c of calls)summary[c.status]=(summary[c.status]||0)+1; return{outgoingDispatcher:outgoing,incomingDispatcher:incoming,handoffTime:new Date().toISOString(),activeCallSummary:summary,notes:''}; }
/* 39: GPS Drift Detection */ export interface GPSDrift { unitId:string; reportedLat:number; reportedLng:number; expectedLat:number; expectedLng:number; driftMeters:number; suspicious:boolean; }
export function detectGPSDrift(reported:{lat:number;lng:number},expected:{lat:number;lng:number},thresholdMeters:number=500): GPSDrift { const R=6371000; const dLat=(expected.lat-reported.lat)*Math.PI/180; const dLon=(expected.lng-reported.lng)*Math.PI/180; const a=Math.sin(dLat/2)**2+Math.cos(reported.lat*Math.PI/180)*Math.cos(expected.lat*Math.PI/180)*Math.sin(dLon/2)**2; const drift=R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); return{unitId:'',reportedLat:reported.lat,reportedLng:reported.lng,expectedLat:expected.lat,expectedLng:expected.lng,driftMeters:Math.round(drift),suspicious:drift>thresholdMeters}; }
/* 40: Dispatch Console Stats */ export interface ConsoleStats { uptimeMinutes:number; callsCreated:number; unitsAssigned:number; alertsAcknowledged:number; avgAckTimeSeconds:number; }
export function trackConsolePerformance(actions:Array<{type:string;timestamp:string}>): ConsoleStats { const calls=actions.filter(a=>a.type==='create_call').length; const assigns=actions.filter(a=>a.type==='assign_unit').length; return{uptimeMinutes:0,callsCreated:calls,unitsAssigned:assigns,alertsAcknowledged:0,avgAckTimeSeconds:0}; }
/* 41: Premise Check-In */ export interface PremiseCheckIn { callId:string; address:string; checkInTime:string; officerId:string; status:'ok'|'suspicious'|'hazard'; }
export function logPremiseCheckIn(callId:string,officerId:string,address:string,status:string): PremiseCheckIn { return{callId,address,checkInTime:new Date().toISOString(),officerId,status:status as any}; }
/* 42: Call Activity Heatmap */ export interface ActivityHeatmapCell { hour:number; day:number; callCount:number; zone:string; }
export function generateCallHeatmap(calls:Array<{hour:number;day:number;zone:string}>): ActivityHeatmapCell[] { const grid=new Map<string,number>(); for(const c of calls){const k=`${c.zone}:${c.day}:${c.hour}`; grid.set(k,(grid.get(k)||0)+1);} return Array.from(grid.entries()).map(([k,v])=>{const[z,d,h]=k.split(':'); return{hour:parseInt(h),day:parseInt(d),callCount:v,zone:z};}); }
/* 43: Unit Pairing Recommendation */ export interface UnitPair { unitA:string; unitB:string; compatibilityScore:number; reason:string; }
export function recommendUnitPairing(units:Array<{id:string;zone:string;experience:number;specialties:string[]}>): UnitPair[] { const pairs:UnitPair[]=[]; for(let i=0;i<units.length;i++){for(let j=i+1;j<units.length;j++){let score=0;if(units[i].zone===units[j].zone)score+=30; if(Math.abs(units[i].experience-units[j].experience)>2)score+=20; pairs.push({unitA:units[i].id,unitB:units[j].id,compatibilityScore:score,reason:score>40?'Recommended pairing':score>20?'Compatible':'Standard'});}} return pairs.sort((a,b)=>b.compatibilityScore-a.compatibilityScore); }
/* 44: Traffic Condition Integration */ export interface TrafficCondition { roadSegment:string; congestionLevel:'free_flow'|'moderate'|'heavy'|'gridlock'; avgSpeedMph:number; delayMinutes:number; }
export function adjustETAforTraffic(baseETA:number,traffic:TrafficCondition): {adjustedETA:number;multiplier:number} { const multipliers={free_flow:1.0,moderate:1.3,heavy:1.8,gridlock:2.5}; const mult=multipliers[traffic.congestionLevel]; return{adjustedETA:Math.round(baseETA*mult),multiplier:mult}; }
/* 45: Pre-Planned Response */ export interface PrePlannedResponse { locationType:string; defaultUnits:number; stagingArea:string; accessInstructions:string; hazards:string[]; }
export const PRE_PLANNED: Record<string,PrePlannedResponse> = { school:{locationType:'School',defaultUnits:3,stagingArea:'Main office',accessInstructions:'Check in at front office. Obtain visitor badge.',hazards:['Multiple buildings','Children present','Lockdown procedures']}, hospital:{locationType:'Hospital',defaultUnits:2,stagingArea:'ER entrance',accessInstructions:'Coordinate with hospital security.',hazards:['Biohazard materials','Mental health patients','Restricted areas']} };
/* 46: Call Priority Reassessment */ export interface PriorityReassessment { callId:string; originalPriority:string; elapsedMinutes:number; ageFactor:number; suggestsUpgrade:boolean; }
export function reassessCallPriority(calls:Array<{id:string;priority:string;createdAt:string}>): PriorityReassessment[] { const now=Date.now(); return calls.map(c=>{const elapsed=(now-new Date(c.createdAt).getTime())/60000; const factor=elapsed/60; return{callId:c.id,originalPriority:c.priority,elapsedMinutes:Math.round(elapsed),ageFactor:Math.round(factor*10)/10,suggestsUpgrade:factor>1&&c.priority!=='P1'};}); }
/* 47: Backup Unit Auto-Dispatch */ export interface AutoBackup { primaryUnitId:string; backupUnitId:string; triggerReason:string; distance:number; autoAssigned:boolean; }
export function autoDispatchBackup(primaryUnit:{id:string;location:{lat:number;lng:number}}, availableUnits:Array<{id:string;lat:number;lng:number;status:string}>): AutoBackup|null { const sorted=availableUnits.filter(u=>u.status==='available').map(u=>({...u,distance:haversine(primaryUnit.location.lat,primaryUnit.location.lng,u.lat,u.lng)})); sorted.sort((a,b)=>a.distance-b.distance); if(sorted.length===0)return null; return{primaryUnitId:primaryUnit.id,backupUnitId:sorted[0].id,triggerReason:'Auto-backup dispatched',distance:Math.round(sorted[0].distance*10)/10,autoAssigned:true}; }
function haversine(lat1:number,lng1:number,lat2:number,lng2:number):number{const R=3959;const dLat=(lat2-lat1)*Math.PI/180;const dLon=(lng2-lng1)*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
/* 48: Dispatch Zone Coverage Gaps */ export interface CoverageGap { zone:string; requiredUnits:number; actualUnits:number; gap:number; timeWindow:string; }
export function identifyCoverageGaps(zones:Array<{name:string;required:number;actual:number}>): CoverageGap[] { return zones.filter(z=>z.actual<z.required).map(z=>({zone:z.name,requiredUnits:z.required,actualUnits:z.actual,gap:z.required-z.actual,timeWindow:'Current'})); }
/* 49: Officer Distress Signal */ export interface DistressSignal { officerId:string; trigger:'no_response'|'manual'|'gps_stop'|'radio_silence'; lastContact:string; escalationLevel:number; }
export function escalateDistress(signal:DistressSignal, elapsedMinutes:number): {level:number;action:string} { if(elapsedMinutes>10)return{level:3,action:'ALL UNITS RESPOND — OFFICER DOWN PROTOCOL'}; if(elapsedMinutes>5)return{level:2,action:'Dispatch supervisor and nearest units'}; return{level:1,action:'Attempt contact via all channels'}; }
/* 50: Dispatch KPI Dashboard */ export interface DispatchKPI { callsToday:number; avgDispatchSeconds:number; avgResponseSeconds:number; callsPerDispatcher:number; unitUtilizationPct:number; }
export function calculateDispatchKPIs(calls:Array<{createdAt:string;dispatchedAt:string|null;onsceneAt:string|null}>,dispatchers:number,units:number): DispatchKPI { const dispatched=calls.filter(c=>c.dispatchedAt).map(c=>(new Date(c.dispatchedAt!).getTime()-new Date(c.createdAt).getTime())/1000); const responded=calls.filter(c=>c.onsceneAt).map(c=>(new Date(c.onsceneAt!).getTime()-new Date(c.createdAt).getTime())/1000); return{callsToday:calls.length,avgDispatchSeconds:dispatched.length>0?Math.round(dispatched.reduce((s,v)=>s+v,0)/dispatched.length):0,avgResponseSeconds:responded.length>0?Math.round(responded.reduce((s,v)=>s+v,0)/responded.length):0,callsPerDispatcher:dispatchers>0?Math.round(calls.length/dispatchers):0,unitUtilizationPct:0}; }
