// ============================================================
// RMPG Flex — Field Training Officer Program (Spillman Flex Standard)
// 10 FTO features: phase tracking, daily observation reports,
// competency evaluation, remedial training, FTO certification,
// recruit progress scoring, phase advancement, FTO workload,
// standardization evaluation, and field training analytics.
// ============================================================

/* 1: Phase Tracking */ export interface FTOPhase { recruitId:string; ftoId:string; phase:1|2|3|4; startDate:string; endDate:string|null; completedDays:number; requiredDays:number; status:'active'|'extended'|'completed'|'remedial'; }
export function checkPhaseProgress(phase:FTOPhase): {onTrack:boolean;daysRemaining:number;pctComplete:number} { const pct=phase.requiredDays>0?Math.round(phase.completedDays/phase.requiredDays*100):0; return{onTrack:phase.completedDays>=phase.requiredDays*0.9,daysRemaining:Math.max(0,phase.requiredDays-phase.completedDays),pctComplete:pct}; }
/* 2: Daily Observation Reports */ export interface DOR { id:string; recruitId:string; ftoId:string; date:string; categories:Array<{category:string;rating:1|2|3|4|5|7;notes:string}>; overallRating:number; narrative:string; }
export function scoreDOR(dor:DOR): {avg:number;criticalItems:Array<{category:string;rating:number}>} { const avg=dor.categories.length>0?Math.round(dor.categories.reduce((s,c)=>s+c.rating,0)/dor.categories.length*10)/10:0; return{avg,criticalItems:dor.categories.filter(c=>c.rating<=3)}; }
/* 3: Competency Evaluation */ export interface Competency { id:string; name:string; category:string; required:boolean; threshold:number; }
export const FTO_COMPETENCIES: Competency[]=[{id:'c1',name:'Officer Safety',category:'safety',required:true,threshold:4},{id:'c2',name:'Use of Force',category:'force',required:true,threshold:4},{id:'c3',name:'Report Writing',category:'reports',required:true,threshold:3},{id:'c4',name:'Radio Procedure',category:'comms',required:true,threshold:3},{id:'c5',name:'Vehicle Operations',category:'driving',required:true,threshold:3},{id:'c6',name:'Decision Making',category:'judgment',required:true,threshold:4},{id:'c7',name:'Tactical Communication',category:'comms',required:true,threshold:3},{id:'c8',name:'Crime Scene Management',category:'investigation',required:false,threshold:3},{id:'c9',name:'Traffic Enforcement',category:'traffic',required:false,threshold:3},{id:'c10',name:'Community Interaction',category:'community',required:false,threshold:3}];
/* 4: Remedial Training */ export interface RemedialPlan { recruitId:string; competencyId:string; startDate:string; endDate:string; exercises:number; passed:boolean; ftoId:string; }
export function needRemedial(ratings:Record<string,number>,competencies:Competency[]): RemedialPlan[] { return competencies.filter(c=>c.required&&(ratings[c.id]||0)<c.threshold).map(c=>({recruitId:'',competencyId:c.id,startDate:new Date().toISOString().slice(0,10),endDate:'',exercises:0,passed:false,ftoId:''})); }
/* 5: FTO Certification */ export interface FTOCert { ftoId:string; certifiedDate:string; expirationDate:string; recruitsTrained:number; status:'active'|'expired'|'inactive'; }
export function checkFTOCert(certs:FTOCert[]): {active:number;expired:number;avgRecruits:number} { const active=certs.filter(c=>c.status==='active'); return{active:active.length,expired:certs.filter(c=>c.status==='expired').length,avgRecruits:active.length>0?Math.round(active.reduce((s,c)=>s+c.recruitsTrained,0)/active.length):0}; }
/* 6: Recruit Progress Scoring */ export function calculateRecruitScore(phase:DOR[],target:number): {score:number;trend:string;readyForSolo:boolean} { if(phase.length===0)return{score:0,trend:'insufficient_data',readyForSolo:false}; const avg=phase.reduce((s,d)=>s+d.overallRating,0)/phase.length; const recent=phase.slice(-5).reduce((s,d)=>s+d.overallRating,0)/Math.max(1,phase.slice(-5).length); return{score:Math.round(avg*10)/10,trend:recent>avg+0.3?'improving':recent<avg-0.3?'declining':'stable',readyForSolo:avg>=target}; }
/* 7: Phase Advancement */ export function approvePhaseAdvancement(recruitId:string,currentPhase:number,dors:DOR[],competencies:Record<string,number>): {approved:boolean;conditions:string[]} { const conditions:string[]=[]; if(dors.length<10)conditions.push('Minimum 10 DORs required'); const unmet=FTO_COMPETENCIES.filter(c=>c.required&&(competencies[c.id]||0)<c.threshold); if(unmet.length>0)conditions.push(`${unmet.length} competencies below threshold`); return{approved:conditions.length===0,conditions}; }
/* 8: FTO Workload */ export interface FTOWorkload { ftoId:string; activeRecruits:number; maxRecruits:number; hoursThisMonth:number; }
export function assessFTOWorkload(ftos:FTOWorkload[]): {overloaded:string[];available:string[]} { return{overloaded:ftos.filter(f=>f.activeRecruits>=f.maxRecruits).map(f=>f.ftoId),available:ftos.filter(f=>f.activeRecruits<f.maxRecruits).map(f=>f.ftoId)}; }
/* 9: Standardization Evaluation */ export interface FTOStandardization { ftoId:string; evalDate:string; evaluator:string; dorQuality:number; feedbackQuality:number; consistency:number; overall:number; }
export function evaluateFTOStandardization(fto:FTOStandardization): {needsCalibration:boolean;recommendation:string} { return{needsCalibration:fto.overall<3.5,recommendation:fto.overall<3?'Remedial FTO training required':fto.overall<3.5?'Calibration recommended':'Meets standards'}; }
/* 10: Field Training Analytics */ export interface FTOAnalytics { period:string; recruitsInProgram:number; recruitsGraduated:number; avgDaysToComplete:number; successRate:number; dropputRate:number; remedialRate:number; }
export function compileFTOAnalytics(recruits:number,graduated:number,dropped:number,avgDays:number,remedial:number): FTOAnalytics { return{period:new Date().toISOString().slice(0,7),recruitsInProgram:recruits,recruitsGraduated:graduated,avgDaysToComplete:avgDays,successRate:recruits>0?Math.round(graduated/recruits*100):0,dropputRate:recruits>0?Math.round(dropped/recruits*100):0,remedialRate:recruits>0?Math.round(remedial/recruits*100):0}; }
