// ============================================================
// RMPG Flex — Firearm & Weapons Management (Spillman Flex Standard)
// 10 weapons features: inventory tracking, qualification
// management, ammunition logs, armor/gear inventory, less-lethal
// tracking, transfer requests, damage/loss reports, armor
// expiration, weapon assignments, and firearms statistics.
// ============================================================

/* 1: Firearm Inventory */ export interface FirearmInventory { serialNumber:string; make:string; model:string; caliber:string; type:'pistol'|'rifle'|'shotgun'|'sniper'|'submachine'; status:'issued'|'armory'|'maintenance'|'retired'|'lost'; assignedTo:string|null; purchaseDate:string; purchasePrice:number; lastInspected:string; }
export function checkInventoryStatus(inventory:FirearmInventory[]): {total:number;issued:number;armory:number;maintenance:number;readinessPct:number} { const issued=inventory.filter(f=>f.status==='issued'); return{total:inventory.length,issued:issued.length,armory:inventory.filter(f=>f.status==='armory').length,maintenance:inventory.filter(f=>f.status==='maintenance').length,readinessPct:inventory.length>0?Math.round((issued.length+inventory.filter(f=>f.status==='armory').length)/inventory.length*100):0}; }
/* 2: Qualification Management */ export interface QualRecord { officerId:string; firearmId:string; qualDate:string; courseType:'day'|'low_light'|'tactical'|'shotgun'|'rifle'; score:number; maxScore:number; passed:boolean; instructor:string; nextQualDue:string; }
export function trackQualifications(records:QualRecord[]): {total:number;passRate:number;avgScore:number;expiring30Days:QualRecord[]} { const now=new Date();const thirtyDays=new Date(now.getTime()+30*86400000); return{total:records.length,passRate:records.length>0?Math.round(records.filter(r=>r.passed).length/records.length*100):0,avgScore:records.length>0?Math.round(records.reduce((s,r)=>s+r.score,0)/records.length):0,expiring30Days:records.filter(r=>new Date(r.nextQualDue)<=thirtyDays&&new Date(r.nextQualDue)>now)}; }
/* 3: Ammunition Logs */ export interface AmmoLog { id:string; date:string; officerId:string; firearmId:string; roundsIssued:number; roundsReturned:number; roundsExpended:number; purpose:string; }
export function trackAmmoUsage(logs:AmmoLog[]): {totalIssued:number;totalExpended:number;returnRate:number;byOfficer:Record<string,number>} { const bo:Record<string,number>={};for(const l of logs){bo[l.officerId]=(bo[l.officerId]||0)+l.roundsExpended;} return{totalIssued:logs.reduce((s,l)=>s+l.roundsIssued,0),totalExpended:logs.reduce((s,l)=>s+l.roundsExpended,0),returnRate:logs.reduce((s,l)=>s+l.roundsIssued,0)>0?Math.round(logs.reduce((s,l)=>s+l.roundsReturned,0)/logs.reduce((s,l)=>s+l.roundsIssued,0)*100):0,byOfficer:bo}; }
/* 4: Armor/Gear */ export interface ArmorVest { serialNumber:string; assignedTo:string|null; level:string; manufactureDate:string; expirationDate:string; status:'issued'|'armory'|'expired'|'retired'; lastInspected:string; }
export function checkArmorExpirations(vests:ArmorVest[]): {active:number;expired:number;expiringSoon:ArmorVest[]} { const now=new Date();const ninetyDays=new Date(now.getTime()+90*86400000); return{active:vests.filter(v=>v.status==='issued'||v.status==='armory').length,expired:vests.filter(v=>new Date(v.expirationDate)<=now).length,expiringSoon:vests.filter(v=>new Date(v.expirationDate)<=ninetyDays&&new Date(v.expirationDate)>now)}; }
/* 5: Less-Lethal Tracking */ export interface LessLethalDevice { serialNumber:string; type:'taser'|'oc_spray'|'baton'|'beanbag'|'flashbang'|'pepper_ball'; status:'issued'|'armory'|'deployed'|'maintenance'; assignedTo:string|null; cartridgeUsed:number; cartridgeRemaining:number; lastDeployed:string|null; nextInspection:string; }
export function checkLessLethalReadiness(devices:LessLethalDevice[]): {ready:number;deployed:number;needsReload:LessLethalDevice[]} { return{ready:devices.filter(d=>d.status==='issued'||d.status==='armory').length,deployed:devices.filter(d=>d.status==='deployed').length,needsReload:devices.filter(d=>d.cartridgeRemaining===0&&d.status==='issued')}; }
/* 6: Transfer Requests */ export interface WeaponTransfer { weaponId:string; fromOfficer:string; toOfficer:string; requestDate:string; approvedBy:string|null; transferDate:string|null; status:'pending'|'approved'|'completed'|'denied'; }
export function approveTransfer(transfer:WeaponTransfer,approver:string): WeaponTransfer { return{...transfer,approvedBy:approver,transferDate:new Date().toISOString().slice(0,10),status:'approved'}; }
/* 7: Damage/Loss */ export interface WeaponIncident { weaponId:string; officerId:string; date:string; incidentType:'damaged'|'lost'|'stolen'|'destroyed'; description:string; policeReport:string|null; status:'reported'|'investigating'|'resolved'; }
export function reportWeaponIncident(weaponId:string,officerId:string,type:string,desc:string): WeaponIncident { return{weaponId,officerId,date:new Date().toISOString().slice(0,10),incidentType:type as any,description:desc,policeReport:null,status:'reported'}; }
/* 8: Armor Expiration */ export function getArmorWarrantyStatus(purchaseDate:string): {warrantyActive:boolean;manufacturerWarrantyYears:number;replaceByDate:string} { const d=new Date(purchaseDate);d.setFullYear(d.getFullYear()+5); return{warrantyActive:new Date()<=d,manufacturerWarrantyYears:5,replaceByDate:d.toISOString().slice(0,10)}; }
/* 9: Weapon Assignment */ export interface WeaponAssignment { weaponId:string; officerId:string; assignedDate:string; returnDate:string|null; conditionAtIssue:string; }
export function assignWeapon(weaponId:string,officerId:string): WeaponAssignment { return{weaponId,officerId,assignedDate:new Date().toISOString().slice(0,10),returnDate:null,conditionAtIssue:'good'}; }
/* 10: Firearms Dashboard */ export interface FirearmsDashboard { totalWeapons:number; issued:number; qualificationsCurrent:number; qualsExpiring:number; ammoInventory:number; armorActive:number; armorExpiring:number; }
export function compileFirearmsDashboard(inventory:FirearmInventory[],quals:QualRecord[],armor:ArmorVest[]): FirearmsDashboard { const now=new Date(); return{totalWeapons:inventory.length,issued:inventory.filter(f=>f.status==='issued').length,qualificationsCurrent:quals.filter(q=>new Date(q.nextQualDue)>now).length,qualsExpiring:quals.filter(q=>new Date(q.nextQualDue)<=new Date(now.getTime()+30*86400000)).length,ammoInventory:0,armorActive:armor.filter(a=>a.status==='issued'||a.status==='armory').length,armorExpiring:armor.filter(a=>new Date(a.expirationDate)<=new Date(now.getTime()+90*86400000)).length}; }
