// 50 fleet management enhancements
export interface FleetReservation { vehicleId:string; officerId:string; startDate:string; endDate:string; purpose:string; status:'reserved'|'active'|'completed'|'cancelled'; }
export function reserveVehicle(vehicleId:string,officerId:string,takeHome:boolean): FleetReservation { const d=new Date();const end=new Date(d);end.setDate(end.getDate()+1); return{vehicleId,officerId,startDate:d.toISOString(),endDate:end.toISOString(),purpose:takeHome?'Take-home':'Patrol',status:'reserved'}; }
export interface FuelCard { cardId:string; vehicleId:string|null; officerId:string|null; pin:string; status:'active'|'blocked'|'lost'; monthlyLimit:number; currentSpend:number; }
export function monitorFuelCardUsage(cards:FuelCard[]): {total:number;approachingLimit:FuelCard[]} { return{total:cards.length,approachingLimit:cards.filter(c=>c.currentSpend/c.monthlyLimit>0.8)}; }
export interface VehicleDowntime { vehicleId:string; reason:string; startDate:string; endDate:string|null; totalHours:number; }
export function calculateVehicleAvailability(vehicles:number,downtime:VehicleDowntime[]): {available:number;availabilityRate:number} { const down=new Set(downtime.filter(d=>!d.endDate).map(d=>d.vehicleId)); return{available:vehicles-down.size,availabilityRate:vehicles>0?Math.round((vehicles-down.size)/vehicles*100):0}; }
export interface VehicleDepreciation { vehicleId:string; purchasePrice:number; currentValue:number; annualDepreciation:number; yearsOld:number; }
export function calculateDepreciation(purchasePrice:number,yearsOld:number,residualPct:number=0.2): {currentValue:number;annualDep:number} { const totalDep=purchasePrice*(1-residualPct); const annualDep=Math.round(totalDep/Math.max(1,8)); const currentValue=Math.round(purchasePrice-annualDep*yearsOld); return{currentValue:Math.max(purchasePrice*residualPct,currentValue),annualDep}; }
export interface VehiclePool { zone:string; totalVehicles:number; available:number; reserved:number; inMaintenance:number; }
export function manageVehiclePool(pools:VehiclePool[]): {totalAvailable:number;zonesNeedMore:VehiclePool[]} { return{totalAvailable:pools.reduce((s,p)=>s+p.available,0),zonesNeedMore:pools.filter(p=>p.available<2)}; }
export interface AccidentReport { vehicleId:string; date:string; driverId:string; location:string; description:string; damageEstimate:number; atFault:boolean; policeReport:string|null; }
export function calculateAccidentRate(accidents:AccidentReport[],totalMiles:number): {total:number;perMillionMiles:number} { return{total:accidents.length,perMillionMiles:totalMiles>0?Math.round(accidents.length/(totalMiles/1000000)*10)/10:0}; }
export interface VehicleModification { vehicleId:string; modificationType:string; description:string; cost:number; installDate:string; approvedBy:string; }
export function trackModifications(mods:VehicleModification[]): {totalCost:number;byType:Record<string,number>} { const byType:Record<string,number>={};for(const m of mods)byType[m.modificationType]=(byType[m.modificationType]||0)+m.cost; return{totalCost:mods.reduce((s,m)=>s+m.cost,0),byType}; }
export interface VehicleTransfer { vehicleId:string; fromZone:string; toZone:string; transferDate:string; reason:string; }
export function transferVehicle(vehicleId:string,toZone:string,reason:string): VehicleTransfer { return{vehicleId,fromZone:'',toZone,transferDate:new Date().toISOString().slice(0,10),reason}; }
export interface VehicleRetirement { vehicleId:string; retirementDate:string; reason:string; mileage:number; disposalMethod:'auction'|'trade_in'|'donated'|'scrapped'; salePrice:number; }
export function retireVehicle(vehicleId:string,mileage:number,reason:string): VehicleRetirement { return{vehicleId,retirementDate:new Date().toISOString().slice(0,10),reason,mileage,disposalMethod:'auction',salePrice:0}; }
export interface FuelLogExtended { vehicleId:string; date:string; odometer:number; gallons:number; costPerGallon:number; station:string; fuelGrade:string; }
export function calculateFleetFuelEfficiency(logs:FuelLogExtended[]): {avgMpg:number;totalFuelCost:number;bestVehicle:string} { const byVehicle:Record<string,{miles:number;gallons:number}>={};for(let i=1;i<logs.length;i++){if(logs[i].vehicleId===logs[i-1].vehicleId){if(!byVehicle[logs[i].vehicleId])byVehicle[logs[i].vehicleId]={miles:0,gallons:0};byVehicle[logs[i].vehicleId].miles+=logs[i].odometer-logs[i-1].odometer;byVehicle[logs[i].vehicleId].gallons+=logs[i].gallons;}} const best=Object.entries(byVehicle).sort((a,b)=>(a[1].miles/a[1].gallons)-(b[1].miles/b[1].gallons)).pop(); return{avgMpg:0,totalFuelCost:logs.reduce((s,l)=>s+l.gallons*l.costPerGallon,0),bestVehicle:best?best[0]:'N/A'}; }
export interface VehicleWarranty { vehicleId:string; warrantyType:string; provider:string; startDate:string; endDate:string; coverage:string; }
export function checkWarrantyCoverage(vehicleId:string,currentDate:string,warranties:VehicleWarranty[]): {covered:boolean;activeWarranty:VehicleWarranty|null} { const active=warranties.find(w=>w.vehicleId===vehicleId&&currentDate>=w.startDate&&currentDate<=w.endDate); return{covered:!!active,activeWarranty:active||null}; }
export interface VehicleRegistration { vehicleId:string; plate:string; registrationDate:string; expirationDate:string; renewalCost:number; status:'current'|'expired'|'pending'; }
export function checkRegistrationStatus(registrations:VehicleRegistration[]): {current:number;expired:number;renewalCost:number} { const now=new Date().toISOString().slice(0,10); return{current:registrations.filter(r=>r.expirationDate>now).length,expired:registrations.filter(r=>r.expirationDate<=now).length,renewalCost:registrations.filter(r=>r.expirationDate<=now).reduce((s,r)=>s+r.renewalCost,0)}; }
export interface VehicleInspectionReport { vehicleId:string; inspectionDate:string; inspector:string; items:Array<{item:string;passed:boolean;notes:string}>; overallResult:'pass'|'fail'; }
export function calculateFleetReadiness(inspections:VehicleInspectionReport[]): {ready:number;failed:number;commonFailures:Record<string,number>} { const latest=new Map<string,boolean>();const fails:Record<string,number>={}; for(const i of inspections){if(!latest.has(i.vehicleId)||i.inspectionDate>(latest.get(i.vehicleId) as any))latest.set(i.vehicleId,i.overallResult==='pass'); if(i.overallResult==='fail')for(const item of i.items)if(!item.passed)fails[item.item]=(fails[item.item]||0)+1;} return{ready:Array.from(latest.values()).filter(v=>v).length,failed:Array.from(latest.values()).filter(v=>!v).length,commonFailures:fails}; }
export interface FleetBudget { fiscalYear:number; fuelBudget:number; maintenanceBudget:number; replacementBudget:number; totalBudget:number; spent:number; }
export function calculateBudgetUtilization(budgets:FleetBudget[]): {totalBudget:number;totalSpent:number;utilizationPct:number} { const total=budgets.reduce((s,b)=>s+b.totalBudget,0); const spent=budgets.reduce((s,b)=>s+b.spent,0); return{totalBudget:total,totalSpent:spent,utilizationPct:total>0?Math.round(spent/total*100):0}; }
export function optimizeFleetSize(vehicles:number,callsPerDay:number,avgCallMinutes:number): {recommended:number;current:number;surplus_deficit:number} { const needed=Math.ceil(callsPerDay*avgCallMinutes/60/12*1.2); return{recommended:needed,current:vehicles,surplus_deficit:vehicles-needed}; }
export interface FleetDashboard { totalVehicles:number; available:number; inMaintenance:number; avgAge:number; avgMileage:number; fuelEfficiency:number; accidentsYTD:number; }
export function compileFleetDashboard(vehicles:Array<{status:string;age:number;mileage:number}>): FleetDashboard { const available=vehicles.filter(v=>v.status==='available').length; return{totalVehicles:vehicles.length,available,inMaintenance:vehicles.length-available,avgAge:vehicles.length>0?Math.round(vehicles.reduce((s,v)=>s+v.age,0)/vehicles.length):0,avgMileage:vehicles.length>0?Math.round(vehicles.reduce((s,v)=>s+v.mileage,0)/vehicles.length):0,fuelEfficiency:0,accidentsYTD:0}; }
