/**
 * Render a Connections Analyst graph (SVG) into a PDF document.
 *
 * The PDF contains:
 *   - Header block: investigation name, seed node, generated-by, generated-at
 *   - Graph image: the SVG rasterized to PNG and embedded (best-effort; falls back
 *     gracefully if rasterization fails — the node table still renders)
 *   - Node table: TYPE / LABEL / ANNOTATION for every node
 *   - Footer disclaimer
 *
 * In jsdom, `svgElementToPngDataUrl` returns a 1x1 fallback PNG — jsPDF still
 * accepts it via addImage without throwing. See graphToPng.ts for details.
 */

import jsPDF from 'jspdf';
import { svgElementToPngDataUrl } from './graphToPng';

export interface GraphPdfMetadata {
  investigationName?: string;
  seedType?: string;
  seedId?: number;
  seedLabel?: string;
  generatedBy?: string;
  generatedAt?: Date;
}

export interface NodeRow {
  type: string;
  label: string;
  annotation?: string;
}

export async function exportGraphToPdf(
  svg: SVGSVGElement,
  nodeRows: NodeRow[],
  meta: GraphPdfMetadata = {}
): Promise<Blob> {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 36;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Connection Analysis', margin, margin + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(80);

  let y = margin + 24;
  const pushLine = (k: string, v: string) => {
    doc.text(`${k}: `, margin, y);
    doc.setFont('helvetica', 'bold');
    doc.text(v, margin + 72, y);
    doc.setFont('helvetica', 'normal');
    y += 12;
  };
  if (meta.investigationName) pushLine('Investigation', meta.investigationName);
  if (meta.seedType && meta.seedId !== undefined) {
    const seedStr = meta.seedLabel
      ? `${meta.seedLabel} (${meta.seedType} #${meta.seedId})`
      : `${meta.seedType} #${meta.seedId}`;
    pushLine('Seed', seedStr);
  }
  if (meta.generatedBy) pushLine('Generated by', meta.generatedBy);
  const ts = meta.generatedAt || new Date();
  pushLine('Generated', ts.toLocaleString());

  // Graph image — best effort, continue on failure
  let imgDataUrl: string | null = null;
  try {
    imgDataUrl = await svgElementToPngDataUrl(svg, { scale: 2, backgroundColor: '#0d2847' });
  } catch (err) {
    console.error('graphToPdf: svg rasterize failed:', err);
  }

  y += 8;
  if (imgDataUrl && imgDataUrl.startsWith('data:image/png')) {
    const imgW = pageW - 2 * margin;
    const imgH = Math.min(400, pageH - y - 200);
    try {
      doc.addImage(imgDataUrl, 'PNG', margin, y, imgW, imgH);
      y += imgH + 12;
    } catch (err) {
      console.error('graphToPdf: addImage failed:', err);
      // Continue without the image — table still renders.
    }
  }

  // Node table
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Nodes', margin, y);
  y += 14;

  doc.setFontSize(8);
  const col1 = margin;
  const col2 = margin + 70;
  const col3 = margin + 280;
  doc.setFont('helvetica', 'bold');
  doc.text('TYPE', col1, y);
  doc.text('LABEL', col2, y);
  doc.text('ANNOTATION', col3, y);
  doc.setFont('helvetica', 'normal');
  y += 10;
  doc.setDrawColor(200);
  doc.line(margin, y - 6, pageW - margin, y - 6);

  for (const r of nodeRows) {
    if (y > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(r.type.toUpperCase(), col1, y);
    const labelTrunc = r.label.length > 45 ? r.label.slice(0, 42) + '\u2026' : r.label;
    doc.text(labelTrunc, col2, y);
    const annotation = r.annotation || '';
    const annTrunc = annotation.length > 50 ? annotation.slice(0, 47) + '\u2026' : annotation;
    doc.text(annTrunc, col3, y);
    y += 11;
  }

  // Footer disclaimer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(
    'RMPG Flex \u2014 Connections Analyst. This report reflects recorded data at the time of generation.',
    margin,
    pageH - 18
  );

  return doc.output('blob');
}
