// 10 officer scheduling features
export interface ShiftRoster { weekStart:string; shifts:Array<{officerId:string;day:number;shift:'day'|'swing'|'graveyard'|'off';zone:string}>; }
export function buildWeeklyRoster(weekStart:string,officers:Array<{id:string;shift:string;zone:string;daysOff:number[]}>): ShiftRoster { const roster:ShiftRoster['shifts']=[]; const d=new Date(weekStart); for(let day=0;day<7;day++){for(const o of officers){if(!o.daysOff.includes(day))roster.push({officerId:o.id,day,shift:o.shift as any,zone:o.zone});} d.setDate(d.getDate()+1);} return{weekStart,shifts:roster}; }
export interface OvertimeRequest { officerId:string; date:string; hours:number; reason:string; status:'requested'|'approved'|'denied'; }
export function manageOvertime(requests:OvertimeRequest[]): {totalHours:number;approvedHours:number;cost:number} { const approved=requests.filter(r=>r.status==='approved'); const hours=approved.reduce((s,r)=>s+r.hours,0); return{totalHours:requests.reduce((s,r)=>s+r.hours,0),approvedHours:hours,cost:Math.round(hours*45*1.5)}; }
export interface ShiftBid { officerId:string; bidRank:number; preferredShift:string; preferredDaysOff:number[]; seniorityPoints:number; awarded:boolean; }
export function processShiftBids(bids:ShiftBid[]): ShiftBid[] { return[...bids].sort((a,b)=>(b.seniorityPoints*10+b.bidRank)-(a.seniorityPoints*10+a.bidRank)).map((b,i)=>({...b,awarded:i<Math.ceil(bids.length*0.7)})); }
export interface MinimumStaffing { zone:string; shift:string; minimum:number; scheduled:number; deficit:number; }
export function checkMinimumStaffing(zones:Array<{name:string;shift:string;min:number;scheduled:number}>): MinimumStaffing[] { return zones.map(z=>({zone:z.name,shift:z.shift,minimum:z.min,scheduled:z.scheduled,deficit:Math.max(0,z.min-z.scheduled)})); }
export interface ShiftSwap { requestingOfficer:string; receivingOfficer:string; shiftDate:string; reason:string; status:'requested'|'approved'|'denied'; }
export function processShiftSwap(request:ShiftSwap,supervisorApproved:boolean): ShiftSwap { return{...request,status:supervisorApproved?'approved':'denied'}; }
export interface VacationBid { officerId:string; preferredDates:Array<{start:string;end:string}>; seniorityPoints:number; awardedDates:Array<{start:string;end:string}>; }
export function allocateVacation(bids:VacationBid[],maxPerWeek:number): VacationBid[] { const sorted=[...bids].sort((a,b)=>b.seniorityPoints-a.seniorityPoints); return sorted.map((b,i)=>({...b,awardedDates:i<maxPerWeek?b.preferredDates:[]})); }
export interface ForceMatrix { zone:string; shift:string; date:string; required:number; scheduled:number; overtime:number; offDuty:number; }
export function calculateForceRequirements(matrix:ForceMatrix[]): {totalRequired:number;totalScheduled:number;overallDeficit:number} { const req=matrix.reduce((s,m)=>s+m.required,0); const sched=matrix.reduce((s,m)=>s+m.scheduled,0); return{totalRequired:req,totalScheduled:sched,overallDeficit:Math.max(0,req-sched)}; }
export interface CourtDay { officerId:string; caseNumber:string; courtDate:string; courtTime:string; compensated:boolean; }
export function trackCourtAppearances(days:CourtDay[]): {total:number;byOfficer:Record<string,number>;uncompensated:CourtDay[]} { const byOff:Record<string,number>={};for(const d of days)byOff[d.officerId]=(byOff[d.officerId]||0)+1; return{total:days.length,byOfficer:byOff,uncompensated:days.filter(d=>!d.compensated)}; }
export interface ScheduleConflict { officerId:string; date:string; conflictType:string; description:string; }
export function detectScheduleConflicts(schedule:Array<{officerId:string;date:string;type:string}>): ScheduleConflict[] { const conflicts:ScheduleConflict[]=[]; for(let i=0;i<schedule.length;i++){for(let j=i+1;j<schedule.length;j++){if(schedule[i].officerId===schedule[j].officerId&&schedule[i].date===schedule[j].date){conflicts.push({officerId:schedule[i].officerId,date:schedule[i].date,conflictType:'double_booked',description:`${schedule[i].type} and ${schedule[j].type}`});}}} return conflicts; }
export interface SchedulingDashboard { officersScheduled:number; vacancies:number; overtimeHours:number; courtDays:number; minimumStaffingMet:boolean; }
export function compileSchedulingDashboard(scheduled:number,total:number,overtime:number,court:number): SchedulingDashboard { return{officersScheduled:scheduled,vacancies:total-scheduled,overtimeHours:overtime,courtDays:court,minimumStaffingMet:scheduled>=Math.ceil(total*0.85)}; }
