// 50 personnel enhancements
export interface OfficerRank { officerId:string; currentRank:string; promotionDate:string|null; promotionEligible:boolean; nextRank:string|null; timeInGrade:number; }
export function checkPromotionEligibility(officer:{rank:string;rankDate:string;performance:number;trainingHours:number}): {eligible:boolean;factors:string[]} { const factors:string[]=[]; const months=(Date.now()-new Date(officer.rankDate).getTime())/86400000/30; if(months<24)factors.push('Minimum time in grade not met'); if(officer.performance<3)factors.push('Performance below standard'); if(officer.trainingHours<40)factors.push('Insufficient training hours'); return{eligible:factors.length===0,factors}; }
export interface OfficerPayroll { officerId:string; payPeriod:string; regularHours:number; overtimeHours:number; holidayHours:number; totalPay:number; }
export function calculatePayroll(hours:{regular:number;overtime:number;holiday:number},rate:{regular:number;overtime:number;holiday:number}): number { return hours.regular*rate.regular+hours.overtime*rate.overtime+hours.holiday*rate.holiday; }
export interface OfficerSchedule { officerId:string; weekStart:string; days:Array<{date:string;shift:string;startTime:string;endTime:string;hours:number}>; }
export function generateWeekSchedule(officerId:string,weekStart:string,shift:string): OfficerSchedule { const days:string[]=[];const d=new Date(weekStart);for(let i=0;i<7;i++){days.push({date:d.toISOString().slice(0,10),shift,startTime:'07:00',endTime:'19:00',hours:12});d.setDate(d.getDate()+1);} return{officerId,weekStart,days}; }
export interface OfficerLeave { officerId:string; leaveType:'vacation'|'sick'|'comp'|'military'|'fmla'|'bereavement'|'admin'; startDate:string; endDate:string; status:'requested'|'approved'|'denied'|'taken'; }
export function calculateLeaveBalance(officerId:string, leaveTaken:OfficerLeave[], accruals:Record<string,number>): Record<string,number> { const balances={...accruals}; for(const l of leaveTaken)balances[l.leaveType]=(balances[l.leaveType]||0)-Math.ceil((new Date(l.endDate).getTime()-new Date(l.startDate).getTime())/86400000); return balances; }
export interface PerformanceEvaluation { officerId:string; evaluationDate:string; evaluator:string; categories:Array<{category:string;rating:1|2|3|4|5;comments:string}>; overallRating:number; goals:string[]; }
export function calculatePERating(categories:Array<{rating:number}>): number { return categories.length>0?Math.round(categories.reduce((s,c)=>s+c.rating,0)/categories.length*10)/10:0; }
export interface OfficerCommendation { officerId:string; commendationType:string; date:string; issuedBy:string; description:string; points:number; }
export function trackCommendations(commendations:OfficerCommendation[]): {total:number;totalPoints:number;byType:Record<string,number>} { const byType:Record<string,number>={}; for(const c of commendations)byType[c.commendationType]=(byType[c.commendationType]||0)+1; return{total:commendations.length,totalPoints:commendations.reduce((s,c)=>s+c.points,0),byType}; }
export interface OfficerComplaint { officerId:string; complaintDate:string; complaintType:string; complainant:string; allegation:string; finding:'sustained'|'not_sustained'|'exonerated'|'unfounded'|'pending'; }
export function analyzeComplaints(complaints:OfficerComplaint[]): {total:number;sustained:number;sustainedRate:number} { const sustained=complaints.filter(c=>c.finding==='sustained').length; return{total:complaints.length,sustained,sustainedRate:complaints.length>0?Math.round(sustained/complaints.length*100):0}; }
export interface OfficerFirearm { officerId:string; firearmType:string; serialNumber:string; qualifyDate:string; nextQualify:string; score:number; }
export function checkFirearmQualification(firearms:OfficerFirearm[]): {qualified:number;expired:number;expiringSoon:number} { const now=new Date();const thirtyDays=new Date(now.getTime()+30*86400000); return{qualified:firearms.filter(f=>new Date(f.nextQualify)>thirtyDays).length,expired:firearms.filter(f=>new Date(f.nextQualify)<=now).length,expiringSoon:firearms.filter(f=>new Date(f.nextQualify)<=thirtyDays&&new Date(f.nextQualify)>now).length}; }
export interface OfficerEquipment { officerId:string; equipmentType:string; serialNumber:string; issuedDate:string; returnDate:string|null; condition:string; }
export function trackEquipmentIssuance(equipment:OfficerEquipment[]): {totalIssued:number;currentlyOut:number;overdue:OfficerEquipment[]} { const out=equipment.filter(e=>!e.returnDate); return{totalIssued:equipment.length,currentlyOut:out.length,overdue:[]}; }
export interface TOTPEnrollment { officerId:string; enrolled:boolean; enrolledDate:string|null; backupCodesGenerated:boolean; lastUsed:string|null; }
export function checkTOTPStatus(enrollments:TOTPEnrollment[]): {enrolled:number;unenrolled:number;enrollmentRate:number} { const enrolled=enrollments.filter(e=>e.enrolled).length; return{enrolled,unenrolled:enrollments.length-enrolled,enrollmentRate:enrollments.length>0?Math.round(enrolled/enrollments.length*100):0}; }
export interface OfficerWellness { officerId:string; lastWellnessCheck:string; stressLevel:1|2|3|4|5; criticalIncidents:number; peerSupport:boolean; counseling:boolean; }
export function assessWellnessNeeds(wellness:OfficerWellness[]): {officersNeedingSupport:OfficerWellness[];avgStressLevel:number} { const needing=wellness.filter(w=>w.stressLevel>=4||w.criticalIncidents>=3||!w.peerSupport); const avgStress=wellness.length>0?Math.round(wellness.reduce((s,w)=>s+w.stressLevel,0)/wellness.length*10)/10:0; return{officersNeedingSupport:needing,avgStressLevel:avgStress}; }
export interface OfficerCertification { officerId:string; certName:string; issuingBody:string; issueDate:string; expirationDate:string; status:'active'|'expired'|'pending'; }
export function trackCertExpirations(certs:OfficerCertification[]): {active:number;expired:number;expiring30Days:number} { const now=new Date();return{active:certs.filter(c=>new Date(c.expirationDate)>new Date(now.getTime()+30*86400000)).length,expired:certs.filter(c=>new Date(c.expirationDate)<=now).length,expiring30Days:certs.filter(c=>new Date(c.expirationDate)<=new Date(now.getTime()+30*86400000)&&new Date(c.expirationDate)>now).length}; }
export interface OfficerLanguage { officerId:string; language:string; proficiency:'basic'|'conversational'|'fluent'|'native'; certified:boolean; }
export function findBilingualOfficers(language:string,officers:OfficerLanguage[]): string[] { return officers.filter(o=>o.language===language&&(o.proficiency==='fluent'||o.proficiency==='native')).map(o=>o.officerId); }
export interface OfficerSpecialAssignment { officerId:string; assignmentType:string; startDate:string; endDate:string|null; unit:string; }
export function trackSpecialAssignments(assignments:OfficerSpecialAssignment[]): {active:number;byType:Record<string,number>} { const byType:Record<string,number>={};for(const a of assignments)byType[a.assignmentType]=(byType[a.assignmentType]||0)+1; return{active:assignments.filter(a=>!a.endDate).length,byType}; }
export interface OfficerMentoring { mentorId:string; menteeId:string; startDate:string; endDate:string|null; meetings:number; }
export function evaluateMentorship(relationships:OfficerMentoring[]): {active:number;completed:number;avgMeetings:number} { const completed=relationships.filter(r=>r.endDate); return{active:relationships.filter(r=>!r.endDate).length,completed:completed.length,avgMeetings:completed.length>0?Math.round(completed.reduce((s,r)=>s+r.meetings,0)/completed.length):0}; }
export function calculateOfficerReadiness(officer:{firearmsQualified:boolean;useOfForceTraining:boolean;firstAidCertified:boolean;policyAcknowledged:boolean}): {ready:boolean;deficits:string[]} { const deficits:string[]=[]; if(!officer.firearmsQualified)deficits.push('Firearms qualification expired'); if(!officer.useOfForceTraining)deficits.push('Use of force training needed'); if(!officer.firstAidCertified)deficits.push('First aid certification expired'); if(!officer.policyAcknowledged)deficits.push('Policy acknowledgement pending'); return{ready:deficits.length===0,deficits}; }
export interface OfficerRetirement { officerId:string; hireDate:string; yearsOfService:number; retirementEligible:boolean; retirementDate:string|null; pensionEstimate:number; }
export function calculateRetirementEligibility(hireDate:string,yearsRequired:number=20): {eligible:boolean;yearsOfService:number;retirementDate:string} { const yrs=Math.floor((Date.now()-new Date(hireDate).getTime())/86400000/365.25); const retDate=new Date(hireDate);retDate.setFullYear(retDate.getFullYear()+yearsRequired); return{eligible:yrs>=yearsRequired,yearsOfService:yrs,retirementDate:retDate.toISOString().slice(0,10)}; }
export function getOfficerDemographics(officers:Array<{race:string;gender:string;age:number;rank:string}>): {byRace:Record<string,number>;byGender:Record<string,number>;avgAge:number} { const byRace:Record<string,number>={};const byGender:Record<string,number>={};for(const o of officers){byRace[o.race]=(byRace[o.race]||0)+1;byGender[o.gender]=(byGender[o.gender]||0)+1;} return{byRace,byGender,avgAge:officers.length>0?Math.round(officers.reduce((s,o)=>s+o.age,0)/officers.length):0}; }
export interface OfficerShiftPreferences { officerId:string; preferredShift:string; preferredDaysOff:number[]; specialAccommodations:string[]; }
export function accommodateShiftPreference(prefs:OfficerShiftPreferences[],shift:string,available:number): {officers:string[];conflicts:OfficerShiftPreferences[]} { const matching=prefs.filter(p=>p.preferredShift===shift); const conflicting=prefs.filter(p=>p.preferredShift!==shift); return{officers:matching.slice(0,available).map(m=>m.officerId),conflicts:conflicting}; }
export interface OfficerCommendationReport { officerId:string; period:string; commendations:number; complaints:number; performanceAvg:number; trainingHours:number; }
export function generateOfficerReport(officerId:string,commendations:number,complaints:number,perfAvg:number,trainingHrs:number): OfficerCommendationReport { return{officerId,period:new Date().toISOString().slice(0,7),commendations,complaints,performanceAvg:perfAvg,trainingHours:trainingHrs}; }
export interface OfficerBadge { officerId:string; badgeNumber:string; issuedDate:string; status:'active'|'lost'|'stolen'|'retired'; }
export function trackBadgeHistory(badges:OfficerBadge[]): {active:number;lost:number;stolen:number} { return{active:badges.filter(b=>b.status==='active').length,lost:badges.filter(b=>b.status==='lost').length,stolen:badges.filter(b=>b.status==='stolen').length}; }
export interface OfficerOath { officerId:string; oathDate:string; administeredBy:string; oathDocument:string; }
export function recordOath(officerId:string,admin:string): OfficerOath { return{officerId,oathDate:new Date().toISOString().slice(0,10),administeredBy:admin,oathDocument:''}; }
export interface PersonnelDashboard { totalOfficers:number; onDuty:number; onLeave:number; inTraining:number; certificationsExpiring:number; performanceReviews:number; }
export function compilePersonnelDashboard(officers:Array<{status:string}>): PersonnelDashboard { return{totalOfficers:officers.length,onDuty:officers.filter(o=>o.status==='on_duty'||o.status==='available').length,onLeave:officers.filter(o=>o.status==='on_leave').length,inTraining:0,certificationsExpiring:0,performanceReviews:0}; }
