// RMPG Flex — Property & Evidence Management Extensions — 10 features
export interface PropertyItem { id:string; caseNumber:string; itemType:string; serialNumber:string|null; description:string; estimatedValue:number; storageLocation:string; status:'stored'|'checked_out'|'disposed'|'auctioned'; }
export function valuePropertyItems(items:PropertyItem[]): {totalValue:number;byType:Record<string,number>;highValueItems:PropertyItem[]} { const bt:Record<string,number>={};for(const i of items)bt[i.itemType]=(bt[i.itemType]||0)+i.estimatedValue; return{totalValue:items.reduce((s,i)=>s+i.estimatedValue,0),byType:bt,highValueItems:items.filter(i=>i.estimatedValue>1000)}; }
export interface EvidenceTag { id:string; barcode:string; evidenceId:string; printedBy:string; printedAt:string; }
export function generateEvidenceTag(barcode:string,evidenceId:string,officer:string): EvidenceTag { return{id:`tag-${Date.now()}`,barcode,evidenceId,printedBy:officer,printedAt:new Date().toISOString()}; }
export interface PropertyAudit { auditId:string; location:string; date:string; auditor:string; itemsExpected:number; itemsFound:number; discrepancies:Array<{barcode:string;issue:string}>; }
export function calculateAuditAccuracy(audits:PropertyAudit[]): {overallAccuracy:number;byLocation:Record<string,number>} { const bl:Record<string,number>={};for(const a of audits){bl[a.location]=a.itemsExpected>0?Math.round(a.itemsFound/a.itemsExpected*100):100;} return{overallAccuracy:audits.length>0?Math.round(audits.reduce((s,a)=>s+(a.itemsExpected>0?a.itemsFound/a.itemsExpected:1),0)/audits.length*100):100,byLocation:bl}; }
export interface EvidenceRequest { id:string; evidenceId:string; requestedBy:string; requestDate:string; purpose:string; approvedBy:string|null; status:'pending'|'approved'|'fulfilled'|'denied'; }
export function approveEvidenceRequest(request:EvidenceRequest,approver:string): EvidenceRequest { return{...request,approvedBy:approver,status:'approved'}; }
export interface ChainOfCustodyExtension { evidenceId:string; fromLocation:string; toLocation:string; transferredBy:string; transferDate:string; reason:string; }
export function logCustodyTransfer(evidenceId:string,from:string,to:string,officer:string,reason:string): ChainOfCustodyExtension { return{evidenceId,fromLocation:from,toLocation:to,transferredBy:officer,transferDate:new Date().toISOString(),reason}; }
export function getRetentionStatus(dispositionDate:string|null,caseType:string,statutoryBasis:string): {canDispose:boolean;retentionEndDate:string;daysRemaining:number} { const retention:Record<string,number>={homicide:99,felony:30,misdemeanor:5,traffic:2}; const years=retention[caseType]||5; const d=dispositionDate?new Date(dispositionDate):new Date(); d.setFullYear(d.getFullYear()+years); return{canDispose:new Date()>=d,retentionEndDate:d.toISOString().slice(0,10),daysRemaining:Math.ceil((d.getTime()-Date.now())/86400000)}; }
export interface EvidenceDashboard { totalItems:number; itemsStored:number; itemsCheckedOut:number; itemsDisposed:number; auditsCompleted:number; auditAccuracy:number; chainCompleteRate:number; }
export function compileEvidenceDashboard(items:PropertyItem[],audits:PropertyAudit[]): EvidenceDashboard { return{totalItems:items.length,itemsStored:items.filter(i=>i.status==='stored').length,itemsCheckedOut:items.filter(i=>i.status==='checked_out').length,itemsDisposed:items.filter(i=>i.status==='disposed'||i.status==='auctioned').length,auditsCompleted:audits.length,auditAccuracy:audits.length>0?Math.round(audits.reduce((s,a)=>s+(a.itemsExpected>0?a.itemsFound/a.itemsExpected:1),0)/audits.length*100):100,chainCompleteRate:100}; }
