// ============================================================
// RMPG Flex — PSO Notice of Communication (adapter)
//
// A RESPONDENT-FACING notice generated when a process-service /
// client-request attempt could not be completed. It is left at the
// door or handed to an occupant, so it is addressed TO the person
// being served (the respondent) — not to the contracting client.
//
// FORMAT: Dispatch's CFS-close PSO notice and Process Server's
// "Notice of Attempt to Serve" produce the SAME line/box NIBRS-style
// police-form PDF — generated by generateNoticeOfAttempt in
// servePdfGenerator.ts. The historical court-paragraph layout was
// REMOVED on 2026-06-22 (PR after #1549) so it can never reappear via
// a stale-bundle accident: there is no longer any code path in the
// repo that renders the old format.
//
// This file remains as the public ADAPTER. DispatchPage and
// psoNoticeAutofill call generateNoticeOfCommunication; the
// implementation maps NoticeOfCommunicationData → NoticeOfAttemptData
// and delegates to the canonical line/box generator.
// ============================================================

import jsPDF from 'jspdf';
import { sanitizePdfText } from './pdfGenerator';
import { generateNoticeOfAttempt } from './servePdfGenerator';
import type { NoticeOfAttemptData } from './servePdfGenerator';
import { lookupPsoCode, formatCodeFull } from '../constants/processServiceCodes';

export interface NoticeOfCommunicationAttempt {
  number: number;
  date: string;
  time: string;
  /** Disposition / outcome of the attempt (e.g. "No Contact", "No Access"). */
  result: string;
  /** Internal attempt notes — kept in the payload but NOT printed on the respondent copy. */
  notes: string;
}

export interface NoticeOfCommunicationData {
  noticeDate: string;
  /** Originating CFS call number — printed as the agency reference number. */
  callNumber: string;
  /** Person being served (recipient/defendant). Falls back to occupant wording. */
  respondentName?: string;
  /** Court case number of the underlying legal matter, if known. */
  courtCaseNumber?: string;
  /** Issuing court of the underlying legal matter, if known. */
  courtName?: string;
  /** Contracting client / requestor — one-line reference only, not the addressee. */
  clientName: string;
  /** Contact person at the contracting client. Retained for compatibility — not printed. */
  clientContact?: string;
  /** Retained for compatibility — not printed on the respondent copy. */
  clientAddress?: string;
  /** Retained for compatibility — not printed on the respondent copy. */
  clientPhone?: string;
  /** What is being delivered (e.g. "Summons Service", "Subpoena Service"). */
  serviceType: string;
  /** The respondent's address — where delivery was attempted. */
  serviceAddress: string;
  /** Retained for compatibility — not printed on the respondent copy. */
  requestedWindow?: string;
  /** Retained for compatibility — internal, not printed on the respondent copy. */
  authorization?: string;
  /** Retained for compatibility — internal, not printed on the respondent copy. */
  billingCode?: string;
  /** One row per delivery attempt. */
  attempts: NoticeOfCommunicationAttempt[];
  /** Retained for compatibility — internal, not printed on the respondent copy. */
  redispatchCallNumber?: string;
  /** Scheduled next attempt window — printed so the respondent knows what to expect. */
  nextWindow?: string;
  officerName: string;
  officerBadge: string;
  officerPhone?: string;
  dispatchPhone?: string;
  signature?: string;
}

/** Human label for a PSO attempt disposition code/value. */
export function psoResultLabel(result: string): string {
  switch ((result || '').trim().toLowerCase()) {
    case 'no_contact':
    case 'no_answer':
    case 'negative contact': return 'No contact at location';
    case 'no_access':
    case 'ps no access': return 'Unable to access premises';
    case 'refused': return 'Access / service refused';
    case 'wrong_address': return 'Incorrect / bad address';
    case 'gtn':
    case 'gone_on_arrival': return 'Subject/condition gone on arrival';
    case 'unable_to_locate':
    case 'utl': return 'Unable to locate';
    case 'cancelled': return 'Cancelled by client';
    case 'completed': return 'Completed';
    // Process-service dispositions stored verbatim on the call ("PS Served",
    // "PS Non-Service", "PS Unknown", "PS Attempted") — map to readable
    // text instead of surfacing the raw code.
    case 'ps served':
    case 'served': return 'Served / completed';
    case 'ps sub-served':
    case 'ps sub served':
    case 'sub_served': return 'Delivered to co-resident / agent';
    case 'ps non-service':
    case 'ps non service':
    case 'non-service': return 'Unable to complete service';
    case 'ps attempted':
    case 'attempted': return 'Attempted — not completed';
    case 'ps unknown':
    case 'unknown': return 'Outcome pending';
    case 'other': return 'Other (see notes)';
    default: return result ? sanitizePdfText(result).replace(/_/g, ' ') : 'Service not completed';
  }
}

/**
 * Strip the trailing country tag from a geocoded address.
 *   "745 East Village Way, Sandy, Utah 84094, United States"
 *     → "745 East Village Way, Sandy, Utah 84094"
 * Mapbox / nominatim / Google all append ", United States" (or "USA") to
 * geocoded addresses, but a domestic recipient-facing notice doesn't need
 * the country line — it just clutters the "2. Service Address" cell.
 */
function trimCountrySuffix(raw: string | null | undefined): string {
  if (!raw) return '';
  return String(raw).replace(/,\s*(United States|USA|US)\.?\s*$/i, '').trim();
}

/**
 * "subpoena_service" → "Subpoena Service"; "civil_summons" → "Civil Summons".
 * The dispatch autofill stores enum-shaped values (snake_case) in
 * pso_service_type when the operator picks from a dropdown. The recipient-
 * facing notice has to render those as proper English — the OLD legacy
 * generator did this implicitly via the body sentence, but the NIBRS
 * field grid prints the raw value, so we normalize here.
 */
function humanizeServiceType(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const s = String(raw).trim();
  if (!s) return null;
  if (/\s/.test(s)) return s; // already has spaces — assume operator-typed
  return s
    .replace(/[_-]+/g, ' ')
    .toLowerCase()
    .replace(/\b\w/g, (m) => m.toUpperCase());
}

/**
 * Generic-title detector. When the recipient name is a placeholder-y title
 * ("Authorized Representative", "Manager", "Resident", "Occupant"), append
 * "(or current occupant)" so the printed name doesn't read as a real human's
 * name. Personal names (anything with a space + at least one lowercase
 * letter pattern other than the few generics) skip the suffix.
 */
function softenGenericRecipient(name: string): string {
  const norm = name.trim().toLowerCase();
  const generics = new Set([
    'authorized representative',
    'authorized agent',
    'registered agent',
    'manager',
    'managing agent',
    'resident',
    'occupant',
    'tenant',
    'owner',
    'person in charge',
    'recipient on file',
  ]);
  if (generics.has(norm)) return `${name.trim()} (or current occupant)`;
  return name.trim();
}

/**
 * Adapt the PSO Communication payload to the unified Notice-of-Attempt
 * shape and delegate to the canonical NIBRS-style generator. Keeping the
 * function signature intact means DispatchPage and psoNoticeAutofill
 * continue to call generateNoticeOfCommunication unchanged.
 */
export async function generateNoticeOfCommunication(data: NoticeOfCommunicationData): Promise<jsPDF> {
  const recipient = (data.respondentName && data.respondentName.trim())
    ? softenGenericRecipient(data.respondentName)
    : 'Occupant / Respondent';

  const noticeAttempts: NoticeOfAttemptData['attempts'] = (data.attempts || []).map((a) => {
    // The historical PSO payload's `result` may already be a structured PS
    // code ("PS/15.05"), a legacy disposition string ("PS Evasive"), or a
    // free-form enum ("no_contact"). The unified Notice generator's
    // serveResultLabel() handles the legacy + free-form path; the PS code
    // path is normalized here so the table cell reads as a full code.
    const psCode = lookupPsoCode(a.result);
    const resultText = psCode ? formatCodeFull(a.result) : (a.result || 'other');
    return {
      number: a.number,
      date: a.date,
      time: a.time,
      result: resultText,
      notes: a.notes || '',
    };
  });

  const adapter: NoticeOfAttemptData = {
    // Field "5. Case Number" prints the COURT case number ONLY — never the
    // agency CFS reference. When no court case has been entered, the field
    // shows N/A and the recipient knows to look at the header's AGENCY
    // REF # for our internal tracking number.
    caseNumber: data.courtCaseNumber || '',
    // Header AGENCY REF # — the CFS call number. Always available; never
    // duplicates field 5.
    agencyRefNumber: data.callNumber || undefined,
    noticeDate: data.noticeDate,
    courtName: data.courtName || 'N/A',
    jurisdiction: 'Salt Lake County, Utah',
    serverName: data.officerName || 'Process Server',
    serverBadge: data.officerBadge || '',
    serverCompany: 'Rocky Mountain Protective Group',
    serverPhone: data.dispatchPhone || data.officerPhone,
    signature: data.signature,
    recipientName: recipient,
    recipientAddress: trimCountrySuffix(data.serviceAddress) || 'Address on file',
    documentType: humanizeServiceType(data.serviceType) || 'Legal Documents',
    // The contracting client maps cleanly onto the Hiring Party slot — keeps
    // the recipient-facing notice honest about who originated the request.
    clientName: data.clientName,
    attempts: noticeAttempts,
    nextAttemptNote: data.nextWindow,
  };

  // Hand off to the unified line/box generator. Anything that touches the
  // visual style (watermark, headers, table chrome, attribution lines,
  // signature block) lives there and is now identical for both surfaces.
  return generateNoticeOfAttempt(adapter);
}
