// 10 regulatory compliance features
export interface RegulatoryRequirement { id:string; regulation:string; agency:string; requirement:string; dueDate:string; status:'compliant'|'pending'|'overdue'; responsibleParty:string; }
export function trackComplianceDeadlines(reqs:RegulatoryRequirement[]): {total:number;compliant:number;overdue:number;complianceRate:number} { const compliant=reqs.filter(r=>r.status==='compliant').length; return{total:reqs.length,compliant,overdue:reqs.filter(r=>r.status==='overdue').length,complianceRate:reqs.length>0?Math.round(compliant/reqs.length*100):0}; }
export interface CLERYReport { year:number; institution:string; crimes:Record<string,number>; submitted:boolean; submissionDate:string|null; }
export function prepareCLERYReport(year:number,institution:string,crimes:Record<string,number>): CLERYReport { return{year,institution,crimes,submitted:false,submissionDate:null}; }
export interface NIBRSSubmission { agency:string; month:string; incidents:number; submitted:boolean; errorRate:number; }
export function validateNIBRS(incidents:number,errors:number): {valid:boolean;errorRate:number;canSubmit:boolean} { const rate=incidents>0?Math.round(errors/incidents*100):0; return{valid:rate<5,errorRate:rate,canSubmit:rate<5}; }
export interface POSTCompliance { officerId:string; status:'compliant'|'pending'|'non_compliant'; requiredHours:number; completedHours:number; deadline:string; }
export function checkPOSTStatus(officers:POSTCompliance[]): {compliant:number;nonCompliant:number;complianceRate:number} { const compliant=officers.filter(o=>o.status==='compliant').length; return{compliant,nonCompliant:officers.length-compliant,complianceRate:officers.length>0?Math.round(compliant/officers.length*100):0}; }
export interface HIPAACompliance { recordId:string; phiPresent:boolean; secured:boolean; accessLogged:boolean; breachPotential:boolean; }
export function assessPHIRisk(record:{containsPHI:boolean;encrypted:boolean;accessControlled:boolean}): HIPAACompliance { return{recordId:'',phiPresent:record.containsPHI,secured:record.encrypted,accessLogged:record.accessControlled,breachPotential:record.containsPHI&&!record.encrypted}; }
export interface CJISCompliance { requirement:string; compliant:boolean; lastAudit:string; nextAudit:string; findings:string[]; }
export function auditCJIS(items:CJISCompliance[]): {complianceRate:number;criticalFindings:string[]} { const compliant=items.filter(i=>i.compliant).length; const findings=items.filter(i=>!i.compliant).map(i=>`${i.requirement}: non-compliant`); return{complianceRate:items.length>0?Math.round(compliant/items.length*100):0,criticalFindings:findings}; }
export interface ODATracking { incidentId:string; useType:string; reportingDeadline:string; reported:boolean; acaNumber:string|null; }
export function trackObligationToReport(incidentId:string,useType:string): ODATracking { const d=new Date();d.setDate(d.getDate()+10); return{incidentId,useType,reportingDeadline:d.toISOString().slice(0,10),reported:false,acaNumber:null}; }
export interface FERPACompliance { recordId:string; studentInfo:boolean; parentalConsent:boolean; disclosureLogged:boolean; }
export function checkFERPA(record:{containsStudentInfo:boolean;hasConsent:boolean;logged:boolean}): {compliant:boolean;violations:string[]} { const v:string[]=[]; if(record.containsStudentInfo&&!record.hasConsent)v.push('No parental consent for student info'); if(record.containsStudentInfo&&!record.logged)v.push('Disclosure not logged'); return{compliant:v.length===0,violations:v}; }
export interface BradyCompliance { officerId:string; bradyListed:boolean; disclosureDate:string|null; disclosedTo:string|null; }
export function checkBradyList(officerId:string,bradyList:string[]): {listed:boolean;disclosureRequired:boolean} { return{listed:bradyList.includes(officerId),disclosureRequired:bradyList.includes(officerId)}; }
export interface ComplianceDashboard { totalRequirements:number; compliant:number; overdue:number; upcomingAudits:number; riskLevel:string; }
export function compileComplianceDashboard(reqs:RegulatoryRequirement[]): ComplianceDashboard { const compliant=reqs.filter(r=>r.status==='compliant').length; const overdue=reqs.filter(r=>r.status==='overdue').length; return{totalRequirements:reqs.length,compliant,overdue,upcomingAudits:0,riskLevel:overdue>0?'elevated':'normal'}; }
