// ═══════════════════════════════════════════════════════════════
// End-of-Shift Report — court-ready PDF generated by an officer
// at the MDT. Replaces the previous .txt-with-Unicode-box-borders
// download (which read as "casual draft", not a submittable record).
//
// Shape matches the /api/reports/shift-activity/:userId payload:
//   officer.full_name / officer.badge_number
//   date
//   summary.{totalCalls, totalIncidents, totalScans, totalCitations, totalFieldInterviews}
//   calls[] / incidents[] / scans[]
//
// Pure-client: feed the parsed JSON response + the in-context unit
// call_sign and the user's full name (from useAuth). Same Arial +
// RMPG-gold idiom as darPdf / clearedSummaryPdf.
// ═══════════════════════════════════════════════════════════════

import jsPDF from 'jspdf';
import { registerArialFont } from './pdf/fonts/registerArial';
import { parseTimestamp } from './dateUtils';
import { toDisplayLabel } from './formatters';
import { openPdfBlob } from './openPdfDocument';
import { drawNavyBanner } from './pdfStandaloneHeader';

const TEXT_DARK = '#1a1a1a';
const TEXT_MUTED = '#555555';
const BORDER = '#9a9a9a';
const ROW_ALT = '#f4f4f0';

export interface ShiftReportSummary {
  totalCalls?: number;
  totalIncidents?: number;
  totalScans?: number;
  totalCitations?: number;
  totalFieldInterviews?: number;
}

export interface ShiftReportCall {
  call_number?: string;
  incident_type?: string;
  priority?: string;
  status?: string;
  location_address?: string;
  created_at?: string;
}

export interface ShiftReportIncident {
  incident_number?: string;
  incident_type?: string;
  status?: string;
  location_address?: string;
}

export interface ShiftReportScan {
  scanned_at?: string;
  checkpoint_name?: string;
}

export interface ShiftReportInput {
  officer?: { full_name?: string; badge_number?: string };
  date?: string;
  unitCallSign?: string;
  summary?: ShiftReportSummary;
  calls?: ShiftReportCall[];
  incidents?: ShiftReportIncident[];
  scans?: ShiftReportScan[];
  /** Fallback officer name when officer.full_name isn't on the payload — pulled
   *  from useAuth on the calling side. */
  officerNameFallback?: string;
}

const MT_TZ = 'America/Denver';

/** "Mon Jun 22, 2026" Mountain-Time. */
function fmtDate(input: Date | string | undefined): string {
  if (!input) return '—';
  const d = typeof input === 'string' ? parseTimestamp(input) : input;
  return new Intl.DateTimeFormat('en-US', {
    timeZone: MT_TZ,
    weekday: 'short', month: 'short', day: 'numeric', year: 'numeric',
  }).format(d);
}

/** "HH:MM MT". */
function fmtTime(input: string | undefined): string {
  if (!input) return '—';
  const d = parseTimestamp(input);
  return new Intl.DateTimeFormat('en-US', {
    timeZone: MT_TZ, hour: '2-digit', minute: '2-digit', hour12: false,
  }).format(d);
}

/** Public for unit testing. Sum of every section's count for the cover stat. */
export function totalActivityCount(s: ShiftReportSummary | undefined): number {
  if (!s) return 0;
  return (s.totalCalls ?? 0) + (s.totalIncidents ?? 0) + (s.totalScans ?? 0)
    + (s.totalCitations ?? 0) + (s.totalFieldInterviews ?? 0);
}

/** Public for unit testing. Reduces a free-text string to the column width;
 *  caller passes char budget, not pixels. */
export function ellipsize(s: string | undefined, max: number): string {
  const value = (s ?? '').toString();
  return value.length <= max ? value : value.slice(0, max - 1) + '…';
}

/** Build the PDF. Layout: 8.5×11 portrait. Gold banner, summary tiles,
 *  per-section tables. Multi-page if a section overflows. */
export function generateShiftReportPdf(input: ShiftReportInput): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  registerArialFont(doc);

  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 36;
  let y = 36;

  // Officer/unit strap
  const officerName = input.officer?.full_name || input.officerNameFallback || 'Unknown Officer';
  const badge = input.officer?.badge_number || '—';
  const unitCallSign = input.unitCallSign || '—';

  y = drawNavyBanner(doc, {
    title: `SHIFT REPORT — ${fmtDate(input.date)}`,
    subtitle: 'Dispatch Operations',
    rightLine1: `Badge: ${badge}  ·  Unit: ${unitCallSign}`,
    rightLine2: `Officer: ${officerName}`,
  });

  // Summary tiles (5-up)
  const tiles: Array<{ label: string; value: number }> = [
    { label: 'CALLS',     value: input.summary?.totalCalls ?? 0 },
    { label: 'INCIDENTS', value: input.summary?.totalIncidents ?? 0 },
    { label: 'CITATIONS', value: input.summary?.totalCitations ?? 0 },
    { label: 'FIs',       value: input.summary?.totalFieldInterviews ?? 0 },
    { label: 'SCANS',     value: input.summary?.totalScans ?? 0 },
  ];
  const tileGap = 6;
  const tileW = (W - 2 * M - tileGap * (tiles.length - 1)) / tiles.length;
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.5);
  tiles.forEach((t, i) => {
    const x = M + i * (tileW + tileGap);
    doc.rect(x, y, tileW, 40);
    doc.setFontSize(8);
    doc.setTextColor(TEXT_MUTED);
    doc.text(t.label, x + 6, y + 12);
    doc.setFontSize(16);
    doc.setFont('Arial', 'bold');
    doc.setTextColor(TEXT_DARK);
    doc.text(String(t.value), x + 6, y + 32);
    doc.setFont('Arial', 'normal');
  });
  y += 52;

  // Section helper
  const newPageIfNeeded = (need: number) => {
    if (y + need > H - 60) {
      doc.addPage();
      y = 48;
    }
  };

  const section = (title: string) => {
    newPageIfNeeded(40);
    doc.setFillColor('#e6e6e6');
    doc.rect(M, y, W - 2 * M, 16, 'F');
    doc.setFontSize(9);
    doc.setFont('Arial', 'bold');
    doc.setTextColor(TEXT_DARK);
    doc.text(title.toUpperCase(), M + 6, y + 11);
    y += 16;
  };

  const tableHeader = (cols: ReadonlyArray<{ label: string; width: number }>) => {
    newPageIfNeeded(16);
    doc.setFillColor('#f6f6f6');
    doc.rect(M, y, W - 2 * M, 14, 'F');
    doc.setFontSize(7.5);
    doc.setFont('Arial', 'bold');
    doc.setTextColor(TEXT_MUTED);
    let x = M + 4;
    for (const c of cols) {
      doc.text(c.label, x, y + 9);
      x += c.width;
    }
    y += 14;
    doc.setFont('Arial', 'normal');
  };

  const row = (
    cols: ReadonlyArray<{ key: string; width: number }>,
    values: Record<string, string>,
    altShade: boolean,
  ) => {
    newPageIfNeeded(13);
    if (altShade) {
      doc.setFillColor(ROW_ALT);
      doc.rect(M, y, W - 2 * M, 13, 'F');
    }
    doc.setFontSize(8);
    doc.setTextColor(TEXT_DARK);
    let x = M + 4;
    for (const c of cols) {
      doc.text(values[c.key] ?? '—', x, y + 9);
      x += c.width;
    }
    doc.setDrawColor(BORDER);
    doc.setLineWidth(0.25);
    doc.line(M, y + 13, W - M, y + 13);
    y += 13;
  };

  // Calls
  if ((input.calls?.length ?? 0) > 0) {
    section(`Calls for Service (${input.calls!.length})`);
    const cols = [
      { key: 'call_number',  label: 'CALL #',    width: 65 },
      { key: 'incident_type', label: 'TYPE',     width: 130 },
      { key: 'priority',     label: 'PRI',       width: 28 },
      { key: 'status',       label: 'STATUS',    width: 60 },
      { key: 'time',         label: 'TIME',      width: 44 },
      { key: 'location',     label: 'LOCATION',  width: 200 },
    ] as const;
    tableHeader(cols);
    input.calls!.forEach((c, i) => {
      row(cols, {
        call_number: c.call_number ?? '—',
        incident_type: ellipsize(toDisplayLabel(c.incident_type), 22),
        priority: c.priority ?? '—',
        status: ellipsize(c.status ?? '—', 9),
        time: fmtTime(c.created_at),
        location: ellipsize(c.location_address ?? '—', 38),
      }, i % 2 === 1);
    });
    y += 6;
  }

  // Incidents
  if ((input.incidents?.length ?? 0) > 0) {
    section(`Incident Reports (${input.incidents!.length})`);
    const cols = [
      { key: 'incident_number', label: 'INC #',     width: 75 },
      { key: 'incident_type',   label: 'TYPE',      width: 150 },
      { key: 'status',          label: 'STATUS',    width: 80 },
      { key: 'location',        label: 'LOCATION',  width: 222 },
    ] as const;
    tableHeader(cols);
    input.incidents!.forEach((i, idx) => {
      row(cols, {
        incident_number: i.incident_number ?? '—',
        incident_type: ellipsize(toDisplayLabel(i.incident_type), 26),
        status: ellipsize(toDisplayLabel(i.status ?? '—'), 14),
        location: ellipsize(i.location_address ?? '—', 42),
      }, idx % 2 === 1);
    });
    y += 6;
  }

  // Patrol scans
  if ((input.scans?.length ?? 0) > 0) {
    section(`Patrol Scans (${input.scans!.length})`);
    const cols = [
      { key: 'time',       label: 'TIME',       width: 70 },
      { key: 'checkpoint', label: 'CHECKPOINT', width: 457 },
    ] as const;
    tableHeader(cols);
    input.scans!.forEach((s, idx) => {
      row(cols, {
        time: fmtTime(s.scanned_at),
        checkpoint: ellipsize(s.checkpoint_name ?? 'Unknown', 90),
      }, idx % 2 === 1);
    });
    y += 6;
  }

  // Signature block
  newPageIfNeeded(70);
  y += 10;
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.5);
  // Two signature lines (officer + supervisor)
  const colW = (W - 2 * M - 24) / 2;
  doc.line(M, y + 28, M + colW, y + 28);
  doc.line(M + colW + 24, y + 28, W - M, y + 28);
  doc.setFontSize(8);
  doc.setTextColor(TEXT_MUTED);
  doc.text('Officer signature', M, y + 38);
  doc.text(`${officerName}  ·  Badge ${badge}`, M, y + 49);
  doc.text('Supervisor signature / date', M + colW + 24, y + 38);
  y += 60;

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(TEXT_MUTED);
  doc.text(
    `Generated ${fmtDate(new Date())} ${fmtTime(new Date().toISOString())} MT  ·  RMPG Flex MDT`,
    M, H - 18,
  );

  return doc;
}

/** Generate + open in a new tab so the operator gets the print dialog. */
export function openShiftReportPdf(input: ShiftReportInput): void {
  const doc = generateShiftReportPdf(input);
  const url = URL.createObjectURL(doc.output('blob'));
  openPdfBlob(url, 'Shift Report');
}
