// 10 system health monitoring features
export interface SystemComponent { id:string; name:string; type:'worker'|'database'|'storage'|'queue'|'durable_object'|'cache'; status:'healthy'|'degraded'|'down'; lastChecked:string; responseTimeMs:number; }
export function checkSystemHealth(components:SystemComponent[]): {overallStatus:string;healthyCount:number;degradedCount:number;downCount:number} { const healthy=components.filter(c=>c.status==='healthy'); const degraded=components.filter(c=>c.status==='degraded'); const down=components.filter(c=>c.status==='down'); return{overallStatus:down.length>0?'down':degraded.length>0?'degraded':'healthy',healthyCount:healthy.length,degradedCount:degraded.length,downCount:down.length}; }
export interface DatabaseStats { tableName:string; rowCount:number; sizeBytes:number; lastVacuum:string|null; indexCount:number; }
export function analyzeDBStats(stats:DatabaseStats[]): {totalRows:number;totalSize:number;largestTable:string} { const total=stats.reduce((s,st)=>s+st.rowCount,0); const largest=stats.sort((a,b)=>b.rowCount-a.rowCount)[0]; return{totalRows:total,totalSize:stats.reduce((s,st)=>s+st.sizeBytes,0),largestTable:largest?.tableName||'N/A'}; }
export interface APIEndpoint { path:string; method:string; avgResponseMs:number; errorRate:number; requestsPerMinute:number; }
export function monitorAPIHealth(endpoints:APIEndpoint[]): {totalEndpoints:number;slowEndpoints:APIEndpoint[];highErrorEndpoints:APIEndpoint[]} { return{totalEndpoints:endpoints.length,slowEndpoints:endpoints.filter(e=>e.avgResponseMs>500),highErrorEndpoints:endpoints.filter(e=>e.errorRate>5)}; }
export interface ErrorLog { id:string; timestamp:string; level:'error'|'warn'|'info'; source:string; message:string; stackTrace:string|null; }
export function analyzeErrors(errors:ErrorLog[]): {total:number;byLevel:Record<string,number>;bySource:Record<string,number>;recentErrors:number} { const bl:Record<string,number>={};const bs:Record<string,number>={};for(const e of errors){bl[e.level]=(bl[e.level]||0)+1;bs[e.source]=(bs[e.source]||0)+1;} const recent=errors.filter(e=>new Date(e.timestamp).getTime()>Date.now()-3600000).length; return{total:errors.length,byLevel:bl,bySource:bs,recentErrors:recent}; }
export interface UsageMetrics { metric:string; currentValue:number; limit:number; utilizationPct:number; trend:'increasing'|'stable'|'decreasing'; }
export function trackResourceUsage(metrics:UsageMetrics[]): {approachingLimit:UsageMetrics[];exceededLimit:UsageMetrics[]} { return{approachingLimit:metrics.filter(m=>m.utilizationPct>=80&&m.utilizationPct<100),exceededLimit:metrics.filter(m=>m.utilizationPct>=100)}; }
export interface BackupStatus { backupType:string; lastBackup:string; nextBackup:string; sizeBytes:number; status:'success'|'failed'|'in_progress'; }
export function checkBackupHealth(backups:BackupStatus[]): {allSuccessful:boolean;failedBackups:BackupStatus[];lastBackupAge:number} { const failed=backups.filter(b=>b.status==='failed'); const lastDate=backups.length>0?Math.max(...backups.map(b=>new Date(b.lastBackup).getTime())):0; return{allSuccessful:failed.length===0,failedBackups:failed,lastBackupAge:lastDate?Math.ceil((Date.now()-lastDate)/86400000):999}; }
export interface SecurityAudit { auditType:string; lastAudit:string; findings:number; criticalFindings:number; status:'passed'|'failed'|'needs_review'; }
export function reviewSecurityAudits(audits:SecurityAudit[]): {totalFindings:number;criticalCount:number;auditsFailed:number} { return{totalFindings:audits.reduce((s,a)=>s+a.findings,0),criticalCount:audits.reduce((s,a)=>s+a.criticalFindings,0),auditsFailed:audits.filter(a=>a.status==='failed').length}; }
export interface UptimeReport { period:string; uptimePct:number; totalIncidents:number; avgResolutionMinutes:number; }
export function compileUptimeReport(incidents:Array<{startTime:string;endTime:string|null}>): UptimeReport { const totalMinutes=30*24*60; const downtime=incidents.filter(i=>i.endTime).reduce((s,i)=>(new Date(i.endTime!).getTime()-new Date(i.startTime).getTime())/60000,0); return{period:new Date().toISOString().slice(0,7),uptimePct:Math.round((1-downtime/totalMinutes)*10000)/100,totalIncidents:incidents.length,avgResolutionMinutes:incidents.length>0?Math.round(downtime/incidents.length):0}; }
export interface SystemAlert { id:string; alertType:string; severity:'critical'|'warning'|'info'; message:string; triggeredAt:string; acknowledgedAt:string|null; resolvedAt:string|null; }
export function manageSystemAlerts(alerts:SystemAlert[]): {active:number;critical:number;unacknowledged:number} { const active=alerts.filter(a=>!a.resolvedAt); return{active:active.length,critical:active.filter(a=>a.severity==='critical').length,unacknowledged:active.filter(a=>!a.acknowledgedAt).length}; }
export interface HealthDashboard { overallStatus:string; componentsHealthy:number; servicesOnline:number; errorsLastHour:number; databaseSize:string; uptime:string; backupsOk:boolean; }
export function compileHealthDashboard(components:SystemComponent[],errors:ErrorLog[],uptime:UptimeReport,backups:BackupStatus[]): HealthDashboard { const status=checkSystemHealth(components); return{overallStatus:status.overallStatus,componentsHealthy:status.healthyCount,servicesOnline:components.length,errorsLastHour:errors.filter(e=>new Date(e.timestamp).getTime()>Date.now()-3600000).length,databaseSize:'N/A',uptime:`${uptime.uptimePct}%`,backupsOk:backups.every(b=>b.status==='success')}; }
