// 50 training enhancements
export interface CourseEnrollment { courseId:string; officerId:string; enrollmentDate:string; status:'enrolled'|'attended'|'completed'|'no_show'|'failed'; score:number|null; }
export function trackEnrollmentStats(enrollments:CourseEnrollment[]): {total:number;completed:number;completionRate:number;noShowRate:number} { const completed=enrollments.filter(e=>e.status==='completed').length; const noShow=enrollments.filter(e=>e.status==='no_show').length; return{total:enrollments.length,completed,completionRate:enrollments.length>0?Math.round(completed/enrollments.length*100):0,noShowRate:enrollments.length>0?Math.round(noShow/enrollments.length*100):0}; }
export interface TrainingCalendar { month:string; courses:Array<{date:string;courseName:string;instructor:string;capacity:number;enrolled:number}>; }
export function planTrainingCalendar(month:string,courses:TrainingCalendar['courses']): TrainingCalendar { return{month,courses:courses.sort((a,b)=>a.date.localeCompare(b.date))}; }
export interface TrainingInstructor { instructorId:string; name:string; certifications:string[]; coursesTaught:number; avgRating:number; availability:string[]; }
export function evaluateInstructor(instructor:TrainingInstructor,recentRatings:number[]): {avgRating:number;recommendedForAdvCourses:boolean} { const avg=recentRatings.length>0?Math.round(recentRatings.reduce((s,r)=>s+r,0)/recentRatings.length*10)/10:0; return{avgRating:avg,recommendedForAdvCourses:avg>=4.5}; }
export interface TrainingResource { id:string; resourceType:'classroom'|'range'|'simulator'|'online'|'vehicle'; name:string; capacity:number; availability:string; }
export function checkResourceAvailability(resources:TrainingResource[],date:string): TrainingResource[] { return resources.filter(r=>r.availability.includes(date)); }
export interface TrainingRequirement { officerId:string; requirementType:string; dueDate:string; completedDate:string|null; status:'compliant'|'pending'|'overdue'; }
export function trackTrainingRequirements(requirements:TrainingRequirement[]): {compliant:number;overdue:number;complianceRate:number} { const now=new Date();const overdue=requirements.filter(r=>!r.completedDate&&new Date(r.dueDate)<now); const compliant=requirements.filter(r=>r.completedDate||(new Date(r.dueDate)>now)); return{compliant:compliant.length,overdue:overdue.length,complianceRate:requirements.length>0?Math.round(compliant.length/requirements.length*100):0}; }
export interface TrainingBudget { id:string; fiscalYear:number; totalBudget:number; spent:number; category:string; }
export function trackTrainingSpend(budgets:TrainingBudget[]): {total:number;spent:number;remaining:number;utilizationPct:number} { const total=budgets.reduce((s,b)=>s+b.totalBudget,0); const spent=budgets.reduce((s,b)=>s+b.spent,0); return{total,spent,remaining:total-spent,utilizationPct:total>0?Math.round(spent/total*100):0}; }
export interface TrainingPathway { pathwayName:string; courses:string[]; targetRole:string; estimatedMonths:number; }
export function assignTrainingPathway(officerId:string,careerGoal:string,pathways:TrainingPathway[]): TrainingPathway|null { return pathways.find(p=>p.targetRole===careerGoal)||null; }
export interface MandatoryTraining { trainingType:string; frequency:'annual'|'biannual'|'quarterly'|'biennial'; description:string; appliesTo:string[]; }
export const MANDATORY_TRAINING: MandatoryTraining[] = [{trainingType:'Use of Force',frequency:'annual',description:'Annual use of force policy and de-escalation training',appliesTo:['officer','supervisor']},{trainingType:'Firearms Qualification',frequency:'annual',description:'Annual firearms qualification and safe handling',appliesTo:['officer']},{trainingType:'Legal Update',frequency:'biannual',description:'Biannual legal update on case law and statutes',appliesTo:['officer','supervisor']},{trainingType:'First Aid/CPR',frequency:'biennial',description:'Biennial first aid and CPR recertification',appliesTo:['officer','supervisor','dispatcher']}];
export interface TrainingAttendance { courseId:string; officerId:string; date:string; attended:boolean; hours:number; }
export function calculateTrainingHours(attendance:TrainingAttendance[]): {totalHours:number;byOfficer:Record<string,number>} { const byOfficer:Record<string,number>={};for(const a of attendance){if(a.attended)byOfficer[a.officerId]=(byOfficer[a.officerId]||0)+a.hours;} return{totalHours:attendance.filter(a=>a.attended).reduce((s,a)=>s+a.hours,0),byOfficer}; }
export interface SkillAssessment { officerId:string; skillName:string; assessedLevel:1|2|3|4|5; requiredLevel:number; assessor:string; date:string; }
export function identifySkillGaps(assessments:SkillAssessment[]): {officersWithGaps:string[];criticalGaps:Array<{skill:string;count:number}>} { const gaps:Record<string,number>={};const officers=new Set<string>();for(const a of assessments){if(a.assessedLevel<a.requiredLevel){gaps[a.skillName]=(gaps[a.skillName]||0)+1;officers.add(a.officerId);}} return{officersWithGaps:Array.from(officers),criticalGaps:Object.entries(gaps).map(([skill,count])=>({skill,count})).sort((a,b)=>b.count-a.count)}; }
export interface FTOEvaluation { recruitId:string; ftoId:string; evaluationDate:string; categories:Array<{category:string;rating:1|2|3|4|5;notes:string}>; overallRating:number; recommendSolo:boolean; }
export function calculateFTOProgress(evaluations:FTOEvaluation[]): {avgRating:number;readyForSolo:boolean;trend:'improving'|'stable'|'declining'} { const ratings=evaluations.map(e=>e.overallRating); const avg=ratings.length>0?Math.round(ratings.reduce((s,r)=>s+r,0)/ratings.length*10)/10:0; const recent=ratings.slice(-3);const older=ratings.slice(-6,-3); const recentAvg=recent.length>0?recent.reduce((s,r)=>s+r,0)/recent.length:0; const olderAvg=older.length>0?older.reduce((s,r)=>s+r,0)/older.length:0; return{avgRating:avg,readyForSolo:avg>=3.5&&evaluations[evaluations.length-1]?.recommendSolo===true,trend:recentAvg>olderAvg+0.3?'improving':recentAvg<olderAvg-0.3?'declining':'stable'}; }
export interface TrainingCertificate { officerId:string; courseId:string; certificateNumber:string; issueDate:string; expirationDate:string|null; }
export function verifyCEUs(officerId:string,certificates:TrainingCertificate[],requiredHours:number): {earned:number;remaining:number;compliant:boolean} { const earned=certificates.filter(c=>c.officerId===officerId).length; return{earned,remaining:Math.max(0,requiredHours-earned),compliant:earned>=requiredHours}; }
export interface TrainingFeedback { courseId:string; officerId:string; rating:1|2|3|4|5; feedback:string; improvementSuggestions:string; }
export function analyzeTrainingFeedback(feedback:TrainingFeedback[]): {avgRating:number;satisfactionRate:number;commonThemes:string[]} { const ratings=feedback.filter(f=>f.rating); const avg=ratings.length>0?Math.round(ratings.reduce((s,f)=>s+f.rating,0)/ratings.length*10)/10:0; return{avgRating:avg,satisfactionRate:ratings.length>0?Math.round(ratings.filter(f=>f.rating>=4).length/ratings.length*100):0,commonThemes:[]}; }
export interface TrainingDashboard { coursesThisMonth:number; officersTrained:number; trainingHours:number; complianceRate:number; budgetUtilization:number; certificationsExpiring:number; }
export function compileTrainingDashboard(courses:number,officers:number,hours:number,compliance:number,budget:number,certs:number): TrainingDashboard { return{coursesThisMonth:courses,officersTrained:officers,trainingHours:hours,complianceRate:compliance,budgetUtilization:budget,certificationsExpiring:certs}; }
