// ============================================================
// RMPG Flex — Use of Force Tracking (Spillman Flex Standard)
// 10 UoF features: force type classification, Graham v Connor
// analysis, subject resistance levels, officer response levels,
// injury tracking, medical aid documentation, supervisor review,
// force continuum compliance, pattern analysis, UoF statistics.
// ============================================================

/* 1: Force Type Classification */ export interface ForceType { id:string; level:1|2|3|4|5; name:string; category:'presence'|'verbal'|'soft_empty_hand'|'hard_empty_hand'|'less_lethal'|'lethal'; requiresMedicalCheck:boolean; requiresSupervisorNotification:boolean; }
export const FORCE_LEVELS: ForceType[] = [{id:'level1',level:1,name:'Officer Presence',category:'presence',requiresMedicalCheck:false,requiresSupervisorNotification:false},{id:'level2',level:2,name:'Verbal Direction',category:'verbal',requiresMedicalCheck:false,requiresSupervisorNotification:false},{id:'level3',level:3,name:'Soft Empty Hand Control',category:'soft_empty_hand',requiresMedicalCheck:false,requiresSupervisorNotification:false},{id:'level4',level:4,name:'Hard Empty Hand / OC / Taser',category:'less_lethal',requiresMedicalCheck:true,requiresSupervisorNotification:true},{id:'level5',level:5,name:'Lethal Force',category:'lethal',requiresMedicalCheck:true,requiresSupervisorNotification:true}];
/* 2: Graham Factors */ export interface GrahamAnalysis { severityOfCrime:string; immediateThreat:boolean; activelyResisting:boolean; attemptingEvasion:boolean; totalityAssessment:string; reasonableForce:boolean; }
export function applyGraham(incident:{crimeType:string;weaponPresent:boolean;subjectFleeing:boolean;subjectFighting:boolean}): GrahamAnalysis { const severity=['felony','violent'].some(t=>incident.crimeType.includes(t))?'serious':'minor'; const reasonable=incident.weaponPresent||incident.subjectFighting; return{severityOfCrime:severity,immediateThreat:incident.weaponPresent,activelyResisting:incident.subjectFighting,attemptingEvasion:incident.subjectFleeing,totalityAssessment:`${severity} crime, ${incident.weaponPresent?'weapon present':'no weapon'}, ${incident.subjectFighting?'actively resisting':'not resisting'}`,reasonableForce:reasonable}; }
/* 3: Subject Resistance */ export interface ResistanceLevel { id:string; level:1|2|3|4|5; description:string; examples:string[]; }
export const RESISTANCE_LEVELS: ResistanceLevel[] = [{id:'r1',level:1,description:'Compliant',examples:['Follows commands','No resistance']},{id:'r2',level:2,description:'Passive Resistance',examples:['Dead weight','Refuses to move','Locks arms']},{id:'r3',level:3,description:'Active Resistance',examples:['Pulling away','Tensing','Bracing']},{id:'r4',level:4,description:'Assaultive',examples:['Punching','Kicking','Fighting']},{id:'r5',level:5,description:'Deadly Force',examples:['Weapon displayed','Attempting to disarm officer']}];
/* 4: Officer Response Matching */ export function matchForceToResistance(resistanceLevel:number): ForceType[] { return FORCE_LEVELS.filter(f=>f.level>=resistanceLevel&&f.level<=resistanceLevel+1); }
/* 5: Injury Tracking */ export interface UoFInjury { incidentId:string; personType:'officer'|'subject'|'bystander'; injuryType:string; severity:'minor'|'moderate'|'serious'|'critical'; medicalTreatment:boolean; hospitalized:boolean; }
export function trackInjuries(injuries:UoFInjury[]): {officerInjuries:number;subjectInjuries:number;seriousInjuries:number;hospitalizationRate:number} { const oi=injuries.filter(i=>i.personType==='officer'); const si=injuries.filter(i=>i.personType==='subject'); return{officerInjuries:oi.length,subjectInjuries:si.length,seriousInjuries:injuries.filter(i=>i.severity==='serious'||i.severity==='critical').length,hospitalizationRate:injuries.length>0?Math.round(injuries.filter(i=>i.hospitalized).length/injuries.length*100):0}; }
/* 6: Medical Aid */ export interface MedicalAid { incidentId:string; offered:boolean; accepted:boolean; providedBy:string; transportMethod:string|null; facility:string|null; }
export function checkMedicalCompliance(aid:MedicalAid[]): {offeredRate:number;acceptedRate:number;transportedRate:number} { const offered=aid.filter(a=>a.offered).length; return{offeredRate:aid.length>0?Math.round(offered/aid.length*100):0,acceptedRate:offered>0?Math.round(aid.filter(a=>a.accepted).length/offered*100):0,transportedRate:aid.length>0?Math.round(aid.filter(a=>a.transportMethod).length/aid.length*100):0}; }
/* 7: Supervisor Review */ export interface UoFReview { incidentId:string; supervisorId:string; reviewDate:string; policyCompliant:boolean; forceReasonable:boolean; deescalationAttempted:boolean; findings:string; recommendations:string; status:'pending'|'reviewed'|'escalated'; }
export function escalateReview(review:UoFReview): {escalated:boolean;reason:string} { const shouldEscalate=!review.policyCompliant||!review.forceReasonable||review.findings.includes('excessive'); return{escalated:shouldEscalate,reason:shouldEscalate?'Policy violation or excessive force finding':'Routine review'}; }
/* 8: Force Continuum Compliance */ export function assessForceContinuum(forceLevel:number,resistanceLevel:number): {withinPolicy:boolean;explanation:string} { const within=forceLevel>=resistanceLevel&&forceLevel<=resistanceLevel+1; return{withinPolicy:within,explanation:within?'Force proportional to resistance':forceLevel<resistanceLevel?'Force below resistance level — officer safety concern':'Force exceeded resistance level — review required'}; }
/* 9: Pattern Analysis */ export interface UoFPattern { officerId:string; period:string; totalIncidents:number; avgForceLevel:number; injuryRate:number; deescalationRate:number; outlierScore:number; }
export function detectOutlierPatterns(patterns:UoFPattern[],threshold:number=2): UoFPattern[] { const avg=patterns.length>0?patterns.reduce((s,p)=>s+p.totalIncidents,0)/patterns.length:0; return patterns.filter(p=>p.totalIncidents>avg*threshold).map(p=>({...p,outlierScore:Math.round(p.totalIncidents/Math.max(1,avg)*100)})); }
/* 10: UoF Statistics */ export interface UoFStats { period:string; totalIncidents:number; byLevel:Record<number,number>; byRace:Record<string,number>; officerInjuries:number; subjectInjuries:number; complaintsRelated:number; }
export function compileUoFStats(incidents:Array<{forceLevel:number}>): UoFStats { const bl:Record<number,number>={};for(const i of incidents)bl[i.forceLevel]=(bl[i.forceLevel]||0)+1; return{period:new Date().toISOString().slice(0,7),totalIncidents:incidents.length,byLevel:bl,byRace:{},officerInjuries:0,subjectInjuries:0,complaintsRelated:0}; }
