// ⚠️ MOCK / SCAFFOLD ONLY — NOT WIRED INTO THE APP (no importers as of 2026-06-02).
// These helpers fabricate warrant priority scores, batches, extradition/recall
// outcomes and bond figures with NO backing data source. They must NEVER feed a
// PDF, an NCIC submission, a real bond/extradition decision, or any officer-facing
// surface. Use the real handlers (src/routes/warrants.ts) + verified D1 data instead.
// Kept only as a UI-shape reference; delete if it remains unused.
// 50 warrant enhancements
export interface WarrantBatch { id:string; warrants:string[]; batchType:'service'|'verification'|'recall'; createdBy:string; status:string; }
export function createWarrantBatch(warrantIds:string[],type:string): WarrantBatch { return{id:`wb-${Date.now()}`,warrants:warrantIds,batchType:type as any,createdBy:'',status:'pending'}; }
export interface WarrantPriority { warrantId:string; score:number; factors:string[]; recommendedAction:string; }
export function prioritizeWarrant(warrant:{charges:string[];extraditable:boolean;ageDays:number;officerSafetyFlags:string[]}): WarrantPriority { let score=0;const factors:string[]=[]; if(warrant.charges.some(c=>c.includes('felony'))){score+=30;factors.push('Felony charges');} if(warrant.extraditable){score+=20;factors.push('Extraditable');} if(warrant.ageDays<30){score+=15;factors.push('Recent warrant');} if(warrant.officerSafetyFlags.length>0){score+=25;factors.push('Officer safety alert');} return{warrantId:'',score,factors,recommendedAction:score>50?'Priority service':score>25?'Routine service':'Monitor'}; }
export interface WarrantServiceZone { zone:string; activeWarrants:number; officersAssigned:number; coveragePct:number; }
export function optimizeWarrantZones(zones:Array<{name:string;warrants:number;officers:number}>): WarrantServiceZone[] { return zones.map(z=>({zone:z.name,activeWarrants:z.warrants,officersAssigned:z.officers,coveragePct:z.officers>0?Math.round(z.warrants/z.officers*100):0})); }
export interface WarrantFee { warrantId:string; feeType:'bond'|'cash_only'|'surety'|'PR'|'signature'; amount:number; posted:boolean; postedAmount:number; }
export function calculateBondSchedule(charge:string): {recommendedAmount:number;schedule:string} { const bonds:Record<string,number>={felony_murder:1000000,felony_violent:100000,felony_property:25000,misdemeanor:5000,traffic:1000}; const key=Object.keys(bonds).find(k=>charge.includes(k))||'misdemeanor'; return{recommendedAmount:bonds[key],schedule:'Standard bond schedule'}; }
export interface WarrantConfirmation { warrantId:string; confirmedBy:string; confirmationSource:'ncic'|'state'|'county'|'agency'; confirmationNumber:string; confirmedAt:string; }
export function confirmWarrant(warrantId:string,officerId:string,source:string,num:string): WarrantConfirmation { return{warrantId,confirmedBy:officerId,confirmationSource:source as any,confirmationNumber:num,confirmedAt:new Date().toISOString()}; }
export interface WarrantEntry { warrantId:string; location:string; entryMethod:string; timeOfDay:string; riskLevel:string; officersNeeded:number; }
export function planWarrantEntry(location:string,riskLevel:string): WarrantEntry { const officers=riskLevel==='high'?6:riskLevel==='medium'?4:2; return{warrantId:'',location,entryMethod:riskLevel==='high'?'dynamic':'knock_and_announce',timeOfDay:new Date().getHours()<6?'night':'day',riskLevel,officersNeeded:officers}; }
export interface WarrantSurveillance { warrantId:string; location:string; startTime:string; endTime:string|null; observations:string[]; subjectPresent:boolean; }
export function logSurveillance(warrantId:string,location:string,observations:string[]): WarrantSurveillance { return{warrantId,location,startTime:new Date().toISOString(),endTime:null,observations,subjectPresent:false}; }
export interface NighttimeService { warrantId:string; judicialAuthorization:boolean; judgeName:string|null; authorizationDate:string|null; reason:string; }
export function authorizeNighttimeService(warrantId:string,reason:string): NighttimeService { return{warrantId,judicialAuthorization:false,judgeName:null,authorizationDate:null,reason}; }
export interface WarrantBriefing { warrantId:string; briefingDate:string; attendees:string[]; subjectPhoto:boolean; locationPhotos:boolean; knownHazards:string[]; contingencyPlan:string; }
export function prepareWarrantBriefing(warrantId:string,hazards:string[]): WarrantBriefing { return{warrantId,briefingDate:new Date().toISOString().slice(0,10),attendees:[],subjectPhoto:false,locationPhotos:false,knownHazards:hazards,contingencyPlan:'Withdraw and contain if compromised. Request supervisor.'}; }
export function rankWarrantServicePriority(warrants:Array<{charges:string[];extraditable:boolean;ageDays:number;officerSafety:boolean}>): typeof warrants { return[...warrants].sort((a,b)=>{const aScore=(a.charges.some(c=>c.includes('felony'))?3:1)+(a.extraditable?2:0)+(a.ageDays<30?1:0)+(a.officerSafety?3:0);const bScore=(b.charges.some(c=>c.includes('felony'))?3:1)+(b.extraditable?2:0)+(b.ageDays<30?1:0)+(b.officerSafety?3:0);return bScore-aScore;}); }
export interface WarrantRecallRequest { warrantId:string; reason:string; supportingDoc:string|null; courtOrderNumber:string; status:string; }
export function requestWarrantRecall(warrantId:string,reason:string,courtOrder:string): WarrantRecallRequest { return{warrantId,reason,supportingDoc:null,courtOrderNumber:courtOrder,status:'submitted'}; }
export interface WarrantExtension { warrantId:string; originalExpiration:string; extendedTo:string; extensionReason:string; authorizedBy:string; }
export function extendWarrant(warrantId:string,days:number,reason:string): WarrantExtension { const exp=new Date();exp.setDate(exp.getDate()+days); return{warrantId,originalExpiration:'',extendedTo:exp.toISOString().slice(0,10),extensionReason:reason,authorizedBy:''}; }
export interface WarrantQuash { warrantId:string; quashReason:string; courtOrderNumber:string; quashDate:string; ncicRemoved:boolean; }
export function quashWarrant(warrantId:string,courtOrder:string,reason:string): WarrantQuash { return{warrantId,quashReason:reason,courtOrderNumber:courtOrder,quashDate:new Date().toISOString().slice(0,10),ncicRemoved:false}; }
export interface WarrantAppeal { warrantId:string; appealGrounds:string; filedBy:string; filedDate:string; hearingDate:string|null; decision:string|null; }
export function fileWarrantAppeal(warrantId:string,grounds:string,attorney:string): WarrantAppeal { return{warrantId,appealGrounds:grounds,filedBy:attorney,filedDate:new Date().toISOString().slice(0,10),hearingDate:null,decision:null}; }
export interface WarrantServiceReport { warrantId:string; serviceDate:string; servingOfficer:string; method:string; useOfForce:boolean; injuries:number; propertyDamage:string; }
export function generateServiceReport(warrantId:string,officer:string,method:string): WarrantServiceReport { return{warrantId,serviceDate:new Date().toISOString().slice(0,10),servingOfficer:officer,method,useOfForce:false,injuries:0,propertyDamage:'None'}; }
export function validateWarrantForm(warrant:{subjectName:string;charges:string[];issuingCourt:string;judge:string}): {valid:boolean;errors:string[]} { const errors:string[]=[]; if(!warrant.subjectName)errors.push('Subject name required'); if(warrant.charges.length===0)errors.push('At least one charge required'); if(!warrant.issuingCourt)errors.push('Issuing court required'); if(!warrant.judge)errors.push('Judge name required'); return{valid:errors.length===0,errors}; }
export interface WarrantNCICEntry { warrantId:string; nicNumber:string; entryDate:string; modifyingAgency:string; status:'entered'|'modified'|'cancelled'|'located'; }
export function submitNCICEntry(warrantId:string): WarrantNCICEntry { return{warrantId,nicNumber:`NIC/W${Date.now()}`.slice(0,15),entryDate:new Date().toISOString().slice(0,10),modifyingAgency:'RMPG',status:'entered'}; }
export function calculateExtraditionDistance(issuingState:string,arrestState:string): {distance:number;extraditable:boolean;estimatedCost:number} { return{distance:500,extraditable:true,estimatedCost:2500}; }
export interface WarrantSearchLog { id:string; searchDate:string; searchedBy:string; searchCriteria:Record<string,string>; resultsCount:number; }
export function logWarrantSearch(searcher:string,criteria:Record<string,string>,results:number): WarrantSearchLog { return{id:`ws-${Date.now()}`,searchDate:new Date().toISOString(),searchedBy:searcher,searchCriteria:criteria,resultsCount:results}; }
export interface WarrantReport { reportType:string; generatedAt:string; filters:Record<string,any>; data:any; }
export function generateWarrantReport(type:string,filters:Record<string,any>): WarrantReport { return{reportType:type,generatedAt:new Date().toISOString(),filters,data:{}}; }
export function getWarrantCountdown(expirationDate:string): {daysRemaining:number;expired:boolean;urgency:string} { const days=Math.ceil((new Date(expirationDate).getTime()-Date.now())/86400000); return{daysRemaining:days,expired:days<=0,urgency:days<=0?'expired':days<=7?'critical':days<=30?'warning':'normal'}; }
export function scrubWarrantData(warrant:Record<string,any>,fieldsToScrub:string[]): Record<string,any> { const scrubbed={...warrant}; for(const f of fieldsToScrub)delete scrubbed[f]; return scrubbed; }
export function compareWarrantVersions(v1:Record<string,any>,v2:Record<string,any>): {changes:Record<string,{from:any;to:any}>} { const changes:Record<string,{from:any;to:any}>={}; for(const k of Object.keys({...v1,...v2})){if(JSON.stringify(v1[k])!==JSON.stringify(v2[k]))changes[k]={from:v1[k],to:v2[k]};} return{changes}; }
export interface WarrantDispatch { warrantId:string; assignedTo:string; assignedAt:string; acceptedAt:string|null; status:string; }
export function dispatchWarrant(warrantId:string,officerId:string): WarrantDispatch { return{warrantId,assignedTo:officerId,assignedAt:new Date().toISOString(),acceptedAt:null,status:'dispatched'}; }
export interface WarrantClearance { warrantId:string; clearanceType:'served'|'recalled'|'quashed'|'dismissed'|'bond_posted'|'other'; clearanceDate:string; clearedBy:string; }
export function clearWarrant(warrantId:string,type:string,officerId:string): WarrantClearance { return{warrantId,clearanceType:type as any,clearanceDate:new Date().toISOString().slice(0,10),clearedBy:officerId}; }
export interface WarrantLocate { warrantId:string; locateDate:string; locateMethod:string; location:string; subjectInCustody:boolean; }
export function logWarrantLocate(warrantId:string,method:string,location:string): WarrantLocate { return{warrantId,locateDate:new Date().toISOString().slice(0,10),locateMethod:method,location,subjectInCustody:true}; }
export interface WarrantMemo { warrantId:string; memoType:string; content:string; author:string; createdAt:string; }
export function addWarrantMemo(warrantId:string,type:string,content:string,author:string): WarrantMemo { return{warrantId,memoType:type,content,author,createdAt:new Date().toISOString()}; }
export function getActiveWarrantCounts(warrants:Array<{status:string}>): {total:number;active:number;served:number;recalled:number} { return{total:warrants.length,active:warrants.filter(w=>w.status==='active').length,served:warrants.filter(w=>w.status==='served').length,recalled:warrants.filter(w=>w.status==='recalled').length}; }
export function filterWarrantsByDateRange(warrants:Array<{issuedDate:string}>,start:string,end:string): typeof warrants { return warrants.filter(w=>w.issuedDate>=start&&w.issuedDate<=end); }
export function groupWarrantsByCharge(warrants:Array<{charges:string[]}>): Record<string,number> { const counts:Record<string,number>={}; for(const w of warrants)for(const c of w.charges)counts[c]=(counts[c]||0)+1; return counts; }
export function getOfficerWarrantStats(warrants:Array<{assignedTo:string;status:string;servedDate:string|null}>): Record<string,{assigned:number;served:number}> { const stats:Record<string,{assigned:number;served:number}>={}; for(const w of warrants){if(!stats[w.assignedTo])stats[w.assignedTo]={assigned:0,served:0}; stats[w.assignedTo].assigned++; if(w.status==='served')stats[w.assignedTo].served++;} return stats; }
export interface WarrantDashboard { activeWarrants:number; warrantsServedThisMonth:number; warrantsIssuedThisMonth:number; averageAgeDays:number; outstandingFelonies:number; ncicEntries:number; }
export function compileWarrantDashboard(active:number,served:number,issued:number,felonies:number,ncic:number): WarrantDashboard { return{activeWarrants:active,warrantsServedThisMonth:served,warrantsIssuedThisMonth:issued,averageAgeDays:0,outstandingFelonies:felonies,ncicEntries:ncic}; }
