import type { jsPDF } from 'jspdf';
import type { AuditLogPdfInput, AuditLogEntryForPdf } from '../../../utils/auditLogPdf';
import type { ConversationTranscriptInput } from '../../../utils/conversationTranscriptPdf';
import type { Message } from '../../../types';
import type { EmailThreadPdfInput } from '../../../utils/emailThreadPdf';
import type { EmailMessage } from '../../../types';
import type { HelpQuickReferenceInput } from '../../../utils/helpQuickReferencePdf';
import type { KnowledgeBaseSearchPdfInput } from '../../../utils/knowledgeBaseSearchPdf';
import type { KbResult } from '../../../utils/knowledgeBase';
import { generateNcicReferencePdf } from '../../../utils/ncicReferencePdf';
import type { StatutePdfOptions } from '../../../utils/statutePdfGenerator';
import type { StatuteResult } from '../../../components/StatuteLookup';
import type { TaskPdfInput, TaskRowForPdf } from '../../../utils/taskPdf';
import type { DispatchGuidePdfOptions } from '../../../utils/dispatchGuidePdfGenerator';
import { generateWebResearchReportPdf } from '../../../utils/webResearchReportPdf';
import type { WebResearchResultForPdf, WebResearchPdfContext } from '../../../utils/webResearchReportPdf';
import type { SafetySheetInput } from '../../../utils/dlSafetySheet';
import type { PdfFixture } from '../types';

// Synthetic data only. No real user, subject, or agency record from live
// data may appear here — organization policy. Realistic domain phrasing
// (Utah Code citations, NCIC operator language, audit-log action verbs,
// real email header shapes) is used deliberately instead of lorem ipsum,
// since genuine phrase collisions are what the placeholder-leak detector
// is meant to catch. US units throughout. Company name spelled out in
// full ("Rocky Mountain Protective Group") except where space forbids it.

const MAXIMAL_NAME =
  'Bartholomew Maximilian Fitzgerald-Whitlock Holdings & Associates, LLC, a Utah Limited Liability Company'.padEnd(120, ' ').slice(0, 120);

const BOILERPLATE_SENTENCE =
  'This record was generated by RMPG Flex and reflects the state of the system at the time of export. ' +
  'Rocky Mountain Protective Group retains the underlying data of record; this printout is a point-in-time snapshot. ';
const MAXIMAL_NARRATIVE = BOILERPLATE_SENTENCE.repeat(Math.ceil(2000 / BOILERPLATE_SENTENCE.length)).slice(0, 2000);

const YEAR_BOUNDARY = '2026-12-31T23:59:00Z';

// ── Audit Log (auditLogPdf.ts) ────────────────────────────────

function auditLogEntry(i: number): AuditLogEntryForPdf {
  return {
    id: 9000 + i,
    user_id: 42,
    user_name: 'Marcus Reyes',
    badge_number: '4417',
    user_role: 'supervisor',
    action: i % 3 === 0 ? 'update' : i % 3 === 1 ? 'view' : 'create',
    entity_type: 'warrant',
    entity_id: `2026-00${4400 + i}`,
    details: `Field "status" changed from "open" to "served" (row ${i})`,
    ip_address: '10.0.4.17',
    created_at: '2026-07-15T14:23:05Z',
  };
}

export const auditLogFixtures: PdfFixture<AuditLogPdfInput>[] = [
  {
    variant: 'typical',
    label: 'Filtered audit slice — entity type + date range, one exporting supervisor',
    input: {
      entries: [
        auditLogEntry(1),
        {
          id: 9002,
          user_id: 7,
          user_name: 'Dana Whitlock',
          badge_number: '1102',
          user_role: 'officer',
          action: 'delete',
          entity_type: 'field_photo',
          entity_id: '883',
          details: 'Removed duplicate upload from call 2026-004417',
          ip_address: '10.0.4.22',
          created_at: '2026-07-15T15:01:44Z',
        },
      ],
      filters: {
        entityType: 'warrant',
        startDate: '2026-07-01',
        endDate: '2026-07-31',
      },
      totalMatching: 2,
      exportedBy: 'Marcus Reyes',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no filters, no export attribution, one bare entry',
    input: {
      entries: [
        {
          id: 1,
          action: 'view',
          entity_type: 'person',
          entity_id: '1',
          created_at: '2026-01-01T00:00:00Z',
        },
      ],
    },
  },
  {
    variant: 'maximal',
    label: '40-row audit table, full filter snapshot, year-boundary entry',
    input: {
      entries: [
        ...Array.from({ length: 39 }, (_, i) => auditLogEntry(i)),
        {
          id: 9999,
          user_id: 42,
          user_name: MAXIMAL_NAME,
          badge_number: '4417',
          user_role: 'admin',
          action: 'update',
          entity_type: 'warrant',
          entity_id: '2026-009999',
          details: MAXIMAL_NARRATIVE,
          ip_address: '10.0.4.17',
          created_at: YEAR_BOUNDARY,
        },
      ],
      filters: {
        action: 'update',
        entityType: 'warrant',
        userId: '42',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        search: 'status',
      },
      totalMatching: 4032,
      exportedBy: MAXIMAL_NAME,
    },
  },
];

// ── Conversation Transcript (conversationTranscriptPdf.ts) ────

function transcriptMessage(i: number): Message {
  return {
    id: `msg-${i}`,
    from_user_id: '42',
    from_user_name: 'Marcus Reyes',
    to_user_id: '7',
    to_user_name: 'Dana Whitlock',
    subject: 'Riverton retail corridor',
    body: `Unit 12 requesting backup at 1400 S State St, call ${i}.`,
    priority: 'normal',
    is_read: true,
    is_broadcast: false,
    thread_id: 'thread-4417',
    created_at: '2026-07-15T14:23:05Z',
  };
}

export const conversationTranscriptFixtures: PdfFixture<ConversationTranscriptInput>[] = [
  {
    variant: 'typical',
    label: 'Two-party thread with one urgent message',
    input: {
      threadId: 'thread-4417',
      subject: 'Riverton retail corridor coverage',
      messages: [
        transcriptMessage(1),
        {
          id: 'msg-2',
          from_user_id: '7',
          from_user_name: 'Dana Whitlock',
          to_user_id: '42',
          to_user_name: 'Marcus Reyes',
          subject: 'Riverton retail corridor coverage',
          body: 'Copy, en route — ETA 4 minutes.',
          priority: 'urgent',
          is_read: false,
          is_broadcast: false,
          thread_id: 'thread-4417',
          created_at: '2026-07-15T14:24:10Z',
        },
      ],
      exportedBy: 'Marcus Reyes',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — empty message list',
    input: {
      threadId: 'thread-0000',
      subject: '',
      messages: [
        {
          id: 'msg-0',
          from_user_id: '1',
          from_user_name: '',
          subject: '',
          body: '',
          priority: 'normal',
          is_read: false,
          is_broadcast: false,
          created_at: '2026-01-01T00:00:00Z',
        },
      ],
    },
  },
  {
    variant: 'maximal',
    label: '40-message broadcast thread, 2,000-char body, year-boundary timestamp',
    input: {
      threadId: 'thread-9999',
      subject: MAXIMAL_NAME,
      messages: [
        ...Array.from({ length: 39 }, (_, i) => transcriptMessage(i)),
        {
          id: 'msg-999',
          from_user_id: '42',
          from_user_name: MAXIMAL_NAME,
          to_group: 'All Units',
          subject: MAXIMAL_NAME,
          body: MAXIMAL_NARRATIVE,
          priority: 'emergency',
          is_read: false,
          is_broadcast: true,
          thread_id: 'thread-9999',
          created_at: YEAR_BOUNDARY,
        },
      ],
      exportedBy: MAXIMAL_NAME,
    },
  },
];

// ── Email Thread Transcript (emailThreadPdf.ts) ───────────────

function emailMessage(i: number): EmailMessage {
  return {
    id: `email-${i}`,
    conversationId: 'conv-4417',
    subject: 'RE: Records request — case 2026-004417',
    fromAddress: 'dana.whitlock@example.gov',
    fromName: 'Dana Whitlock',
    toAddresses: [{ email: 'marcus.reyes@example.gov', name: 'Marcus Reyes' }],
    ccAddresses: [],
    bodyPreview: `Attached is the requested documentation for case 2026-004417 (message ${i}).`,
    hasAttachments: false,
    isRead: true,
    isFlagged: false,
    importance: 'normal',
    receivedAt: '2026-07-15T14:23:05Z',
  };
}

export const emailThreadFixtures: PdfFixture<EmailThreadPdfInput>[] = [
  {
    variant: 'typical',
    label: 'Two-message thread with one attachment, high importance',
    input: {
      threadId: 'conv-4417',
      folder: 'Inbox',
      messages: [
        emailMessage(1),
        {
          id: 'email-2',
          conversationId: 'conv-4417',
          subject: 'RE: Records request — case 2026-004417',
          fromAddress: 'marcus.reyes@example.gov',
          fromName: 'Marcus Reyes',
          toAddresses: [{ email: 'dana.whitlock@example.gov', name: 'Dana Whitlock' }],
          ccAddresses: [{ email: 'records@example.gov', name: 'Records Unit' }],
          bodyPreview: 'Received — filing under case 2026-004417.',
          hasAttachments: true,
          isRead: false,
          isFlagged: true,
          importance: 'high',
          receivedAt: '2026-07-15T15:01:44Z',
        },
      ],
      attachmentsByMessageId: {
        'email-1': [
          { id: 'att-1', name: 'incident-report.pdf', contentType: 'application/pdf', size: 204800, isInline: false },
        ],
      },
      exportedBy: 'Marcus Reyes',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no folder, no attachments, no export attribution',
    input: {
      threadId: 'conv-0000',
      messages: [
        {
          id: 'email-0',
          subject: '',
          fromAddress: 'unknown@example.gov',
          fromName: '',
          toAddresses: [],
          ccAddresses: [],
          bodyPreview: '',
          hasAttachments: false,
          isRead: false,
          isFlagged: false,
          importance: 'normal',
          receivedAt: '2026-01-01T00:00:00Z',
        },
      ],
    },
  },
  {
    variant: 'maximal',
    label: '40-message thread, 2,000-char body preview, year-boundary timestamp',
    input: {
      threadId: 'conv-9999',
      folder: 'Sent Items',
      messages: [
        ...Array.from({ length: 39 }, (_, i) => emailMessage(i)),
        {
          id: 'email-999',
          conversationId: 'conv-9999',
          subject: MAXIMAL_NAME,
          fromAddress: 'dana.whitlock@example.gov',
          fromName: MAXIMAL_NAME,
          toAddresses: Array.from({ length: 5 }, (_, i) => ({ email: `recipient${i}@example.gov`, name: `Recipient ${i}` })),
          ccAddresses: Array.from({ length: 5 }, (_, i) => ({ email: `cc${i}@example.gov`, name: `CC ${i}` })),
          bodyPreview: MAXIMAL_NARRATIVE,
          hasAttachments: true,
          isRead: false,
          isFlagged: true,
          importance: 'low',
          receivedAt: YEAR_BOUNDARY,
        },
      ],
      attachmentsByMessageId: {
        'email-999': Array.from({ length: 5 }, (_, i) => ({
          id: `att-${i}`,
          name: `evidence-${i}.pdf`,
          contentType: 'application/pdf',
          size: 51200 * (i + 1),
          isInline: false,
        })),
      },
      exportedBy: MAXIMAL_NAME,
    },
  },
];

// ── Help Quick Reference Card (helpQuickReferencePdf.ts) ──────

export const helpQuickReferenceFixtures: PdfFixture<HelpQuickReferenceInput>[] = [
  {
    variant: 'typical',
    label: 'Two shortcut groups, standard priority/status/command tables',
    input: {
      shortcutGroups: [
        {
          title: 'Global',
          shortcuts: [
            { keys: ['Ctrl', 'K'], description: 'Open global search' },
            { keys: ['/'], description: 'Focus the CAD command line' },
          ],
        },
        {
          title: 'Dispatch',
          shortcuts: [
            { keys: ['F8'], description: 'Focus unit status line' },
          ],
        },
      ],
      priorities: [
        { level: '1', label: 'Emergency', desc: 'Immediate life-safety response' },
        { level: '3', label: 'Routine', desc: 'Non-urgent, next-available unit' },
      ],
      unitStatuses: [
        { code: '10-8', label: 'In Service', desc: 'Available for dispatch' },
        { code: '10-7', label: 'Out of Service', desc: 'Unavailable for dispatch' },
      ],
      cadCommands: [
        { cmd: '.st', desc: 'Set unit status' },
        { cmd: '.re', desc: 'Request records check' },
      ],
      appVersion: '5.8.4',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — one bare row per table',
    input: {
      shortcutGroups: [{ title: 'Global', shortcuts: [{ keys: [], description: '' }] }],
      priorities: [{ level: '', label: '', desc: '' }],
      unitStatuses: [{ code: '', label: '', desc: '' }],
      cadCommands: [{ cmd: '', desc: '' }],
      appVersion: '',
    },
  },
  {
    variant: 'maximal',
    label: '40-row CAD command table, 2,000-char description, long app version string',
    input: {
      shortcutGroups: [
        {
          title: MAXIMAL_NAME,
          shortcuts: Array.from({ length: 20 }, (_, i) => ({
            keys: ['Ctrl', 'Shift', String(i)],
            description: `Shortcut description ${i}`,
          })),
        },
      ],
      priorities: [
        { level: '1', label: 'Emergency', desc: MAXIMAL_NARRATIVE },
      ],
      unitStatuses: [
        { code: '10-8', label: 'In Service', desc: MAXIMAL_NARRATIVE },
      ],
      cadCommands: Array.from({ length: 40 }, (_, i) => ({ cmd: `.cmd${i}`, desc: `Command description ${i}` })),
      appVersion: MAXIMAL_NAME,
    },
  },
];

// ── Knowledge Base Search (knowledgeBaseSearchPdf.ts) ─────────

function kbResult(i: number): KbResult {
  return {
    type: i % 2 === 0 ? 'person' : 'call',
    label: `2026-00${4400 + i}`,
    title: `Result ${i}`,
    subtitle: 'Salt Lake City, UT',
    route: `/calls/${4400 + i}`,
    recordId: 4400 + i,
  };
}

export const knowledgeBaseSearchFixtures: PdfFixture<KnowledgeBaseSearchPdfInput>[] = [
  {
    variant: 'typical',
    label: 'Plate search with mixed-type results, active type filter',
    input: {
      query: 'UT-7X4K21',
      results: [
        { type: 'vehicle', label: 'UT-7X4K21', title: 'Vehicle — UT-7X4K21', subtitle: '2019 Ford F-150, silver', route: '/vehicles/301', recordId: 301 },
        { type: 'call', label: '2026-004417', title: 'Call 2026-004417', subtitle: '1400 S State St, Salt Lake City, UT', route: '/calls/4417', recordId: 4417 },
      ],
      activeTypeFilter: 'vehicle',
      officerName: 'Marcus Reyes',
      badgeNumber: '4417',
      caseNumber: '2026-004417',
      generatedAt: new Date('2026-07-15T14:23:05Z'),
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no results, no attribution',
    input: {
      query: '',
      results: [],
    },
  },
  {
    variant: 'maximal',
    label: '40 grouped results, 120-char query, year-boundary generation time',
    input: {
      query: MAXIMAL_NAME,
      results: Array.from({ length: 40 }, (_, i) => kbResult(i)),
      activeTypeFilter: null,
      officerName: MAXIMAL_NAME,
      badgeNumber: '4417',
      caseNumber: '2026-004417',
      generatedAt: new Date(YEAR_BOUNDARY), // new-date-ok: YEAR_BOUNDARY is an explicit ISO-8601 UTC literal ending in Z, not a naive server timestamp
    },
  },
];

// ── NCIC Operator Reference Guide (ncicReferencePdf.ts) ───────
// generateNcicReferencePdf(now, opts) takes two positional args and
// returns `jsPDF | void` depending on opts.returnDoc — the registry's
// `generate` contract requires a single argument that always returns
// a document, so this adapter forces `returnDoc: true` and unwraps.
// The generator's own content (terminal commands, code tables, Utah
// offense codes) is static reference data; the only real input is the
// injectable "now" clock used for the title-page timestamp.

export interface NcicReferenceFixtureInput {
  now?: Date;
}

export function ncicReferenceAdapter(input: NcicReferenceFixtureInput): jsPDF {
  const doc = generateNcicReferencePdf(input.now, { returnDoc: true });
  if (!doc) {
    throw new Error('generateNcicReferencePdf did not return a document with returnDoc: true');
  }
  return doc;
}

export const ncicReferenceFixtures: PdfFixture<NcicReferenceFixtureInput>[] = [
  {
    variant: 'typical',
    label: 'Standard generation timestamp',
    input: { now: new Date('2026-07-15T14:23:05Z') },
  },
  {
    variant: 'empty',
    label: 'No injected clock — generator falls back to the live Date',
    input: {},
  },
  {
    variant: 'maximal',
    label: 'Year-boundary generation timestamp',
    input: { now: new Date(YEAR_BOUNDARY) }, // new-date-ok: YEAR_BOUNDARY is an explicit ISO-8601 UTC literal ending in Z, not a naive server timestamp
  },
];

// ── Utah Law Book / Statute (statutePdfGenerator.ts) ──────────

function statuteSection(i: number): StatuteResult {
  return {
    id: 7600 + i,
    citation: `76-6-${206 + i}`,
    short_title: 'Burglary of a Vehicle',
    description: '(1) A person is guilty of burglary of a vehicle who unlawfully enters any vehicle with intent to commit an assault or a theft.',
    offense_level: 'class_a_misdemeanor',
    category: 'criminal',
    subcategory: 'Burglary',
    source_url: 'https://le.utah.gov/xcode/Title76/Chapter6/76-6-S206.html',
  };
}

export const statuteFixtures: PdfFixture<StatutePdfOptions>[] = [
  {
    variant: 'typical',
    label: 'Single-chapter export with plain-language summary',
    input: {
      docTitle: '76-6 · Offenses Against Property',
      subtitle: '2 sections',
      sections: [
        statuteSection(0),
        {
          id: 7601,
          citation: '76-6-206',
          short_title: 'Burglary of a Vehicle',
          description: '(1) A person is guilty of burglary of a vehicle who unlawfully enters any vehicle with intent to commit an assault or a theft.',
          offense_level: 'class_a_misdemeanor',
          category: 'criminal',
          subcategory: 'Burglary',
          plain_summary: 'Entering someone else\'s vehicle without permission, intending to steal from it or assault someone inside.',
          plain_elements: ['Unlawful entry into a vehicle', 'Intent to commit theft or assault'],
          effective_date: '2010-05-11',
          source_url: 'https://le.utah.gov/xcode/Title76/Chapter6/76-6-S206.html',
        },
      ],
      fileName: 'RMPG-Statute-76-6-206',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no subtitle, no plain-language summary, one section',
    input: {
      docTitle: '76-6-206',
      sections: [
        {
          id: 1,
          citation: '76-6-206',
          short_title: 'Burglary of a Vehicle',
          offense_level: null,
          category: 'criminal',
          subcategory: '',
        },
      ],
    },
  },
  {
    variant: 'maximal',
    label: '40-section chapter export, 2,000-char statutory text, 120-char title',
    input: {
      docTitle: MAXIMAL_NAME,
      subtitle: '40 sections',
      sections: Array.from({ length: 40 }, (_, i) => ({
        ...statuteSection(i),
        description: MAXIMAL_NARRATIVE,
        plain_summary: MAXIMAL_NARRATIVE,
        plain_elements: ['Element one', 'Element two', 'Element three'],
        effective_date: '2026-12-31',
      })),
      fileName: MAXIMAL_NAME,
    },
  },
];

// ── Tasks (taskPdf.ts) ────────────────────────────────────────

function taskRow(i: number): TaskRowForPdf {
  return {
    id: 500 + i,
    task_title: `Follow up on case 2026-00${4400 + i}`,
    priority: i % 2 === 0 ? 'high' : 'normal',
    status: 'open',
    assigned_to_name: 'Dana Whitlock',
    assigned_by_name: 'Marcus Reyes',
    due_date: '2026-07-31',
    linked_entity_type: 'call',
    linked_entity_id: 4400 + i,
    description: `Confirm disposition on call ${4400 + i}.`,
    created_at: '2026-07-15T14:23:05Z',
  };
}

export const taskFixtures: PdfFixture<TaskPdfInput>[] = [
  {
    variant: 'typical',
    label: 'Filtered open-task roster for one squad, with a completed task',
    input: {
      tasks: [
        taskRow(1),
        {
          id: 502,
          task_title: 'File evidence receipt',
          priority: 'low',
          status: 'completed',
          assigned_to_name: 'Marcus Reyes',
          assigned_by_name: 'Dana Whitlock',
          due_date: '2026-07-20',
          completed_at: '2026-07-19T09:12:00Z',
        },
      ],
      filters: {
        status: 'open',
        assignedToName: 'Dana Whitlock',
      },
      totalMatching: 2,
      exportedBy: 'Marcus Reyes',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — one bare task, no filters',
    input: {
      tasks: [{ id: 1, task_title: 'Untitled task' }],
    },
  },
  {
    variant: 'maximal',
    label: '40-row task list, 2,000-char description, year-boundary due date',
    input: {
      tasks: [
        ...Array.from({ length: 39 }, (_, i) => taskRow(i)),
        {
          id: 999,
          task_title: MAXIMAL_NAME,
          priority: 'high',
          status: 'overdue',
          assigned_to_name: MAXIMAL_NAME,
          assigned_by_name: 'Marcus Reyes',
          due_date: '2026-12-31',
          linked_entity_type: 'warrant',
          linked_entity_id: '2026-009999',
          description: MAXIMAL_NARRATIVE,
          created_at: YEAR_BOUNDARY,
        },
      ],
      filters: {
        status: 'open',
        priority: 'high',
        assignedTo: '42',
        assignedToName: MAXIMAL_NAME,
        entityType: 'warrant',
        overdue: true,
      },
      totalMatching: 4032,
      exportedBy: MAXIMAL_NAME,
    },
  },
];

// ── Dispatch Guide (dispatchGuidePdfGenerator.ts) ─────────────
// buildDispatchGuideDoc's own content (training narrative, quick-
// reference tables) is static; `options.printTarget` is the only
// caller-supplied input, so the three variants exercise the print-
// target switch rather than data shape. The live-codes fetch inside
// the generator fails closed to `null` in this (non-browser) test
// environment and the guide falls back to its hardcoded tables.

export const dispatchGuideFixtures: PdfFixture<DispatchGuidePdfOptions>[] = [
  { variant: 'typical', label: 'Office print target (default letter layout)', input: { printTarget: 'office' } },
  { variant: 'empty', label: 'Required fields only — no printTarget specified', input: {} },
  { variant: 'maximal', label: 'Mobile thermal print target (top-offset layout)', input: { printTarget: 'mobile' } },
];

// ── Web Research Report (webResearchReportPdf.ts) ─────────────
// generateWebResearchReportPdf(results, ctx) takes two positional
// args, not one — same single-argument adapter pattern as
// skipTracerAdapter / proposalAdapter in fixtures/clientFacing.ts.

export interface WebResearchFixtureInput {
  results: WebResearchResultForPdf[];
  ctx: WebResearchPdfContext;
}

export function webResearchReportAdapter(input: WebResearchFixtureInput): jsPDF {
  return generateWebResearchReportPdf(input.results, input.ctx);
}

function webResearchResult(i: number): WebResearchResultForPdf {
  return {
    id: 700 + i,
    query: 'Dana Whitlock Salt Lake City',
    title: `Search result ${i}`,
    url: `https://example-osint.test/profile/${i}`,
    description: 'Public directory listing, no verified law-enforcement source.',
    type: 'search',
    notes: null,
    linked_entity_type: 'person',
    linked_entity_id: 401,
    scraped_content: null,
    created_at: '2026-07-15T14:23:05Z',
  };
}

export const webResearchReportFixtures: PdfFixture<WebResearchFixtureInput>[] = [
  {
    variant: 'typical',
    label: 'Person-linked corpus with one scrape and operator notes',
    input: {
      results: [
        webResearchResult(1),
        {
          id: 702,
          query: 'Dana Whitlock Salt Lake City',
          title: 'Public records aggregator profile',
          url: 'https://example-osint.test/records/402',
          description: 'Aggregated public-records profile — name and city match only.',
          type: 'scrape',
          notes: 'Possible match — verify DOB before relying on this.',
          linked_entity_type: 'person',
          linked_entity_id: 401,
          scraped_content: 'Name: Dana Whitlock. City: Salt Lake City, UT. No DOB listed.',
          created_at: '2026-07-15T15:01:44Z',
        },
      ],
      ctx: {
        filter: 'person',
        officerName: 'Marcus Reyes',
        badgeNumber: '4417',
        caseNumber: '2026-004417',
      },
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no saved results, unlinked filter',
    input: {
      results: [],
      ctx: { filter: 'unlinked' },
    },
  },
  {
    variant: 'maximal',
    label: '40 saved results, 2,000-char scraped excerpt, year-boundary capture',
    input: {
      results: [
        ...Array.from({ length: 39 }, (_, i) => webResearchResult(i)),
        {
          id: 999,
          query: MAXIMAL_NAME,
          title: MAXIMAL_NAME,
          url: 'https://example-osint.test/profile/999',
          description: MAXIMAL_NARRATIVE,
          type: 'scrape',
          notes: MAXIMAL_NARRATIVE,
          linked_entity_type: 'case',
          linked_entity_id: 4419,
          scraped_content: MAXIMAL_NARRATIVE,
          created_at: YEAR_BOUNDARY,
        },
      ],
      ctx: {
        filter: 'case',
        officerName: MAXIMAL_NAME,
        badgeNumber: '4419',
        caseNumber: '2026-004419',
      },
    },
  },
];

// ── Pre-Contact Officer Safety Sheet (dlSafetySheet.ts) ───────

export const dlSafetySheetFixtures: PdfFixture<SafetySheetInput>[] = [
  {
    variant: 'typical',
    label: 'DL scan with one active warrant and a records-sweep hit',
    input: {
      ocrResult: { first_name: 'Dana', last_name: 'Whitlock', middle_name: '', dob: '1990-04-17', dl_number: '1234567', dl_state: 'UT' },
      leFields: [
        { tag: 'NAM', label: 'Name', value: 'WHITLOCK, DANA' },
        { tag: 'DOB', label: 'DOB', value: '1990-04-17' },
      ],
      scanAlerts: [{ level: 'danger', code: 'WARR', message: 'Active warrant on file' }],
      scanMatches: [{ id: 401, last_name: 'Whitlock', first_name: 'Dana', active_warrants: 1, total_warrants: 2 }],
      deepSweep: {
        sources: [{ key: 'utah_warrants', label: 'Utah Statewide Warrants', danger: true, rows: [{ summary: 'Failure to appear — 2026-004417', danger: true }] }],
        profile: { person: { probation_parole: 'Active supervision — Salt Lake County' } },
      },
      courtRecords: null,
      fbiRecords: null,
      officerName: 'Marcus Reyes',
    },
  },
  {
    variant: 'empty',
    label: 'Required fields only — no OCR result, no alerts, no matches',
    input: {
      ocrResult: null,
      leFields: null,
      scanAlerts: [],
      scanMatches: null,
      deepSweep: null,
      courtRecords: null,
    },
  },
  {
    variant: 'maximal',
    label: '40-row criminal history + FBI wanted + federal court records, year-boundary scan',
    input: {
      ocrResult: { first_name: 'Marcus', last_name: 'Reyes', middle_name: 'Anthony', dob: '1988-12-31', dl_number: '7654321', dl_state: 'UT' },
      leFields: [
        { tag: 'NAM', label: 'Name', value: 'REYES, MARCUS ANTHONY' },
        { tag: 'DOB', label: 'DOB', value: '1988-12-31' },
        { tag: 'ADR', label: 'Address', value: '1400 S State St' },
      ],
      scanAlerts: [
        { level: 'danger', code: 'WARR', message: 'Active warrant on file' },
        { level: 'caution', code: 'SUSP', message: 'License suspended — verify status' },
      ],
      scanMatches: [{ id: 402, last_name: 'Reyes', first_name: 'Marcus', active_warrants: 3, total_warrants: 6 }],
      deepSweep: {
        sources: [
          { key: 'utah_sor', label: 'Utah Sex Offender Registry', danger: true, rows: Array.from({ length: 5 }, (_, i) => ({ summary: `Registry entry ${i}`, danger: true })) },
        ],
        profile: {
          person: {
            is_sex_offender: 0,
            gang_affiliation: 'Documented associate — regional intelligence file',
            caution_flags: '["armed","flight risk"]',
            criminal_history: Array.from({ length: 40 }, (_, i) => ({ offense_date: '2026-01-01', offense: `Offense ${i}`, disposition: 'Convicted' })),
            incidents: [],
            vehicles: [{ plate_number: 'UT-7X4K21', state: 'UT', year: 2019, color: 'Silver', make: 'Ford', model: 'F-150', is_stolen: false }],
          },
        },
      },
      courtRecords: [{ is_criminal: true, case_name: 'State v. Reyes', court: 'Third District Court', date_filed: '2026-12-31' }],
      fbiRecords: [{ title: 'Wanted subject — description only', warning: MAXIMAL_NARRATIVE, is_danger: true }],
      officerName: MAXIMAL_NAME,
    },
  },
];
