export type CopyVariantId = 'violator' | 'officer' | 'administrative';

export interface CitationCopyVariant {
  id: CopyVariantId;
  bannerText: string;
  /** Lines as rendered top-to-bottom. Empty strings = blank line. */
  body: string[];
}

export const CITATION_INSTRUCTIONS: CitationCopyVariant[] = [
  {
    id: 'violator',
    bannerText: 'VIOLATOR COPY',
    body: [
      'You are charged with the violation',
      'described on the left half of this',
      'citation.',
      '',
      'YOUR OPTIONS',
      '',
      '1. PAY THE FINE',
      '   Mail payment to the court address',
      '   shown at left. Make checks payable',
      '   to the court.',
      '',
      '2. REQUEST A COURT HEARING',
      '   Appear in person at the court',
      '   named on or before the court date',
      '   shown.',
      '',
      '3. REQUEST A PLEA IN ABEYANCE',
      '   Contact the court directly within',
      '   14 days of issuance.',
      '',
      'WARNING — FAILURE TO RESPOND',
      '',
      'If you do not respond by the court',
      'date shown, a bench warrant may be',
      'issued for your arrest and your',
      "driver's license may be suspended.",
      '(Utah Code §53-3-218)',
      '',
      'Signature below acknowledges receipt',
      'only and is NOT an admission of',
      'guilt.',
      '',
      'X _______________________________',
      '  Violator Signature',
      '',
      'Date: ____________________________',
      '',
      'Issued under Utah Code Title 41',
      'Chapter 6a (Traffic Code) and',
      'Title 77 Chapter 7 (Criminal',
      'Procedure).',
    ],
  },
  {
    id: 'officer',
    bannerText: 'OFFICER COPY — RETAIN FOR RECORDS',
    body: [
      'ISSUING OFFICER ATTESTATION',
      '',
      'I certify under penalty of perjury',
      'under the laws of the State of Utah',
      'that I personally observed the',
      'violation described on the left,',
      'that the violation occurred at the',
      'date/time/location indicated, and',
      'that I issued this citation to the',
      'person identified.',
      '',
      'Officer ____________________________',
      '',
      'Badge # ____________________________',
      '',
      'Date ____________  Time ____________',
      '',
      'FIELD NOTES (court testimony)',
      '',
      '____________________________________',
      '____________________________________',
      '____________________________________',
      '____________________________________',
      '____________________________________',
      '____________________________________',
      '____________________________________',
      '',
      'WITNESS INFORMATION (if any)',
      '',
      'Name ______________________________',
      '',
      'Phone _____________________________',
      '',
      'Address ___________________________',
      '___________________________________',
      '',
      'X _______________________________',
      '  Officer Signature',
      '',
      'Date: ____________________________',
    ],
  },
  {
    id: 'administrative',
    bannerText: 'ADMINISTRATIVE COPY — COURT FILING',
    body: [
      'ROUTING',
      '',
      '[ ] Sent to court within 5 business',
      '  days',
      '[ ] Filed in agency records',
      '[ ] Forwarded to prosecutor (if',
      '  criminal)',
      '[ ] Bond posted: $ __________________',
      '',
      'CLERK PROCESSING',
      '',
      'Date Received _____________________',
      '',
      'Clerk Initials ____________________',
      '',
      'Case Number Assigned _______________',
      '',
      'DISPOSITION',
      '',
      '[ ] Pending court appearance',
      '[ ] Paid in full',
      '[ ] Dismissed',
      '[ ] Warrant issued (FTA)',
      '[ ] Plea in abeyance / Diversion',
      '[ ] Reduced/amended charge',
      '[ ] Other: __________________________',
      '',
      'SUPERVISOR REVIEW',
      '',
      'X _______________________________',
      '  Supervisor Signature',
      '',
      'Date: ____________________________',
      '',
      'NOTES FOR FILE',
      '',
      '____________________________________',
      '____________________________________',
      '____________________________________',
    ],
  },
];
