#!/usr/bin/env bash
# ============================================================
# RMPG Flex — OSM overlay tile builder
# ============================================================
# Builds PMTiles archives of statewide Utah OpenStreetMap reference data and
# uploads them to R2 (system-essentials/tiles/), where src/routes/tiles.ts
# serves them as /api/tiles/<name>/{z}/{x}/{y}.mvt.
#
# OSM is a DATA source only — this never touches the Mapbox basemap or style.
#
# Usage:
#   scripts/build-osm-tiles.sh --count-only        # measure, write counts doc, no tiles
#   scripts/build-osm-tiles.sh                     # full build + upload
#   scripts/build-osm-tiles.sh --group safety      # one group
#   scripts/build-osm-tiles.sh --skip-download     # reuse the cached extract
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="${ROOT}/.osm-build"
CATALOG="${ROOT}/config/osm-layers.json"
COUNTS_DOC="${ROOT}/docs/osm-utah-feature-counts.md"
BUCKET="system-essentials"

COUNT_ONLY=0
SKIP_DOWNLOAD=0
ONLY_GROUP=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --count-only)    COUNT_ONLY=1; shift ;;
    --skip-download) SKIP_DOWNLOAD=1; shift ;;
    --group)         ONLY_GROUP="${2:?--group needs a name}"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# ── Preflight ───────────────────────────────────────────────
# Fail up front with an actionable message rather than partway through a
# 250 MB pipeline.
missing=0
need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "MISSING: $1 — install with: $2" >&2
    missing=1
  fi
}
need osmium     "brew install osmium-tool"
need tippecanoe "brew install tippecanoe"
need jq         "brew install jq"
need node       "https://nodejs.org (v20+)"
if [[ $COUNT_ONLY -eq 0 ]]; then
  need npx      "ships with node"
fi
if [[ $missing -ne 0 ]]; then
  echo "" >&2
  echo "Install the tools above, then re-run." >&2
  exit 1
fi

[[ -f "$CATALOG" ]] || { echo "catalog not found: $CATALOG" >&2; exit 1; }

mkdir -p "$WORK"

EXTRACT_URL="$(jq -r '.extract' "$CATALOG")"
EXTRACT="${WORK}/utah-latest.osm.pbf"

# ── Download ────────────────────────────────────────────────
if [[ $SKIP_DOWNLOAD -eq 0 || ! -f "$EXTRACT" ]]; then
  echo "==> Downloading Utah extract (~250 MB)"
  curl -fL --progress-bar -o "${EXTRACT}.tmp" "$EXTRACT_URL"
  mv "${EXTRACT}.tmp" "$EXTRACT"
else
  echo "==> Reusing cached extract: $EXTRACT"
fi

EXTRACT_DATE="$(osmium fileinfo -e -g data.timestamp.last "$EXTRACT" 2>/dev/null | cut -dT -f1 || echo unknown)"
echo "==> Extract data timestamp: $EXTRACT_DATE"

# NOT `GROUPS` — that is a bash special variable holding the user's group IDs.
# Assigning to it is silently ignored and $GROUPS then yields a numeric GID
# (20 = staff on macOS), so every group name becomes "20". Passes bash -n and
# code review; fails only at runtime.
OSM_GROUPS="$(jq -r '.groups[].name' "$CATALOG")"
if [[ -n "$ONLY_GROUP" ]]; then
  echo "$OSM_GROUPS" | grep -qx "$ONLY_GROUP" || { echo "unknown group: $ONLY_GROUP" >&2; exit 2; }
  OSM_GROUPS="$ONLY_GROUP"
fi

# ── Per-group filter + transform ────────────────────────────
# Emits ${WORK}/<group>.geojsonseq and ${WORK}/<group>.counts.json for every
# group. Both modes need this; only the full build goes on to tippecanoe.
declare -a BUILT_GROUPS=()

for g in $OSM_GROUPS; do
  echo ""
  echo "==> [$g] filtering"
  # NOT `mapfile` — that is bash 4+, and macOS /bin/bash is 3.2. On 3.2 mapfile
  # is a missing builtin, FILTERS stays empty, and osmium would filter NOTHING —
  # producing an archive of the entire state instead of erroring.
  FILTERS=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && FILTERS+=("$f")
  done < <(jq -r --arg g "$g" \
    '.groups[] | select(.name==$g) | [.categories[].filters[]] | unique | .[]' "$CATALOG")
  [[ ${#FILTERS[@]} -gt 0 ]] || { echo "[$g] no filters resolved from catalog" >&2; exit 1; }

  osmium tags-filter --overwrite -o "${WORK}/${g}.osm.pbf" "$EXTRACT" "${FILTERS[@]}"

  echo "==> [$g] exporting + transforming"
  osmium export -f geojsonseq --overwrite -o "${WORK}/${g}.raw.geojsonseq" "${WORK}/${g}.osm.pbf"

  node "${ROOT}/scripts/osm/transform.mjs" --group "$g" \
    < "${WORK}/${g}.raw.geojsonseq" \
    > "${WORK}/${g}.geojsonseq" \
    2> "${WORK}/${g}.counts.json"

  # transform.mjs writes its summary as the LAST stderr line; keep only that.
  tail -n 1 "${WORK}/${g}.counts.json" > "${WORK}/${g}.counts.tmp"
  mv "${WORK}/${g}.counts.tmp" "${WORK}/${g}.counts.json"

  jq -r '"    " + (.counts | to_entries | map("\(.key)=\(.value)") | join("  "))' "${WORK}/${g}.counts.json"
  BUILT_GROUPS+=("$g")
done

# ── Counts doc ──────────────────────────────────────────────
write_counts_doc() {
  {
    echo "# Utah OSM Feature Counts"
    echo ""
    echo "Generated by \`scripts/build-osm-tiles.sh --count-only\`."
    echo "Extract data timestamp: **${EXTRACT_DATE}**"
    echo ""
    echo "Grounding record for the spec's drop rule: any category under 50"
    echo "statewide features is removed from the layer set before client work,"
    echo "unless it is high-consequence and low-frequency by nature (mine"
    echo "shafts, sally ports, helipads, riser inlets). Record the reason when keeping one."
    echo ""
    echo "| Group | Category | Features | Keep? | Reason |"
    echo "|---|---|---:|---|---|"
    for g in "${BUILT_GROUPS[@]}"; do
      jq -r --arg g "$g" '.counts | to_entries[] |
        "| \($g) | \(.key) | \(.value) | " +
        (if .value >= 50 then "yes | " else "**review** | " end) + " |"' \
        "${WORK}/${g}.counts.json"
    done
    echo ""
    echo "Skipped (matched a group filter but no category rule) and malformed:"
    echo ""
    echo "| Group | Skipped | Malformed |"
    echo "|---|---:|---:|"
    for g in "${BUILT_GROUPS[@]}"; do
      jq -r --arg g "$g" '"| \($g) | \(.skipped) | \(.malformed) |"' "${WORK}/${g}.counts.json"
    done
  } > "$COUNTS_DOC"
  echo ""
  echo "==> Wrote $COUNTS_DOC"
}

if [[ $COUNT_ONLY -eq 1 ]]; then
  write_counts_doc
  echo "==> Count-only run complete. No tiles generated, nothing uploaded."
  exit 0
fi

echo ""
echo "==> Tile generation is Task 6 — not yet implemented."
exit 0
