#!/usr/bin/env bash
#
# Idempotent Cloud Agent / local-dev bootstrap for RMPG Flex.
#
# Prepares a fully working local development environment:
#   1. Worker (root) dependencies
#   2. Client (React SPA) dependencies
#   3. Local dev secrets (.dev.vars) — generated once, never overwritten
#   4. A local Cloudflare D1 database seeded from the schema baseline, with
#      post-baseline migrations layered on top and a throwaway admin login
#
# Safe to re-run: every step converges to the same state.
#
# The dev servers themselves are NOT started here (a server does not belong in
# an install phase). Start them from .cursor/environment.json `terminals`, or
# manually:
#   npm run dev -- --local --enable-containers=false   # Worker on :8787
#   cd client && npm run dev                            # Vite  on :5173
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> [1/4] Installing Worker dependencies"
npm install

echo "==> [2/4] Installing client dependencies"
( cd client && npm install --legacy-peer-deps )

echo "==> [3/4] Ensuring local dev secrets (.dev.vars)"
if [ ! -f .dev.vars ]; then
  gen() { openssl rand -base64 32; }
  cat > .dev.vars <<EOF
# Local development secrets — generated by scripts/cloud-agent-setup.sh.
# This file is gitignored. These values are for LOCAL dev only and never touch
# production. Optional integration keys (ROBOFLOW_API_KEY, FLEETIO_API_KEY, ...)
# are left unset; their routes return 503 "not_configured" rather than crashing.
# See .dev.vars.example for the full list.
JWT_SECRET=$(gen)
EMAIL_FIELD_ENCRYPTION_KEK=$(gen)
RMPG_PQ_MASTER_KEY=$(gen)
RECOVERY_KEY=$(gen)
PDF_SIGNING_KEY=$(gen)
TRACCAR_ENC_KEY=$(gen)
CPG_ENC_KEY=$(gen)
EOF
  echo "    created .dev.vars with generated local secrets"
else
  echo "    .dev.vars already present — leaving it untouched"
fi

echo "==> [4/4] Bootstrapping local D1 database (rmpg-flex)"
# The historical migrations/*.sql files are NOT replayable from scratch (see
# migrations/README.md): duplicate 0001 files, ordering violations, and
# dup-column ALTERs make a from-scratch `wrangler d1 migrations apply` die on
# the second file. Instead we bootstrap from the authoritative schema-only
# snapshot of live, then layer migrations added after it.
npx wrangler d1 execute rmpg-flex --local --file migrations/baseline/schema.sql >/dev/null
echo "    baseline schema applied"

# Locate the miniflare-backed sqlite file for the rmpg-flex D1 binding
# (identified by a signature table so we never touch GEO_DB / KIOSK_DB).
DB=""
for f in .wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite; do
  [ "$(basename "$f")" = "metadata.sqlite" ] && continue
  if [ "$(sqlite3 "$f" "SELECT count(*) FROM sqlite_master WHERE name='calls_for_service'" 2>/dev/null || echo 0)" = "1" ]; then
    DB="$f"; break
  fi
done
if [ -z "$DB" ]; then
  echo "ERROR: could not locate the local rmpg-flex D1 sqlite file" >&2
  exit 1
fi

# Layer migrations newer than the baseline seed (0072+), tolerating the
# idempotent dup-column errors that come from the dirty-schema history.
#  * skip DROP TABLE rebuilds — they recreate core tables from the divergent
#    migration lineage (e.g. call_type instead of the live incident_type) and
#    would clobber the baseline's live-matching shape.
#  * strip ADD COLUMN against calls_for_service / persons — workerd's D1 rejects
#    a schema with >100 columns on a table, and both sit at the cap on live
#    (new columns belong in the *_ext overflow tables).
applied=0
for f in $(ls migrations/*.sql | sort); do
  base="$(basename "$f")"; prefix="${base:0:4}"
  case "$prefix" in [0-9][0-9][0-9][0-9]) ;; *) continue ;; esac
  [ "$prefix" -ge 0072 ] 2>/dev/null || continue
  if grep -qiE 'DROP TABLE' "$f"; then continue; fi
  sed -E '/^[[:space:]]*ALTER TABLE (calls_for_service|persons) ADD COLUMN/d' "$f" \
    | sqlite3 "$DB" 2>/dev/null || true
  applied=$((applied + 1))
done
echo "    layered $applied post-baseline migrations"

# Mark every migration filename as applied so a later `wrangler d1 migrations
# apply --local` is a clean no-op.
for f in migrations/*.sql; do
  sqlite3 "$DB" "INSERT OR IGNORE INTO d1_migrations (name, applied_at) VALUES ('$(basename "$f")', datetime('now'));" 2>/dev/null || true
done

# Seed a throwaway LOCAL admin so the environment is immediately loginable
# (the schema baseline carries no rows — never snapshot PII from a police DB).
HASH="$(node -e "console.log(require('bcryptjs').hashSync('DevPass123!', 10))")"
sqlite3 "$DB" "INSERT OR IGNORE INTO users (username, password_hash, full_name, role, status, email) VALUES ('devadmin', '$HASH', 'Dev Admin', 'admin', 'active', 'devadmin@example.test');"

echo ""
echo "Setup complete."
echo "  Local dev login (local-only, never production):  devadmin / DevPass123!"
echo "  Worker:  npm run dev -- --local --enable-containers=false   (http://localhost:8787)"
echo "  Client:  cd client && npm run dev                            (http://localhost:5173)"
