// ============================================================
// RMPG Flex — Arizona Revised Statutes (ARS)
// ============================================================
// Title 13: Criminal Code | Title 28: Transportation
// Offense levels mapped to Utah enum for UI compatibility:
//   AZ Class 1 Felony → first_degree_felony (death/life)
//   AZ Class 2 Felony → first_degree_felony
//   AZ Class 3 Felony → second_degree_felony
//   AZ Class 4 Felony → second_degree_felony
//   AZ Class 5 Felony → third_degree_felony
//   AZ Class 6 Felony → third_degree_felony
//   AZ Class 1 Misdemeanor → class_a_misdemeanor
//   AZ Class 2 Misdemeanor → class_b_misdemeanor
//   AZ Class 3 Misdemeanor → class_c_misdemeanor
//   AZ Petty Offense → infraction
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const ARIZONA_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // TITLE 13 — CRIMINAL CODE
  // ────────────────────────────────────────────────────────────

  // ── Chapter 1: General Provisions ──────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 1, section: '101', subsection: null, citation: 'ARS 13-101', short_title: 'Title & Purpose', description: 'Title and purposes of the Arizona Criminal Code', definition: 'Arizona Criminal Code (Title 13) defines criminal offenses, defenses, and sentences. Effective October 1, 1978, replacing the prior criminal code.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 6, section: '601', subsection: null, citation: 'ARS 13-601', short_title: 'Classification of Offenses', description: 'Classification of felonies (classes 1-6), misdemeanors (classes 1-3), and petty offenses', definition: 'Felonies: Class 1 (death/life) through Class 6 (4 months-2 years). Misdemeanors: Class 1 (up to 6 months) through Class 3 (up to 30 days). Petty offense: fine only. Arizona uses a presumptive sentencing system with aggravating/mitigating factors.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 7, section: '701', subsection: null, citation: 'ARS 13-701', short_title: 'Sentencing Ranges', description: 'Presumptive, minimum, maximum, and aggravated sentencing ranges for felonies', definition: 'Class 2: 3/4/5/10/12.5 yrs (min/presumptive/max/aggravated/super). Class 3: 2/2.5/3.5/7/8.75. Class 4: 1/1.5/2.5/3/3.75. Class 5: 0.5/0.75/1.5/2/2.5. Class 6: 0.33/0.5/1/1.5/2.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 1, section: '105', subsection: null, citation: 'ARS 13-105', short_title: 'Definitions', description: 'Key definitions used throughout the Arizona Criminal Code', definition: 'Dangerous offense: involves use or threatening exhibition of a deadly weapon or dangerous instrument, or intentional/knowing infliction of serious physical injury. Repetitive offender: 2+ historical prior felonies. Serious offense: enumerated list including murder, sexual assault, robbery, etc.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 10, section: '1001', subsection: null, citation: 'ARS 13-1001', short_title: 'Attempt', description: 'Intentionally doing anything which is a step in a course of conduct planned to culminate in a crime', definition: 'Elements: (1) Intentionally; (2) does or omits to do anything; (3) under circumstances which would constitute a crime; (4) a step in a course of conduct planned to culminate in commission. One class lower than completed offense (minimum class 6 felony).', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 10, section: '1003', subsection: null, citation: 'ARS 13-1003', short_title: 'Conspiracy', description: 'Agreeing with one or more persons to commit an offense and one party commits an overt act', definition: 'Elements: (1) With intent to promote or aid; (2) agrees with one or more persons; (3) that at least one will engage in conduct constituting an offense; (4) one of the conspirators commits an overt act. Same class as underlying offense.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 10, section: '1002', subsection: null, citation: 'ARS 13-1002', short_title: 'Solicitation', description: 'Commanding, encouraging, or requesting another person to engage in specific conduct constituting an offense', definition: 'Elements: (1) With intent to promote or facilitate; (2) commands, encourages, requests, or solicits; (3) another person to engage in conduct constituting an offense. Same class as completed offense.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },

  // ── Chapter 11: Homicide ───────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 11, section: '1101', subsection: null, citation: 'ARS 13-1101', short_title: 'Homicide Definitions', description: 'Definitions applicable to homicide offenses', definition: 'Adequate provocation: conduct sufficient to deprive reasonable person of self-control. Homicide: first/second degree murder, manslaughter, negligent homicide. Person includes unborn child at any stage of development.', offense_level: null, category: 'criminal', subcategory: 'Homicide' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 11, section: '1105', subsection: null, citation: 'ARS 13-1105', short_title: 'First Degree Murder', description: 'Intending or knowing that conduct will cause death, with premeditation, or during enumerated felonies', definition: 'Elements: (1) Intending or knowing; (2) causes death; (3) with premeditation; OR (4) during commission of specified felonies (felony murder). Class 1 felony: death or life imprisonment (with/without parole after 25 years). Only Arizona crime punishable by death.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 11, section: '1104', subsection: null, citation: 'ARS 13-1104', short_title: 'Second Degree Murder', description: 'Intentionally causing death without premeditation, or recklessly causing death under circumstances manifesting extreme indifference', definition: 'Elements: (1) Without premeditation; (2) intentionally causing death; OR (3) recklessly causing death under circumstances manifesting extreme indifference to human life. Class 1 felony: 10-25 years (no death penalty).', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 11, section: '1103', subsection: null, citation: 'ARS 13-1103', short_title: 'Manslaughter', description: 'Recklessly causing the death of another person, or committing second degree murder upon adequate provocation', definition: 'Elements: (1) Recklessly causes death; OR (2) commits second degree murder upon sudden quarrel/heat of passion from adequate provocation; OR (3) intentionally aids suicide; OR (4) causes death of unborn child by injury to mother. Class 2 felony: 3-12.5 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 11, section: '1102', subsection: null, citation: 'ARS 13-1102', short_title: 'Negligent Homicide', description: 'Causing the death of another person with criminal negligence', definition: 'Elements: (1) With criminal negligence; (2) causes the death of another person. Class 4 felony: 1-3.75 years. Common in vehicular death cases without DUI or extreme recklessness.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },

  // ── Chapter 12: Assault ────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 12, section: '1203', subsection: null, citation: 'ARS 13-1203', short_title: 'Assault', description: 'Intentionally, knowingly, or recklessly causing physical injury to another, or placing another in reasonable apprehension', definition: 'Elements: (1) Intentionally, knowingly, or recklessly causing any physical injury; (2) intentionally placing another in reasonable apprehension of imminent physical injury; (3) knowingly touching with intent to injure, insult, or provoke. Class 1 misdemeanor (injury), Class 2 misdemeanor (apprehension), Class 3 misdemeanor (touching).', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 12, section: '1204', subsection: null, citation: 'ARS 13-1204', short_title: 'Aggravated Assault', description: 'Assault causing serious physical injury, using a deadly weapon, on a peace officer, or other aggravating factors', definition: 'Aggravating factors: (1) Causes serious physical injury; (2) uses deadly weapon/dangerous instrument; (3) victim bound/restrained; (4) victim is under 15; (5) victim is peace officer, teacher, firefighter, EMT, health care worker, prosecutor, or judge while performing duties. Class 2-6 felony depending on factors.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 12, section: '1204', subsection: 'A8', citation: 'ARS 13-1204(A)(8)', short_title: 'Aggravated Assault on Peace Officer', description: 'Knowingly assaulting a peace officer engaged in official duties', definition: 'Elements: (1) Assault or aggravated assault; (2) person knows or has reason to know; (3) victim is a peace officer; (4) engaged in official duties. If physical injury: Class 5 felony. If serious injury or deadly weapon: Class 2 felony (dangerous offense).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },

  // ── Sexual Offenses ────────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 14, section: '1406', subsection: null, citation: 'ARS 13-1406', short_title: 'Sexual Assault', description: 'Intentionally or knowingly engaging in sexual intercourse or oral sexual contact without consent', definition: 'Elements: (1) Intentionally or knowingly; (2) engages in sexual intercourse or oral sexual contact; (3) with any person; (4) without consent. Class 2 felony: 5.25-14 years (presumptive 7 years). If victim under 12: life without parole eligibility for 35 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },

  // ── Kidnapping ─────────────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 13, section: '1304', subsection: null, citation: 'ARS 13-1304', short_title: 'Kidnapping', description: 'Knowingly restraining another person with intent to hold for ransom, use as hostage, facilitate crime, or inflict injury', definition: 'Elements: (1) Knowingly restrains another; (2) with intent to: hold for ransom/reward/benefit; use as shield/hostage; aid flight after crime; inflict physical injury/sexual offense; interfere with government; seize transportation. Class 2 felony: 4-10 years. If victim under 15 or ransom demand: class 2 dangerous.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },

  // ── Property Offenses ──────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 15, section: '1506', subsection: null, citation: 'ARS 13-1506', short_title: 'Burglary - Third Degree', description: 'Entering or remaining unlawfully in a non-residential structure with intent to commit theft or felony', definition: 'Elements: (1) Entering or remaining unlawfully; (2) in or on a non-residential structure or fenced commercial/residential yard; (3) with intent to commit any theft or felony. Class 4 felony: 1-3.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 15, section: '1507', subsection: null, citation: 'ARS 13-1507', short_title: 'Burglary - Second Degree', description: 'Entering or remaining unlawfully in a residential structure with intent to commit theft or felony', definition: 'Elements: (1) Entering or remaining unlawfully; (2) in a residential structure; (3) with intent to commit any theft or felony. Class 3 felony: 2-8.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 15, section: '1508', subsection: null, citation: 'ARS 13-1508', short_title: 'Burglary - First Degree', description: 'Committing second or third degree burglary while knowingly possessing a weapon, explosive, or dangerous instrument', definition: 'Elements: (1) Commits burglary 2nd or 3rd degree; (2) knowingly possesses explosives, deadly weapon, or dangerous instrument in course of burglary. Class 2 felony: 4-10 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 19, section: '1902', subsection: null, citation: 'ARS 13-1902', short_title: 'Robbery', description: 'Taking property from person or immediate presence of another against will by force, threat, or fear', definition: 'Elements: (1) Takes property; (2) from person or immediate presence; (3) of another; (4) against will; (5) by use or threatened use of force. Class 4 felony: 1-3.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 19, section: '1903', subsection: null, citation: 'ARS 13-1903', short_title: 'Aggravated Robbery', description: 'Robbery committed with aid of one or more accomplices', definition: 'Elements: (1) Commits robbery; (2) aided by one or more accomplices actually present. Class 3 felony: 2-8.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 19, section: '1904', subsection: null, citation: 'ARS 13-1904', short_title: 'Armed Robbery', description: 'Robbery committed while armed with a deadly weapon or simulated deadly weapon, or using force threatening death or serious injury', definition: 'Elements: (1) Commits robbery; (2) while armed with deadly weapon or simulated deadly weapon; OR (3) uses or threatens force that causes serious physical injury. Class 2 felony (dangerous): 7-21 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Robbery' },

  // Theft
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 18, section: '1802', subsection: null, citation: 'ARS 13-1802', short_title: 'Theft', description: 'Controlling property of another with intent to deprive, converting, obtaining by fraud, or diverting services', definition: 'Unified theft statute. Elements: (1) Without lawful authority; (2) knowingly controls, converts, obtains, or takes; (3) property or services of another; (4) with intent to deprive. Penalties by value: <$1,000 Class 1 misdemeanor; $1,000-$2,000 Class 6 felony; $2,000-$3,000 Class 5; $3,000-$4,000 Class 4; $4,000-$25,000 Class 3; $25,000+ Class 2.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 18, section: '1814', subsection: null, citation: 'ARS 13-1814', short_title: 'Theft of Means of Transportation', description: 'Controlling another persons means of transportation (vehicle) knowing it is stolen or intending to deprive', definition: 'Elements: (1) Knowingly controls; (2) means of transportation of another; (3) without lawful authority; (4) knowing or having reason to know it was stolen. Class 3 felony: 2-8.75 years. This is Arizonas motor vehicle theft statute.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 20, section: '2002', subsection: null, citation: 'ARS 13-2002', short_title: 'Forgery', description: 'Falsely making, completing, or altering a written instrument with intent to defraud', definition: 'Elements: (1) Falsely makes, completes, or alters; (2) a written instrument; (3) with intent to defraud. Class 4 felony: 1-3.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 20, section: '2008', subsection: null, citation: 'ARS 13-2008', short_title: 'Identity Theft', description: 'Knowingly taking, purchasing, manufacturing, or possessing personal identifying information of another with intent to obtain benefit', definition: 'Elements: (1) Knowingly; (2) takes, purchases, or possesses; (3) personal identifying information; (4) of another person; (5) without consent; (6) with intent to obtain or use to obtain benefit. Class 4 felony: 1-3.75 years. Aggravated (5+ victims): Class 2 felony.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },

  // Property Damage / Trespass
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 16, section: '1602', subsection: null, citation: 'ARS 13-1602', short_title: 'Criminal Damage', description: 'Recklessly defacing, damaging, or tampering with property of another', definition: 'Elements: (1) Recklessly; (2) defaces, damages, or tampers; (3) with property of another. $10,000+: Class 4 felony. $2,000-$10,000: Class 5. $250-$2,000: Class 6. <$250: Class 2 misdemeanor. Utilities/infrastructure: Class 6 minimum.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Property Damage' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 15, section: '1502', subsection: null, citation: 'ARS 13-1502', short_title: 'Criminal Trespass - Third Degree', description: 'Knowingly entering or remaining unlawfully on any real property', definition: 'Elements: (1) Knowingly; (2) entering or remaining unlawfully; (3) on any real property or fenced residential yard. Class 3 misdemeanor: up to 30 days and/or $500.', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Trespass' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 15, section: '1504', subsection: null, citation: 'ARS 13-1504', short_title: 'Criminal Trespass - First Degree', description: 'Knowingly entering or remaining unlawfully in a residential structure or fenced yard', definition: 'Elements: (1) Knowingly; (2) entering or remaining unlawfully; (3) in or on a residential structure or fenced residential yard. Class 6 felony: 4 months-2 years. If to commit a dangerous offense: Class 5.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Trespass' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 17, section: '1702', subsection: null, citation: 'ARS 13-1702', short_title: 'Arson - Occupied Structure', description: 'Knowingly and unlawfully damaging an occupied structure or property by fire or explosion', definition: 'Elements: (1) Knowingly and unlawfully; (2) damages; (3) an occupied structure; (4) by knowingly causing a fire or explosion. Class 2 felony: 4-10 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Arson' },

  // ── Domestic Violence (ARS 13-3601) ────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 36, section: '3601', subsection: null, citation: 'ARS 13-3601', short_title: 'Domestic Violence', description: 'Criminal offense committed against a family/household member — enhances underlying offense', definition: 'Domestic violence is a designation applied to underlying offenses (assault, criminal damage, disorderly conduct, etc.) when committed against spouse, ex-spouse, cohabitant, co-parent, child, or romantic partner. DV designation adds: mandatory arrest, prohibited firearm possession, enhanced sentences for repeat offenses. Third DV offense in 84 months: Class 5 felony.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 29, section: '2923', subsection: null, citation: 'ARS 13-2923', short_title: 'Stalking', description: 'Intentionally or knowingly engaging in a course of conduct directed at a specific person that would cause a reasonable person to fear for safety', definition: 'Elements: (1) Intentionally or knowingly; (2) engages in course of conduct (directed at another over period of time); (3) would cause reasonable person to fear death or physical injury to self/family member, OR fear property damage. Class 5 felony: 6 months-2.5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Weapons (ARS 13-31) ────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 31, section: '3102', subsection: null, citation: 'ARS 13-3102', short_title: 'Misconduct Involving Weapons', description: 'Carrying a concealed deadly weapon if under 21, carrying in prohibited places, or possessing as a prohibited possessor', definition: 'Arizona allows constitutional carry (21+ without permit). Prohibited: (1) Carrying concealed if under 21; (2) carrying in bars (with 12+ posted), polling places, schools, airports, prisons; (3) prohibited possessors (felons, DV, mentally incompetent). Class 6 felony generally. Prohibited possessor: Class 4 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 31, section: '3102', subsection: 'A5', citation: 'ARS 13-3102(A)(5)', short_title: 'Prohibited Possessor - Firearm', description: 'Possessing a firearm while classified as a prohibited possessor (convicted felon, domestic violence, etc.)', definition: 'Prohibited possessors: (1) Found to be a danger to self/others or has persistent/acute disability; (2) convicted of a felony; (3) on probation/parole for DV offense; (4) undocumented; (5) under order of protection with firearm prohibition. Class 4 felony: 1-3.75 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Weapons' },

  // ── Drug Offenses (ARS 13-34) ──────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 34, section: '3407', subsection: null, citation: 'ARS 13-3407', short_title: 'Possession of Dangerous Drug', description: 'Knowingly possessing or using a dangerous drug (meth, LSD, etc.) without prescription', definition: 'Elements: (1) Knowingly; (2) possesses or uses; (3) a dangerous drug (meth, ecstasy, LSD, mushrooms, etc.). Possession/use: Class 4 felony (1-3.75 yrs). Possession for sale: Class 2 (3-12.5 yrs). Manufacturing: Class 2. Prop 200 (1996) requires probation for first two drug possession convictions.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 34, section: '3405', subsection: null, citation: 'ARS 13-3405', short_title: 'Marijuana Offenses', description: 'Possession, use, sale, or transportation of marijuana', definition: 'Arizona legalized recreational marijuana (21+) in 2020 (Prop 207). Legal: up to 1 oz (5g concentrate). Exceeding legal amounts: Class 6 felony. Sale without license: Class 3-4 felony. Under 21: Class 1 misdemeanor.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 34, section: '3408', subsection: null, citation: 'ARS 13-3408', short_title: 'Possession of Narcotic Drug', description: 'Knowingly possessing or using a narcotic drug (heroin, cocaine, fentanyl, etc.)', definition: 'Elements: (1) Knowingly; (2) possesses, uses, administers, acquires, sells, manufactures, or transports; (3) a narcotic drug (heroin, cocaine, fentanyl, oxycodone). Possession/use: Class 4 felony. Possession for sale: Class 2. Transport for sale: Class 2.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 34, section: '3415', subsection: null, citation: 'ARS 13-3415', short_title: 'Drug Paraphernalia', description: 'Use or possession with intent to use drug paraphernalia', definition: 'Elements: (1) Uses or possesses with intent to use; (2) drug paraphernalia; (3) to use a drug. Paraphernalia does not include items for marijuana personal use (21+). Class 6 felony: 4 months-2 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Drugs' },

  // ── Public Order ───────────────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 29, section: '2904', subsection: null, citation: 'ARS 13-2904', short_title: 'Disorderly Conduct', description: 'Engaging in fighting, violent or seriously disruptive behavior, making unreasonable noise, or recklessly handling a weapon', definition: 'Elements: (1) Engages in fighting, violent, or seriously disruptive behavior; (2) makes unreasonable noise; (3) uses abusive language to any person present to provoke immediate retaliation; (4) makes protracted commotion to prevent transaction of business; (5) refuses to obey lawful order to disperse; (6) recklessly handles or displays a deadly weapon. Class 1 misdemeanor (6), otherwise Class 1 misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 24, section: '2404', subsection: null, citation: 'ARS 13-2404', short_title: 'Resisting Arrest', description: 'Intentionally preventing or attempting to prevent a peace officer from effecting an arrest', definition: 'Elements: (1) Intentionally prevents or attempts to prevent; (2) a person reasonably known to be a peace officer; (3) from effecting an arrest; (4) by using or threatening physical force. Class 6 felony: 4 months-2 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Public Order' },

  // ── Crimes Against Children ────────────────────────────────
  { state: 'AZ', state_name: 'Arizona', title: 13, chapter: 36, section: '3623', subsection: null, citation: 'ARS 13-3623', short_title: 'Child Abuse', description: 'Causing or permitting a child to suffer physical injury, abuse, or emotional or physical neglect', definition: 'Elements: (1) Under circumstances likely to produce death or serious physical injury; (2) causes or permits a child; (3) to suffer physical injury, abuse, or neglect. If likely death: Class 2 felony. If likely physical injury: Class 4. Emotional abuse: Class 6. Negligence-based: one class lower.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Crimes Against Children' },

  // ────────────────────────────────────────────────────────────
  // TITLE 28 — TRANSPORTATION
  // ────────────────────────────────────────────────────────────

  // DUI
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 4, section: '1381', subsection: null, citation: 'ARS 28-1381', short_title: 'DUI - Driving Under the Influence', description: 'Driving or being in actual physical control while impaired or with BAC of .08 or more', definition: 'Elements: (1) Drives or is in actual physical control; (2) of a vehicle; (3) while under the influence of intoxicating liquor, any drug, vapor, or combination to the slightest degree; OR (4) BAC 0.08% or more (0.04% commercial). Class 1 misdemeanor: minimum 1 day jail (first), 30 days (second within 84 months).', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 250 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 4, section: '1382', subsection: null, citation: 'ARS 28-1382', short_title: 'Extreme DUI', description: 'Driving with BAC of 0.15 or more (extreme DUI) or 0.20 or more (super extreme DUI)', definition: 'BAC 0.15-0.199 (Extreme DUI): Class 1 misdemeanor, minimum 30 days jail, $2,500+ fines, interlock. BAC 0.20+ (Super Extreme DUI): Class 1 misdemeanor, minimum 45 days jail, $3,250+ fines, interlock. Arizona has among the toughest DUI penalties in the nation.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 2500 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 4, section: '1383', subsection: null, citation: 'ARS 28-1383', short_title: 'Aggravated DUI (Felony)', description: 'DUI while license suspended, third DUI within 84 months, with child under 15, or refusing BAC with prior DUI', definition: 'Aggravated DUI: (1) While license suspended/revoked for DUI; (2) third or subsequent within 84 months; (3) wrong-way driver; (4) with ignition interlock requirement; (5) with child under 15 in vehicle. Class 4 felony: 4 months prison minimum (presumptive 2.5 years).', offense_level: 'second_degree_felony', category: 'vehicle', subcategory: 'DUI', citation_fine: 4000 },

  // Moving Violations
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 7, section: '701', subsection: null, citation: 'ARS 28-701', short_title: 'Speeding', description: 'Operating a vehicle in excess of reasonable speed or posted speed limits', definition: 'Speed limits: Residential 25 mph, Business 25 mph, Urban highway 65 mph, Rural highway 65 mph, Interstate 75 mph (or posted). Arizona uses reasonable and prudent standard AND absolute speed limits. Fines: $150-$250 base.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 200 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 7, section: '701.02', subsection: null, citation: 'ARS 28-701.02', short_title: 'Racing on Highways', description: 'Racing or drag racing on any highway', definition: 'Elements: (1) Drives a vehicle in a race; (2) on a highway; (3) in competition with another vehicle or against time. Class 1 misdemeanor: up to 6 months, $250-$1,000.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 500 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 6, section: '693', subsection: null, citation: 'ARS 28-693', short_title: 'Reckless Driving', description: 'Driving in reckless disregard for the safety of persons or property', definition: 'Elements: (1) Drives a vehicle; (2) in reckless disregard; (3) for safety of persons or property. Class 2 misdemeanor: up to 4 months and/or $750. Second within 24 months: Class 1 misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 250 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 6, section: '622.01', subsection: null, citation: 'ARS 28-622.01', short_title: 'Unlawful Flight from Law Enforcement', description: 'Willfully fleeing from a pursuing law enforcement vehicle', definition: 'Elements: (1) Willfully flees; (2) from a pursuing law enforcement vehicle; (3) after being given a signal to stop. Class 5 felony: 6 months-2.5 years.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 1000 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 6, section: '661', subsection: null, citation: 'ARS 28-661', short_title: 'Hit and Run - Property', description: 'Leaving the scene of an accident involving property damage without stopping and providing information', definition: 'Elements: (1) Involved in accident; (2) property damage; (3) fails to stop and exchange name/address/registration/license info. Class 2 misdemeanor or Class 3 misdemeanor depending on circumstances.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 250 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 6, section: '661', subsection: 'A', citation: 'ARS 28-661(A)', short_title: 'Hit and Run - Injury/Death', description: 'Leaving the scene of an accident involving injury or death', definition: 'Elements: (1) Involved in accident; (2) injury or death; (3) fails to stop, give information, and render aid. If injury: Class 5 felony (6 months-2.5 yrs). If death: Class 3 felony (2-8.75 yrs).', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 2000 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 6, section: '645', subsection: null, citation: 'ARS 28-645', short_title: 'Traffic Signal Violations', description: 'Failure to obey traffic signals and control devices', definition: 'Drivers must obey all official traffic-control signals. Steady circular red: stop. Right on red after stop unless prohibited. Steady yellow: caution, stop before intersection if safe.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 7, section: '773', subsection: null, citation: 'ARS 28-773', short_title: 'Stop Sign Violations', description: 'Failure to stop at a stop sign', definition: 'Driver must stop at the limit line, crosswalk, or entrance to the intersecting roadway.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 7, section: '730', subsection: null, citation: 'ARS 28-730', short_title: 'Following Too Closely', description: 'Following another vehicle more closely than is reasonable and prudent', definition: 'Driver shall not follow another vehicle more closely than is reasonable and prudent, considering speed, traffic, and road conditions.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 9, section: '914', subsection: null, citation: 'ARS 28-914', short_title: 'School Bus - Failure to Stop', description: 'Failing to stop for a school bus displaying alternating red lights and stop arm', definition: 'All traffic must stop when school bus displays alternating red lights. May not pass until bus resumes motion or stop arm withdrawn. Class 1 misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 500 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 9, section: '914.01', subsection: null, citation: 'ARS 28-914.01', short_title: 'Move Over Law', description: 'Failure to move over or slow down for emergency or roadside assistance vehicles', definition: 'When approaching stopped emergency vehicle with lights: must change to non-adjacent lane if safe, otherwise reduce speed to safe level. Extends to tow trucks and ADOT vehicles. Class 2 misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 250 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 9, section: '914.02', subsection: null, citation: 'ARS 28-914.02', short_title: 'Handheld Device While Driving', description: 'Using a handheld wireless device while operating a motor vehicle (hands-free law effective 2021)', definition: 'Elements: (1) Operates motor vehicle; (2) uses or holds a portable wireless communication device. Hands-free use allowed. First offense: warning or $75-$149. Second: $150-$250. Third+: $250+.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },

  // Registration / License / Insurance
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 21, section: '2153', subsection: null, citation: 'ARS 28-2153', short_title: 'Vehicle Registration Required', description: 'Every motor vehicle operated on Arizona highways must be registered with ADOT MVD', definition: 'All motor vehicles operated on public highways must be registered. Registration valid for 1 year (12 months). Emissions testing required in Maricopa and Pima counties.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 150 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 30, section: '3151', subsection: null, citation: 'ARS 28-3151', short_title: 'Drivers License Required', description: 'No person shall drive a motor vehicle on Arizona highways without a valid drivers license', definition: 'Must possess valid Arizona drivers license or valid license from another jurisdiction. Must carry license while driving. Arizona does not issue licenses to undocumented immigrants.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 200 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 30, section: '3473', subsection: null, citation: 'ARS 28-3473', short_title: 'Driving While Suspended/Revoked', description: 'Operating a motor vehicle while license is suspended or revoked', definition: 'Elements: (1) Drives motor vehicle; (2) while license suspended or revoked. Class 1 misdemeanor: up to 6 months and/or $2,500. If suspended for DUI: aggravated DUI (Class 4 felony).', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 500 },
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 40, section: '4135', subsection: null, citation: 'ARS 28-4135', short_title: 'Liability Insurance Required', description: 'Every motor vehicle registered in Arizona must maintain financial responsibility (liability insurance)', definition: 'Minimum coverage: $25,000 bodily injury per person, $50,000 per accident, $15,000 property damage. Proof of insurance must be provided at registration, traffic stops, and after accidents.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Insurance', citation_fine: 500 },

  // Equipment
  { state: 'AZ', state_name: 'Arizona', title: 28, chapter: 9, section: '909', subsection: null, citation: 'ARS 28-909', short_title: 'Seatbelt Violations', description: 'Failure to wear a seatbelt while operating or riding in a motor vehicle', definition: 'Driver and front seat passengers must wear seatbelts. Children under 5 or under 40 lbs must be in child restraint. 5-7: booster seat. 8-15: seatbelt required all positions. Secondary enforcement for adults. Fine: $10.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 10 },
];
