// ============================================================
// RMPG Flex — Colorado Revised Statutes (CRS)
// ============================================================
// Title 18: Criminal Code | Title 42: Vehicles & Traffic
// Offense levels mapped to Utah enum for UI compatibility:
//   CO Class 1 Felony → first_degree_felony
//   CO Class 2 Felony → first_degree_felony
//   CO Class 3 Felony → second_degree_felony
//   CO Class 4 Felony → third_degree_felony
//   CO Class 5 Felony → third_degree_felony
//   CO Class 6 Felony → third_degree_felony
//   CO Class 1 Misdemeanor → class_a_misdemeanor
//   CO Class 2 Misdemeanor → class_b_misdemeanor
//   CO Class 3 Misdemeanor → class_c_misdemeanor
//   CO Petty Offense → infraction
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const COLORADO_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // TITLE 18 — COLORADO CRIMINAL CODE
  // ────────────────────────────────────────────────────────────

  // ── Article 1: Provisions Applicable to Offenses Generally ──
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '101', subsection: null, citation: 'CRS 18-1-101', short_title: 'Short Title', description: 'This title shall be known as the Colorado Criminal Code', definition: 'The Colorado Criminal Code governs all criminal offenses in the State of Colorado. CRS Title 18 replaces the former criminal statutes.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '104', subsection: null, citation: 'CRS 18-1-104', short_title: 'Classes of Offenses', description: 'Classification of felonies (classes 1-6), misdemeanors (classes 1-3), petty offenses, and drug offenses', definition: 'Felonies: Class 1 (life/death) through Class 6 (1-1.5 yrs). Misdemeanors: Class 1 (6-18 months) through Class 3 (up to 6 months). Petty offenses: fine only, no jail.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '105', subsection: null, citation: 'CRS 18-1-105', short_title: 'Felony Sentencing', description: 'Presumptive sentencing ranges for felony offenses classes 1 through 6', definition: 'Class 1: Life or death. Class 2: 8-24 yrs. Class 3: 4-12 yrs. Class 4: 2-6 yrs. Class 5: 1-3 yrs. Class 6: 1-1.5 yrs. Extraordinary risk crimes add up to double.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '106', subsection: null, citation: 'CRS 18-1-106', short_title: 'Misdemeanor Sentencing', description: 'Sentencing ranges for misdemeanor offenses classes 1 through 3', definition: 'Class 1: 6-18 months jail, $500-$5,000 fine. Class 2: 3-12 months, $250-$1,000. Class 3: up to 6 months, $50-$750.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '401', subsection: null, citation: 'CRS 18-1-401', short_title: 'Culpable Mental States', description: 'Definitions of intentionally, knowingly, recklessly, and criminal negligence under Colorado law', definition: 'Intentionally: conscious objective to cause result. Knowingly: aware conduct is practically certain to cause result. Recklessly: conscious disregard of substantial risk. Criminal negligence: failure to perceive substantial risk.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '704', subsection: null, citation: 'CRS 18-1-704', short_title: 'Use of Physical Force - Defense of Person', description: 'Justification for using physical force in defense of self or others', definition: 'A person may use reasonable physical force upon another when the person reasonably believes it necessary to defend against imminent use of unlawful physical force. Deadly force justified only to prevent death or serious bodily injury.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '704.5', subsection: null, citation: 'CRS 18-1-704.5', short_title: 'Make My Day Law', description: 'Use of deadly force against an intruder in a dwelling (Castle Doctrine)', definition: 'Any occupant of a dwelling is justified in using any degree of physical force, including deadly force, against another person who has made an unlawful entry into the dwelling and when the occupant has a reasonable belief that the intruder has committed or intends to commit a crime and might use physical force against any occupant.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 1, section: '707', subsection: null, citation: 'CRS 18-1-707', short_title: 'Use of Force by Peace Officer', description: 'Authority for peace officers to use physical force in making arrests or preventing escapes', definition: 'A peace officer is justified in using reasonable and appropriate physical force upon another person when and to the extent the officer reasonably believes it necessary to effect an arrest, prevent escape, or defend against imminent threat.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },

  // ── Article 2: Inchoate Offenses ───────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 2, section: '101', subsection: null, citation: 'CRS 18-2-101', short_title: 'Criminal Attempt', description: 'Engaging in conduct constituting a substantial step toward commission of an offense', definition: 'Elements: (1) Acting with the kind of culpability otherwise required for commission of an offense; (2) engaging in conduct constituting a substantial step toward commission. Attempt to commit a class 1 felony is a class 2 felony.', offense_level: null, category: 'criminal', subcategory: 'Inchoate Offenses' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 2, section: '201', subsection: null, citation: 'CRS 18-2-201', short_title: 'Conspiracy', description: 'Agreeing with another person to commit an offense and performing an overt act in furtherance', definition: 'Elements: (1) Agreement with one or more persons that they or one of them will commit a crime; (2) an overt act in furtherance of the conspiracy. Conspiracy to commit class 1 felony is a class 2 felony.', offense_level: null, category: 'criminal', subcategory: 'Inchoate Offenses' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 2, section: '301', subsection: null, citation: 'CRS 18-2-301', short_title: 'Solicitation', description: 'Commanding, inducing, entreating, or otherwise attempting to persuade another person to commit a felony', definition: 'Elements: (1) Intent that another person commit a felony; (2) commands, induces, entreats, or otherwise attempts to persuade the other person. Same class as the underlying felony minus one degree.', offense_level: null, category: 'criminal', subcategory: 'Inchoate Offenses' },

  // ── Article 3: Offenses Against the Person ─────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '102', subsection: null, citation: 'CRS 18-3-102', short_title: 'Murder in the First Degree', description: 'After deliberation, intentionally causing the death of another person; or causing death during certain felonies', definition: 'Elements: (1) After deliberation and with intent to cause death; (2) causes the death of a person. Also includes felony murder during arson, robbery, kidnapping, sexual assault, burglary, or escape. Class 1 felony (life without parole or death).', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '103', subsection: null, citation: 'CRS 18-3-103', short_title: 'Murder in the Second Degree', description: 'Knowingly causing the death of another person', definition: 'Elements: (1) Knowingly causes the death of a person. Class 2 felony (8-24 years). Heat of passion reduces to class 3 felony manslaughter.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '104', subsection: null, citation: 'CRS 18-3-104', short_title: 'Manslaughter', description: 'Recklessly causing the death of another person, or intentionally causing death under heat of passion', definition: 'Elements: (1) Recklessly causing death of another; OR (2) intentionally but upon sudden heat of passion caused by a serious and highly provoking act of the victim. Class 4 felony (2-6 years).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '105', subsection: null, citation: 'CRS 18-3-105', short_title: 'Criminally Negligent Homicide', description: 'Causing death by criminal negligence', definition: 'Elements: (1) By conduct amounting to criminal negligence; (2) causes the death of a person. Class 5 felony (1-3 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '106', subsection: null, citation: 'CRS 18-3-106', short_title: 'Vehicular Homicide', description: 'Driving recklessly or under the influence and causing the death of another person', definition: 'Elements: (1) Operating a motor vehicle; (2) in a reckless manner or while under the influence; (3) proximate cause of death. DUI vehicular homicide: class 3 felony. Reckless: class 4 felony.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '202', subsection: null, citation: 'CRS 18-3-202', short_title: 'Assault in the First Degree', description: 'Intentionally causing serious bodily injury with a deadly weapon, or causing serious bodily injury with intent to disfigure/destroy a body part', definition: 'Elements: (1) With intent to cause serious bodily injury; (2) causes serious bodily injury by means of a deadly weapon. Class 3 felony (4-12 years). Extraordinary risk crime.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '203', subsection: null, citation: 'CRS 18-3-203', short_title: 'Assault in the Second Degree', description: 'Intentionally causing bodily injury with a deadly weapon, or recklessly causing serious bodily injury', definition: 'Elements: (1) Intentionally causing bodily injury with a deadly weapon; OR (2) recklessly causing serious bodily injury; OR (3) causing stupor/physical helplessness by administering a drug. Class 4 felony (2-6 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '204', subsection: null, citation: 'CRS 18-3-204', short_title: 'Assault in the Third Degree', description: 'Knowingly or recklessly causing bodily injury, or with criminal negligence causing bodily injury with a deadly weapon', definition: 'Elements: (1) Knowingly or recklessly causes bodily injury to another; OR (2) with criminal negligence causes bodily injury with a deadly weapon. Class 1 misdemeanor (6-18 months). Extraordinary risk crime.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '205', subsection: null, citation: 'CRS 18-3-205', short_title: 'Vehicular Assault', description: 'Operating a motor vehicle recklessly or under the influence causing serious bodily injury', definition: 'Elements: (1) Operating a vehicle; (2) recklessly or while DUI/DWAI; (3) proximate cause of serious bodily injury. DUI vehicular assault: class 4 felony. Reckless: class 5 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '206', subsection: null, citation: 'CRS 18-3-206', short_title: 'Menacing', description: 'Knowingly placing or attempting to place another person in fear of imminent serious bodily injury', definition: 'Elements: (1) Knowingly places or attempts to place another person in fear of imminent serious bodily injury. By use of a deadly weapon or any article used or fashioned in a manner to cause a person to believe it is a deadly weapon: class 5 felony. Otherwise: class 3 misdemeanor.', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '206(DW)', subsection: null, citation: 'CRS 18-3-206(DW)', short_title: 'Menacing with Deadly Weapon', description: 'Menacing another person by the use of a deadly weapon or article fashioned to resemble one', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '207', subsection: null, citation: 'CRS 18-3-207', short_title: 'Criminal Extortion', description: 'Making a substantial threat to another person and threatening to commit a criminal act in the future', definition: 'Elements: (1) Without legal authority; (2) makes a substantial threat; (3) thereby coerces another to do or refrain from doing something. Class 4 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '208', subsection: null, citation: 'CRS 18-3-208', short_title: 'Reckless Endangerment', description: 'Recklessly engaging in conduct which creates a substantial risk of serious bodily injury to another person', definition: 'Elements: (1) Recklessly engages in conduct; (2) creates a substantial risk of serious bodily injury to another. Class 3 misdemeanor.', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '301', subsection: null, citation: 'CRS 18-3-301', short_title: 'First Degree Kidnapping', description: 'Forcibly seizing and carrying a person from one place to another with intent to force them to do something', definition: 'Elements: (1) Knowingly seizes and carries any person from one place to another; (2) without consent and without lawful justification; (3) by use of force, threat, or deception. Class 1 felony if ransom/bodily injury. Class 2 felony otherwise.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '302', subsection: null, citation: 'CRS 18-3-302', short_title: 'Second Degree Kidnapping', description: 'Knowingly seizing and carrying a person without consent using force or threat', definition: 'Class 2 felony if victim is a child or held for ransom; otherwise class 4 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '303', subsection: null, citation: 'CRS 18-3-303', short_title: 'False Imprisonment', description: 'Knowingly confining or detaining another person without legal authority', definition: 'Elements: (1) Knowingly confines or detains another; (2) without consent; (3) without legal authority. Class 2 misdemeanor (3-12 months).', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '402', subsection: null, citation: 'CRS 18-3-402', short_title: 'Sexual Assault', description: 'Knowingly inflicting sexual intrusion or penetration on a victim without consent', definition: 'Elements: (1) Any actor who knowingly inflicts sexual intrusion or sexual penetration; (2) on a victim; (3) when the victim does not consent, or is incapable of consent. Class 3 felony (4-12 years). Class 2 felony if weapon used or victim seriously injured.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '404', subsection: null, citation: 'CRS 18-3-404', short_title: 'Unlawful Sexual Contact', description: 'Knowingly subjecting a victim to sexual contact without consent', definition: 'Elements: (1) Any actor who knowingly subjects a victim to any sexual contact; (2) without consent or when victim is incapable of consent. Class 1 misdemeanor. Class 4 felony if actor is in position of trust.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '405', subsection: null, citation: 'CRS 18-3-405', short_title: 'Sexual Assault on a Child', description: 'Sexual contact with a child by one in a position of trust or when child is under 15', definition: 'Elements: (1) Actor subjects another not the actor\'s spouse to sexual contact; (2) victim is less than 15 years of age. Class 4 felony. Position of trust: class 3 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '602', subsection: null, citation: 'CRS 18-3-602', short_title: 'Stalking', description: 'Repeatedly following, approaching, contacting, or surveilling another person causing reasonable fear', definition: 'Elements: (1) Directly or indirectly through a third party; (2) repeatedly follows, approaches, contacts, places under surveillance, or makes credible threat; (3) in a manner that would cause a reasonable person to suffer serious emotional distress. Class 5 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 3, section: '602(DV)', subsection: null, citation: 'CRS 18-3-602(DV)', short_title: 'Stalking - Domestic Violence', description: 'Stalking involving an intimate partner or household member', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Person' },

  // ── Article 4: Offenses Against Property ───────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '101', subsection: null, citation: 'CRS 18-4-101', short_title: 'Arson - First Degree', description: 'Knowingly setting fire to, burning, or causing to be burned any building or occupied structure', definition: 'Elements: (1) Knowingly sets fire to, burns, or causes to be burned; (2) any building or occupied structure. Class 3 felony (4-12 years).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '102', subsection: null, citation: 'CRS 18-4-102', short_title: 'Arson - Second Degree', description: 'Knowingly setting fire to property of another without consent', definition: 'Class 4 felony (2-6 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '103', subsection: null, citation: 'CRS 18-4-103', short_title: 'Arson - Third Degree', description: 'Recklessly starting a fire or causing an explosion that damages property of another', definition: 'Class 4 felony if >$100 damage. Otherwise class 2 misdemeanor.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '202', subsection: null, citation: 'CRS 18-4-202', short_title: 'First Degree Burglary', description: 'Knowingly breaking into or entering an occupied building with intent to commit a crime and assaulting or menacing a person therein', definition: 'Elements: (1) Knowingly breaks an entrance into, enters, or remains unlawfully; (2) in a building or occupied structure; (3) with intent to commit therein a crime; (4) assaults or menaces any person therein. Class 3 felony.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '203', subsection: null, citation: 'CRS 18-4-203', short_title: 'Second Degree Burglary', description: 'Knowingly breaking into or entering a building or occupied structure with intent to commit a crime therein', definition: 'Elements: (1) Knowingly breaks an entrance into, enters, or remains unlawfully; (2) in a building or occupied structure; (3) with intent to commit a crime therein. Class 4 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '204', subsection: null, citation: 'CRS 18-4-204', short_title: 'Third Degree Burglary', description: 'Breaking into a vault, safe, cash register, or coin machine', definition: 'Class 5 felony (1-3 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '301', subsection: null, citation: 'CRS 18-4-301', short_title: 'Robbery', description: 'Knowingly taking anything of value from the person or presence of another by use of force, threats, or intimidation', definition: 'Elements: (1) Knowingly takes anything of value; (2) from the person or presence of another; (3) by the use of force, threats, or intimidation. Class 4 felony (2-6 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '302', subsection: null, citation: 'CRS 18-4-302', short_title: 'Aggravated Robbery', description: 'Robbery during which the actor is armed with a deadly weapon or causes bodily injury', definition: 'Elements: Robbery where the actor (1) is armed with a deadly weapon; (2) uses or threatens use of deadly weapon; or (3) causes bodily injury. Class 3 felony (4-12 years). Extraordinary risk crime.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '401', subsection: null, citation: 'CRS 18-4-401', short_title: 'Theft', description: 'Knowingly obtaining, retaining, or exercising control over anything of value of another without authorization', definition: 'Elements: (1) Knowingly obtains, retains, or exercises control over; (2) anything of value; (3) of another person; (4) without authorization or by threat or deception; (5) with intent to permanently deprive. Classification by value: <$300 petty offense; $300-$749 class 2 misd; $750-$1,999 class 1 misd; $2,000-$4,999 class 6 felony; $5,000-$19,999 class 5 felony; $20,000-$99,999 class 4 felony; $100,000-$999,999 class 3 felony; $1M+ class 2 felony.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '401(F4)', subsection: null, citation: 'CRS 18-4-401(F4)', short_title: 'Theft - $2,000 to $4,999', description: 'Theft of property or services valued between $2,000 and $4,999', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '401(F3)', subsection: null, citation: 'CRS 18-4-401(F3)', short_title: 'Theft - $5,000 to $19,999', description: 'Theft of property or services valued between $5,000 and $19,999', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '401(F2)', subsection: null, citation: 'CRS 18-4-401(F2)', short_title: 'Theft - $20,000 to $99,999', description: 'Theft of property or services valued between $20,000 and $99,999', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '402', subsection: null, citation: 'CRS 18-4-402', short_title: 'Theft by Receiving', description: 'Receiving, retaining, or disposing of stolen property knowing or believing it was stolen', definition: 'Elements: (1) Receives, retains, loans money by pawn, or otherwise disposes of; (2) anything of value; (3) of another; (4) knowing or believing the thing to have been stolen. Same classification as theft by value.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '405', subsection: null, citation: 'CRS 18-4-405', short_title: 'Theft of Rental Property', description: 'Failure to return rented or leased personal property including motor vehicles within 72 hours of demand or agreement expiration', definition: 'Elements: (1) Obtains property by rental or lease agreement; (2) knowingly fails to reveal material information or presents false information; (3) fails to return within 72 hours after written demand or expiration. Classification follows standard theft value thresholds.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '409', subsection: null, citation: 'CRS 18-4-409', short_title: 'Theft of Trade Secrets', description: 'Stealing, copying, or using trade secrets without authorization', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '410', subsection: null, citation: 'CRS 18-4-410', short_title: 'Motor Vehicle Theft', description: 'Knowingly obtaining or exercising control over a motor vehicle of another without authorization', definition: 'Elements: (1) Knowingly obtains or exercises control over; (2) the motor vehicle of another; (3) without authorization. Class 5 felony if value <$20,000. Class 4 felony if value $20,000+. Aggravated motor vehicle theft (Class 4 felony) if defendant used deception, took from custody, altered VIN, or had two prior convictions.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '410(AGG)', subsection: null, citation: 'CRS 18-4-410(AGG)', short_title: 'Aggravated Motor Vehicle Theft', description: 'Motor vehicle theft with aggravating factors (used deception, altered VIN, prior convictions)', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '501', subsection: null, citation: 'CRS 18-4-501', short_title: 'Criminal Mischief', description: 'Knowingly damaging the real or personal property of another', definition: 'Elements: (1) Knowingly damages; (2) the real or personal property of one or more other persons. <$300: class 3 misdemeanor. $300-$749: class 2 misdemeanor. $750-$999: class 1 misdemeanor. $1,000-$4,999: class 6 felony. $5,000+: class 5 felony.', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '502', subsection: null, citation: 'CRS 18-4-502', short_title: 'Criminal Tampering', description: 'Tampering with property so as to endanger person or property', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '503', subsection: null, citation: 'CRS 18-4-503', short_title: 'First Degree Criminal Trespass', description: 'Knowingly entering or remaining unlawfully in a dwelling of another', definition: 'Elements: (1) Knowingly and unlawfully enters or remains; (2) in the dwelling of another. Class 5 felony (1-3 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '504', subsection: null, citation: 'CRS 18-4-504', short_title: 'Second Degree Criminal Trespass', description: 'Unlawfully entering or remaining in a building or occupied structure that is enclosed', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Property' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 4, section: '505', subsection: null, citation: 'CRS 18-4-505', short_title: 'Third Degree Criminal Trespass', description: 'Unlawfully entering or remaining on the property of another', offense_level: 'infraction', category: 'criminal', subcategory: 'Offenses Against Property' },

  // ── Article 5: Fraud & Forgery ─────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '102', subsection: null, citation: 'CRS 18-5-102', short_title: 'Forgery', description: 'Falsely making, completing, or altering a written instrument with intent to defraud', definition: 'Elements: (1) With intent to defraud; (2) falsely makes, completes, alters, or utters; (3) a written instrument. Class 5 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '103', subsection: null, citation: 'CRS 18-5-103', short_title: 'Second Degree Forgery', description: 'Possessing or uttering a forged instrument knowing it to be forged', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Fraud' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '113', subsection: null, citation: 'CRS 18-5-113', short_title: 'Identity Theft', description: 'Knowingly using personal identifying information of another to obtain credit, property, services, or benefits', definition: 'Elements: (1) Knowingly uses; (2) the personal identifying information, financial identifying information, or financial device; (3) of another person; (4) without permission or lawful authority; (5) with intent to obtain anything of value or to commit or facilitate any unlawful act. Class 4 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '205', subsection: null, citation: 'CRS 18-5-205', short_title: 'Offering a False Instrument for Recording', description: 'Knowingly offering a false instrument to be filed or recorded in a public office', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '301', subsection: null, citation: 'CRS 18-5-301', short_title: 'Issuing a Bad Check', description: 'Issuing a check knowing there are insufficient funds', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Fraud' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 5, section: '401', subsection: null, citation: 'CRS 18-5-401', short_title: 'Criminal Impersonation', description: 'Assuming a false identity with intent to gain a benefit or injure another', definition: 'Elements: (1) Knowingly assumes a false or fictitious identity or capacity; (2) with intent to unlawfully gain a benefit or injure or defraud another. Class 6 felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },

  // ── Article 6: Offenses Involving the Family ───────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 6, section: '401', subsection: null, citation: 'CRS 18-6-401', short_title: 'Child Abuse', description: 'Causing injury to or placing a child in a situation that poses a threat of injury', definition: 'Elements: (1) A person; (2) causes an injury to a child\'s life or health; (3) or permits a child to be unreasonably placed in a situation posing a threat of injury. Class 2 felony if death results. Class 3 felony if serious bodily injury.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Family' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 6, section: '403', subsection: null, citation: 'CRS 18-6-403', short_title: 'Wrongs to Children', description: 'Selling, lending, or giving to a child any intoxicating liquor, malt beverages, or controlled substance', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Family' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 6, section: '800.3', subsection: null, citation: 'CRS 18-6-800.3', short_title: 'Domestic Violence Definition', description: 'Act or threatened act of violence upon a person with whom the actor is or has been in an intimate relationship, or crime against person or property used to coerce/intimidate intimate partner', definition: 'Domestic violence is used as a sentence enhancer. It means an act or threatened act of violence upon a person with whom the actor is or has been involved in an intimate relationship. Includes crimes against property or animals used to coerce, control, punish, intimidate, or take revenge against an intimate partner.', offense_level: 'enhancement', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 6, section: '801', subsection: null, citation: 'CRS 18-6-801', short_title: 'Violation of Protection Order', description: 'Knowingly violating a restraining or protection order', definition: 'Elements: (1) Knowingly violates; (2) a protection order. Class 1 misdemeanor. Class 5 felony for third or subsequent conviction.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 6, section: '803', subsection: null, citation: 'CRS 18-6-803', short_title: 'Harassment - DV', description: 'Harassment involving an intimate relationship partner', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Article 7: Weapons Offenses ────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '102', subsection: null, citation: 'CRS 18-12-102', short_title: 'Possessing a Dangerous Weapon - Felon', description: 'Possession of a weapon by a previous offender (felon in possession)', definition: 'A person who has been convicted of a felony and possesses, uses, or carries a firearm. Class 6 felony. Class 5 felony for violent crime conviction.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '105', subsection: null, citation: 'CRS 18-12-105', short_title: 'Unlawfully Carrying a Concealed Weapon', description: 'Carrying a concealed handgun without a valid permit', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Weapons' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '106', subsection: null, citation: 'CRS 18-12-106', short_title: 'Prohibited Use of Weapons', description: 'Recklessly or illegally discharging, aiming, or displaying a firearm', definition: 'Recklessly discharging a firearm or aimed at another, or knowingly setting a trap with a firearm. Class 5 felony for aimed/trap. Class 2 misdemeanor for reckless discharge.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Weapons' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '108', subsection: null, citation: 'CRS 18-12-108', short_title: 'Possession of Weapons on School Grounds', description: 'Knowingly carrying, bringing, or having a firearm or deadly weapon on school grounds', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '108.5', subsection: null, citation: 'CRS 18-12-108.5', short_title: 'Unlawfully Providing Firearm to Minor', description: 'Providing, selling, or giving a handgun to a person under 18', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Weapons' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 12, section: '111', subsection: null, citation: 'CRS 18-12-111', short_title: 'Illegal Discharge of Firearm', description: 'Recklessly or negligently discharging a firearm within city limits or into a building', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Weapons' },

  // ── Article 8: Offenses Against Public Administration ──────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '102', subsection: null, citation: 'CRS 18-8-102', short_title: 'Obstructing a Peace Officer', description: 'Knowingly obstructing, impairing, or hindering a peace officer in the performance of duties', definition: 'Elements: (1) By using or threatening to use violence, force, physical interference, or obstacle; (2) knowingly obstructs, impairs, or hinders; (3) the enforcement of the penal law or the preservation of the peace by a peace officer. Class 2 misdemeanor. Class 1 misdemeanor if by physical interference.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '103', subsection: null, citation: 'CRS 18-8-103', short_title: 'Resisting Arrest', description: 'Knowingly preventing or attempting to prevent a peace officer from effecting an arrest by using physical force', definition: 'Elements: (1) Knowingly prevents or attempts to prevent; (2) a peace officer from effecting an arrest; (3) by the use of physical force or any other means creating a substantial risk of causing bodily injury. Class 2 misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '104', subsection: null, citation: 'CRS 18-8-104', short_title: 'Assault on Peace Officer/Firefighter', description: 'Assaulting a peace officer or firefighter while performing official duties', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '104.5', subsection: null, citation: 'CRS 18-8-104.5', short_title: 'Disarming a Peace Officer', description: 'Taking or attempting to take a firearm from a peace officer during official duties', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '105', subsection: null, citation: 'CRS 18-8-105', short_title: 'Escape', description: 'Departing or failing to return to lawful custody', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '111', subsection: null, citation: 'CRS 18-8-111', short_title: 'Perjury', description: 'Making a materially false statement under oath or affirmation', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '208', subsection: null, citation: 'CRS 18-8-208', short_title: 'Making a False Report', description: 'Knowingly making a false report to law enforcement authorities', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '209', subsection: null, citation: 'CRS 18-8-209', short_title: 'Impersonating a Peace Officer', description: 'Falsely pretending to be a peace officer or other public servant', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '212', subsection: null, citation: 'CRS 18-8-212', short_title: 'Tampering with Evidence', description: 'Knowingly destroying, mutilating, concealing, or altering physical evidence', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Offenses Against Public Order' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 8, section: '306', subsection: null, citation: 'CRS 18-8-306', short_title: 'Failure to Appear', description: 'Failing to appear before a court as required after release on bail or personal recognizance', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Order' },

  // ── Article 9: Public Order/Decency ────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '106', subsection: null, citation: 'CRS 18-9-106', short_title: 'Disorderly Conduct', description: 'Making coarse or offensive utterances, gestures, or displays in a public place, or making unreasonable noise', definition: 'Elements: (1) In a public place; (2) makes a coarse and obviously offensive utterance, gesture, or display; OR makes unreasonable noise; OR fights with another. Class 1 petty offense.', offense_level: 'infraction', category: 'criminal', subcategory: 'Offenses Against Public Safety' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '106.5', subsection: null, citation: 'CRS 18-9-106.5', short_title: 'Harassment', description: 'With intent to harass, annoy, or alarm another person, striking, shoving, or subjecting to physical contact', definition: 'Elements: (1) With intent to harass, annoy, or alarm; (2) strikes, shoves, kicks, or subjects to physical contact; OR follows in public places; OR makes obscene gesture/communication; OR initiates communication with intent to harass. Class 3 misdemeanor. Class 1 misdemeanor if based on bias.', offense_level: 'class_c_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Safety' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '107', subsection: null, citation: 'CRS 18-9-107', short_title: 'Criminal Trespass - Premises/Land', description: 'Entering or remaining upon premises or real property of another when a no-trespass order exists', offense_level: 'infraction', category: 'criminal', subcategory: 'Offenses Against Public Safety' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '108', subsection: null, citation: 'CRS 18-9-108', short_title: 'Prohibition on Camping', description: 'Unauthorized camping on public or private property in violation of local ordinance', offense_level: 'infraction', category: 'criminal', subcategory: 'Offenses Against Public Safety' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '111', subsection: null, citation: 'CRS 18-9-111', short_title: 'Cruelty to Animals', description: 'Knowingly or recklessly overdriving, overloading, mistreating, or neglecting an animal', definition: 'Class 1 misdemeanor. Aggravated cruelty (knowingly torturing, needlessly mutilating, or killing): Class 6 felony.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Safety' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 9, section: '202', subsection: null, citation: 'CRS 18-9-202', short_title: 'Riot', description: 'Three or more persons acting together without authority of law engaging in tumultuous and violent conduct', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Public Safety' },

  // ── Article 13: Bias-Motivated Crimes ──────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 13, section: '105', subsection: null, citation: 'CRS 18-13-105', short_title: 'Contributing to Delinquency of Minor', description: 'Inducing, aiding, or encouraging a child to violate any law or be truant', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Offenses Against Family' },

  // ── Article 18: Drug Offenses ──────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '403.5', subsection: null, citation: 'CRS 18-18-403.5', short_title: 'Unlawful Use of Controlled Substance', description: 'Using a controlled substance other than as authorized by law', definition: 'Level 2 drug misdemeanor. Fine: $50-$750. Can include substance abuse assessment and treatment.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '404', subsection: null, citation: 'CRS 18-18-404', short_title: 'Unlawful Possession of Controlled Substance', description: 'Possession of any schedule I-V controlled substance without valid prescription', definition: 'Schedule I/II possession (>4 grams): Level 4 drug felony (6-12 months). Schedule I/II (4g or less): Level 1 drug misdemeanor. Schedule III/IV: Level 1 drug misdemeanor. Schedule V: Level 2 drug misdemeanor. Marijuana >2 oz: Level 1 drug misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '405', subsection: null, citation: 'CRS 18-18-405', short_title: 'Manufacturing/Dispensing/Distributing', description: 'Unlawfully manufacturing, dispensing, selling, or distributing a controlled substance', definition: 'Schedule I/II: Level 2 drug felony (4-8 yrs). Schedule III/IV: Level 3 drug felony (2-4 yrs). Schedule V: Level 4 drug felony (6-12 months). Marijuana >2.5 lbs: Level 3 drug felony. Sale to minor: Level 1 drug felony (8-32 yrs).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '406', subsection: null, citation: 'CRS 18-18-406', short_title: 'Possession with Intent to Distribute', description: 'Possession of a controlled substance with intent to manufacture, distribute, or dispense', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '407', subsection: null, citation: 'CRS 18-18-407', short_title: 'Special Offender - Drug Sales', description: 'Enhanced penalties for drug offenses committed by special offenders (near schools, using minors)', offense_level: 'enhancement', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '412', subsection: null, citation: 'CRS 18-18-412', short_title: 'Possession of Drug Paraphernalia', description: 'Possession of drug paraphernalia used for manufacturing, processing, or using controlled substances', offense_level: 'infraction', category: 'criminal', subcategory: 'Controlled Substances' },
  { state: 'CO', state_name: 'Colorado', title: 18, chapter: 18, section: '430.5', subsection: null, citation: 'CRS 18-18-430.5', short_title: 'Fentanyl Distribution Causing Death', description: 'Distribution of fentanyl or carfentanil resulting in death of the user', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Controlled Substances' },

  // ────────────────────────────────────────────────────────────
  // TITLE 42 — COLORADO VEHICLE & TRAFFIC CODE
  // ────────────────────────────────────────────────────────────

  // ── DUI/DWAI ──────────────────────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1301', subsection: null, citation: 'CRS 42-4-1301', short_title: 'DUI / DWAI', description: 'Driving under the influence of alcohol (BAC .08+) or drugs, or driving while ability impaired (BAC .05-.079)', definition: 'DUI (BAC .08+): Class 1 traffic misdemeanor (5 days-1 year jail, $600-$1,000 fine). DWAI (BAC .05-.079): Class 2 traffic misdemeanor (up to 180 days, $200-$500 fine). Third offense DUI: Class 4 felony. DUI per se: BAC .08+.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1301(AGG)', subsection: null, citation: 'CRS 42-4-1301(AGG)', short_title: 'Aggravated DUI', description: 'DUI with BAC of .15 or higher, or DUI causing serious bodily injury', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1301(F)', subsection: null, citation: 'CRS 42-4-1301(F)', short_title: 'DUI - Felony (4th+ Offense)', description: 'Fourth or subsequent DUI or DWAI conviction', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'DUI' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1301.1', subsection: null, citation: 'CRS 42-4-1301.1', short_title: 'Express Consent / Implied Consent', description: 'Operating a motor vehicle constitutes expressed consent to chemical testing', offense_level: null, category: 'vehicle', subcategory: 'DUI' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1302', subsection: null, citation: 'CRS 42-4-1302', short_title: 'Open Container in Vehicle', description: 'Possessing an open container of alcohol in the passenger area of a motor vehicle', offense_level: 'infraction', category: 'vehicle', subcategory: 'DUI', citation_fine: 50 },

  // ── Speeding & Moving Violations ──────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1101', subsection: null, citation: 'CRS 42-4-1101', short_title: 'Speeding', description: 'Operating a vehicle at a speed greater than the posted maximum speed limit', definition: '1-4 mph over: $30 fine (non-points). 5-9 over: $70/1 point. 10-19 over: $135/4 points. 20-24 over: $200/6 points. 25-39 over: $300/6 points + mandatory appearance. 40+ over: $500/12 points + mandatory.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Speeding', citation_fine: 135 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1101(25+)', subsection: null, citation: 'CRS 42-4-1101(25+)', short_title: 'Speeding - 25+ Over', description: 'Exceeding speed limit by 25 mph or more (mandatory court appearance)', offense_level: 'class_c_misdemeanor', category: 'vehicle', subcategory: 'Speeding', citation_fine: 300 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1102', subsection: null, citation: 'CRS 42-4-1102', short_title: 'Speed Contests / Racing', description: 'Engaging in a speed contest or exhibition of speed on a public highway', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 300 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1401', subsection: null, citation: 'CRS 42-4-1401', short_title: 'Reckless Driving', description: 'Driving a motor vehicle in willful or wanton disregard for the safety of persons or property', definition: 'Class 2 traffic misdemeanor. 8 points. Up to 90 days jail, $150-$300 fine. License suspension for 30 days.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 300 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1402', subsection: null, citation: 'CRS 42-4-1402', short_title: 'Careless Driving', description: 'Driving without due regard for the width, grade, curves, corners, and traffic conditions of highways', definition: 'Class 2 traffic misdemeanor. 4 points. Up to 90 days jail, $150-$300 fine.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1402(DI)', subsection: null, citation: 'CRS 42-4-1402(DI)', short_title: 'Careless Driving Causing Death/Injury', description: 'Careless driving that is the proximate cause of death or bodily injury', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1403', subsection: null, citation: 'CRS 42-4-1403', short_title: 'Eluding a Police Officer', description: 'Willfully fleeing or attempting to elude a peace officer after being given a visual or audible signal to stop', definition: 'Class 5 felony (1-3 years). If reckless driving during evasion or bodily injury results: Class 4 felony. If death results: Class 3 felony.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Moving Violations' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1601', subsection: null, citation: 'CRS 42-4-1601', short_title: 'Hit and Run - Property Damage', description: 'Leaving the scene of an accident involving damage to property without providing required information', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Accident Reporting', citation_fine: 100 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1601(BI)', subsection: null, citation: 'CRS 42-4-1601(BI)', short_title: 'Hit and Run - Bodily Injury', description: 'Leaving the scene of an accident involving bodily injury without providing aid and information', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Accident Reporting' },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1601(D)', subsection: null, citation: 'CRS 42-4-1601(D)', short_title: 'Hit and Run - Death', description: 'Leaving the scene of an accident involving death', offense_level: 'second_degree_felony', category: 'vehicle', subcategory: 'Accident Reporting' },

  // ── Right of Way & Signals ────────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '603', subsection: null, citation: 'CRS 42-4-603', short_title: 'Failure to Obey Traffic Signal', description: 'Proceeding through a red traffic signal or failing to obey a traffic control device', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '701', subsection: null, citation: 'CRS 42-4-701', short_title: 'Failure to Yield Right of Way', description: 'Failure to yield the right of way at an intersection or when required by sign or signal', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '706', subsection: null, citation: 'CRS 42-4-706', short_title: 'Failure to Yield to Emergency Vehicle', description: 'Failure to yield to an authorized emergency vehicle using lights and/or sirens', offense_level: 'class_c_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '705', subsection: null, citation: 'CRS 42-4-705', short_title: 'Failure to Yield to Pedestrian', description: 'Failure to yield right of way to a pedestrian in a crosswalk', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '714', subsection: null, citation: 'CRS 42-4-714', short_title: 'Failure to Stop for School Bus', description: 'Passing a school bus when red lights are flashing and stop arm is extended', offense_level: 'class_c_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 300 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '713', subsection: null, citation: 'CRS 42-4-713', short_title: 'Move Over Law', description: 'Failure to move over or slow down for stationary emergency, maintenance, or tow vehicles', offense_level: 'class_c_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1003', subsection: null, citation: 'CRS 42-4-1003', short_title: 'Following Too Closely', description: 'Following another vehicle more closely than is reasonable and prudent', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1012', subsection: null, citation: 'CRS 42-4-1012', short_title: 'Texting While Driving', description: 'Using a wireless telephone for texting, emailing, or internet while operating a vehicle', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1013', subsection: null, citation: 'CRS 42-4-1013', short_title: 'Handheld Phone Use While Driving', description: 'Using a handheld wireless communication device while operating a motor vehicle', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },

  // ── License, Registration, Insurance ──────────────────────
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 2, section: '101', subsection: null, citation: 'CRS 42-2-101', short_title: 'Driver License Required', description: 'Operating a motor vehicle on any highway without a valid driver license', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License Violations', citation_fine: 100 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 2, section: '138', subsection: null, citation: 'CRS 42-2-138', short_title: 'Driving Under Restraint/Revocation', description: 'Operating a motor vehicle while license is under restraint, suspension, or revocation', definition: 'Class 1 traffic misdemeanor if DUI-related. Class 2 traffic misdemeanor otherwise. May carry up to 12 months jail for habitual offenders.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License Violations', citation_fine: 200 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 3, section: '105', subsection: null, citation: 'CRS 42-3-105', short_title: 'Registration Required', description: 'Operating a motor vehicle on any highway without current valid registration', offense_level: 'class_c_misdemeanor', category: 'vehicle', subcategory: 'Registration', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 3, section: '116', subsection: null, citation: 'CRS 42-3-116', short_title: 'Expired Registration', description: 'Operating a vehicle with expired registration', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 3, section: '202', subsection: null, citation: 'CRS 42-3-202', short_title: 'Display of License Plates', description: 'Failure to properly display license plates on front and rear of vehicle', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 65 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1409', subsection: null, citation: 'CRS 42-4-1409', short_title: 'Compulsory Insurance', description: 'Operating a motor vehicle without the required minimum insurance coverage', definition: 'Minimum liability: $25,000/$50,000 bodily injury, $15,000 property damage. Class 1 traffic misdemeanor. Fine $500+ and license suspension.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Insurance', citation_fine: 500 },

  // ── Vehicle Equipment ─────────────────────────────────────
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '204', subsection: null, citation: 'CRS 42-4-204', short_title: 'Window Tint Violation', description: 'Vehicle window tinting darker than legally permitted (27% VLT front windows)', offense_level: 'infraction', category: 'vehicle', subcategory: 'Vehicle Equipment', citation_fine: 50 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '227', subsection: null, citation: 'CRS 42-4-227', short_title: 'Seatbelt Violation', description: 'Failure to wear a seatbelt or properly restrain a child passenger', offense_level: 'infraction', category: 'vehicle', subcategory: 'Safety', citation_fine: 65 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '236', subsection: null, citation: 'CRS 42-4-236', short_title: 'Child Restraint Violation', description: 'Failure to properly restrain a child under 8 in a child safety seat', offense_level: 'infraction', category: 'vehicle', subcategory: 'Safety', citation_fine: 65 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '201', subsection: null, citation: 'CRS 42-4-201', short_title: 'Defective Vehicle Equipment', description: 'Operating a vehicle with defective or non-functioning required equipment (headlights, brakes, etc.)', offense_level: 'infraction', category: 'vehicle', subcategory: 'Vehicle Equipment', citation_fine: 50 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '215', subsection: null, citation: 'CRS 42-4-215', short_title: 'Emissions Inspection Required', description: 'Operating a vehicle in Denver metro area without passing required emissions test', offense_level: 'infraction', category: 'vehicle', subcategory: 'Vehicle Equipment', citation_fine: 50 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1406', subsection: null, citation: 'CRS 42-4-1406', short_title: 'Parking Violation', description: 'Parking in violation of posted signs, fire lane, or handicapped space restrictions', offense_level: 'infraction', category: 'vehicle', subcategory: 'Parking', citation_fine: 50 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1208', subsection: null, citation: 'CRS 42-4-1208', short_title: 'Lane Change Violation', description: 'Changing lanes without signaling or when unsafe to do so', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'CO', state_name: 'Colorado', title: 42, chapter: 4, section: '1209', subsection: null, citation: 'CRS 42-4-1209', short_title: 'Passing on Right / Improper Passing', description: 'Passing another vehicle on the right when not permitted or passing in a no-passing zone', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },

  // ── Colorado DOC / Corrections References ─────────────────
  { state: 'CO', state_name: 'Colorado', title: 17, chapter: 1, section: '101', subsection: null, citation: 'CRS 17-1-101', short_title: 'Department of Corrections - Purpose', description: 'Creation and purpose of the Colorado Department of Corrections (CDOC)', definition: 'The Department of Corrections is established in the executive branch of state government. It has authority over all state penal and correctional institutions. CDOC manages approximately 20 facilities housing state inmates.', offense_level: null, category: 'criminal', subcategory: 'Corrections' },
  { state: 'CO', state_name: 'Colorado', title: 17, chapter: 2, section: '201', subsection: null, citation: 'CRS 17-2-201', short_title: 'Parole Board', description: 'Colorado State Board of Parole and parole eligibility criteria', definition: 'The Board of Parole consists of seven members. Parole eligibility: Inmates are generally eligible after serving 50% of their sentence (75% for violent crimes). Mandatory parole period follows release.', offense_level: null, category: 'criminal', subcategory: 'Corrections' },
  { state: 'CO', state_name: 'Colorado', title: 17, chapter: 22, section: '103', subsection: null, citation: 'CRS 17-22.5-103', short_title: 'Mandatory Parole', description: 'Mandatory parole period upon release from incarceration', definition: 'All inmates sentenced for Class 2-6 felonies serve a mandatory parole period: Class 2: 5 years. Class 3: 5 years. Class 4: 3 years. Class 5: 2 years. Class 6: 1 year. Sex offenses: 10 years to life.', offense_level: null, category: 'criminal', subcategory: 'Corrections' },
  { state: 'CO', state_name: 'Colorado', title: 17, chapter: 27, section: '101', subsection: null, citation: 'CRS 17-27.8-101', short_title: 'Sex Offender Registration', description: 'Requirements for sex offender registration in Colorado', definition: 'Persons convicted of unlawful sexual behavior must register. Duration: 5 years (misdemeanor), 10 years (felony), lifetime (sexually violent predator). Registration with local law enforcement within 5 days of release or address change.', offense_level: null, category: 'criminal', subcategory: 'Corrections' },
];
