// ============================================================
// RMPG Flex — Idaho Code (IC)
// ============================================================
// Title 18: Crimes & Punishments | Title 49: Motor Vehicles
// Offense levels mapped to Utah enum for UI compatibility:
//   ID felony (life) → first_degree_felony
//   ID felony (≥5 yrs) → second_degree_felony
//   ID felony (≤5 yrs) → third_degree_felony
//   ID misdemeanor → class_a_misdemeanor
//   ID infraction → infraction
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const IDAHO_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // TITLE 18 — CRIMES AND PUNISHMENTS
  // ────────────────────────────────────────────────────────────

  // ── Chapter 1: General Provisions ──────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 1, section: '101', subsection: null, citation: 'IC 18-101', short_title: 'Title of Code', description: 'Title 18 of Idaho Code governing crimes and punishments', definition: 'Idaho Crimes and Punishments code. Defines all criminal offenses, defenses, and penalties for the State of Idaho.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 1, section: '111', subsection: null, citation: 'IC 18-111', short_title: 'Felony Defined', description: 'A crime which is punishable with death or by imprisonment in the state prison', definition: 'Felony: any crime punishable by death or imprisonment in the state prison. Every other crime is a misdemeanor. Idaho does not use numbered felony classes; specific sentencing is per-statute.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 1, section: '112', subsection: null, citation: 'IC 18-112', short_title: 'Misdemeanor Defined', description: 'A crime punishable by fine or county jail not exceeding one year, or both', definition: 'Misdemeanor: every crime other than a felony. Punishable by fine, county jail up to 1 year, or both. Idaho distinguishes misdemeanors informally by severity but has no formal classes.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 2, section: '204', subsection: null, citation: 'IC 18-204', short_title: 'Aiding and Abetting', description: 'All persons concerned in the commission of a crime are principals', definition: 'Elements: (1) Directly commits the crime; (2) aids and abets in its commission; (3) advises, encourages, or commands. All principals are equally punishable.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 3, section: '306', subsection: null, citation: 'IC 18-306', short_title: 'Attempt', description: 'An act done with intent to commit a crime, tending but failing to accomplish it', definition: 'Elements: (1) Intent to commit a specific crime; (2) a direct act done toward its commission; (3) failing to consummate. Punishable by up to half the maximum for completed crime.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 17, section: '1701', subsection: null, citation: 'IC 18-1701', short_title: 'Conspiracy', description: 'Agreement between two or more persons to commit a crime with an overt act', definition: 'Elements: (1) Two or more persons agree; (2) to commit any crime; (3) one or more does an overt act in furtherance. If underlying crime is felony: up to 5 years. If misdemeanor: same as underlying.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },

  // ── Homicide ───────────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 40, section: '4001', subsection: null, citation: 'IC 18-4001', short_title: 'Murder Defined', description: 'The unlawful killing of a human being with malice aforethought', definition: 'Murder is the unlawful killing of a human being including a human embryo or fetus, with malice aforethought. Malice may be express (deliberate intention) or implied (circumstances showing abandoned and malignant heart).', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 40, section: '4003', subsection: null, citation: 'IC 18-4003', short_title: 'Murder - First Degree', description: 'Murder perpetrated by poison, lying in wait, torture, or premeditated killing', definition: 'Murder of the first degree: (1) perpetrated by means of poison, lying in wait, torture; (2) any willful, deliberate, premeditated killing; (3) during arson, rape, robbery, burglary, kidnapping, mayhem. Penalty: death or life imprisonment, minimum 10 years before parole.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 40, section: '4006', subsection: null, citation: 'IC 18-4006', short_title: 'Manslaughter', description: 'The unlawful killing of a human being without malice', definition: 'Voluntary manslaughter: upon a sudden quarrel or heat of passion. Involuntary manslaughter: unintentional killing during unlawful act not amounting to felony, or lawful act performed without due caution. Penalty: up to 15 years (voluntary), up to 10 years (involuntary).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 40, section: '4006', subsection: '3', citation: 'IC 18-4006(3)', short_title: 'Vehicular Manslaughter', description: 'Unlawfully killing a human being by operation of a motor vehicle in a reckless manner', definition: 'Elements: (1) Operation of a motor vehicle; (2) commission of an unlawful act, not amounting to felony; (3) gross negligence; (4) resulting in death. Penalty: up to 15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },

  // ── Assault & Battery ──────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '901', subsection: null, citation: 'IC 18-901', short_title: 'Assault Defined', description: 'An unlawful attempt, coupled with apparent ability, to commit a violent injury on the person of another', definition: 'Assault: (1) unlawful attempt, with apparent ability, to commit violent injury on another; OR (2) intentional, unlawful threat by word or act to do violence with apparent ability creating well-founded fear. No physical contact required.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '903', subsection: null, citation: 'IC 18-903', short_title: 'Battery Defined', description: 'Willful and unlawful use of force or violence upon the person of another', definition: 'Battery: (1) willful and unlawful use of force or violence upon another; (2) actual, intentional, and unlawful touching or striking; (3) intentionally causing bodily harm. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '905', subsection: null, citation: 'IC 18-905', short_title: 'Aggravated Assault', description: 'Assault with a deadly weapon or instrument, or by means likely to produce great bodily harm', definition: 'Elements: (1) Assault; (2) with a deadly weapon or instrument; (3) without intent to kill; OR (4) by any means or force likely to produce great bodily harm. Felony: up to 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '907', subsection: null, citation: 'IC 18-907', short_title: 'Aggravated Battery', description: 'Battery which causes great bodily harm, permanent disability, or disfigurement', definition: 'Elements: (1) Commits battery; (2) causes great bodily harm, permanent disability, or permanent disfigurement; OR (3) uses a deadly weapon or instrument; OR (4) uses poison or other noxious substance. Felony: up to 15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '915', subsection: null, citation: 'IC 18-915', short_title: 'Assault/Battery on Officer', description: 'Assault or battery on a law enforcement officer, firefighter, EMT, or corrections officer', definition: 'Elements: (1) Commits assault or battery; (2) upon a law enforcement officer, firefighter, EMT, paramedic, judicial officer, correctional officer, or school employee; (3) while performing official duties. Felony: up to 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Assault' },

  // ── Sexual Offenses ────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 61, section: '6101', subsection: null, citation: 'IC 18-6101', short_title: 'Rape', description: 'Penetration accomplished where the victim is unable to resist or consent, or through force or threat', definition: 'Elements: (1) Penetration; (2) where victim cannot resist due to intoxicant, condition, or disability; OR (3) accomplished through force, violence, duress, or menace of injury; OR (4) victim under 16. Felony: up to life imprisonment.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },

  // ── Kidnapping ─────────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 45, section: '4501', subsection: null, citation: 'IC 18-4501', short_title: 'Kidnapping - First Degree', description: 'Willfully seizing, confining, or carrying away another person with intent to demand ransom, commit robbery, or inflict harm', definition: 'Elements: (1) Willfully seizes, confines, or carries away; (2) another person; (3) with intent to hold for ransom, commit robbery, facilitate felony, or inflict injury. Penalty: up to 25 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 45, section: '4502', subsection: null, citation: 'IC 18-4502', short_title: 'Kidnapping - Second Degree', description: 'Willfully detaining or concealing another person without lawful authority', definition: 'Elements: (1) Willfully; (2) without lawful authority; (3) forcibly or secretly confines or imprisons; (4) another person. Penalty: 1-10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },

  // ── Property Offenses ──────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 14, section: '1401', subsection: null, citation: 'IC 18-1401', short_title: 'Burglary', description: 'Entering any house, room, apartment, or building with intent to commit any theft or felony', definition: 'Elements: (1) Enters; (2) any house, room, apartment, tenement, shop, warehouse, or other building; (3) with intent to commit any theft or any felony. Felony: 1-10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 65, section: '6501', subsection: null, citation: 'IC 18-6501', short_title: 'Robbery', description: 'Taking personal property from the person or immediate presence of another by force or fear', definition: 'Elements: (1) Felonious taking; (2) of personal property; (3) in possession of another; (4) from person or immediate presence; (5) against will; (6) accomplished by force or fear. Felony: 5 years to life.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 24, section: '2403', subsection: null, citation: 'IC 18-2403', short_title: 'Theft', description: 'Knowingly taking, obtaining, or withholding property of another with intent to deprive', definition: 'Unified theft statute. Elements: (1) Knowingly; (2) takes, obtains, or withholds; (3) property of another; (4) with intent to deprive. Grand theft (≥$1,000 or firearm/vehicle): felony up to 14 years. Petit theft (<$1,000): misdemeanor up to 1 year.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 24, section: '2403', subsection: '4', citation: 'IC 18-2403(4)', short_title: 'Grand Theft', description: 'Theft of property valued at $1,000 or more, or theft of certain specified property (firearms, vehicles)', definition: 'Grand theft if: (1) value ≥$1,000; (2) property is a firearm; (3) property is a horse, steer, or cow; (4) property taken from the person of another; (5) is a motor vehicle. Felony: up to 14 years and/or $5,000.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 24, section: '2407', subsection: null, citation: 'IC 18-2407', short_title: 'Petit Theft', description: 'Theft of property valued at less than $1,000', definition: 'Petit theft: property value less than $1,000 and not a firearm, motor vehicle, or other specified grand theft item. Misdemeanor: up to 1 year and/or $1,000. Second offense in 5 years may be charged as felony.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 24, section: '2409', subsection: null, citation: 'IC 18-2409', short_title: 'Motor Vehicle Theft', description: 'Unauthorized taking or operation of a motor vehicle of another', definition: 'Elements: (1) Takes, drives, or uses; (2) a motor vehicle; (3) without authorization of the owner. Grand theft: felony up to 14 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 70, section: '7001', subsection: null, citation: 'IC 18-7001', short_title: 'Malicious Injury to Property', description: 'Maliciously injuring or destroying any real or personal property of another', definition: 'Elements: (1) Maliciously; (2) injures or destroys; (3) real or personal property; (4) of another. If damage ≥$1,000: felony up to 5 years. If <$1,000: misdemeanor up to 1 year.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Property Damage' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 70, section: '7008', subsection: null, citation: 'IC 18-7008', short_title: 'Trespass', description: 'Entering or remaining upon the property of another without permission after notice', definition: 'Elements: (1) Enters or remains upon; (2) property of another; (3) after being notified (signs, verbal, fencing). Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Trespass' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 13, section: '1301', subsection: null, citation: 'IC 18-1301', short_title: 'Arson - First Degree', description: 'Willfully and unlawfully setting fire to or burning an occupied dwelling house', definition: 'Elements: (1) Willfully and unlawfully; (2) sets fire to or burns; (3) any dwelling house or occupied structure. Felony: up to 25 years and/or $100,000.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Arson' },

  // ── Fraud ──────────────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 36, section: '3601', subsection: null, citation: 'IC 18-3601', short_title: 'Forgery', description: 'Falsely making, altering, or forging a written instrument with intent to defraud', definition: 'Elements: (1) Falsely makes, alters, or forges; (2) any check, draft, money order, or written instrument; (3) with intent to defraud. Felony: up to 14 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 31, section: '3126', subsection: null, citation: 'IC 18-3126', short_title: 'Identity Theft', description: 'Obtaining, possessing, or using personal identifying information of another with intent to defraud', definition: 'Elements: (1) Obtains, possesses, transfers, or uses; (2) personal identifying information of another; (3) without authorization; (4) with intent to obtain financial benefit or commit fraud. Felony: up to 5 years and/or $50,000.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },

  // ── Weapons ────────────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 33, section: '3302', subsection: null, citation: 'IC 18-3302', short_title: 'Concealed Weapons', description: 'Idaho allows concealed carry without permit for residents 18+ (constitutional carry since 2020)', definition: 'Idaho is a constitutional carry state. Residents 18+ may carry concealed firearms without a permit. Non-residents 21+ with valid home-state permit may also carry concealed. Enhanced permits available for reciprocity.', offense_level: null, category: 'criminal', subcategory: 'Weapons' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 33, section: '3316', subsection: null, citation: 'IC 18-3316', short_title: 'Felon in Possession of Firearm', description: 'A person convicted of a felony who possesses, controls, or has custody of a firearm', definition: 'Elements: (1) Convicted of a felony; (2) possesses, controls, or has custody of; (3) any firearm. Felony: up to 5 years and/or $5,000.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },

  // ── Drugs ──────────────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 37, chapter: 27, section: '2732', subsection: 'a', citation: 'IC 37-2732(a)', short_title: 'Drug Trafficking', description: 'Manufacturing, delivering, or bringing into state a controlled substance in specific quantities', definition: 'Elements: (1) Manufactures, delivers, or brings into state; (2) a specified quantity of controlled substance. Mandatory minimums vary by drug and quantity. Marijuana 1+ lb: 1-5 years, $5,000. Meth 28g+: 3-life.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'ID', state_name: 'Idaho', title: 37, chapter: 27, section: '2732', subsection: 'c', citation: 'IC 37-2732(c)', short_title: 'Possession of Controlled Substance', description: 'Possession of a controlled substance without valid prescription', definition: 'Elements: (1) Possesses; (2) a controlled substance; (3) without valid prescription. Felony (Schedule I): up to 7 years and/or $15,000. Felony (Schedule II/III): up to 5 years and/or $10,000. Misdemeanor (Schedule IV/V).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'ID', state_name: 'Idaho', title: 37, chapter: 27, section: '2734A', subsection: null, citation: 'IC 37-2734A', short_title: 'Drug Paraphernalia', description: 'Use or possession with intent to use drug paraphernalia', definition: 'Elements: (1) Uses or possesses with intent to use; (2) drug paraphernalia; (3) to introduce a controlled substance into the human body. Misdemeanor: up to 1 year and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Drugs' },
  { state: 'ID', state_name: 'Idaho', title: 37, chapter: 27, section: '2732B', subsection: null, citation: 'IC 37-2732B', short_title: 'Marijuana Possession', description: 'Possession of marijuana (all amounts are illegal in Idaho, no recreational or medical program)', definition: 'Idaho has no medical or recreational marijuana program. Any amount of marijuana possession is illegal. Less than 3 oz: misdemeanor up to 1 year and/or $1,000. 3+ oz: felony up to 5 years.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Drugs' },

  // ── Domestic Violence ──────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 9, section: '918', subsection: null, citation: 'IC 18-918', short_title: 'Domestic Violence', description: 'Assault or battery committed against a household member', definition: 'Elements: (1) Commits assault or battery; (2) against a household member (spouse, former spouse, cohabitant, person with whom defendant has a child). First: misdemeanor up to 6 months. Second within 10 years: misdemeanor up to 1 year. Third within 15 years: felony up to 10 years. Traumatic injury: felony up to 10 years.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 79, section: '7905', subsection: null, citation: 'IC 18-7905', short_title: 'Stalking - First Degree', description: 'Engaging in a knowing and willful course of conduct directed at a specific person that seriously alarms, annoys, or harasses', definition: 'Elements: (1) Knowingly and willfully; (2) course of conduct (repeated acts); (3) directed at a specific person; (4) would cause reasonable person to feel frightened, intimidated, or harassed. First degree (with threats of bodily harm, prior conviction, or violated protection order): felony up to 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Public Order ───────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 64, section: '6409', subsection: null, citation: 'IC 18-6409', short_title: 'Disturbing the Peace', description: 'Maliciously and willfully disturbing the peace of any neighborhood or person', definition: 'Elements: (1) Maliciously and willfully; (2) disturbs the peace; (3) of any neighborhood or person; (4) by loud or unusual noise, tumultuous or offensive conduct, or threatening, quarreling, challenging to fight. Misdemeanor: up to 6 months.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 7, section: '705', subsection: null, citation: 'IC 18-705', short_title: 'Resisting/Obstructing Officer', description: 'Willfully resisting, delaying, or obstructing a public officer in the discharge of duty', definition: 'Elements: (1) Willfully resists, delays, or obstructs; (2) any public officer; (3) in the discharge or attempt to discharge official duties. Misdemeanor: up to 1 year and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },

  // ── Child Offenses ─────────────────────────────────────────
  { state: 'ID', state_name: 'Idaho', title: 18, chapter: 15, section: '1501', subsection: null, citation: 'IC 18-1501', short_title: 'Injury to Children', description: 'Willfully causing or permitting a child to be placed in a situation dangerous to its health or well-being', definition: 'Elements: (1) Willfully causes or permits; (2) a child to suffer; (3) unjustifiable physical pain or mental suffering; OR to be placed in a situation where health, person, or morals are endangered. If great bodily harm or death: felony up to 10 years. Otherwise: up to 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Crimes Against Children' },

  // ────────────────────────────────────────────────────────────
  // TITLE 49 — MOTOR VEHICLES
  // ────────────────────────────────────────────────────────────

  // DUI
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 14, section: '1402', subsection: null, citation: 'IC 18-8004', short_title: 'DUI - Driving Under the Influence', description: 'Operating a motor vehicle while under the influence of alcohol, drugs, or intoxicating substances (BAC .08+)', definition: 'Elements: (1) Drives or is in actual physical control; (2) of a motor vehicle; (3) while under the influence of alcohol/drugs/intoxicants, OR BAC 0.08% or more. First offense: misdemeanor up to 6 months and/or $1,000. Second within 10 years: misdemeanor up to 1 year and/or $2,000. BAC 0.20+: enhanced penalties.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 1000 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 14, section: '1402', subsection: 'b', citation: 'IC 18-8004B', short_title: 'Felony DUI', description: 'Third or subsequent DUI within 10 years, or DUI causing death or serious bodily injury', definition: 'Felony DUI: (1) Third or subsequent DUI within 10 years; OR (2) any DUI that causes death or serious bodily injury. Penalty: 1-10 years state prison and/or $5,000.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'DUI', citation_fine: 5000 },

  // Moving Violations
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 6, section: '654', subsection: null, citation: 'IC 49-654', short_title: 'Speeding', description: 'Operating a vehicle in excess of posted speed limits', definition: 'Speed limits: Business district 35 mph, Residential 35 mph, Interstate 80 mph (posted), otherwise as posted. Infraction: $33.50 base + $5 per mph over up to 15, $6 per mph 16+. Excessive speed (25+ over): misdemeanor.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 14, section: '1401', subsection: null, citation: 'IC 49-1401', short_title: 'Reckless Driving', description: 'Driving a vehicle in a manner that shows a willful or wanton disregard for the safety of persons or property', definition: 'Elements: (1) Drives a vehicle; (2) carelessly and heedlessly; (3) in willful or wanton disregard of rights or safety of others; (4) without due caution at speed or manner endangering person or property. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 300 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 14, section: '1404', subsection: null, citation: 'IC 49-1404', short_title: 'Eluding Police', description: 'Willfully fleeing or attempting to elude a pursuing police vehicle', definition: 'Elements: (1) Willfully; (2) flees or attempts to elude; (3) a pursuing police vehicle; (4) after receiving visual or audible signal to stop. Felony: up to 5 years and/or $5,000. If injury: up to 10 years.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 5000 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 13, section: '1301', subsection: null, citation: 'IC 49-1301', short_title: 'Hit and Run - Property', description: 'Leaving the scene of an accident involving property damage without providing information', definition: 'Elements: (1) Involved in accident; (2) resulting in property damage; (3) fails to stop, give name/address/registration/license info. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 300 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 13, section: '1301', subsection: '2', citation: 'IC 49-1301(2)', short_title: 'Hit and Run - Injury/Death', description: 'Leaving the scene of an accident involving injury or death without providing information and aid', definition: 'Elements: (1) Involved in accident; (2) resulting in injury or death; (3) fails to stop and render aid. Felony: up to 5 years and/or $5,000.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 5000 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 8, section: '801', subsection: null, citation: 'IC 49-801', short_title: 'Traffic Signal Violations', description: 'Failure to obey traffic signals and control devices', definition: 'Drivers must obey all official traffic-control signals. Steady red: stop. Flashing red: stop then proceed. Green: go when safe. Infraction: $33.50-$90.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 8, section: '802', subsection: null, citation: 'IC 49-802', short_title: 'Stop Sign Violations', description: 'Failure to stop at a stop sign', definition: 'Driver must come to a complete stop at stop signs. Must yield right-of-way to vehicles and pedestrians already in the intersection.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 6, section: '638', subsection: null, citation: 'IC 49-638', short_title: 'Following Too Closely', description: 'Following another vehicle more closely than is reasonable and prudent', definition: 'Driver shall not follow more closely than is reasonable and prudent, having due regard for speed, traffic, and road conditions.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 6, section: '637', subsection: null, citation: 'IC 49-637', short_title: 'Improper Lane Change', description: 'Changing lanes when unsafe or without proper signal', definition: 'Vehicle must be driven as nearly as practicable entirely within a single lane. Must not move from lane until driver has ascertained that movement can be made safely.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 10, section: '1012', subsection: null, citation: 'IC 49-1012', short_title: 'Texting While Driving', description: 'Using a mobile electronic device to text, email, or access internet while driving', definition: 'Elements: (1) Drives a motor vehicle; (2) uses a mobile electronic device; (3) to manually compose, send, or read text-based communication. Infraction: $75.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 8, section: '852', subsection: null, citation: 'IC 49-852', short_title: 'School Bus - Failure to Stop', description: 'Failing to stop for a school bus displaying alternating red lights', definition: 'All vehicles must stop when school bus displays alternating red lights. May not proceed until bus resumes motion or driver signals. Fine: up to $150 first offense, up to $300 subsequent.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 150 },

  // Registration / License / Insurance
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 4, section: '401', subsection: null, citation: 'IC 49-401', short_title: 'Vehicle Registration Required', description: 'Every motor vehicle operated on Idaho highways must be registered', definition: 'All motor vehicles operated on public highways must be registered with the Idaho Transportation Department. Registration renewed annually. Temporary permits available.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 150 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 3, section: '301', subsection: null, citation: 'IC 49-301', short_title: 'Drivers License Required', description: 'No person shall drive a motor vehicle on Idaho highways without a valid drivers license', definition: 'Must possess valid Idaho drivers license or valid license from another jurisdiction. Must have license in immediate possession while driving.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 150 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 3, section: '326', subsection: null, citation: 'IC 49-326', short_title: 'Driving Without Privileges', description: 'Operating a motor vehicle while license is suspended, revoked, or disqualified', definition: 'Elements: (1) Operates motor vehicle; (2) on public roadway; (3) while license is suspended, revoked, disqualified, or was never issued. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 500 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 12, section: '1229', subsection: null, citation: 'IC 49-1229', short_title: 'Liability Insurance Required', description: 'Every owner of a motor vehicle registered in Idaho must maintain liability insurance', definition: 'Minimum coverage: $25,000 bodily injury per person, $50,000 per accident, $15,000 property damage. Proof must be carried and presented on demand.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Insurance', citation_fine: 75 },

  // Equipment
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 6, section: '672', subsection: null, citation: 'IC 49-672', short_title: 'Seatbelt Violations', description: 'Failure to wear a seatbelt while operating or riding in a motor vehicle', definition: 'Driver and all passengers must wear seatbelts. Children under 7 must be in child restraint system. Primary enforcement. Fine: $10.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 10 },
  { state: 'ID', state_name: 'Idaho', title: 49, chapter: 9, section: '903', subsection: null, citation: 'IC 49-903', short_title: 'Headlight Violations', description: 'Failure to display headlights during required hours or conditions', definition: 'Headlights required from sunset to sunrise and when visibility less than 500 feet. Must use low beams within 300 feet of oncoming traffic and 200 feet when following.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 50 },
];
