// ============================================================
// RMPG Flex — Nevada Revised Statutes (NRS)
// ============================================================
// NRS 193-207: Crimes | NRS 484: Motor Vehicles
// Offense levels mapped to Utah enum for UI compatibility:
//   NV Category A Felony → first_degree_felony
//   NV Category B Felony → second_degree_felony
//   NV Category C Felony → third_degree_felony
//   NV Category D Felony → third_degree_felony
//   NV Category E Felony → third_degree_felony
//   NV Gross Misdemeanor → class_a_misdemeanor
//   NV Misdemeanor → class_b_misdemeanor
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const NEVADA_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // NRS 193-207 — CRIMES AND PUNISHMENTS
  // ────────────────────────────────────────────────────────────

  // ── General Provisions (NRS 193) ───────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 193, chapter: 193, section: '120', subsection: null, citation: 'NRS 193.120', short_title: 'Felony Defined', description: 'A crime which may be punished by death or imprisonment in the state prison', definition: 'Felony: a crime punishable by death or imprisonment in the state prison. Categories: A (death/life), B (1-20 yrs), C (1-5 yrs), D (1-4 yrs), E (1-4 yrs probation eligible). Nevada uses lettered felony categories unique among US states.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NV', state_name: 'Nevada', title: 193, chapter: 193, section: '130', subsection: null, citation: 'NRS 193.130', short_title: 'Gross Misdemeanor Defined', description: 'A crime punishable by imprisonment in the county jail for not more than 364 days and/or $2,000 fine', definition: 'Gross misdemeanor: imprisonment in county jail up to 364 days and/or fine up to $2,000. Intermediate category between felony and misdemeanor unique to Nevada.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NV', state_name: 'Nevada', title: 193, chapter: 193, section: '140', subsection: null, citation: 'NRS 193.140', short_title: 'Misdemeanor Defined', description: 'A crime punishable by imprisonment in the county jail for not more than 6 months and/or $1,000 fine', definition: 'Misdemeanor: imprisonment in county jail up to 6 months and/or fine up to $1,000.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NV', state_name: 'Nevada', title: 193, chapter: 193, section: '330', subsection: null, citation: 'NRS 193.330', short_title: 'Attempt', description: 'A person who attempts to commit a crime and does an act in furtherance is guilty of attempt', definition: 'Elements: (1) Intent to commit a crime; (2) performs an act in furtherance of the crime. Punishment: one category lower than completed offense. Attempt to commit Cat A: Cat B (2-20 yrs).', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NV', state_name: 'Nevada', title: 199, chapter: 199, section: '480', subsection: null, citation: 'NRS 199.480', short_title: 'Conspiracy', description: 'Agreement between two or more persons to commit a crime with an overt act', definition: 'Elements: (1) Two or more persons agree; (2) to commit a crime or accomplish a lawful purpose by unlawful means; (3) one or more commits an overt act. Same category as underlying offense or one lower depending on crime.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },

  // ── Homicide (NRS 200) ─────────────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '010', subsection: null, citation: 'NRS 200.010', short_title: 'Murder Defined', description: 'The unlawful killing of a human being with malice aforethought', definition: 'Murder is the unlawful killing of a human being with malice aforethought, either express or implied. Express: deliberate intention to take life. Implied: killing resulting from acts extremely dangerous showing depraved mind.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '030', subsection: null, citation: 'NRS 200.030', short_title: 'Murder - First Degree', description: 'Murder perpetrated by poison, lying in wait, torture, or premeditated killing', definition: 'First degree murder: (1) by poison, lying in wait, torture, or willful/deliberate/premeditated killing; (2) during arson, robbery, burglary, kidnapping, sexual assault, child abuse, terrorism. Category A felony: death or life with/without parole.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '030', subsection: '2', citation: 'NRS 200.030(2)', short_title: 'Murder - Second Degree', description: 'All other kinds of murder not constituting first degree', definition: 'Second degree murder: all murder that is not first degree. Category A felony: life with possibility of parole, minimum 10 years before eligible.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '040', subsection: null, citation: 'NRS 200.040', short_title: 'Voluntary Manslaughter', description: 'Killing upon a sudden heat of passion caused by provocation sufficient to make a reasonable person act rashly', definition: 'Elements: (1) Unlawful killing; (2) upon sudden heat of passion; (3) caused by sufficient provocation rendering a reasonable person incapable of cool reflection. Category B felony: 1-10 years and/or $10,000.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '070', subsection: null, citation: 'NRS 200.070', short_title: 'Involuntary Manslaughter', description: 'Unintentional killing during unlawful act not amounting to a felony, or lawful act performed negligently', definition: 'Elements: (1) Unintentional killing; (2) during commission of unlawful act not amounting to felony, OR lawful act without due caution. Category D felony: 1-4 years and/or $5,000.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B657', subsection: null, citation: 'NRS 484B.657', short_title: 'Vehicular Homicide (DUI)', description: 'Causing death while driving under the influence of alcohol or drugs', definition: 'Elements: (1) Driving under the influence; (2) proximately causes death. Category A felony: 25 years to life. Separate from vehicular manslaughter which applies to non-DUI reckless driving deaths.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },

  // ── Assault & Battery (NRS 200) ────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '471', subsection: null, citation: 'NRS 200.471', short_title: 'Assault', description: 'Unlawfully attempting to use physical force against another person, or intentionally placing in reasonable fear of harm', definition: 'Elements: (1) Unlawfully attempts to use physical force against another; OR (2) intentionally places another in reasonable apprehension of immediate bodily harm. Simple assault: misdemeanor up to 6 months and/or $1,000.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '481', subsection: null, citation: 'NRS 200.481', short_title: 'Battery', description: 'Willful and unlawful use of force or violence upon the person of another', definition: 'Elements: (1) Willful and unlawful; (2) use of force or violence; (3) upon person of another. Simple battery: misdemeanor up to 6 months and/or $1,000. With substantial bodily harm: Category C felony (1-5 yrs).', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '471', subsection: '2', citation: 'NRS 200.471(2)', short_title: 'Assault with Deadly Weapon', description: 'Assault committed with a deadly weapon or the present ability to use a deadly weapon', definition: 'Elements: (1) Assault; (2) with a deadly weapon or present ability to use a deadly weapon. Category B felony: 1-6 years and/or $5,000.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '481', subsection: '2', citation: 'NRS 200.481(2)', short_title: 'Battery with Deadly Weapon/Substantial Bodily Harm', description: 'Battery committed with a deadly weapon or resulting in substantial bodily harm', definition: 'Elements: (1) Battery; (2) with deadly weapon; OR (3) resulting in substantial bodily harm. Category B felony: 2-10 years. If both deadly weapon and substantial bodily harm: 2-15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '471', subsection: '3', citation: 'NRS 200.471(3)', short_title: 'Assault on Protected Person', description: 'Assault on a peace officer, firefighter, EMT, or other protected person performing official duties', definition: 'Elements: (1) Assault; (2) upon a peace officer, school employee, sports official, health care worker, taxi driver, transit operator; (3) while performing official duties. Gross misdemeanor: up to 364 days and/or $2,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },

  // ── Sexual Offenses (NRS 200) ──────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '366', subsection: null, citation: 'NRS 200.366', short_title: 'Sexual Assault', description: 'Subjecting another person to sexual penetration against the will or under conditions where victim cannot consent', definition: 'Elements: (1) Sexual penetration; (2) against the will of the victim; (3) by force, threat, or when victim is incapable of consent. Category A felony: life with/without parole. If victim under 16: life without parole. If victim 16+: 10 years to life.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },

  // ── Kidnapping (NRS 200) ───────────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '310', subsection: null, citation: 'NRS 200.310', short_title: 'Kidnapping - First Degree', description: 'Willfully seizing, confining, or carrying away a person with intent to extort ransom or facilitate crime', definition: 'Elements: (1) Willfully seizes, confines, or carries away; (2) by force, fraud, or intimidation; (3) with intent to hold for ransom, kill, inflict harm, commit sexual assault, or facilitate crime. Category A felony: life with/without parole.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '310', subsection: '2', citation: 'NRS 200.310(2)', short_title: 'Kidnapping - Second Degree', description: 'Willfully seizing or confining another person without intent to hold for ransom or commit further crime', definition: 'Elements: (1) Willfully; (2) seizes, confines, or carries away; (3) another person without specific intent required for first degree. Category B felony: 2-15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },

  // ── Property Offenses (NRS 205) ────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '060', subsection: null, citation: 'NRS 205.060', short_title: 'Burglary', description: 'Entering any building, structure, or vehicle with intent to commit a crime therein', definition: 'Elements: (1) Enters; (2) any house, room, apartment, building, vehicle, railroad car, or vessel; (3) with intent to commit grand or petit larceny, assault, battery, or any felony. Category B felony: 1-10 years. If inhabited dwelling: 2-15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '380', subsection: null, citation: 'NRS 200.380', short_title: 'Robbery', description: 'Unlawful taking of personal property from the person of another by force, violence, or fear', definition: 'Elements: (1) Unlawful taking; (2) personal property; (3) from person or presence of another; (4) against will; (5) by force, violence, fear of injury, or threat. Category B felony: 2-15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },

  // Theft
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '0832', subsection: null, citation: 'NRS 205.0832', short_title: 'Theft - General', description: 'Knowingly controlling property of another with intent to deprive, obtaining by fraud, or stealing', definition: 'Unified theft statute. Elements: (1) Knowingly; (2) controls, converts, obtains, or uses; (3) property of another; (4) with intent to deprive, by fraud, or knowing stolen. Penalties based on value thresholds.', offense_level: null, category: 'criminal', subcategory: 'Theft' },
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '0835', subsection: null, citation: 'NRS 205.0835', short_title: 'Theft ≥$1,200 (Grand Larceny)', description: 'Theft of property valued at $1,200 or more', definition: 'Grand larceny: property value $1,200 or more. $1,200-$5,000: Category C felony (1-5 yrs). $5,000-$25,000: Category C felony (1-5 yrs). $25,000-$100,000: Category B (1-10 yrs). $100,000+: Category B (1-20 yrs).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '240', subsection: null, citation: 'NRS 205.240', short_title: 'Petit Larceny', description: 'Theft of property valued at less than $1,200', definition: 'Petit larceny: value less than $1,200. Misdemeanor: up to 6 months and/or $1,000. Prior convictions may elevate to gross misdemeanor or felony.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '2715', subsection: null, citation: 'NRS 205.2715', short_title: 'Motor Vehicle Theft', description: 'Taking a motor vehicle not ones own without consent of the owner', definition: 'Elements: (1) Takes; (2) a motor vehicle; (3) not ones own; (4) without consent of owner. Category C felony: 1-5 years and/or $10,000.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '463', subsection: null, citation: 'NRS 205.463', short_title: 'Identity Theft', description: 'Obtaining, possessing, or using personal identifying information of another with intent to harm or defraud', definition: 'Elements: (1) Knowingly obtains, possesses, or uses; (2) personal identifying information of another; (3) to harm, impersonate, or defraud. Category B felony: 1-20 years depending on amount of harm/loss.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '090', subsection: null, citation: 'NRS 205.090', short_title: 'Forgery', description: 'Falsely making, altering, or forging a written instrument with intent to defraud', definition: 'Elements: (1) Falsely makes, alters, counterfeits, or forges; (2) any written instrument; (3) with intent to defraud. Category B felony: 1-6 years and/or $5,000 (non-financial), 1-20 years (financial instruments).', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },

  // Arson / Trespass / Criminal Mischief
  { state: 'NV', state_name: 'Nevada', title: 205, chapter: 205, section: '010', subsection: null, citation: 'NRS 205.010', short_title: 'Arson - First Degree', description: 'Willfully and maliciously setting fire to or burning an occupied dwelling', definition: 'Elements: (1) Willfully and maliciously; (2) sets fire to or burns; (3) any occupied structure or dwelling. Category B felony: 2-15 years and/or $15,000.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Arson' },
  { state: 'NV', state_name: 'Nevada', title: 207, chapter: 207, section: '200', subsection: null, citation: 'NRS 207.200', short_title: 'Trespass', description: 'Going upon the land or into any building of another after being warned not to trespass', definition: 'Elements: (1) Goes upon land or into building; (2) of another person; (3) after being warned not to trespass (signs, verbal, fencing). Misdemeanor: up to 6 months and/or $1,000. If with threat: gross misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Trespass' },
  { state: 'NV', state_name: 'Nevada', title: 206, chapter: 206, section: '310', subsection: null, citation: 'NRS 206.310', short_title: 'Destroying/Injuring Property', description: 'Willfully or maliciously destroying or injuring personal property of another', definition: 'Elements: (1) Willfully or maliciously; (2) destroys or injures; (3) property of another. If damage ≥$5,000: Category B felony. $250-$5,000: gross misdemeanor. <$250: misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Property Damage' },

  // ── Domestic Violence (NRS 200) ────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '485', subsection: null, citation: 'NRS 200.485', short_title: 'Battery Constituting Domestic Violence', description: 'Battery committed against a person with whom the defendant has a domestic relationship', definition: 'Elements: (1) Battery (willful/unlawful force); (2) upon a spouse, former spouse, relative by blood/marriage, dating partner, cohabitant, or co-parent. First offense: misdemeanor, 2 days to 6 months, 48-120 hrs community service. Third within 7 years: Category B felony 1-6 years.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '575', subsection: null, citation: 'NRS 200.575', short_title: 'Stalking', description: 'Willfully or maliciously engaging in a course of conduct that would cause a reasonable person to feel terrorized', definition: 'Elements: (1) Without lawful authority; (2) willfully or maliciously; (3) engages in a course of conduct (pattern of 2+ acts over time); (4) would cause reasonable person to feel terrorized, frightened, intimidated, harassed. First offense: misdemeanor. Aggravated (threats, violates TPO): Category B felony 2-15 years.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Weapons (NRS 202) ──────────────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 202, chapter: 202, section: '350', subsection: null, citation: 'NRS 202.350', short_title: 'Carrying Concealed Weapon', description: 'Carrying a concealed firearm without a valid concealed carry permit', definition: 'Nevada requires a concealed carry permit (CCW) from county sheriff. Open carry is legal without permit. Carrying concealed without CCW: first offense Category C felony (1-5 yrs). Exceptions: home, business, vehicle. Permit requires background check, training.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },
  { state: 'NV', state_name: 'Nevada', title: 202, chapter: 202, section: '360', subsection: null, citation: 'NRS 202.360', short_title: 'Felon in Possession of Firearm', description: 'A person convicted of a felony who possesses or has under control any firearm', definition: 'Elements: (1) Convicted of a felony in any jurisdiction; (2) owns, possesses, or has under control; (3) any firearm. Category B felony: 1-6 years. Mental health prohibition also applies.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Weapons' },

  // ── Drug Offenses (NRS 453) ────────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 453, chapter: 453, section: '336', subsection: null, citation: 'NRS 453.336', short_title: 'Possession of Controlled Substance', description: 'Knowingly or intentionally possessing a controlled substance without valid prescription', definition: 'Elements: (1) Knowingly or intentionally; (2) possesses; (3) a controlled substance; (4) without valid prescription. Schedule I/II first offense: Category E felony (1-4 yrs, probation eligible). Second: Category E. Third: Category D (1-4 yrs prison). Nevada suspended sentences and treatment programs available.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'NV', state_name: 'Nevada', title: 453, chapter: 453, section: '337', subsection: null, citation: 'NRS 453.337', short_title: 'Possession for Sale / Manufacturing', description: 'Possessing a controlled substance with intent to sell, or manufacturing a controlled substance', definition: 'Elements: (1) Manufactures, sells, or possesses with intent to sell; (2) any Schedule I/II substance. Category B felony: 1-6 years and/or $5,000. If Schedule I/II narcotics: 1-20 years. Trafficking amounts have mandatory minimums.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'NV', state_name: 'Nevada', title: 453, chapter: 453, section: '566', subsection: null, citation: 'NRS 453.566', short_title: 'Marijuana Possession (Over Legal Limit)', description: 'Possession of more than the legal limit of marijuana (over 1 oz or 3.5g concentrate)', definition: 'Nevada legalized recreational marijuana (21+) in 2017 (AB 266). Legal: up to 1 oz flower or 3.5g concentrate. Over legal limit: misdemeanor. Selling without license: felony.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Drugs' },
  { state: 'NV', state_name: 'Nevada', title: 453, chapter: 453, section: '411', subsection: null, citation: 'NRS 453.411', short_title: 'Drug Paraphernalia', description: 'Use or possession of drug paraphernalia to introduce a controlled substance', definition: 'Elements: (1) Uses or possesses with intent to use; (2) drug paraphernalia; (3) to use a controlled substance (excluding marijuana paraphernalia for personal use). Misdemeanor: up to 6 months and/or $600.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Drugs' },

  // ── Public Order (NRS 199, 207) ────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 199, chapter: 199, section: '280', subsection: null, citation: 'NRS 199.280', short_title: 'Resisting Public Officer', description: 'Willfully resisting, delaying, or obstructing a public officer in discharging official duty', definition: 'Elements: (1) Willfully resists, delays, or obstructs; (2) a public officer; (3) in discharging or attempting to discharge official duty. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'NV', state_name: 'Nevada', title: 207, chapter: 207, section: '030', subsection: null, citation: 'NRS 207.030', short_title: 'Disorderly Conduct', description: 'Engaging in tumultuous or offensive conduct, making unreasonable noise, or fighting in public', definition: 'Elements: (1) Engages in tumultuous or offensive conduct; (2) makes unreasonable noise; (3) fights or challenges to fight in public; (4) discharges firearm in public; (5) uses obscene language in public. Misdemeanor: up to 6 months and/or $1,000.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Public Order' },

  // ── Crimes Against Children ────────────────────────────────
  { state: 'NV', state_name: 'Nevada', title: 200, chapter: 200, section: '508', subsection: null, citation: 'NRS 200.508', short_title: 'Child Abuse/Neglect', description: 'Willfully causing a child to suffer unjustifiable physical pain or mental suffering', definition: 'Elements: (1) Willfully causes; (2) a child under 18; (3) to suffer unjustifiable physical pain, mental suffering; OR (4) permits child to be in situation where endangered. No substantial harm: gross misdemeanor. Substantial bodily/mental harm: Category B felony 2-20 years.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Crimes Against Children' },

  // ────────────────────────────────────────────────────────────
  // NRS 484 — TRAFFIC LAWS
  // ────────────────────────────────────────────────────────────

  // DUI
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'C110', subsection: null, citation: 'NRS 484C.110', short_title: 'DUI - Driving Under the Influence', description: 'Operating a vehicle while under the influence of intoxicating liquor or controlled substance (BAC .08+)', definition: 'Elements: (1) Drives or is in actual physical control; (2) of a vehicle; (3) while under the influence of intoxicating liquor/controlled substance, OR BAC 0.08% or more (0.04% commercial). First offense: misdemeanor, 2 days to 6 months, $400-$1,000. Second within 7 years: misdemeanor, 10 days to 6 months, $750-$1,000.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 400 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'C400', subsection: null, citation: 'NRS 484C.400', short_title: 'DUI - Felony (Third Offense)', description: 'Third or subsequent DUI within 7 years becomes a felony', definition: 'Third DUI within 7 years: Category B felony: 1-6 years state prison and/or $2,000-$5,000. Must serve minimum 1 year before parole eligibility.', offense_level: 'second_degree_felony', category: 'vehicle', subcategory: 'DUI', citation_fine: 2000 },

  // Moving Violations
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B600', subsection: null, citation: 'NRS 484B.600', short_title: 'Speeding', description: 'Operating a vehicle in excess of posted speed limits', definition: 'Speed limits: Residential 25 mph, Business 25 mph, Interstate 80 mph (posted). 1-10 over: $50-$100. 11-20 over: $100-$200. 21-30 over: $200-$300. 31+ over: misdemeanor.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B653', subsection: null, citation: 'NRS 484B.653', short_title: 'Reckless Driving', description: 'Driving in willful or wanton disregard of the safety of persons or property', definition: 'Elements: (1) Drives a vehicle; (2) in willful or wanton disregard; (3) of safety of persons or property. Misdemeanor: up to 6 months and/or $250-$1,000. Second: 10 days to 6 months and/or $1,000-$1,500.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 500 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B550', subsection: null, citation: 'NRS 484B.550', short_title: 'Eluding Police', description: 'Failing to stop when signaled by a peace officer, or fleeing', definition: 'Elements: (1) Receives signal from peace officer (siren, flashing lights); (2) willfully fails to stop or attempts to elude. Misdemeanor: up to 6 months. If endangering others: Category B felony 1-6 years.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 1000 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'E020', subsection: null, citation: 'NRS 484E.020', short_title: 'Hit and Run - Property', description: 'Leaving the scene of an accident involving property damage without providing information', definition: 'Elements: (1) Involved in accident; (2) property damage; (3) fails to stop and provide name/address/registration. Misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 500 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'E030', subsection: null, citation: 'NRS 484E.030', short_title: 'Hit and Run - Injury/Death', description: 'Leaving the scene of an accident involving injury or death', definition: 'Elements: (1) Involved in accident; (2) resulting in injury or death; (3) fails to stop, give information, and render aid. If injury: Category B felony 2-15 years. If death: Category A felony 2 years to life.', offense_level: 'second_degree_felony', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 5000 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B300', subsection: null, citation: 'NRS 484B.300', short_title: 'Traffic Signal Violations', description: 'Failure to obey traffic signals and control devices', definition: 'Drivers must obey all official traffic-control signals. Steady red: stop. Right on red after stop (unless prohibited). Green: proceed when safe.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B310', subsection: null, citation: 'NRS 484B.310', short_title: 'Stop Sign Violations', description: 'Failure to stop at a stop sign', definition: 'Driver must stop at the limit line, crosswalk, or entrance to the intersecting roadway, whichever is first encountered.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B127', subsection: null, citation: 'NRS 484B.127', short_title: 'Handheld Device While Driving', description: 'Using a handheld wireless communications device while driving', definition: 'Elements: (1) Drives a motor vehicle; (2) uses a handheld wireless device (holding, talking, texting). Hands-free allowed. First offense: $50. Second: $100. Third+: $250.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B350', subsection: null, citation: 'NRS 484B.350', short_title: 'School Bus - Failure to Stop', description: 'Failing to stop for a school bus displaying flashing red lights', definition: 'All traffic must stop when school bus displays flashing red lights and stop arm. May not proceed until bus resumes motion or driver signals. Fine: $250-$500.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 250 },
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'B443', subsection: null, citation: 'NRS 484B.443', short_title: 'Move Over Law', description: 'Failure to yield or slow down for emergency or maintenance vehicles on the roadside', definition: 'When approaching stopped emergency vehicle with lights flashing: must change to non-adjacent lane if safe, otherwise reduce speed to safe level. Extends to tow trucks and maintenance vehicles.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },

  // Registration / License / Insurance
  { state: 'NV', state_name: 'Nevada', title: 482, chapter: 482, section: '385', subsection: null, citation: 'NRS 482.385', short_title: 'Vehicle Registration Required', description: 'Every motor vehicle operated on Nevada highways must be registered with the DMV', definition: 'All motor vehicles operated on public highways must be registered. Registration renewed annually. Emissions testing required in Clark and Washoe counties.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 100 },
  { state: 'NV', state_name: 'Nevada', title: 483, chapter: 483, section: '230', subsection: null, citation: 'NRS 483.230', short_title: 'Drivers License Required', description: 'No person shall drive a motor vehicle on Nevada highways without a valid drivers license', definition: 'Must possess valid Nevada drivers license or valid license from another jurisdiction. Must have license in immediate possession while driving.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 200 },
  { state: 'NV', state_name: 'Nevada', title: 483, chapter: 483, section: '560', subsection: null, citation: 'NRS 483.560', short_title: 'Driving While Suspended/Revoked', description: 'Operating a motor vehicle while license is suspended or revoked', definition: 'Elements: (1) Operates motor vehicle; (2) while license suspended or revoked. Misdemeanor: up to 6 months and/or $500. If DUI-related suspension: 30 days to 6 months.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 500 },
  { state: 'NV', state_name: 'Nevada', title: 485, chapter: 485, section: '187', subsection: null, citation: 'NRS 485.187', short_title: 'Liability Insurance Required', description: 'Every motor vehicle registered in Nevada must maintain liability insurance', definition: 'Minimum coverage: $25,000 bodily injury per person, $50,000 per accident, $20,000 property damage. Proof of insurance required when registering. Uninsured vehicle: registration suspended.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Insurance', citation_fine: 250 },

  // Equipment
  { state: 'NV', state_name: 'Nevada', title: 484, chapter: 484, section: 'D495', subsection: null, citation: 'NRS 484D.495', short_title: 'Seatbelt Violations', description: 'Failure to wear a seatbelt while operating or riding in a motor vehicle', definition: 'Driver and all passengers must wear seatbelts. Children under 6 and under 60 lbs must be in approved child restraint. Secondary enforcement. Fine: $25.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 25 },
];
