// ============================================================
// RMPG Flex — New Mexico Statutes Annotated (NMSA)
// ============================================================
// Chapter 30: Criminal Offenses | Chapter 66: Motor Vehicles
// Offense levels mapped to Utah enum for UI compatibility:
//   NM Capital Felony → first_degree_felony (death/life)
//   NM First Degree Felony → first_degree_felony
//   NM Second Degree Felony → second_degree_felony
//   NM Third Degree Felony → third_degree_felony
//   NM Fourth Degree Felony → third_degree_felony
//   NM Misdemeanor → class_a_misdemeanor
//   NM Petty Misdemeanor → class_b_misdemeanor
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const NEW_MEXICO_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // CHAPTER 30 — CRIMINAL OFFENSES
  // ────────────────────────────────────────────────────────────

  // ── Article 1: General Provisions ──────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 1, section: '1', subsection: null, citation: 'NMSA 30-1-1', short_title: 'Short Title', description: 'Chapter 30 NMSA governing criminal offenses in New Mexico', definition: 'New Mexico Criminal Code. Chapter 30 defines criminal offenses, defenses, and penalties for the State of New Mexico.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NM', state_name: 'New Mexico', title: 31, chapter: 18, section: '12', subsection: null, citation: 'NMSA 31-18-12', short_title: 'Classification of Felonies', description: 'Felony classification and basic sentencing: first degree (18 yrs), second degree (9 yrs), third degree (3 yrs), fourth degree (18 months)', definition: 'First degree felony: basic sentence 18 years. Second degree: 9 years. Third degree: 3 years. Fourth degree: 18 months. Capital felony: death or life. New Mexico abolished the death penalty in 2009 but life without parole remains for some crimes.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NM', state_name: 'New Mexico', title: 31, chapter: 19, section: '1', subsection: null, citation: 'NMSA 31-19-1', short_title: 'Misdemeanor Sentencing', description: 'Misdemeanor: up to 364 days and/or $1,000. Petty misdemeanor: up to 6 months and/or $500', definition: 'Misdemeanor: up to 364 days county jail and/or $1,000 fine. Petty misdemeanor: up to 6 months and/or $500. New Mexico does not use lettered or numbered misdemeanor classes.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 28, section: '1', subsection: null, citation: 'NMSA 30-28-1', short_title: 'Attempt', description: 'Attempting to commit a felony by performing an act which tends toward but fails to complete the crime', definition: 'Elements: (1) Performs an overt act; (2) tending but failing to effect commission of the crime; (3) with specific intent to commit the crime. Punishment: one degree lower than completed felony. Attempt to commit misdemeanor is a petty misdemeanor.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 28, section: '2', subsection: null, citation: 'NMSA 30-28-2', short_title: 'Conspiracy', description: 'Agreement between two or more persons to commit a felony with an overt act', definition: 'Elements: (1) Two or more persons agree; (2) with intent to commit a felony; (3) one or more commits an overt act in furtherance. Punishment: one degree lower than underlying felony.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 28, section: '3', subsection: null, citation: 'NMSA 30-28-3', short_title: 'Solicitation', description: 'Soliciting, commanding, or inducing another to commit a felony with intent that it be committed', definition: 'Elements: (1) Solicits, commands, or induces; (2) another person; (3) to commit a felony; (4) with specific intent that the felony be committed. Third degree felony regardless of underlying crime.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'General Provisions' },

  // ── Article 2: Homicide ────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 2, section: '1', subsection: 'A', citation: 'NMSA 30-2-1(A)', short_title: 'First Degree Murder', description: 'Willful, deliberate and premeditated killing, or killing during commission of enumerated felonies', definition: 'Elements: (1) Willful, deliberate, and premeditated killing; OR (2) killing during commission/attempt of arson, sexual penetration, robbery, burglary, kidnapping, child abuse, CSP. Capital felony (life imprisonment since death penalty abolished in 2009).', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 2, section: '1', subsection: 'B', citation: 'NMSA 30-2-1(B)', short_title: 'Second Degree Murder', description: 'Killing of a human being without lawful justification or excuse, when acting with knowledge that conduct is a strong probability of death or great harm', definition: 'Elements: (1) Killing of a human being; (2) without lawful justification; (3) knowing acts create a strong probability of death or great bodily harm. Also: depraved mind murder (utter disregard for human life). Second degree felony: basic sentence 15 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 2, section: '3', subsection: null, citation: 'NMSA 30-2-3', short_title: 'Voluntary Manslaughter', description: 'Killing upon sufficient provocation or committed in the heat of passion', definition: 'Elements: (1) Killing of a human being; (2) upon sufficient provocation; (3) in the heat of passion. A killing that would otherwise be murder but for sufficient provocation. Third degree felony: basic sentence 6 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 2, section: '3', subsection: 'B', citation: 'NMSA 30-2-3(B)', short_title: 'Involuntary Manslaughter', description: 'Killing of a human being without any design to effect death, during commission of an unlawful act or by negligence', definition: 'Elements: (1) Killing of human being; (2) without design to cause death; (3) during commission of a lawful act with insufficient caution, or unlawful act not amounting to felony. Fourth degree felony: basic sentence 18 months.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '101.1', subsection: null, citation: 'NMSA 66-8-101.1', short_title: 'Vehicular Homicide', description: 'Causing death of another by operating a vehicle while under the influence of alcohol or drugs', definition: 'Elements: (1) Operation of a motor vehicle; (2) while under the influence (DUI); (3) proximately causing death. Third degree felony: basic sentence 6 years. Separate from homicide by vehicle (reckless driving).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '101', subsection: null, citation: 'NMSA 66-8-101', short_title: 'Homicide by Vehicle', description: 'Causing death by the unlawful operation of a motor vehicle due to negligence or recklessness', definition: 'Elements: (1) Operates a motor vehicle; (2) in a negligent or reckless manner; (3) proximately causes death. If great bodily harm: third degree felony. If death: third degree felony (basic sentence 3 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Homicide' },

  // ── Article 3: Assault ─────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '1', subsection: null, citation: 'NMSA 30-3-1', short_title: 'Assault', description: 'An attempt to commit a battery upon the person of another, or any unlawful act threatening injury', definition: 'Elements: (1) Attempt to commit a battery; OR (2) unlawful act, threat, or menacing conduct causing another to reasonably believe in danger of receiving immediate battery. Petty misdemeanor: up to 6 months and/or $500.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '2', subsection: null, citation: 'NMSA 30-3-2', short_title: 'Aggravated Assault', description: 'Unlawfully assaulting or striking at another with a deadly weapon, or committing assault with intent to commit a felony', definition: 'Elements: (1) Assaults or strikes at another; (2) with a deadly weapon; OR (3) with intent to commit any felony. Fourth degree felony: basic sentence 18 months.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '4', subsection: null, citation: 'NMSA 30-3-4', short_title: 'Battery', description: 'Unlawful, intentional touching or application of force to the person of another', definition: 'Elements: (1) Unlawful; (2) intentional touching or application of force; (3) to the person of another; (4) when done in a rude, insolent, or angry manner. Petty misdemeanor: up to 6 months and/or $500.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '5', subsection: null, citation: 'NMSA 30-3-5', short_title: 'Aggravated Battery', description: 'Unlawfully touching or applying force with intent to injure, causing great bodily harm or using a deadly weapon', definition: 'Elements: (1) Unlawful touching or application of force; (2) with intent to injure; (3) causing great bodily harm; OR (4) with a deadly weapon or dangerous instrument. Great bodily harm: third degree felony (3 yrs). Deadly weapon: third degree felony.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '9', subsection: null, citation: 'NMSA 30-3-9', short_title: 'Assault on Peace Officer', description: 'Assaulting or battering a peace officer, correctional officer, or health care worker performing official duties', definition: 'Elements: (1) Assault or battery; (2) upon a peace officer, detention officer, or health care worker; (3) while performing official duties. Assault: misdemeanor (364 days). Battery: fourth degree felony (18 months).', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },

  // ── Sexual Offenses ────────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 9, section: '11', subsection: null, citation: 'NMSA 30-9-11', short_title: 'Criminal Sexual Penetration', description: 'The unlawful and intentional causing of penetration of another by force, coercion, or when victim cannot consent', definition: 'CSP in first degree: penetration by force/coercion resulting in personal injury + deadly weapon or accomplices (1st degree felony, 18 yrs). Second degree: force/coercion with personal injury, OR victim under 13 (2nd degree, 15 yrs). Third degree: force/coercion without injury (3rd degree, 6 yrs). Fourth degree: position of authority (4th degree, 18 months).', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },

  // ── Kidnapping ─────────────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 4, section: '1', subsection: null, citation: 'NMSA 30-4-1', short_title: 'Kidnapping', description: 'Taking, restraining, or confining another by force, intimidation, or deception with intent to hold for ransom or service', definition: 'Elements: (1) Takes, restrains, transports, or confines; (2) by force, intimidation, or deception; (3) with intent to hold for ransom, as hostage, to facilitate felony, to inflict harm, or to terrorize. First degree felony: basic sentence 18 years. If victim freed unharmed: second degree felony.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },

  // ── Property Offenses ──────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '3', subsection: null, citation: 'NMSA 30-16-3', short_title: 'Burglary', description: 'Unauthorized entry into any building or structure with intent to commit a felony or theft therein', definition: 'Elements: (1) Unauthorized entry; (2) into any vehicle, watercraft, aircraft, dwelling, or other structure; (3) with intent to commit any felony or theft therein. Non-dwelling: fourth degree felony (18 months). Dwelling (residential): third degree felony (3 years).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Burglary' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '2', subsection: null, citation: 'NMSA 30-16-2', short_title: 'Robbery', description: 'Taking anything of value from person or immediate control of another by force or violence or threat', definition: 'Elements: (1) Theft of anything of value; (2) from the person of another or his immediate control/presence; (3) by use or threatened use of force or violence. Third degree felony: basic sentence 3 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '2', subsection: 'B', citation: 'NMSA 30-16-2(B)', short_title: 'Aggravated Robbery', description: 'Robbery committed while armed with a deadly weapon', definition: 'Elements: (1) Commits robbery; (2) while armed with a deadly weapon. Second degree felony: basic sentence 9 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '1', subsection: null, citation: 'NMSA 30-16-1', short_title: 'Larceny (Theft)', description: 'Intentionally taking, receiving, or concealing property of another with intent to permanently deprive', definition: 'Elements: (1) Takes, obtains, or exercises control over; (2) anything of value; (3) of another; (4) with intent to deprive permanently. Over $20,000: 2nd degree felony. $2,500-$20,000: 3rd degree. $500-$2,500: 4th degree. Under $500: misdemeanor. Under $250: petty misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '20', subsection: null, citation: 'NMSA 30-16-20', short_title: 'Motor Vehicle Theft', description: 'Taking a motor vehicle or motor vehicle part without consent of the owner with intent to deprive permanently or temporarily', definition: 'Unauthorized taking of motor vehicle: (1) Permanently: third degree felony (3 years); (2) Temporarily (joyriding): fourth degree felony (18 months). Also applies to motorcycles, ATVs, and other motorized vehicles.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '24.1', subsection: null, citation: 'NMSA 30-16-24.1', short_title: 'Identity Theft', description: 'Willfully obtaining, recording, or transferring personal identifying information of another with intent to defraud', definition: 'Elements: (1) Willfully obtains, records, or transfers; (2) personal identifying information; (3) of another person; (4) without authorization; (5) with intent to defraud. Fourth degree felony: basic sentence 18 months.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 16, section: '10', subsection: null, citation: 'NMSA 30-16-10', short_title: 'Forgery', description: 'Falsely making or altering any writing with intent to injure or defraud', definition: 'Elements: (1) Falsely makes, alters, or forges; (2) any written instrument; (3) with intent to injure or defraud. Third degree felony: basic sentence 3 years. Uttering (passing forged instrument): same penalty.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 15, section: '1', subsection: null, citation: 'NMSA 30-15-1', short_title: 'Criminal Damage to Property', description: 'Intentionally damaging any real or personal property of another', definition: 'Elements: (1) Intentionally; (2) damages; (3) real or personal property; (4) of another. Over $1,000: fourth degree felony. Under $1,000: misdemeanor. Under $500: petty misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Property Damage' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 14, section: '1', subsection: null, citation: 'NMSA 30-14-1', short_title: 'Criminal Trespass', description: 'Knowingly entering or remaining upon the lands of another after being notified to depart', definition: 'Elements: (1) Knowingly; (2) entering or remaining upon; (3) lands or premises of another; (4) after being notified not to enter by owner or posted signs. If dwelling: misdemeanor (364 days). If land: petty misdemeanor (6 months).', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Trespass' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 17, section: '5', subsection: null, citation: 'NMSA 30-17-5', short_title: 'Arson', description: 'Willfully and maliciously setting fire to any building, structure, or property', definition: 'Elements: (1) Willfully and maliciously; (2) sets fire to or causes to be burned; (3) any building, structure, forest, or property. Dwelling: third degree felony (3 yrs). Other structure: fourth degree felony (18 months). Other property: misdemeanor.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Arson' },

  // ── Domestic Violence ──────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '12', subsection: null, citation: 'NMSA 30-3-12', short_title: 'Domestic Violence - Assault', description: 'Assault against a household member', definition: 'Elements: (1) Assault (attempt or threat); (2) against a household member (spouse, ex-spouse, cohabitant, co-parent, family member, dating partner). Petty misdemeanor: up to 6 months. Enhanced if prior DV: misdemeanor, then fourth degree felony.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '15', subsection: null, citation: 'NMSA 30-3-15', short_title: 'Battery Against Household Member', description: 'Battery committed against a household member', definition: 'Elements: (1) Battery (unlawful touching/force); (2) against a household member. First offense: petty misdemeanor. Prior DV within 2 years: misdemeanor. Second prior within 3 years: fourth degree felony (18 months).', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: '16', subsection: null, citation: 'NMSA 30-3-16', short_title: 'Aggravated Battery Against Household Member', description: 'Battery against a household member causing great bodily harm or using a deadly weapon', definition: 'Elements: (1) Battery; (2) against household member; (3) causing great bodily harm; OR (4) with a deadly weapon. Third degree felony: basic sentence 3 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 3, section: 'A3', subsection: null, citation: 'NMSA 30-3A-3', short_title: 'Stalking', description: 'Knowingly pursuing a pattern of conduct directed at a specific person that would cause a reasonable person to feel frightened', definition: 'Elements: (1) Knowingly pursues a pattern of conduct; (2) directed at specific person; (3) would cause reasonable person to feel frightened, intimidated, or threatened. Misdemeanor. Aggravated (threats, violation of order, prior conviction): fourth degree felony.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Weapons ────────────────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 7, section: '2', subsection: null, citation: 'NMSA 30-7-2', short_title: 'Unlawful Carrying of a Deadly Weapon', description: 'Carrying a concealed loaded firearm or deadly weapon on or about the person or in a vehicle in a municipality', definition: 'New Mexico requires a concealed carry license for carrying concealed loaded firearms in municipalities. Open carry is legal without permit. Carrying concealed without license: petty misdemeanor. Prohibited locations: schools, courts, establishments selling liquor. New Mexico recognizes licenses from states with similar requirements.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Weapons' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 7, section: '16', subsection: null, citation: 'NMSA 30-7-16', short_title: 'Felon in Possession of Firearm', description: 'A person convicted of a felony who possesses a firearm or destructive device', definition: 'Elements: (1) Convicted of a felony; (2) possesses, transports, or receives; (3) any firearm or destructive device. Fourth degree felony: basic sentence 18 months.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },

  // ── Drug Offenses ──────────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 31, section: '23', subsection: null, citation: 'NMSA 30-31-23', short_title: 'Possession of Controlled Substance', description: 'Knowingly possessing a controlled substance without valid prescription or order', definition: 'Elements: (1) Knowingly; (2) possesses; (3) a controlled substance; (4) without valid prescription. First offense: misdemeanor (364 days and/or $1,000). Subsequent: fourth degree felony (18 months). New Mexico decriminalized small amounts of marijuana in 2021 (Cannabis Regulation Act).', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Drugs' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 31, section: '20', subsection: null, citation: 'NMSA 30-31-20', short_title: 'Trafficking Controlled Substance', description: 'Manufacturing, distributing, or possessing with intent to distribute a controlled substance', definition: 'Elements: (1) Manufactures, distributes, or possesses with intent to distribute; (2) a controlled substance. Penalty based on schedule and quantity. Schedule I/II: second degree felony (9 years). Schedule III/IV: third degree felony (3 years). Trafficking amounts have mandatory minimums.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'NM', state_name: 'New Mexico', title: 26, chapter: 2, section: 'C', subsection: null, citation: 'NMSA 26-2C-25', short_title: 'Cannabis Regulation Act', description: 'Legal recreational cannabis for adults 21+ (effective June 2021)', definition: 'New Mexico legalized recreational cannabis (21+) via the Cannabis Regulation Act (2021). Legal: up to 2 oz flower, 16g extract, 800mg edibles. Home grow: up to 6 mature plants (12 per household). Prohibited: public consumption, driving under influence, sale without license.', offense_level: null, category: 'criminal', subcategory: 'Drugs' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 31, section: '25.1', subsection: null, citation: 'NMSA 30-31-25.1', short_title: 'Drug Paraphernalia', description: 'Use or possession with intent to use drug paraphernalia to introduce a controlled substance', definition: 'Elements: (1) Uses or possesses with intent to use; (2) drug paraphernalia; (3) to inject, ingest, inhale, or otherwise introduce a controlled substance (excluding cannabis for personal use). Petty misdemeanor: up to 6 months and/or $100.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Drugs' },

  // ── Public Order ───────────────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 20, section: '1', subsection: null, citation: 'NMSA 30-20-1', short_title: 'Disorderly Conduct', description: 'Engaging in violent, abusive, indecent, profane, boisterous, unreasonably loud, or otherwise disorderly conduct', definition: 'Elements: (1) Engages in violent, abusive, indecent, profane, boisterous, unreasonably loud, or disorderly conduct; (2) which tends to disturb the peace. Petty misdemeanor: up to 6 months and/or $500.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 22, section: '1', subsection: null, citation: 'NMSA 30-22-1', short_title: 'Resisting, Evading or Obstructing Officer', description: 'Willfully resisting, evading, or obstructing a peace officer in performance of duties', definition: 'Elements: (1) Knowingly; (2) resists, evades, or obstructs; (3) any officer of the state while in the lawful discharge of duties. Misdemeanor: up to 364 days and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },

  // ── Crimes Against Children ────────────────────────────────
  { state: 'NM', state_name: 'New Mexico', title: 30, chapter: 6, section: '1', subsection: null, citation: 'NMSA 30-6-1', short_title: 'Child Abuse', description: 'Intentionally, knowingly, recklessly, or negligently causing a child to be placed in a situation endangering life or health', definition: 'Elements: (1) Intentionally, knowingly, recklessly, or negligently; (2) causes or permits; (3) a child to be placed in a situation; (4) that may endanger life or health. No harm: third degree felony. Harm: second degree felony. Great bodily harm: first degree felony. Death: first degree felony (life).', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Crimes Against Children' },

  // ────────────────────────────────────────────────────────────
  // CHAPTER 66 — MOTOR VEHICLES
  // ────────────────────────────────────────────────────────────

  // DUI
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '102', subsection: null, citation: 'NMSA 66-8-102', short_title: 'DUI - Driving Under the Influence', description: 'Operating a motor vehicle while under the influence of intoxicating liquor or drugs (BAC .08+)', definition: 'Elements: (1) Drives a vehicle; (2) while under the influence of intoxicating liquor or drug; OR (3) BAC 0.08% or more. First offense: up to 90 days jail, $500 fine, 1 year license revocation, IID. Second within 10 years: 96 hrs to 364 days, $500-$1,000. Third: 30 days to 364 days, $750-$1,000.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 500 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '102', subsection: 'D', citation: 'NMSA 66-8-102(D)', short_title: 'Aggravated DUI', description: 'DUI with BAC of 0.16 or higher, or causing great bodily harm or death', definition: 'Aggravated DUI: (1) BAC 0.16 or higher; (2) refusal to submit to chemical test; (3) DUI causing bodily injury. Enhanced penalties: mandatory 48 hrs jail (first), mandatory 96 hrs (second), mandatory 60 days (third). All with mandatory IID.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 1000 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '102', subsection: 'F', citation: 'NMSA 66-8-102(F)', short_title: 'DUI - Fourth Offense (Felony)', description: 'Fourth or subsequent DUI offense is a fourth degree felony', definition: 'Fourth or subsequent DUI: fourth degree felony. Basic sentence 18 months. Mandatory minimum 6 months jail. Lifetime license revocation with potential restricted license after 5 years.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'DUI', citation_fine: 5000 },

  // Moving Violations
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '301', subsection: null, citation: 'NMSA 66-7-301', short_title: 'Speeding', description: 'Driving in excess of posted speed limits', definition: 'Speed limits: Residential 15 mph (school zone), 30 mph (residential), Business 25 mph, Highway 55 mph, Interstate 75 mph (or posted). Fine schedule varies by jurisdiction, typically $25-$150 base.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 8, section: '113', subsection: null, citation: 'NMSA 66-8-113', short_title: 'Reckless Driving', description: 'Driving in willful or wanton disregard for the safety of persons or property', definition: 'Elements: (1) Drives any vehicle; (2) carelessly and heedlessly; (3) in willful or wanton disregard; (4) of rights or safety of others; (5) endangering person or property. Misdemeanor: 5-90 days and/or $25-$300.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 200 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '332', subsection: null, citation: 'NMSA 66-7-332', short_title: 'Eluding Officer', description: 'Willfully and intentionally fleeing from a peace officer who has signaled the driver to stop', definition: 'Elements: (1) Willfully and intentionally; (2) flees, attempts to elude, or evades; (3) a peace officer; (4) after receiving a visual or audible signal to stop. Fourth degree felony: basic sentence 18 months. If injury or death results: third degree felony.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 2000 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '201', subsection: null, citation: 'NMSA 66-7-201', short_title: 'Hit and Run - Property', description: 'Leaving the scene of an accident involving property damage without stopping and providing information', definition: 'Elements: (1) Involved in accident; (2) property damage; (3) fails to stop, give name/address/registration, and exhibit drivers license. Misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 300 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '201', subsection: 'A', citation: 'NMSA 66-7-201(A)', short_title: 'Hit and Run - Injury/Death', description: 'Leaving the scene of an accident involving injury or death', definition: 'Elements: (1) Involved in accident; (2) personal injury or death; (3) fails to stop, give information, and render aid. If injury: misdemeanor (90 days to 364 days). If death: fourth degree felony (18 months).', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 5000 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '104', subsection: null, citation: 'NMSA 66-7-104', short_title: 'Traffic Signal Violations', description: 'Failure to obey traffic signals and control devices', definition: 'Drivers must obey all traffic-control signals. Steady red: stop. Right on red after stop (unless prohibited). Green: proceed when safe.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '345', subsection: null, citation: 'NMSA 66-7-345', short_title: 'Stop Sign Violations', description: 'Failure to stop at a stop sign', definition: 'Driver must come to a complete stop at the limit line, crosswalk, or entrance to the intersecting roadway.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '318', subsection: null, citation: 'NMSA 66-7-318', short_title: 'Following Too Closely', description: 'Following another vehicle more closely than is reasonable and prudent', definition: 'Driver shall not follow more closely than is reasonable and prudent, considering speed, traffic, and road conditions.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '374', subsection: null, citation: 'NMSA 66-7-374', short_title: 'Handheld Device While Driving', description: 'Using a handheld mobile device while operating a motor vehicle', definition: 'Elements: (1) Operates motor vehicle; (2) uses handheld mobile telecommunications device (talking, texting). Hands-free allowed. First: $25-$50. Second: $50-$100. Third+: $75-$200.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '352', subsection: null, citation: 'NMSA 66-7-352', short_title: 'School Bus - Failure to Stop', description: 'Failing to stop for a school bus displaying flashing red lights', definition: 'All vehicles must stop when school bus displays flashing red lights and stop arm. May not pass until bus resumes motion. Fine: up to $500.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 500 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '332.1', subsection: null, citation: 'NMSA 66-7-332.1', short_title: 'Move Over Law', description: 'Failure to move over or slow down for emergency or utility vehicles on the roadside', definition: 'When approaching stopped emergency vehicle with lights: must change to non-adjacent lane if safe, otherwise reduce speed. Extends to utility, tow, and maintenance vehicles. Misdemeanor.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 100 },

  // Registration / License / Insurance
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 3, section: '1', subsection: null, citation: 'NMSA 66-3-1', short_title: 'Vehicle Registration Required', description: 'Every motor vehicle operated on New Mexico highways must be registered with MVD', definition: 'All motor vehicles operated on public roads must be registered with New Mexico Motor Vehicle Division. Registration valid for 1-2 years depending on vehicle type.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 100 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 5, section: '2', subsection: null, citation: 'NMSA 66-5-2', short_title: 'Drivers License Required', description: 'No person shall operate a motor vehicle on New Mexico highways without a valid drivers license', definition: 'Must possess valid New Mexico drivers license or valid license from another jurisdiction. Must have license in possession while driving. New Mexico issues licenses to all residents regardless of immigration status.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 100 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 5, section: '39', subsection: null, citation: 'NMSA 66-5-39', short_title: 'Driving While Suspended/Revoked', description: 'Operating a motor vehicle while license is suspended or revoked', definition: 'Elements: (1) Operates motor vehicle; (2) while license suspended, revoked, or denied. Misdemeanor: up to 364 days and/or $300-$1,000.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 500 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 5, section: '205', subsection: null, citation: 'NMSA 66-5-205', short_title: 'Liability Insurance Required', description: 'Every owner of a motor vehicle registered in New Mexico must maintain financial responsibility', definition: 'Minimum coverage: $25,000 bodily injury per person, $50,000 per accident, $10,000 property damage. Proof must be in vehicle and shown on demand or at traffic stops.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Insurance', citation_fine: 300 },

  // Equipment
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 7, section: '372', subsection: null, citation: 'NMSA 66-7-372', short_title: 'Seatbelt Violations', description: 'Failure to wear a seatbelt while operating or riding in a motor vehicle', definition: 'Driver and all passengers must wear seatbelts. Children under 7 or under 60 lbs must be in child restraint. Primary enforcement. Fine: $25.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 25 },
  { state: 'NM', state_name: 'New Mexico', title: 66, chapter: 3, section: '801', subsection: null, citation: 'NMSA 66-3-801', short_title: 'Headlight Violations', description: 'Failure to display headlights during required hours or conditions', definition: 'Headlights required from sunset to sunrise and when visibility less than 500 feet due to weather. Must use low beams within 500 feet of oncoming traffic.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 25 },
];
