// ============================================================
// RMPG Flex — Wyoming Statutes (WS)
// ============================================================
// Title 6: Crimes & Offenses | Title 31: Motor Vehicles
// Offense levels mapped to Utah enum for UI compatibility:
//   WY felony (life) → first_degree_felony
//   WY felony (≥5 yrs) → second_degree_felony
//   WY felony (≤5 yrs) → third_degree_felony
//   WY high misdemeanor → class_a_misdemeanor
//   WY misdemeanor → class_b_misdemeanor
//   WY infraction → infraction
// ============================================================

import type { StatuteSeed } from './utahStatutes';

export const WYOMING_STATUTES: StatuteSeed[] = [
  // ────────────────────────────────────────────────────────────
  // TITLE 6 — CRIMES AND OFFENSES
  // ────────────────────────────────────────────────────────────

  // ── Chapter 1: General Provisions ──────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '101', subsection: null, citation: 'WS 6-1-101', short_title: 'Short Title', description: 'Title 6 of Wyoming Statutes governs all crimes and offenses', definition: 'Wyoming Criminal Code. Title 6 defines criminal offenses, penalties, and procedures for the State of Wyoming.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '104', subsection: null, citation: 'WS 6-1-104', short_title: 'Classification of Offenses', description: 'Offenses classified as felonies (punishable by death or imprisonment in state penitentiary) or misdemeanors', definition: 'Felony: punishable by death or imprisonment in the state penitentiary for any period. Misdemeanor: punishable by fine and/or imprisonment in a county jail for not more than one year. Wyoming does not use numbered felony/misdemeanor classes.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '109', subsection: null, citation: 'WS 6-1-109', short_title: 'Accessory Before the Fact', description: 'A person who counsels, encourages, hires, commands, or procures another to commit a felony is punishable as a principal', definition: 'Elements: (1) Counseled, encouraged, hired, commanded, or procured commission of a felony; (2) another person committed the felony. Punished same as principal.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '301', subsection: null, citation: 'WS 6-1-301', short_title: 'Attempt', description: 'A person is guilty of attempt when with intent to commit a specific crime he does any act which constitutes a substantial step', definition: 'Elements: (1) Intent to commit a specific crime; (2) an act constituting a substantial step toward commission. Attempt to commit a felony punishable by imprisonment for not more than half the maximum term for the completed offense.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '302', subsection: null, citation: 'WS 6-1-302', short_title: 'Conspiracy', description: 'Agreement between two or more persons to commit a crime with an overt act in furtherance', definition: 'Elements: (1) Agreement between two or more persons to commit a crime; (2) one or more of them does an overt act in furtherance. Punishable the same as the underlying crime.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 1, section: '303', subsection: null, citation: 'WS 6-1-303', short_title: 'Solicitation', description: 'Commanding, entreating, or attempting to persuade another person to commit a felony', definition: 'Elements: (1) With intent that a felony be committed; (2) commands, entreats, or attempts to persuade another person to commit the felony. Class of underlying felony minus one degree.', offense_level: null, category: 'criminal', subcategory: 'General Provisions' },

  // ── Chapter 2: Offenses Against the Person ─────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '101', subsection: 'a', citation: 'WS 6-2-101(a)', short_title: 'Murder - First Degree', description: 'Purposely and with premeditated malice killing a human being', definition: 'Elements: (1) Purposely; (2) with premeditated malice; (3) kills another human being. Also includes killing during perpetration of certain felonies (felony murder). Penalty: death or life imprisonment.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '104', subsection: null, citation: 'WS 6-2-104', short_title: 'Murder - Second Degree', description: 'Purposely and maliciously but without premeditation killing a human being', definition: 'Elements: (1) Purposely; (2) maliciously; (3) without premeditation; (4) kills another human being. Penalty: 20 years to life imprisonment.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '105', subsection: null, citation: 'WS 6-2-105', short_title: 'Manslaughter', description: 'Unlawfully killing a human being without malice, expressed or implied', definition: 'Elements: (1) Unlawful killing; (2) without malice; (3) voluntary (heat of passion with adequate provocation) or involuntary (reckless conduct). Penalty: not more than 20 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '106', subsection: null, citation: 'WS 6-2-106', short_title: 'Homicide by Vehicle', description: 'Causing death of another by unlawful or reckless operation of a motor vehicle', definition: 'Elements: (1) Operates a motor vehicle; (2) in an unlawful manner or while under the influence; (3) causes death of another. Penalty: not more than 20 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Homicide' },

  // Assault
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '501', subsection: 'a', citation: 'WS 6-2-501(a)', short_title: 'Simple Assault', description: 'Attempting to cause or intentionally, knowingly, or recklessly causing bodily injury to another', definition: 'Elements: (1) Attempts to cause, or intentionally, knowingly, or recklessly causes; (2) bodily injury to another; OR threatens another with bodily injury. Misdemeanor: not more than 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '501', subsection: 'b', citation: 'WS 6-2-501(b)', short_title: 'Assault - Bodily Injury', description: 'Intentionally, knowingly, or recklessly causing bodily injury to another person', definition: 'Elements: (1) Intentionally, knowingly, or recklessly; (2) causes bodily injury; (3) to another person. Misdemeanor: not more than 1 year and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Assault' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '502', subsection: 'a', citation: 'WS 6-2-502(a)', short_title: 'Aggravated Assault & Battery', description: 'Causing or attempting to cause serious bodily injury intentionally, knowingly, or recklessly under circumstances manifesting extreme indifference', definition: 'Elements: (1) Intentionally, knowingly, or recklessly under circumstances manifesting extreme indifference; (2) causes or attempts to cause serious bodily injury; OR (3) causes bodily injury with a deadly weapon. Felony: not more than 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '503', subsection: null, citation: 'WS 6-2-503', short_title: 'Assault on Peace Officer', description: 'Intentionally, knowingly, or recklessly causing bodily injury to a peace officer acting in official capacity', definition: 'Elements: (1) Intentionally, knowingly, or recklessly; (2) causes bodily injury; (3) to a peace officer, firefighter, or EMT; (4) while engaged in official duties. Felony: not more than 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Assault' },

  // Sexual Offenses
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '301', subsection: 'a', citation: 'WS 6-2-301(a)', short_title: 'Sexual Assault - First Degree', description: 'Sexual intrusion when actor causes submission through physical force, threat, or victim is incapable of consent', definition: 'Elements: (1) Actor causes submission through physical force or fear of physical force; (2) sexual intrusion (penetration). Also includes victim physically helpless, mentally incapacitated, or under 13. Penalty: 5-50 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '302', subsection: null, citation: 'WS 6-2-302', short_title: 'Sexual Assault - Second Degree', description: 'Sexual intrusion when actor is in a position of authority over victim or victim is 13-15 and actor 4+ years older', definition: 'Elements: (1) Sexual intrusion; (2) actor in position of authority or trust over victim. Also includes victim aged 13-15 and actor at least 4 years older. Penalty: 1-20 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '303', subsection: null, citation: 'WS 6-2-303', short_title: 'Sexual Assault - Third Degree', description: 'Sexual contact through force, threat, or when victim cannot consent', definition: 'Elements: (1) Sexual contact (touching intimate parts); (2) through force, threat, or victim incapable of consent. Felony: not more than 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Sexual Offenses' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '304', subsection: null, citation: 'WS 6-2-304', short_title: 'Sexual Assault - Fourth Degree', description: 'Sexual contact when in position of authority over victim', definition: 'Elements: (1) Sexual contact; (2) actor in position of authority over victim. Misdemeanor: not more than 1 year.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Sexual Offenses' },

  // Kidnapping
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '201', subsection: null, citation: 'WS 6-2-201', short_title: 'Kidnapping', description: 'Unlawfully removing or confining a person with intent to hold for ransom, use as hostage, or facilitate commission of a felony', definition: 'Elements: (1) Unlawfully removes from place or unlawfully confines; (2) with intent to hold for ransom/reward, facilitate felony, inflict bodily injury, terrorize, or interfere with government/political function. Penalty: 25 years to life if victim harmed; otherwise up to 25 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Kidnapping' },

  // Domestic Violence
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '511', subsection: null, citation: 'WS 6-2-511', short_title: 'Domestic Battery', description: 'Intentionally, knowingly, or recklessly causing bodily injury to a household member', definition: 'Elements: (1) Intentionally, knowingly, or recklessly; (2) causes bodily injury; (3) to a household member (spouse, former spouse, cohabitant, co-parent). First offense: misdemeanor up to 6 months. Third offense: felony up to 5 years.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '514', subsection: null, citation: 'WS 6-2-514', short_title: 'Stalking', description: 'Engaging in a course of conduct directed at a specific person that would cause a reasonable person to fear for safety', definition: 'Elements: (1) Course of conduct (pattern of acts over time); (2) directed at a specific person; (3) would cause reasonable person to fear for safety or suffer emotional distress. Misdemeanor, felony if violating protection order or prior stalking conviction.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },

  // ── Chapter 3: Property Offenses ───────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '301', subsection: null, citation: 'WS 6-3-301', short_title: 'Arson - First Degree', description: 'Intentionally starting a fire or causing an explosion that damages an occupied structure', definition: 'Elements: (1) Intentionally starts fire or causes explosion; (2) damages an occupied structure. Penalty: not more than 20 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Arson' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '302', subsection: null, citation: 'WS 6-3-302', short_title: 'Arson - Second Degree', description: 'Intentionally starting a fire or causing an explosion that damages any structure or property', definition: 'Elements: (1) Intentionally starts fire or causes explosion; (2) damages any structure or property. Penalty: not more than 10 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Arson' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '301', subsection: 'b', citation: 'WS 6-3-301(b)', short_title: 'Arson - Third Degree', description: 'Recklessly starting a fire or causing an explosion that damages property', definition: 'Elements: (1) Recklessly; (2) starts fire or causes explosion; (3) damages property. Misdemeanor: not more than 1 year.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Arson' },

  // Burglary
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '301', subsection: 'c', citation: 'WS 6-3-301(c)', short_title: 'Burglary', description: 'Entering or remaining in a building or occupied structure without authorization with intent to commit a crime therein', definition: 'Elements: (1) Without authorization; (2) enters or remains in a building or occupied structure; (3) with intent to commit larceny or a felony therein. Penalty: not more than 10 years. If during nighttime or with a deadly weapon: not more than 25 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Burglary' },

  // Robbery
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '401', subsection: null, citation: 'WS 6-2-401', short_title: 'Robbery', description: 'Taking property from another by force, threats, or putting in fear', definition: 'Elements: (1) Intentionally takes property; (2) from person or presence of another; (3) against will; (4) by force, threats, or putting in fear. Penalty: not more than 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Robbery' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '401', subsection: 'c', citation: 'WS 6-2-401(c)', short_title: 'Aggravated Robbery', description: 'Robbery while armed with a deadly weapon or causing serious bodily injury', definition: 'Elements: (1) Commits robbery; (2) while armed with a deadly weapon; OR (3) causes serious bodily injury. Penalty: 5-25 years.', offense_level: 'first_degree_felony', category: 'criminal', subcategory: 'Robbery' },

  // Theft / Larceny
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '402', subsection: 'a', citation: 'WS 6-3-402(a)', short_title: 'Larceny - Felony', description: 'Stealing property valued at $1,000 or more', definition: 'Elements: (1) Takes, obtains, or exercises control over; (2) movable property of another; (3) with intent to deprive; (4) value $1,000 or more. Penalty: not more than 10 years and/or $10,000 fine.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '402', subsection: 'b', citation: 'WS 6-3-402(b)', short_title: 'Larceny - Misdemeanor', description: 'Stealing property valued at less than $1,000', definition: 'Elements: (1) Takes, obtains, or exercises control over; (2) movable property of another; (3) with intent to deprive; (4) value less than $1,000. Misdemeanor: not more than 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '404', subsection: null, citation: 'WS 6-3-404', short_title: 'Theft of Services', description: 'Obtaining services by deception, threat, or false token with intent to avoid payment', definition: 'Elements: (1) Obtains services; (2) by deception, threat, false token, or tampering with meter/device; (3) with intent to avoid payment. Same penalties as larceny based on value.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Theft' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '407', subsection: null, citation: 'WS 6-3-407', short_title: 'Theft of Motor Vehicle', description: 'Unlawfully taking, driving, or using a motor vehicle without the consent of the owner', definition: 'Elements: (1) Takes, drives, or uses; (2) a motor vehicle; (3) without the consent of the owner. Felony: not more than 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Theft' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '414', subsection: null, citation: 'WS 6-3-414', short_title: 'Identity Theft', description: 'Using personal identifying information of another person with intent to defraud', definition: 'Elements: (1) Knowingly uses; (2) personal identifying information of another person; (3) without authorization; (4) with intent to defraud or harm. Felony: not more than 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '601', subsection: null, citation: 'WS 6-3-601', short_title: 'Forgery', description: 'Making, altering, or uttering a false writing with intent to defraud', definition: 'Elements: (1) Makes, completes, alters, or utters; (2) any writing; (3) with intent to defraud or injure anyone. Felony: not more than 10 years.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Fraud' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '201', subsection: null, citation: 'WS 6-3-201', short_title: 'Criminal Trespass', description: 'Entering or remaining on the land or in the building of another without authorization', definition: 'Elements: (1) Enters or remains on land or in building; (2) of another person; (3) knowing not authorized. Misdemeanor: not more than 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Trespass' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '305', subsection: null, citation: 'WS 6-3-305', short_title: 'Criminal Mischief', description: 'Intentionally or knowingly damaging property of another', definition: 'Elements: (1) Intentionally or knowingly; (2) damages or destroys; (3) property of another. If damage ≥$1,000: felony up to 10 years. If <$1,000: misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Property Damage' },

  // ── Chapter 4: Fraud & Deceit ──────────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 3, section: '602', subsection: null, citation: 'WS 6-3-602', short_title: 'Worthless Checks', description: 'Issuing or delivering a check knowing insufficient funds to cover it', definition: 'Elements: (1) Issues or delivers a check; (2) knowing insufficient funds on deposit; (3) with intent to defraud. Over $1,000: felony. Under $1,000: misdemeanor.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Fraud' },

  // ── Chapter 5: Public Order Offenses ────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 6, section: '102', subsection: null, citation: 'WS 6-6-102', short_title: 'Disorderly Conduct', description: 'Unreasonably disturbing the peace by fighting, making unreasonable noise, or creating a hazardous condition', definition: 'Elements: (1) Unreasonably disturbs the peace; (2) by fighting, making unreasonable noise, using abusive language, or creating hazardous/offensive condition. Misdemeanor: not more than 6 months.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 5, section: '204', subsection: null, citation: 'WS 6-5-204', short_title: 'Resisting Arrest', description: 'Intentionally preventing or attempting to prevent a peace officer from making a lawful arrest', definition: 'Elements: (1) Intentionally prevents or attempts to prevent; (2) a peace officer; (3) from effecting a lawful arrest of the actor or another. Misdemeanor: not more than 1 year.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 5, section: '211', subsection: null, citation: 'WS 6-5-211', short_title: 'Interference with Peace Officer', description: 'Knowingly obstructing, impeding, or interfering with a peace officer in the performance of official duty', definition: 'Elements: (1) Knowingly obstructs, impedes, or interferes; (2) with any peace officer; (3) while engaged in lawful performance of official duties. Misdemeanor: not more than 1 year.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Public Order' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 5, section: '301', subsection: null, citation: 'WS 6-5-301', short_title: 'Escape', description: 'Unlawfully removing oneself from official detention or failing to return', definition: 'Elements: (1) Removes self from official detention; (2) without lawful authority. If from felony detention: felony up to 10 years. If from misdemeanor detention: misdemeanor.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Public Order' },

  // ── Chapter 7: Weapons Offenses ────────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 8, section: '101', subsection: null, citation: 'WS 6-8-101', short_title: 'Wearing or Carrying Concealed Weapons', description: 'Wyoming allows concealed carry without permit for residents 21+; restrictions for non-residents and certain locations', definition: 'Wyoming is a constitutional carry state. Residents 21+ may carry concealed firearms without a permit. Non-residents must have valid concealed carry permit from their home state. Prohibited locations include government meetings, schools (without permission), and law enforcement facilities.', offense_level: null, category: 'criminal', subcategory: 'Weapons' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 8, section: '102', subsection: null, citation: 'WS 6-8-102', short_title: 'Felon in Possession of Firearm', description: 'A person convicted of a violent felony or attempt who possesses a firearm', definition: 'Elements: (1) Previously convicted of a violent felony or felony attempt; (2) possesses a firearm. Felony: not more than 3 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 8, section: '104', subsection: null, citation: 'WS 6-8-104', short_title: 'Possession of Deadly Weapon - Intent to Assault', description: 'Possessing a deadly weapon with intent to unlawfully threaten or injure another', definition: 'Elements: (1) Possesses a deadly weapon; (2) with intent to unlawfully threaten the life or physical well-being of another. Felony: not more than 5 years.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Weapons' },

  // ── Drug Offenses ──────────────────────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 35, chapter: 7, section: '1031', subsection: 'a', citation: 'WS 35-7-1031(a)', short_title: 'Possession of Controlled Substance', description: 'Knowingly or intentionally possessing a controlled substance without valid prescription', definition: 'Elements: (1) Knowingly or intentionally; (2) possesses; (3) a controlled substance; (4) without valid prescription. Schedule I/II: felony up to 5 years and/or $5,000. Schedule III-V: misdemeanor up to 1 year and/or $1,000.', offense_level: 'third_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'WY', state_name: 'Wyoming', title: 35, chapter: 7, section: '1031', subsection: 'b', citation: 'WS 35-7-1031(b)', short_title: 'Possession with Intent to Deliver', description: 'Possessing a controlled substance with intent to manufacture or deliver', definition: 'Elements: (1) Knowingly or intentionally; (2) manufactures, delivers, or possesses with intent to deliver; (3) a controlled substance. Felony: up to 10 years and/or $10,000 for Schedule I/II.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'WY', state_name: 'Wyoming', title: 35, chapter: 7, section: '1031', subsection: 'c', citation: 'WS 35-7-1031(c)', short_title: 'Marijuana Possession - Personal Use', description: 'Possessing 3 ounces or less of marijuana for personal use', definition: 'Elements: (1) Possesses; (2) 3 ounces or less of marijuana; (3) for personal use only. Misdemeanor: not more than 12 months and/or $1,000.', offense_level: 'class_a_misdemeanor', category: 'criminal', subcategory: 'Drugs' },
  { state: 'WY', state_name: 'Wyoming', title: 35, chapter: 7, section: '1036', subsection: null, citation: 'WS 35-7-1036', short_title: 'Methamphetamine Manufacturing', description: 'Manufacturing or attempting to manufacture methamphetamine', definition: 'Elements: (1) Manufactures or attempts to manufacture; (2) methamphetamine or precursor chemicals. Felony: up to 20 years and/or $25,000.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Drugs' },
  { state: 'WY', state_name: 'Wyoming', title: 35, chapter: 7, section: '1039', subsection: null, citation: 'WS 35-7-1039', short_title: 'Drug Paraphernalia', description: 'Use or possession of drug paraphernalia', definition: 'Elements: (1) Uses or possesses with intent to use; (2) drug paraphernalia; (3) to plant, propagate, cultivate, grow, harvest, manufacture, compound, convert, produce, process, prepare, test, analyze, pack, repack, store, contain, conceal, inject, ingest, inhale, or otherwise introduce a controlled substance. Misdemeanor: up to 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Drugs' },

  // ── Child Offenses ─────────────────────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 2, section: '503', subsection: 'b', citation: 'WS 6-2-503(b)', short_title: 'Child Abuse', description: 'Intentionally or recklessly causing physical injury to a child under 16 or endangering their health', definition: 'Elements: (1) Intentionally or recklessly; (2) causes physical injury, mental injury, or endangers health; (3) of a child under 16. If serious injury: felony up to 10 years. Otherwise: misdemeanor up to 1 year.', offense_level: 'second_degree_felony', category: 'criminal', subcategory: 'Crimes Against Children' },

  // ── Protection Order Violations ─────────────────────────────
  { state: 'WY', state_name: 'Wyoming', title: 6, chapter: 4, section: '404', subsection: null, citation: 'WS 6-4-404', short_title: 'Violation of Protection Order', description: 'Knowingly violating the terms of a protection order issued under the domestic violence protection order act', definition: 'Elements: (1) Knowingly violates; (2) terms of a protection order; (3) issued under the Wyoming Domestic Violence Protection Order Act. First offense: misdemeanor up to 6 months. Subsequent: up to 1 year or felony.', offense_level: 'class_b_misdemeanor', category: 'criminal', subcategory: 'Domestic Violence' },

  // ────────────────────────────────────────────────────────────
  // TITLE 31 — MOTOR VEHICLES
  // ────────────────────────────────────────────────────────────

  // DUI
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '233', subsection: 'a', citation: 'WS 31-5-233(a)', short_title: 'DUI - Driving Under the Influence', description: 'Operating a motor vehicle while under the influence of alcohol or controlled substances (BAC .08+)', definition: 'Elements: (1) Drives or is in actual physical control; (2) of a motor vehicle; (3) while under the influence of intoxicating liquor to a degree which renders person incapable of safely driving, OR BAC of 0.08% or more. First offense: up to 6 months and/or $750. Second in 10 years: up to 6 months, 7 days mandatory. Third: felony up to 5 years.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'DUI', citation_fine: 750 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '233', subsection: 'b', citation: 'WS 31-5-233(b)', short_title: 'DUI - Third Offense (Felony)', description: 'Third or subsequent DUI within 10 years becomes a felony', definition: 'Elements: (1) Third or subsequent DUI conviction; (2) within 10 years of prior convictions. Felony: not more than 5 years and/or $5,000.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'DUI', citation_fine: 5000 },

  // Speed / Moving Violations
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '301', subsection: null, citation: 'WS 31-5-301', short_title: 'Speeding', description: 'Operating a vehicle in excess of posted speed limits', definition: 'Speed limits: Residential 30 mph, Business 20 mph, Interstate 80 mph (or posted), otherwise 55 mph. 1-5 over: $5/mph. 6-10 over: $7/mph. 11+ over: $10/mph.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '224', subsection: null, citation: 'WS 31-5-224', short_title: 'Reckless Driving', description: 'Driving a vehicle in willful or wanton disregard for the safety of persons or property', definition: 'Elements: (1) Drives a vehicle; (2) in willful or wanton disregard; (3) for safety of persons or property. Misdemeanor: not more than 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 750 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '226', subsection: null, citation: 'WS 31-5-226', short_title: 'Eluding Police', description: 'Willfully failing to stop or attempting to elude a peace officer after receiving a visual or audible signal', definition: 'Elements: (1) Receives a visual or audible signal from peace officer; (2) willfully fails to stop or attempts to elude. Misdemeanor: up to 6 months. If endangering others: felony up to 5 years.', offense_level: 'class_a_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 1000 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '1101', subsection: null, citation: 'WS 31-5-1101', short_title: 'Hit and Run - Attended Vehicle/Property', description: 'Leaving the scene of an accident involving attended property without providing required information', definition: 'Elements: (1) Involved in accident; (2) attended vehicle or property damaged; (3) fails to stop, give name/address/registration, and render aid. Misdemeanor: up to 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 750 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '1102', subsection: null, citation: 'WS 31-5-1102', short_title: 'Hit and Run - Injury/Death', description: 'Leaving the scene of an accident involving injury or death without providing required information and aid', definition: 'Elements: (1) Involved in accident; (2) resulting in injury or death; (3) fails to stop, give information, and render reasonable aid. If death or serious injury: felony up to 5 years.', offense_level: 'third_degree_felony', category: 'vehicle', subcategory: 'Hit and Run', citation_fine: 5000 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '504', subsection: null, citation: 'WS 31-5-504', short_title: 'Traffic Signal Violations', description: 'Failure to obey traffic signals, signs, or control devices', definition: 'Drivers must obey all traffic control signals and devices. Steady red: stop. Steady yellow: caution, stop before intersection if safe. Green: proceed.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '508', subsection: null, citation: 'WS 31-5-508', short_title: 'Stop Sign Violations', description: 'Failure to stop at a stop sign', definition: 'Driver must come to a complete stop at the nearest line, crosswalk, or entering the intersection, whichever is first encountered.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '705', subsection: null, citation: 'WS 31-5-705', short_title: 'Following Too Closely', description: 'Following another vehicle more closely than is reasonable and prudent', definition: 'Driver must maintain sufficient distance from vehicle ahead to allow safe stopping. Following distance must be reasonable given speed, traffic, and road conditions.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '901', subsection: null, citation: 'WS 31-5-901', short_title: 'Improper Passing', description: 'Passing another vehicle in violation of no-passing zones or unsafe conditions', definition: 'Must not pass on the left unless road clearly visible and free of oncoming traffic for sufficient distance. Passing prohibited where signs or markings prohibit.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 50 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '1205', subsection: null, citation: 'WS 31-5-1205', short_title: 'Texting While Driving', description: 'Using a wireless communication device to write, send, or read text-based communication while driving', definition: 'Elements: (1) Drives a motor vehicle; (2) uses wireless communication device to compose, send, or read text/email/instant message. Exceptions: emergency, GPS, hands-free. Fine: $75 first, $150 subsequent.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 75 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '956', subsection: null, citation: 'WS 31-5-956', short_title: 'School Bus - Failure to Stop', description: 'Failing to stop for a school bus with red lights flashing and stop arm extended', definition: 'All traffic on both sides must stop when school bus activates red lights and stop arm. Exceptions: divided highway, opposite direction on 4+ lane road. Fine: up to $750.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'Moving Violations', citation_fine: 750 },

  // Registration / License / Insurance
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 2, section: '201', subsection: null, citation: 'WS 31-2-201', short_title: 'Vehicle Registration Required', description: 'Every motor vehicle operated on Wyoming highways must be registered with the county treasurer', definition: 'All motor vehicles operated on public highways must be registered. Registration must be renewed annually. Temporary permits available for new purchases.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Registration', citation_fine: 100 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 7, section: '101', subsection: null, citation: 'WS 31-7-101', short_title: 'Drivers License Required', description: 'No person shall drive a motor vehicle on Wyoming highways without a valid drivers license', definition: 'Must possess valid Wyoming drivers license or valid license from another state. License must be carried while driving and displayed on demand.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 200 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 7, section: '128', subsection: null, citation: 'WS 31-7-128', short_title: 'Driving While Suspended', description: 'Operating a motor vehicle while license is suspended or revoked', definition: 'Elements: (1) Operates motor vehicle; (2) on public highway; (3) while license is suspended, revoked, or cancelled. Misdemeanor: not more than 6 months and/or $750.', offense_level: 'class_b_misdemeanor', category: 'vehicle', subcategory: 'License', citation_fine: 750 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 4, section: '103', subsection: null, citation: 'WS 31-4-103', short_title: 'Liability Insurance Required', description: 'Every owner of a motor vehicle registered in Wyoming must maintain liability insurance', definition: 'Minimum coverage: $25,000 bodily injury per person, $50,000 bodily injury per accident, $20,000 property damage. Proof must be carried in vehicle.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Insurance', citation_fine: 250 },

  // Equipment
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '924', subsection: null, citation: 'WS 31-5-924', short_title: 'Seatbelt Violations', description: 'Failure to wear a seatbelt while operating or riding in a motor vehicle', definition: 'Driver and all front seat passengers must wear seatbelts. Children under 9 must be in child restraint system. Secondary enforcement (cannot be sole reason for stop). Fine: $25.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 25 },
  { state: 'WY', state_name: 'Wyoming', title: 31, chapter: 5, section: '940', subsection: null, citation: 'WS 31-5-940', short_title: 'Headlight Violations', description: 'Failure to display headlights during required hours or conditions', definition: 'Headlights required from sunset to sunrise and whenever visibility is less than 1,000 feet. Must use low beams within 500 feet of oncoming traffic.', offense_level: 'infraction', category: 'vehicle', subcategory: 'Equipment', citation_fine: 25 },
];
