// src/utils/footage/clearpathSource.ts
import { getApiConfig, listMedia, listAllMedia, getCameraIdForAsset, API_BASE, type CpgClient } from '../clearpathGps';
import { classifyDrivingEvent } from '../drivingEvents';
import type { FootageSource, FootageRequestHandle, FootageChunkStatus, AvailableRequestClip } from './types';

// Confirmed 2026-06-15 via HAR capture: on-demand clips use the camera-service
// entity ID (camera.id from /v1.0/assets/ids), NOT the fleet assetId.
const MAX_CHUNK_SECONDS = 40;

type EnvLike = { KV: KVNamespace; CPG_ENC_KEY?: string; CPG_REFRESH_TOKEN?: string; CPG_USER_ID?: string };

// ── Pure builders (exported for tests) ───────────────────────

export function buildMediaRequestPayload(fromTs: number, toTs: number, channel: string) {
  return {
    timestamp: fromTs,
    cameraTypes: [channel === 'inside' ? 'INSIDE' : 'OUTSIDE'],
    duration: Math.round((toTs - fromTs) / 1000),
  };
}

export function parseRequestId(resp: Record<string, unknown>): string | null {
  for (const k of ['requestId', 'mediaRequestId', 'id', 'batchId']) {
    const v = resp?.[k];
    if (v != null && v !== '') return String(v);
  }
  return null;
}

/** Returns true when a media object should be treated as a trigger/event clip
 *  and skipped for use as a 40s continuous segment. Trigger clips are ~20s
 *  driving-event clips auto-generated by the camera; they belong in
 *  footage_markers only. Two guards:
 *  1. Recognised driving event type (classifyDrivingEvent returns non-'custom').
 *  2. Duration guard — declared duration < 75% of the requested chunk window
 *     (catches unlabelled short clips from unrecognised event types). */
export function isTriggerClip(eventType: string, durationSec: number | null | undefined, chunkDurationSec: number): boolean {
  if (eventType && classifyDrivingEvent(eventType).type !== 'custom') return true;
  if (durationSec != null && durationSec < chunkDurationSec * 0.75) return true;
  return false;
}

/** Pure: pick the best available clip from a listMedia page for a given chunk window,
 *  skipping trigger clips, out-of-territory clips, and any URL already claimed by another
 *  chunk in the same request. Exported for tests. */
export interface PollCandidatePage {
  items: Array<{
    eventTimestamp: number;
    mediaObject: Array<{
      channel: string; type: string; eventType: string;
      durationSec?: number | null;
      status?: string; accessUrl?: string; contentType?: string; thumbnailUrl?: string;
    }>;
  }>;
}

export function pickBestClip(
  page: PollCandidatePage, fromTs: number, toTs: number, channel: string,
  slopMs: number, claimedUrls?: Set<string>,
): FootageChunkStatus {
  const chunkSpan = toTs - fromTs;
  const chunkMid = (fromTs + toTs) / 2;
  let best: FootageChunkStatus | null = null;
  let bestDelta = Infinity;
  for (const ev of page.items) {
    const delta = Math.abs(ev.eventTimestamp - chunkMid);
    if (delta > chunkSpan + slopMs) continue;
    for (const mo of ev.mediaObject) {
      const matchChannel = channel === 'inside' ? mo.channel === 'inside' : mo.channel !== 'inside';
      if (!matchChannel || mo.type !== 'VIDEO') continue;
      if (isTriggerClip(mo.eventType, mo.durationSec, chunkSpan / 1000)) continue;
      const st = classifyChunkStatus(mo as unknown as Record<string, unknown>);
      if (st.state === 'missing' || st.state === 'error') return st;
      if (st.state === 'available' && st.accessUrl && claimedUrls?.has(st.accessUrl)) continue;
      if (st.state === 'available' && delta < bestDelta) { best = st; bestDelta = delta; }
    }
  }
  return best ?? { state: 'requested' };
}

export function classifyChunkStatus(obj: Record<string, unknown>): FootageChunkStatus {
  const status = String(obj?.status ?? '').toUpperCase();
  const accessUrl = obj?.accessUrl ? String(obj.accessUrl) : undefined;
  if (status === 'NO_MEDIA' || status === 'UNAVAILABLE') return { state: 'missing' };
  if (status === 'ERROR' || status === 'FAILED') return { state: 'error' };
  if (accessUrl && (status === 'AVAILABLE' || status === 'READY')) {
    return { state: 'available', accessUrl, contentType: obj?.contentType ? String(obj.contentType) : undefined,
      thumbnailUrl: obj?.thumbnailUrl ? String(obj.thumbnailUrl) : undefined };
  }
  return { state: 'requested' };
}

// ── IO helpers ───────────────────────────────────────────────

async function post(env: EnvLike, client: CpgClient, path: string, body: unknown): Promise<Record<string, unknown>> {
  const attempt = async (retried: boolean): Promise<Record<string, unknown>> => {
    const token = await client.getToken();
    const res = await fetch(new URL(path, API_BASE).toString(), {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(30_000),
    });
    if (res.status === 401 && !retried) {
      try { await env.KV.delete('cpg:access_token'); } catch { /* KV optional */ }
      return attempt(true);
    }
    // 409 = ClearPath already has a pending request for this camera+window.
    // Treat as an accepted request — the clip will appear in listMedia when ready.
    if (res.status === 409) return (await res.json().catch(() => ({}))) as Record<string, unknown>;
    if (!res.ok) {
      const body = await res.text().catch(() => '');
      throw new Error(`ClearPath media-request ${res.status}: ${body.slice(0, 200)}`);
    }
    return (await res.json()) as Record<string, unknown>;
  };
  return attempt(false);
}

// ── The source ───────────────────────────────────────────────

export class ClearPathSource implements FootageSource {
  readonly id = 'clearpathgps';
  readonly maxChunkSeconds = MAX_CHUNK_SECONDS;
  constructor(private env: EnvLike, private client: CpgClient) {}

  async requestChunk(assetId: number, fromTs: number, toTs: number, channel: string): Promise<string | null> {
    const cameraId = await getCameraIdForAsset(this.env, this.client, assetId);
    if (!cameraId) throw new Error(`ClearPath: no camera ID for asset ${assetId}`);
    const path = `/v2.0/media/cameras/${cameraId}/request-media`;
    const resp = await post(this.env, this.client, path, buildMediaRequestPayload(fromTs, toTs, channel));
    return parseRequestId(resp) ?? String(cameraId);
  }

  async pollChunk(assetId: number, handle: FootageRequestHandle): Promise<FootageChunkStatus> {
    // ClearPath indexes media by event-trigger time, not media-start time. On-demand
    // clips can appear in listMedia with eventTimestamp offset from the requested
    // fromTs by up to ~90s (pre-event buffer, async processing, GPS clock drift).
    // 30s was too tight — 248 poll attempts produced zero matches. 2 minutes gives
    // enough headroom to find the clip without crossing into adjacent chunk territory
    // (delta guard below enforces uniqueness). isTriggerClip (not SLOP size) is what
    // prevents trigger clips from being used as continuous segments.
    const SLOP_MS = 120_000; // 2min — covers ClearPath on-demand indexing lag
    const searchFrom = handle.fromTs - SLOP_MS;
    const searchTo = handle.toTs + SLOP_MS;
    const page = await listMedia(this.env, this.client, assetId, searchFrom, searchTo, 0, 50);
    return pickBestClip(page, handle.fromTs, handle.toTs, handle.channel, SLOP_MS, handle.claimedUrls);
  }

  async listRequestWindow(assetId: number, fromTs: number, toTs: number): Promise<AvailableRequestClip[]> {
    const SLOP_MS = 120_000; // mirror pollChunk
    const events = await listAllMedia(this.env, this.client, assetId, fromTs - SLOP_MS, toTs + SLOP_MS).catch(() => []);
    const chunkSec = MAX_CHUNK_SECONDS; // typical chunk size for the trigger heuristic
    const out: AvailableRequestClip[] = [];
    for (const ev of events) {
      for (const mo of ev.mediaObject) {
        if (mo.type !== 'VIDEO') continue;
        if (isTriggerClip(mo.eventType, mo.durationSec, chunkSec)) continue;
        const status = String(mo.status ?? '').toUpperCase();
        if (status !== 'AVAILABLE' && status !== 'READY') continue;
        if (!mo.accessUrl) continue;
        // CpgMediaObject has an index signature: contentType is `unknown` —
        // coerce defensively the same way pickBestClip's classifyChunkStatus does.
        const ct = mo.contentType != null ? String(mo.contentType) : undefined;
        out.push({
          eventTimestamp: ev.eventTimestamp,
          channel: mo.channel,
          accessUrl: mo.accessUrl,
          contentType: ct,
          thumbnailUrl: mo.thumbnailUrl || undefined,
        });
      }
    }
    return out;
  }
}

/** Resolve a ClearPath source from config, or null if not configured. */
export async function getClearPathSource(db: D1Database, env: EnvLike): Promise<ClearPathSource | null> {
  const client = await getApiConfig(db, env).catch(() => null);
  return client ? new ClearPathSource(env, client) : null;
}
